### ISSUE TITLE
Add additional columns into Event table

### ISSUE THREAD

**Issue by bruceliu2008** [thepirat000/Audit.NET#101]
Hi,
    Are there any way to add new columns to the default table which only has the following fields?
EventId	InsertedDate	LastUpdatedDate	Data, I know there is one way to create custom data provide which can map one entity to one event table, but I only need one event table for all entities, but with more structural data.
Thanks.

**Comment by bruceliu2008** [comment]
I like to add at least the following columns, reference id(guid), userid(varchar), customerid(varchar).
Thanks.

**Comment by bruceliu2008** [comment]
Sorry, another question, if I am using Audit.Framework.Core, how can I create audit event manually? The following code throws null point exception, seems the scope is null.
AuditScope.CreateAndSave("Player::Query", new { ExtraField = "extra value" });
Basically I want to test to audit a data query action and I need new columns extending the default Event table.

Thanks.

**Comment by thepirat000** [comment]
Can you share your audit setup configuration (Audit.Core.Configuration calls)? Do you use the Sql or the Postgres provider?
Anyway none of these providers allows to change the insert/update commands, so you'll need to create a custom data provider inheriting from `AuditDataProvider`. Check the doc [here](https://github.com/thepirat000/Audit.NET#data-providers)

**Comment by thepirat000** [comment]
Feel free to re-open this if you're still having problems

**Comment by shobhitvaish** [comment]
Hi, Thanks for the great library!

I also have same requirement. To make sure I understand your answer - It is not possible to add new columns in table using SqlServerProvider and if I want to add it I would have to write my own custom data provider. Is this correct understanding?

Thanks!

**Comment by thepirat000** [comment]
That is correct. The `SqlDataProvider` only inserts/updates the _json column_ containing the audit event, and optionally a _LastUpdatedDate column_.

For something more specific, you must implement your own `AuditDataProvider`. Check the documentation [here](https://github.com/thepirat000/Audit.NET#data-providers).

**Comment by shobhitvaish** [comment]
Alright, thanks!
