### ISSUE TITLE
Audit fails if multiple foreignkeys contains the same property name

### ISSUE THREAD

**Issue by bromose** [thepirat000/Audit.NET#104]
Audit fails if multiple foreignkeys contains the same property name. It fails in GetForeignKeysValues 

I suggest that You make the following change to EntityKeyHelper:
 Change line 79 
from:
string[] keyNames = navProps?.SelectMany(n => n.GetDependentProperties()).Select(fk => fk.Name).ToArray();
to:
string[] keyNames = navProps?.SelectMany(n => n.GetDependentProperties()).Select(fk => fk.Name).Distinct().ToArray();

Best regards

**Comment by thepirat000** [comment]
Fix included on version 11.0.7, thanks!
