### ISSUE TITLE
EntityFramework relationships support

### ISSUE THREAD

**Issue by joseandresromero** [thepirat000/Audit.NET#108]
How do you handle entity relationships changes logging. I mean, given the following example how do you handle when an entity relationship is updated?

These are my models:

```
public class Service {
    public Guid Id { get; set; };
    public virtual Guid MyEquipmentId { get; set; };
    public virtual Equipment MyEquipment { get; set; };
    public virtual string ServiceName { get; set; };
}
```

```
public class Equipment {
    public Guid Id { get; set; };
    public virtual string Name { get; set; };
}
```

These are my audit models:

```
public class AuditService {
    public virtual Guid            AuditId { get; set; }
    public virtual string          AuditAction { get; set; }

    public Guid Id { get; set; };
    public virtual Guid MyEquipmentId { get; set; };
    public virtual Equipment MyEquipment { get; set; };
    public virtual string ServiceName { get; set; };
}
```

```
public class AuditEquipment {
    public virtual Guid            AuditId { get; set; }
    public virtual string          AuditAction { get; set; }

    public Guid Id { get; set; };
    public virtual string Name { get; set; };
}
```

This way querying the **AuditService** model I'm able to track the **ServiceName** changes on each update, but I'm not able to know to which version of **Equipment** were associated a specific version of **Service**. For example, initially the **Service** named "ServiceOne" is associated to the **Equipment** named "EquipmentOne". So then I update that **Equipment** to "EquipmentOneUpdated". I want to get the row in **AuditService** when the **Equipment** was still "EquipmentOne", but that row is pointing to the updated **Equipment**. 

How would this be handled?

**Comment by thepirat000** [comment]
You could know that by analyzing the Audit records. Assuming you configured an AuditEntityAction including the Audit Action, you will end up having (at least) the following audits in chronological order:
1- INSERT - AuditEquipment { Id=1, Name="EquipmentOne" } 
2- INSERT - AuditService (Id=100, Name="ServiceOne", EquipmentId=1)
3- UPDATE - AuditEquipment { Id=1, Name="EquipmentOneUpdated" } 

So you know that after 2 and before 3, Equipment was "EquipmentOne" and related to the service.

Also note you can access the audit event before it's saved, with the [EF Audit Action](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#ef-provider-configuration) or even with a generic [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) so you have [all the information](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#output-details) about the event. For example:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeNameMapper(n => n + "Audit")
        .AuditEntityAction((evt, entry, auditEntity) =>
        {
            var a = (dynamic)auditEntity;
            a.AuditAction = entry.Action;
            var ef = evt.GetEntityFrameworkEvent(); // you can access the audit model
        }));
```

**Comment by thepirat000** [comment]
Closing this for now. Feel free to re-open if you're still having problems
