### ISSUE TITLE
Ignore column

### ISSUE THREAD

**Issue by pavlopanashchuk** [thepirat000/Audit.NET#112]
Hello.

I am trying to use Audit.net library.

But my table contains one very large field which I do not want to save into log table.

I cannot find solution how to ignore one column in table.

Could you help me?

**Comment by pavlopanashchuk** [comment]
We use Audit.EntityFramework.Core and Audit.NET.SqlServer. 

Thanks in advance.

**Comment by thepirat000** [comment]
Sorry, there is no built-in mechanism to ignore columns, but you have at least two ways to accomplish that:

1- Override the `OnScopeCreated` method on your AuditDbContext and remove the references to the column:
```c#
class YourContext : AuditDbContext
{
    public override void OnScopeCreated(AuditScope auditScope)
    {
        FixScope(auditScope);
    }
}
```

2- Use a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) `OnEventSaving` for the same purpose:
```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, auditScope =>
{
    FixScope(auditScope);
});
```

And the FixScope could be like this:

```c#
private void FixScope(AuditScope auditScope)
{
    var efEvent = auditScope.Event.GetEntityFrameworkEvent();
    foreach (var entry in efEvent.Entries)
    {
        if (entry.Table == "SomeTable")
        {
            // Remove the column from Changes list
            entry.Changes.RemoveAll(x => x.ColumnName == "BigColumnName");
            // Remove value from ColumnValue dictionary
            entry.ColumnValues.Remove("BigColumnName");
            // Remove value from the entity
            (entry.Entity as SomeTable).BigColumnName = null;
        }
    }
}
```

Let me know if that fits your need. Anyway I'm leaving this open to think about a built-in mechanism to ignore columns. This seems to be a common requirement.

**Comment by pavlopanashchuk** [comment]
Thanks a lot.
Yes, this approach worked for me.

But it is like hard-coding table and column names.

**Comment by thepirat000** [comment]
Hi. I have added a built-in mechanism to **Ignore** and and **Override** column values on the audit logs.

This is available starting from version 11.1.0.

Now you should be able to configure your entities like this:

```c#
Audit.EntityFramework.Configuration.Setup()
    .ForContext<YourContext>(config => config
        .ForEntity<SomeTable>(_ => _
            .Ignore(t => t.BigColumn)));
```

You can also ignore properties by decorating the entity properties with AuditIgnore:
```c#
public class SomeTable
{
    [AuditIgnore]
    public string BigColumn { get; set; }
}
```

Please note this mechanism will ignore/override values on `ColumnValues` and `Changes` collections of the [EventEntry](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#evententry) output. It will not override values on the `Entity` when you set the `IncludeEntityObjects` to true.

I have put some more documentation on the [readme file](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#configuration), please take a look.

**Comment by bturner1273** [comment]
Are AuditIgnore/AuditInclude events as well as optin/optout modes supposed to work with a custom data provider? I am using entityframework with an elasticsearch data provider and would rather not hard code table/column names to ignore.

**Comment by brownjr38** [comment]
Used the following to ignore JsonData column.  I broke up the data with CustomColumns  and had no need for a giant JSON.

`Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(config => config
                .ForEntity<AuditDbContext>(x => x.Ignore("JsonData")));
`

I used the built in EntityFramework.  Included Audit.EntityFramework.Core NuGet package.
