### ISSUE TITLE
Password not hiden

### ISSUE THREAD

**Issue by pavlopanashchuk** [thepirat000/Audit.NET#113]
Hello.

Thanks for operative help with library issue.

Now I am trying save controller action into database. I use Audit.MVC.Core and Audit.Net.SqlServer.
We want log data when user login. Problem that we are logging password not encrypted. 

Maybe the best solution is to remove this field from FormVariables and ActionParameters. What do you think?

Best regards.

**Comment by thepirat000** [comment]
For Action Parameters we could have an attribute like `AuditIgnore` to decorate the action parameters maybe... But how should the library know which fields to remove from the form variables?

**Comment by thepirat000** [comment]
Anyway you can attach a `OnEventSaving` [custom action](https://github.com/thepirat000/Audit.NET#custom-actions) for all the events, and make the modifications before the audit saving occurs:

```c#
Audit.Core.Configuration.Setup()
    .UseSqlServer(x => x.ConnectionString("..."))
    .WithCreationPolicy(EventCreationPolicy.InsertOnEnd)
    .WithAction(x => x.OnEventSaving(scope =>
    {
        var mvcAction = scope.Event.GetMvcAuditAction();
        mvcAction.ActionParameters["Password"] = "***";
        mvcAction.FormVariables["Password"] = "***";
    }));
```

Or alternatively: 

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var mvcAction = scope.Event.GetMvcAuditAction();
    //...
});
```

**Comment by pavlopanashchuk** [comment]
Maybe we can create somethink like 

auditScope.SetCustomField("UserName", currentUser.PersonName);

but hide field which we can find by Key....

Now my configuration:

         Audit.Core.Configuration.Setup()
        .UseSqlServer(config => config
        .ConnectionString(Configuration.GetConnectionString("DefaultConnection"))
        .TableName(ev => ev.EventType == "MyDatabase" ? "AuditLogEntity" : "AuditLogMVC")
        .IdColumnName("EventId")
        .JsonColumnName("Data")
        .LastUpdatedColumnName("LastUpdatedDate"))
        .WithCreationPolicy(EventCreationPolicy.InsertOnEnd)
        .WithAction(
                x => x.OnEventSaving(scope =>
                {
                    var mvcAction = scope.Event.GetMvcAuditAction();

                    if (mvcAction != null && mvcAction.ActionParameters != null)
                    {
                        if (mvcAction.ActionName == "Login")
                        {
                            var obj = mvcAction.ActionParameters.Where(a => a.Key == "model").FirstOrDefault().Value as LoginViewModel;
                            if (obj != null)
                            {
                                obj.Password = "***";
                                obj.ConfirmPassword = "***";
                            }
                        };

                        if (mvcAction.ActionName == "Register")
                        {
                            var obj = mvcAction.ActionParameters.Where(a => a.Key == "model").FirstOrDefault().Value as RegisterViewModel;
                            if (obj != null)
                            {
                                obj.Password = "***";
                                obj.ConfirmPassword = "***";
                            }
                        }
                    };

                    if (mvcAction != null && mvcAction.FormVariables != null && mvcAction.FormVariables.ContainsKey("Password"))
                    {
                        mvcAction.FormVariables["Password"] = "***";
                        mvcAction.FormVariables["ConfirmPassword"] = "***";
                    };
                }));
        }.

Also I cannot find how do not save ActionParameters.

**Comment by thepirat000** [comment]
You can avoid saving the action parameters with `mvcAction.ActionParameters.Clear()` right?

**Comment by alexeid1337** [comment]
`[AuditIgnore]` option for model property would be good, or even the `[AuditHide]` one, so as not to confuse someone browsing the logs, why did this option disappear, instead hide it with asterisks or something.
I'm not sure about FormVariables, I hardly see any point to use [FromForm] nowadays.

For now I cope with my custom attribute, it works like this in Audit config:
```
.WithCreationPolicy(EventCreationPolicy.InsertOnEnd)
.WithAction(x => x.OnEventSaving(scope =>
{
  var action = scope.Event.GetWebApiAuditAction();
  var model  = action?.ActionParameters?.SingleOrDefault(a => a.Key == "model").Value;
  model?.GetType().GetProperties().ForEach(property =>
  {
    if (property.GetCustomAttributes(typeof(AuditHideAttribute), true).Any())
    {
      property.SetValue(model, "***");
    }
  });
}));
```

Although come to think of it, another solution would be to allow to ignore certain controller actions to be ignored by audit (using `[AuditIgnore]` or something). Just like it's possible to overcome global filters of `AuthorizeFilter` and `AutoValidateAntiforgeryTokenAttribute` with `[AllowAnonymous]` and `[IgnoreAntiforgeryToken]` respectively.
This way we could ignore Login/Register/ChangePassword/Whatsoever actions, and simply use own audit functions for such important actions.

**Comment by thepirat000** [comment]
I found the logic to be very specific for your use case and I don't see an easy way to implement a generalization of that. If you can think of a generic way to implement this please provide the implementation details or create a pull request.

Regards

**Comment by thepirat000** [comment]
latest version (12.2.2) includes an [AuditIgnoreAttribute] that can be used:

- At the controller class level (to ignore all its actions)
- At the action method level (to ignore a particular action)
- At the method parameters level (to ignore a particular action argument)

**Comment by csutorasr** [comment]
Can this attribute ignore properties from EF?  This could benefit for users using GDPR.

The personal data attribute could be also ignored.
Maybe some options can enable it.

I think it is related. If this is the wrong thread tell me and I will create a new issue.
