### ISSUE TITLE
How to audit changes in n to m relations?

### ISSUE THREAD

**Issue by Izelude** [thepirat000/Audit.NET#116]
Hi, 

I have the following Scenario with Entity Framework Core as Dataprovider: 
I have a User Table and  Role Table and a UserRole Table to model the relationship.
How can i audit changes in the realationship to be able to later easily create divs  between Role Changes for a User?

**Comment by thepirat000** [comment]
It depends on how are your entities mapped to EF, how do you store the audits, and so on. Could you share your current configuration, mappings and the exact problem you are experiencing?

**Comment by Izelude** [comment]
ok i can try without overflowing the post here with too much Code

The Role/User Entitiy:
```
    public class Role
    {
        public Guid RoleId { get; set; }
        public string Name { get; set; }

        public ICollection<UserRole> UserRoles { get; set; }
    }

    public class AuditRole : IAuditable
    {
        public AuditRole()
        {
            AuditId = new Guid();
        }

        public Guid AuditId { get; set; }
        public Guid RoleId { get; set; }
        public string Name { get; set; }

        public string AuditUsername { get; set; }
        public DateTime AuditTimestamp { get; set; }
        public string AuditAction { get; set; }
    }
```
The User Entity is the same just with couple different fields.

and here is the join Table Property (UserRole):

   ```
 public class UserRole
    {
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
        public Guid UserId { get; set; }
        public User User { get; set; }
    }

    public class AuditUserRole : Core.IAuditable
    {
        public Guid AuditId { get; set; }
        public Guid RoleId { get; set; }
        public Role Role { get; set; }
        public Guid UserId { get; set; }
        public User User { get; set; }
        public string AuditUsername { get; set; }
        public DateTime AuditTimestamp { get; set; }
        public string AuditAction { get; set; }
    }

```
Audit Configuration:
```
Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                            .AuditTypeNameMapper(typeName => "Audit" + typeName)
                            .AuditEntityAction<IAuditable>((ev, entry, auditEntity) =>
                            {
                                auditEntity.AuditTimestamp = DateTime.UtcNow;
                                auditEntity.AuditAction = entry.Action;
                                auditEntity.AuditUsername = "GetUserNameFromHttpContextOrWahtever";
                            }
                    ));
```

some dbContext config:
```
modelBuilder.Entity<UserRole>()
                .HasKey(u => new {u.RoleId, u.UserId });


            modelBuilder.Entity<UserRole>()
                .HasOne(u => u.User)
                .WithMany(u => u.UserRoles)
                .HasForeignKey(u => u.UserId);

            modelBuilder.Entity<UserRole>()
                .HasOne(r => r.Role)
                .WithMany(r => r.UserRoles)
                .HasForeignKey(r => r.RoleId);
```

there is some more shadowproperties and filter for soft deletes but i don't think thats relevant for the question.

So my Problem right now is that when i take away a role from a user it gets audited in the AuditUserRole Table and the AuditUser Table, but in the EventEntry.Changes for AuditUser Table i dont see what changed. basically it tells me there was an update and makes an entry to the table but it's the same as the last entry.

hope that clears up my Problem.

thx for the fast answer btw :)

**Comment by thepirat000** [comment]
If you take away a role from a user, it makes sense that don't see the change on AuditUser because there was no change at all on the User table... Why isn't enough to have that information (who taken away a role from a user) on the AuditUserRole?
