### ISSUE TITLE
Multiple types of Audits

### ISSUE THREAD

**Issue by newbieHasher** [thepirat000/Audit.NET#118]
Hi, it is an amazing API you have here. 
Sorry for being a noob, I've been trying to figure out how to use both MVC.Core's controllers audits and EntityFrameworkCore's entities audits together in the same Net.Core project, but was unsuccessful. I plan to direct the controller's audits to an Event table and also audit the changes in "Happiness" table to "Audit_Happiness".  However, I keep encountering errors. Am I using the API wrongly? 

Audit.EntityFramework.Configuration.Setup()
   .ForContext<HappinessDbContext>(config => config
   .IncludeEntityObjects());

Audit.Core.Configuration.Setup()
    .UseSqlServer(config => config
    .ConnectionString("ConnectionString")
    .Schema("dbo")
    .TableName(ev => "Event")
    .IdColumnName(ev => "EventId")
    .JsonColumnName(ev => "Data")
    .LastUpdatedColumnName("LastUpdatedDate"))
    .WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd)
    .ResetActions();

Audit.Core.Configuration.Setup()
     .UseEntityFramework(ef => ef
          .AuditTypeExplicitMapper(m => m.Map<Happiness, Audit_Happiness>()
              .AuditEntityAction((evt, entry, auditEntity) =>
             {
                  var a = (dynamic)auditEntity;
                  a.AuditDate = DateTime.UtcNow;
                  a.UserName = evt.Environment.UserName;
                  a.AuditAction = entry.Action;
              })));

**Comment by newbieHasher** [comment]
Hi pirat000, it worked! Thanks for your help:)

**Comment by sagark-comnet** [comment]
I did it by creating a custom data provider, though the entities are not getting saved to the database yet.
```
 public class MultiDataProvider : AuditDataProvider
{
    
    private SqlDataProvider sqlDataProvider;
    private EntityFrameworkDataProvider entityFrameworkDataProvider;

    private FileDataProvider fileDataProvider;
    public MultiDataProvider(SqlDataProvider sqlDataProvider,EntityFrameworkDataProvider entityFrameworkDataProvider,FileDataProvider fileDataProvider)
    {
        
        this.sqlDataProvider=sqlDataProvider;

        this.entityFrameworkDataProvider=entityFrameworkDataProvider;
        this.fileDataProvider=fileDataProvider;
    }
    public override object InsertEvent(AuditEvent auditEvent)
    {
        try
        {
            if(auditEvent is AuditEventMvcAction)
            {
            return  sqlDataProvider?.InsertEvent(auditEvent);
            }
            else
            {
                
            return entityFrameworkDataProvider?.InsertEvent(auditEvent);
            }
        }
        catch (Exception)
        {
            return fileDataProvider?.InsertEvent(auditEvent);
        }
    }
    public override async Task<object> InsertEventAsync(AuditEvent auditEvent)
    {
        try
        {
            if(auditEvent is AuditEventMvcAction)
            {
               return  await sqlDataProvider?.InsertEventAsync(auditEvent);
            }
            else
            {
                return await sqlDataProvider?.InsertEventAsync(auditEvent);
            }
        }
        catch (Exception)
        {
            return await fileDataProvider?.InsertEventAsync(auditEvent);
        }
    }
    public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
    {
        try
        {
            if(auditEvent is AuditEventMvcAction)
            {
                sqlDataProvider?.ReplaceEvent(eventId, auditEvent) ;
            }
            else
            {
                entityFrameworkDataProvider?.ReplaceEvent(eventId,auditEvent);
            }
        }
        catch (Exception)
        {
            fileDataProvider?.ReplaceEvent(eventId, auditEvent);
        }
    }
    public override async Task ReplaceEventAsync(object eventId, AuditEvent auditEvent)
    {
        try
        {
            if(auditEvent is AuditEventMvcAction)
            {
                await sqlDataProvider?.ReplaceEventAsync(eventId, auditEvent);
            }
            else{
                
                await entityFrameworkDataProvider?.ReplaceEventAsync(eventId,auditEvent);
            }
        }
        catch (Exception)
        {
            await fileDataProvider?.ReplaceEventAsync(eventId, auditEvent);
        }
    }
}
```
In startup.cs
```
MultiDataProvider multiDataProvider=new MultiDataProvider(sqlDataProvider,/*efDataProvider*/null,fileDataProvider);

            Audit.Core.Configuration.DataProvider=multiDataProvider;

```

**Comment by lourencocotta** [comment]
> Actually that's a pretty good question.
> 
> The data providers are conflicting. Unafortunately, you can only have one data provider configured _globally_ (or _by default_). So the methods `UseSqlServer()` and `UseEntityFramework()` are conflicting since both will set the global data provider, and the latter will _win_.
> 
> You have many options to accomplish this. I think the most straightforward is to use the SqlServer data provider globally to use it for MVC actions., and set the EF data provider on your DbContext instances, for example:
> 
> ```cs
> public class MyDbContext : AuditDbContext
> {
>     // Have a static instance of an EF DataProvider
>     private static EntityFrameworkDataProvider EfDataProvider = new EntityFrameworkDataProvider()
>     {
>         AuditTypeMapper = t => t == typeof(Happiness) ? typeof(Audit_Happiness) : null,
>         AuditEntityAction = (evt, entry, auditEntity) =>
>         {
>             var a = (dynamic)auditEntity;
>             a.AuditDate = DateTime.UtcNow;
>             a.UserName = evt.Environment.UserName;
>             a.AuditAction = entry.Action;
>         }
>     };
> 
>     // As soon as a DbContext is created, set its data provider
>     public MyDbContext()
>     {
>         this.AuditDataProvider = EfDataProvider;
>     }
> 
>     //...
> }
> ```
> 
> So for MVC you can use the global data provider:
> 
> ```cs
> Audit.Core.Configuration.Setup()
>     .UseSqlServer(config => config
>     .ConnectionString("ConnectionString")
>     .Schema("dbo")
>     .TableName(ev => "Event")
>     .IdColumnName(ev => "EventId")
>     .JsonColumnName(ev => "Data")
>    .LastUpdatedColumnName("LastUpdatedDate"))
>     .WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd)
>     .ResetActions();
> ```
> 
> Let me know if that works for you. Good luck!

Didn't work for me.
