### ISSUE TITLE
HttpPostedFileWrapper error

### ISSUE THREAD

**Issue by TrueBurn** [thepirat000/Audit.NET#119]
When using a custom AuditDataProvider (to log to ElasticSearch) you get 
"Error getting value from 'ReadTimeout' on 'System.Web.HttpInputStream'."
error if there is a HttpPostedFile as a ActionParameter. This requires a custom JsonConvtere to correct

 public class HttpPostedFileConverter : JsonConverter
    {
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            var stream = (Stream)value;
            using (var sr = new BinaryReader(stream))
            {
                var buffer = sr.ReadBytes((int)stream.Length);
                writer.WriteValue(Convert.ToBase64String(buffer));
            }
        }

Having this is the project by default would be useful so you can use the .ToJson() function

**Comment by thepirat000** [comment]
I'm not sure if this should be added by default. 

Because that is a serializer/converter for Streams,, so if we add it by default it should also take into account things like if the stream can be read or not, if it should reset its position to 0, and so on...

Maybe if I add an overload to the ToJson method to pass a JsonSerializer where you can set
the converters you want. Will that help?

```
var settings = new JsonSerializerSettings() { Converters = new List<JsonConverter>() { new HttpPostedFileConverter() };
auditEvent.ToJson(settings);
```

**Comment by TrueBurn** [comment]
Hi

I updated Audit.Mvc and Audit.NET to 12.0.1 now and able to serialise HttpPostedFiles in the Action parameters without error now  using both the global setting config and the override. Thank you very much.

For ElasticSearch:

Using the ElasticSearch using the NEST high-level client I do the below:

`public override object InsertEvent(AuditEvent auditEvent)
{
	var auditID = Guid.NewGuid().ToString();

	try
	{

		SystemAuditModal _mvcEvent = JsonConvert.DeserializeObject<SystemAuditModal>(auditEvent.ToJson());

		Parallel.ForEach(_mvcEvent.Action.ActionParameters.ToList(), (aParam) =>
		{
			if (aParam.Key.ToLower().Contains("encoded"))
			{
				_mvcEvent.Action.ActionParameters[aParam.Key] = "Encoded value trimmed...";
			}
		});

		Parallel.ForEach(_mvcEvent.Action.FormVariables.ToList(), (fVar) =>
		{
			if (fVar.Key.ToLower().Contains("encoded"))
			{
				_mvcEvent.Action.FormVariables[fVar.Key] = "Encoded value trimmed...";
			}
		});

		SingleNodeConnectionPool pool = new SingleNodeConnectionPool(new Uri(ConfigurationManager.AppSettings["ES.ServerURL"]));

		ConnectionSettings settings = new ConnectionSettings(connectionPool: pool)
			.DefaultIndex(ESIndex);
		ElasticClient ESClient = new ElasticClient(settings);

		var indexResult = ESClient.Index<AuditEvent>(_mvcEvent, e => e
			.Index(ESIndex)
			.Type(ESType)
			.Id(auditID)
		);

		if(!indexResult.IsValid)
		{
			log.Error($"Unable to audit event {JsonConvert.SerializeObject(_mvcEvent)}");
		}

	}
	catch (Exception Ex)
	{
		log.Error("Error in InsertEvent", Ex);
	}

	return auditID;
}`

Then for replace:

` var indexResult = ESClient.Index<AuditEvent>(auditEvent, e => e
                        .Index(ESIndex)
                        .Type(ESType)
                        .Id(eventId.ToString())
                    );`

and get:

`var getExisting = ESClient.Get<AuditEvent>(eventId.ToString(), i => i
                        .Index(ESIndex)
                        .Type(ESType)
                    );

                    if (getExisting.IsValid && getExisting.Found)
                    {
                        exisitngEvent = getExisting.Source;
                    }
                    else
                    {
                        exisitngEvent = null;
                    }`

There are also async versions of the methods. I override any fields with "encoded" in the name to prevent passwords from being logged in the audits.

**Comment by thepirat000** [comment]
I have added a generic Elasticsearch data provider, please take a look.

https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.ElasticSearch

Regards
