### ISSUE TITLE
Audit.Net WebApi AND EF6

### ISSUE THREAD

**Issue by CasperJ** [thepirat000/Audit.NET#12]
Hi I'm currently using Audit.NET for WebApi. I've im using the attribute based approach for auditing specific api calls. This works great.
However, now I want to include whatever changes that API calls have made to the underlying EF6 scope.
My question is; can I include both webapi and ef6 audit information in the same audit record?
Also, how do I ensure that all the other EF6 are not audited?
Any ideas or thoughts?

**Comment by thepirat000** [comment]
Hi, nice question!

I can think on one way to accomplish that, but it's probably too invasive.
The idea is to make the EntityFramework audit event to insert itself on the WebApi audit event.

You need a way to inject the WebApi audit scope to the EntityFramework context, so the EF context saving can be changed to do this insertion instead of its event saving.

Basically this is what you need to change on your DbContext class:
```c#
public class MyContext : AuditDbContext
{
    //Locally store the current web api scope
    private AuditScope _webApiAuditScope;
    public MyContext(AuditScope webApiAuditScope)
    {
        _webApiAuditScope = webApiAuditScope;
        // Set an empty DynamicDataProvider to avoid saving on the EF data provider
        AuditDataProvider = new DynamicDataProvider();
    }

    //Override scope saving to insert the EF event into the WebApi scope
    protected override void OnScopeSaving(AuditScope auditScope)
    {
        _webApiAuditScope.SetCustomField("EF_Event", auditScope.Event.GetEntityFrameworkEvent());
    }
}
```

In this case I'm injecting the scope in the `MyContext` constructor.

So on the web api methods, you need to inject the Web Api scope that you can get via `GetCurrentAuditScope`. For example:

```c#
[HttpPost]
public void Post([FromBody]string value)
{
    using (var ctx = new MyContext(this.GetCurrentAuditScope()))
    {
        // ... hard work
        ctx.SaveChanges();
     }
}
```

So you get something like this as the output for the Web Api audit:
```javascript
{
  "EventType": "Values/Get (GET)",
  "Environment": {
    "UserName": "Federico",
    "MachineName": "HP",
    "Culture": "en-GB"
  },
  "StartDate": "2016-11-14T13:17:51.9785226-06:00",
  "EndDate": "2016-11-14T13:18:00.2833814-06:00",
  "Duration": 8305,
  "Action": {
    "HttpMethod": "GET",
    "ControllerName": "Values",
    "ActionName": "Get",
    "ActionParameters": {},
    "FormVariables": null,
    "UserName": null,
    "RequestUrl": "http://localhost:52336/api/values",
    "IpAddress": "::1",
    "ResponseStatus": "200",
    "ResponseStatusCode": 200,
    "ResponseBodyType": "ObjectResult",
    "ResponseBody": [
      "value1",
      "value2"
    ],
    "ModelStateValid": true
  },
  "EF_Event": {
    "Database": "Blogs",
    "Entries": [
      {
        "Table": "Posts",
        "Action": "Insert",
        "PrimaryKey": {
          "Id": -2147482647
        },
        "ColumnValues": {
          "Id": -2147482647,
          "BlogId": 1,
          "Content": "text-content",
          "DateCreated": "2016-11-14T13:17:52.0881209-06:00",
          "Title": "some-title"
        },
        "Valid": true
      }
    ],
    "Result": 1,
    "Success": true
  }
}
```

**Comment by CasperJ** [comment]
Hi

I think I nailed it. Thanks for pushing me in the right direction.

I ended up taking a dependency in my EF project on Audit.net and Audit.EntityFramework which I think i okay as I might need audit from other APIs in the future.

Then I added an event delegate for the saving event

```cs
internal Action<AuditScope> AuditScopeSaving = null;
protected override void OnScopeSaving(AuditScope auditScope)
{
   AuditScopeSaving?.Invoke(auditScope);
}
```

I was then able to catch that thing in the WebApi by decorating my DataAccess with something like this:

```cs
 internal class WebApiAuditDbAccess : IDbAccess
 {
    private readonly IDbAccess _dbAccessToBeDecorated;
    public WebApiAuditDbAccess(IDbAccess dbAccessToBeDecorated)
    {
       _dbAccessToBeDecorated = dbAccessToBeDecorated;
       _dbAccessToBeDecorated.AuditScopeSaving = OnAuditScopeSaving;
    }
```
The "OnAuditScopeSaving" then grabs the current auditScope from HttpContentBase and injects the EF event as a CustomField.

**Comment by thepirat000** [comment]
Great!
