### ISSUE TITLE
efcore- the internal on different object make it impossible to create custom provider

### ISSUE THREAD

**Issue by mhamri** [thepirat000/Audit.NET#120]
I'm trying to write a new provider because the current provider can't understand correct change tracker and custom logging that I want from it. I will create another issue to discuss about the provider problem.

I tried to create a new provider by copying the current `EntityFrameworkDataProvider.cs` and do some modification. but unfortunately, different objects are marked as internal including 

`EventEntry.Entry` in `~\Audit.NET\src\Audit.EntityFramework\EventEntry.cs`
`EntityFrameworkEvent.DbContext` in `~\Audit.NET\src\Audit.EntityFramework\EntityFrameworkEvent.cs`

this makes it impossible to extend the provider since I don't have access to same objects to use in the provider

**Comment by thepirat000** [comment]
Agree. Will mark as public those props on next version.

**Comment by thepirat000** [comment]
A small problem I see here is that those properties should never be serialized, regardless of the serialization method you use, so having them internal was useful to protect them from most of the serializers. Maybe I can expose just a getter, will that work for you?

**Comment by thepirat000** [comment]
This was fixed on version 12.0.2, please update and re-test.

Now the `EventEntry` class exposes a `GetEntry()` method and `EntityFrameworkEvent` class a `GetDbContext()` method.

Feel free to re-open if you're still having problems
