### ISSUE TITLE
Web API problem with ready request content body

### ISSUE THREAD

**Issue by Thorarin** [thepirat000/Audit.NET#124]
I've run into an issue with the way the `AuditApiAttribute` reads the content body. I'm registering it as a global action filter, which should make it execute relatively early in the pipeline, but I'm also registering some custom binding.

```
HttpConfiguration config = ...
config.ParameterBindingRules = config.ParameterBindingRules.Insert(0, ...);
```

This custom binding accesses the content body through the `HttpActionContext`. It happens to be executed **before** the action filter for Audit.NET, which results in this error when it tries to also access the content body:

```
This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.
```

This makes me wonder why the AuditApiAttribute is accessing the body through the `HttpContext`, instead of the "Web API way". There may be a good reason for it, but it would be really nice if it were possible to override this behavior without copying several classes into my own codebase (`AuditApiAttribute`, `ContextWrapper` and `AuditApiHelper`).

If it's not possible to straight up change the implementation to access the content through `HttpRequestMessage` (I can imagine this would be a breaking change for others), would it be possible to do something like this:
* Move `GetRequestBody` method to the `ContextWrapper`
* Introduce an interface `IContextWrapper` and make the implementation injectable
* Make ContextWrapper public and make its methods virtual, or provide another way to easily override part of the default behavior

Alternatively:
* Make `GetRequestBody` virtual protected

Used Audit.NET version: 7.x - 12.0.1

**Comment by Thorarin** [comment]
Full framework yes.

Using constructor injection would make it only directly usable by means of adding `AuditApiAttribute` as a filter in code, which kind of defies the purpose of attributes I suppose. Still, it would be possible to do this:

```
public class MyAuditApiAttribute: AuditApiAttribute
{
    MyAuditApiAttribute : base(new MyContextWrapper()) {}
}
```

This would make it more flexible than just making the single method virtual. For my particular purpose the virtual method would be sufficient, so the choice depends on whether it could be expected that anyone would want to change any of the other behavior in `ContextWrapper`.

**Comment by thepirat000** [comment]
what about injecting your IContextWrapper like this:

```
[AuditApi(ContextWrapperType = typeof(YourContextWrapper)]
public class MyController : Controller 
{ ... }
```

Will something like that work for you?

So you could implement the entire IContextWrapper interface, or inherit from the default ContextWrapper and override whatever you need, like:

```
public class YourContextWrapper : ContextWrapper
{
    public YourWrapper(HttpRequestMessage request)
        : base(request)
    {
    }

    public override HttpContextBase GetHttpContext()
    {
        var currentContext = System.Web.HttpContext.Current;
        return currentContext == null ? null : new HttpContextWrapper(currentContext);
    }
}
```

**Comment by thepirat000** [comment]
Please update to the latest version (12.0.5) and you should be able to set the implementation of `IContextWrapper` to use, via the `ContextWrapperType` property on the `AuditApiAttribute`, as shown on my previous message.

Hope it helps.

Feel free to re-open if you're still having problems.
