### ISSUE TITLE
Support hostname instead of IP only in Audit.NET.Udp

### ISSUE THREAD

**Issue by TDabasinskas** [thepirat000/Audit.NET#129]
Hello,

Similar to this [Serilog.Sinks.Udp request](https://github.com/FantasticFiasco/serilog-sinks-udp/issues/26), would it be possible for `Audit.NET.Udp` package to support providing a hostname (FQDN) instead of an IP only for `IUdpProviderConfigurator.RemoteAddress()`?.

Being able to resolve the hostname at runtime, would allow having more versatile configuration and, in some cases, better availability.

Thank you.

**Comment by thepirat000** [comment]
Please check the solution on this commit:

https://github.com/thepirat000/Audit.NET/commit/4ba764ea63e1387d30daf689c9e3158a4c6f4733

And let me know if that will solve your issue, so I can update a new version of the library.

Regards

**Comment by TDabasinskas** [comment]
Well, that was quick 😃 

Just tried and it seems to be working as expected. Looking forward for an official Nuget package.

Thank you!

**Comment by thepirat000** [comment]
Please upgrade to version 12.1.6. Closing this.

Feel free to re-open if you're still having problems
