### ISSUE TITLE
Audit.WebAPI Ignores EventCreationPolicy

### ISSUE THREAD

**Issue by dammitjanet** [thepirat000/Audit.NET#13]
I've come across an issue whereby the WebAPI extension appears to be ignoring the EventCreation Policy.

I've set the policy in two ways, both in the fluent style as follows:

```
			Audit.Core.Configuration.CreationPolicy = EventCreationPolicy.InsertOnStartReplaceOnEnd;
			var connectionString = ConfigurationManager.ConnectionStrings[contextName].ConnectionString;
			Audit.Core.Configuration
				.Setup()
				.UseSqlServer(config => config.ConnectionString(connectionString)
						.Schema("dbo")
						.TableName("events")
						.IdColumnName("id")
						.JsonColumnName("data")
						.LastUpdatedColumnName("lastUpdatedDate")
						)
				.WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd);
```
however all my events are only being written to the log at the end of the request, and none of the events have a populated 'lastUpdatedField'

**Comment by thepirat000** [comment]
Hi.
Will take a look.

Do you target .net core or the full framework?

**Comment by thepirat000** [comment]
In the meantime, you could workaround this by adding a Custom Action on ScopeCreated, so each time a scope is created, you can call the Save method.

For example:
```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    scope.Save();
});
```

**Comment by thepirat000** [comment]
Ok, this was fixed on v.4.6.2

Now the WebAPI and MVC should respect the configured Creation Policy.

Feel free to re-open the issue if you still have problems

**Comment by dammitjanet** [comment]
perfect
