### ISSUE TITLE
Missing method exception on saving audited entity on .netcore 2.0

### ISSUE THREAD

**Issue by mmsommer** [thepirat000/Audit.NET#130]
I tried to implement Audit.EntityFramework for my application I get the following error when saving an entity which should be audited:
`An unhandled exception occurred while processing the request.
MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations Microsoft.EntityFrameworkCore.SqlServerMetadataExtensions.SqlServer(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.

I am using .net core 2.0

**Comment by mmsommer** [comment]
I did see [this issue](https://github.com/thepirat000/Audit.NET/issues/25). But the problem for that one was that it was using .net standard 1.6x. In this case I am using .net core 2.0x which is as far as I know later than standard 1.6x
So I was actually hoping you knew what could be the problem from that difference. :)

**Comment by mmsommer** [comment]
Ignore anything above. I was using a very old version of this library (4.x) So the problem was completely on my side.
Mea Culpa!

**Comment by thepirat000** [comment]
np. good to know it's working

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
