### ISSUE TITLE
InvalidDataException in AuditApiAdapter.Core when content type is MultipartContentType

### ISSUE THREAD

**Issue by akuzin87** [thepirat000/Audit.NET#131]
We use MultipartContentType for uploading files.
In AuditApiAdapter.Core.cs in BeforeExecutingAsync we have a line:
`FormVariables = httpContext.Request.HasFormContentType ? ToDictionary(httpContext.Request.Form) : null,`
In a case with MultipartContentType `httpContext.Request.HasFormContentType == true` but 
httpContext.Request.Form return us InvalidDataException when we try to get value.

Other words there are situations when `httpContext.Request.HasFormContentType == true` but httpContext.Request.Form return us an Exception.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.WebApi.Core: 12.1.6

**Comment by thepirat000** [comment]
You're right, there are cases is which accessing the Form property will throw an exception.

But could you provide the entire exception message and stack trace?

**Comment by thepirat000** [comment]
Anyway I've put the Form retrieval within a Try/Catch on `InvalidDataException` (only for the asp.net core version). 

So you should get NULL on the `FormVariables` property instead of the exception.

Please upgrade to version 12.1.7. and re-test.

**Comment by akuzin87** [comment]
Hi! 
Sorry for the long answer.
I've tested you fix but it doesn't work. 
In my case we haven't call `context.Request.Form`. 
When we call `context.Request.Form` we change the internal stream position that give us the incorrect result. I've tested this fix and it looks correct in my case:
`       
        private static bool IsMultipartContentType(string contentType)
        {
            return !string.IsNullOrEmpty(contentType)
                   && contentType.IndexOf("multipart/", StringComparison.OrdinalIgnoreCase) >= 0;
        }

        private static IDictionary<string, string> GetFormVariables(HttpContext context)
        {
            if (!context.Request.HasFormContentType || IsMultipartContentType(context.Request.ContentType))
            {
                return null;
            }

            return ToDictionary(context.Request.Form);
        }
`

Sorry for code formatting but I could't format better.

**Comment by thepirat000** [comment]
First you wrote:

> httpContext.Request.Form return us InvalidDataException when we try to get value.

and then:

> In my case we haven't call context.Request.Form

So I'm confused now... Please provide the complete information and context needed to reproduce the issue so I can help (Stack trace, exception message and/or code to reproduce).
