### ISSUE TITLE
Question - How to use both Audit.WebApi and Audit.EntityFramework together

### ISSUE THREAD

**Issue by gato-negro** [thepirat000/Audit.NET#133]
Hi, this is not a bug but rather a question and since it is about more than one Audit.NET libraries i thought i should open it here. 

I am wondering if it is possible to use both Audit.WebApi and Audit.EntityFramework together.

I would like to store all activity in my EF DB using the Audit.EntityFramework storing each table's data in a corresponding table eg: Products-> ProductAudits, Categories -> CategoryAudits and the same time be able to log all WebApi calls to another table named eg WebApiAudits.

The problem is that although i set both of them i have to do something like this in my startup:

Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                    .AuditTypeNameMapper(typeName => typeName + "Audit")
                    .AuditEntityAction<IAuditFields>((ev, ent, auditEntity) =>
                    {
                        .................................
                    }));

            Audit.Core.Configuration.Setup()
                .UseSqlServer(config => config
                    .ConnectionString(Configuration.GetConnectionString("conStr"))
                    .Schema("dbo")
                    .TableName("WebApiAudits")
                    .IdColumnName("WebApiAuditId")
                    .JsonColumnName("Data"));

which means that the last overrides the previous. I could just log everything to WebApiAudits including EF Core Events but this would not be very helpfull in my case.

Is it possible somehow to set that i want to use Audit.EntityFramework for my EF DB logging and WebApiAudits table for WebApi requests logging?

**Comment by thepirat000** [comment]
I think this is duplicated, please check the issue https://github.com/thepirat000/Audit.NET/issues/118 to see if that solves your problem

**Comment by gato-negro** [comment]
This works great for me! Thank you!
