### ISSUE TITLE
Environment.UserName returns DefaultAppPool

### ISSUE THREAD

**Issue by rcheung9** [thepirat000/Audit.NET#134]
I'm using the `OnScopeSaving` to audit all updates to records.

The database context save is called from a WebAPI controller.  In the WebAPI controller, I get the username (Windows Authentication), but how can I pass that value to `OnScopeSaving`?

The `auditScope.Event.Environment.UserName` returns the username of the app pool running the IIS instance.

**Comment by thepirat000** [comment]
Do you target .net core or the full framework?

**Comment by rcheung9** [comment]
I'm using the full framework.  I get the username by `User.Identity.Name` in WebAPI.

I'll try the custom action.

**Comment by thepirat000** [comment]
ok.

You can also put the user name it in a [custom field](https://github.com/thepirat000/Audit.NET#custom-fields-and-comments):

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	scope.SetCustomField("IdentityName", User.Identity.Name);
});
```

**Comment by thepirat000** [comment]
You can try something like this, on your startup:

```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, IHttpContextAccessor httpContextAccessor)
    {
        //...
        app.UseMvc();

        Audit.Core.Configuration.Setup()
            .UseDynamicProvider(_ => _.OnInsert(ev =>
            {
                ev.CustomFields["IdentityName"] = httpContextAccessor.HttpContext.User.Identity.Name;
            }));
    }
}
```

**Comment by thepirat000** [comment]
Any update on this?

**Comment by rcheung9** [comment]
@thepirat000 It worked, thanks for your help.

**Comment by rcheung9** [comment]
Actually this sets a global variable.

So it does capture the username.  But if User2 spins up a session, all the values are set to User2.  If User3 spins up, then all User3.

Essentially it uses the latest user as Username, globally.

Is there a way to do this per transaction?

**Comment by thepirat000** [comment]
It's not global.. it's per HttpContext which is different for each individual HTTP request.

**Comment by thepirat000** [comment]
Any update on this?

**Comment by rcheung9** [comment]
I've been initializing it in `Session_Start` for each user.  And each subsequent user overwrote the previous one when saving the audit log.

You're saying I should create it for each `Application_BeginRequest`?

I'm using `Thread.CurrentPrincipal.Identity.Name` now which seems to work.

**Comment by thepirat000** [comment]
ok, so I think I can close this.

https://stackoverflow.com/questions/6810808/thread-currentprincipal-identity-vs-httpcontext-user-identity

https://www.hanselman.com/blog/SystemThreadingThreadCurrentPrincipalVsSystemWebHttpContextCurrentUserOrWhyFormsAuthenticationCanBeSubtle.aspx
