### ISSUE TITLE
Fire and Forget WebApi Audit Task Handle

### ISSUE THREAD

**Issue by MAliM1988** [thepirat000/Audit.NET#138]
Hi, this is not a bug but a question.

I Need To Know Audit.Net Support Fire and Forget Task Running for Audit WebApi Request/Response Or Not?

I need to be able to return a response if there is an error in the Auditing WebApi in data storage process ?

Thanks

**Comment by thepirat000** [comment]
I'm sure what do you mean with _Fire and Forget Task Running for Audit WebApi Request/Response_, if you mean async, yes it supports async methods. But the library does not provide any fire-and-forget mechanism by default. 

Didn't understand your last question, if you need special error handling on the data provider, you will need to implement your own data provider. Note that you can inherit from an existing Data Provider.

**Comment by thepirat000** [comment]
An implementation of a `SqlDataProvider` with fire-and-forget saving methods could be as follows. Please note this will not work for [CreationPolicies](https://github.com/thepirat000/Audit.NET#event-creation-policy) that uses the _replace event_ methods, like `InsertOnStartReplaceOnEnd`.

```
public class FireAndForgetSqlDataProvider : SqlDataProvider
{
    public AuditDataProvider FallbackProvider { get; set; }
    public FireAndForgetSqlDataProvider(Action<ISqlServerProviderConfigurator> c) : base(c)
    {
    }
    public override object InsertEvent(AuditEvent auditEvent)
    {
        Task.Run(() => 
        { 
            try { base.InsertEvent(auditEvent); } catch { }
        });
        return null;
    }
    public override async Task<object> InsertEventAsync(AuditEvent auditEvent)
    {
#pragma warning disable 4014
        Task.Run(async () =>
        {
            try { await base.InsertEventAsync(auditEvent); } catch { }
        });
        return Task.FromResult<object>(null);
#pragma warning restore 4014
    }
}
```

And then you configure it like:

```
var dp = new FireAndForgetSqlDataProvider(_ => _
	.ConnectionString("cnnstring")
	.TableName("table")
	.IdColumnName("id")
	.JsonColumnName("data"));
	
Audit.Core.Configuration.Setup()
	.UseCustomProvider(dp);
```

**Comment by thepirat000** [comment]
Assuming this is solved. If not, please reply.
