### ISSUE TITLE
ContainerNameBuilder?

### ISSUE THREAD

**Issue by Eneuman** [thepirat000/Audit.NET#14]
Hi and thanks for the awesome Audit package you created :)

We are creating a lot of audit logs in azure and we need to remove them when they reach a certain age.
Deleting the files one by one takes to long time. If there were a ContainerNameBuilder, I could create a new container per month, and delete this container after a certain time and all the files will be deleted with it :)

Another question: Whats the performance cost for auditing to azure blobs? Are you batching the updates? Runing the update async or on another thread?

Regards
//Per

**Comment by thepirat000** [comment]
Hi
Thanks for your comments and interest on this library.

I've added support for `ContainerNameBuilder`. Please get the latest version.

Alternatively, you could change the ContainerName on a custom action, for example:
```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	var azProv = (scope.DataProvider as AzureBlobDataProvider);
	azProv.ContainerName = "events-" + DateTime.Now.ToString("yyyy-MM");
});
```

The updates are not async nor batched. You should implement your own `DataProvider` if you need special storage handling.

Hope it helps

**Comment by thepirat000** [comment]
Reopening this because it seems to be not thread-safe.
Will be working on this

**Comment by thepirat000** [comment]
Added a _blob container_ intenal cache to make it thread-safe

Please use latest version >= 4.6.4
