### ISSUE TITLE
Audit.WebApi AuditIgnoreAttribute

### ISSUE THREAD

**Issue by MAliM1988** [thepirat000/Audit.NET#142]
Hi 

How can i use `AuditIgnoreAttribute` for ignoring some properties in ViewModel webapi parameters ?

thanks.

**Comment by thepirat000** [comment]
There is no AuditIgnoreAttribute for web api, but I will take a look to check if something like that can be implemented.

**Comment by thepirat000** [comment]
Note that if you use the [Global Filter](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#2--global-action-filter) you can setup an action that determines if an action should be logged.

**Comment by thepirat000** [comment]
I can only see three places where an `AuditIgnoreAttribute` could be placed:

- At the controller class level (to ignore all its actions)
- At the action method level (to ignore a particular action
- At the method parameters level (to ignore a particular action argument)

But you are asking for ignoring _some properties_ of the arguments, that will be a difficult task to accomplish generalically and efficiently. Also if you are using the default JSON.NET serializer, you can probably ignore the properties by decorating with [```[JsonIgnore]```](https://www.newtonsoft.com/json/help/html/PropertyJsonIgnore.htm) attribute.

**Comment by MAliM1988** [comment]
Hi

Thanks for suggest,my problem fixed with CustomAction
