### ISSUE TITLE
Exception info

### ISSUE THREAD

**Issue by evandro-santos** [thepirat000/Audit.NET#143]
Is it possible to include **Exception Stacktrace** on exception from auditevent  action?

 - Audit.WebApi

**Comment by thepirat000** [comment]
yes I think it could be included. I will take a look on Monday

**Comment by thepirat000** [comment]
The new version 12.3.0 is now including the entire string representation of the Exception, including the stack trace. 

I'm closing this, if you still have problems, please reply
