### ISSUE TITLE
[Question] - Automatic audit on savechangesasync?

### ISSUE THREAD

**Issue by blek-id** [thepirat000/Audit.NET#148]
Hi there, is there a possible way so that when a savechangesasync function is called, the audit automatically runs and gets the data for audit?

Oh and also, where is the output stored? I wanted to store it on SQL Server, i downloaded the package called Audit.NET.SqlServer as well, but I have no idea on how to use it (because i wanted automatic audit on each call for savechangesasync function)

Thanks in advance.

EDIT: I'm very new to using someone's work. I'm very sorry for the lack of knowledge.

**Comment by thepirat000** [comment]
I guess you mean EntityFramework's `SaveChangesAsync()` on `DbContext` class. 

For that, you have the EF extension for Audit.NET: [nuget](https://www.nuget.org/packages/Audit.EntityFramework/) | [docs](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#auditentityframework) 

It actually overrides the SaveChanges/SaveChangesAsync methods: [code](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/AuditDbContext.cs#L177)

**Comment by thepirat000** [comment]
The output is handled by a _Data Provider_, check the documentation [here](https://github.com/thepirat000/Audit.NET#data-providers).

Note there are [many built-in providers](https://github.com/thepirat000/Audit.NET#storage-providers) you can use, from SQL to Redis, including MySql, Postgre, UDP datagrams, Files, and so on...

Also the Audit.EntityFramework library includes a special Data Provider you can use if you plan to store the audit logs on the same database as the audited entities. Check the documentation [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider)

**Comment by blek-id** [comment]
Hello there,
I'm wondering Is there any way to store the audit on a different DB Context, and make some custom audit tables?

**Comment by thepirat000** [comment]
On the new version (12.3.4) you should be able to use a different DbContext to store your audits.

So for example, you have a DbContext to store some User information, that looks like this:

```c#
public class UserEntity
{
    [Key]
    public int Id { get; set; }
    public int Name { get; set; }
}

public class UserContext : DbContext
{
    public DbSet<UserEntity> Users { get; set; }
}
```

In order to enable auditing on your context, you can change your DbContext to inherit from `AuditDbContext`:

```c#
[AuditDbContext(IncludeEntityObjects = true)]
public class UserContext : AuditDbContext
{
    public DbSet<UserEntity> Users { get; set; }
}
```

And suppose you have a different DbContext where you are going to store the User table modifications:

```c#
public class AuditUserEntity : IAuditProperties
{
    [Key]
    public int AuditUserId { get; set; }
    public int UserId { get; set; }
    public int UserName { get; set; }

    // Extra audit columns:
    public string Action { get; set; }
    public string ModifiedBy { get; set; }
    public DateTime ModifiedWhen { get; set; }
}

public class AuditUserContext : DbContext
{
    public DbSet<AuditUserEntity> Audit_Users { get; set; }
}
```

Note the audit entity implements an interface for the common audit fields (Action, ModifiedBy and ModifiedWhen) this is not mandatory, but makes the configuration easier to set up.

Then the most important part is where you setup the DataProvider, this should be part of your startup logic:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .UseDbContext<AuditUserContext>()
        .AuditTypeExplicitMapper(map => map
            .Map<UserEntity, AuditUserEntity>((user, auditUser) =>
            {
                // Mapping between UserEntity and AuditUserEntity
                auditUser.UserId = user.Id;
                auditUser.UserName = user.Name;
            })
            //.Map<AnotherEntity, AnotherAuditEntity>(...)
            .AuditEntityAction<IAuditProperties>((ev, ent, audit) =>
            {
                // Set the common properties for all the audit entities
                audit.Action = ent.Action;
                audit.ModifiedWhen = DateTime.UtcNow;
                audit.ModifiedBy = Environment.UserName;
            })));
```
