### ISSUE TITLE
UseDbContext does not resolve my db context from ASP.NET Core's IoC container.

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#149]
**Describe the bug**
`.UseDbContext<MyAppAuditDbContext>()` does not request an instance of my MyAppAuditDbContext from the service provider. It tries to "new up" the context itself.

```
Unhandled Exception
System.MissingMethodException: Constructor on type 'WuitCMDB.Infrastructure.Data.MyAppAuditDbContext' not found.
```

I should never get this error, because the instance of `MyAppAuditDbContext` should have been resolved from the default dependency injection container.

**To Reproduce**
```csharp
  public class MyAppAuditDbContext : DbContext
{
    public MyAppAuditDbContext(DbContextOptions<MyAppAuditDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Audit_WuitInventoryAppliance> WuitInventoryServer { get; set; }
}

// Register the main DBContext and migration asssembly
services
    .AddDbContext<MyAppAuditDbContext>(options => {
        //options.UseLoggerFactory(MyLoggerFactory);
        options.UseSqlServer(Configuration.GetConnectionString(identityServerAuditConnectionStringKey), sql =>
        {
            sql.MigrationsAssembly(migrationsAssembly);
        });
    });

Audit.Core.Configuration.Setup()
    .UseEntityFramework(x => x
        .UseDbContext<MyAppAuditDbContext>()
        .AuditTypeNameMapper(typeName => "Audit_" + typeName)
        .AuditEntityAction<IAudit>((ev, ent, auditEntity) =>
        {
            // auditEntity is of IAudit type
            auditEntity.AuditDate = DateTime.UtcNow;
            auditEntity.AuditAction = ent.Action;
            return true;
        }));
```

**Expected behavior**
No error should have been thrown and my audit record should have been inserted.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework.Core Version="12.3.4"
 - Microsoft.EntityFrameworkCore Version="2.1.2"
 - Microsoft.EntityFrameworkCore.SqlServer Version="2.1.2"

**Comment by thepirat000** [comment]
Note that `UseDbContext` should only be called when your Audit entities are in a different DbContext than your audited entities. If you store the audit events on the same database and context, you just do not call `UseDbContext`.

**Comment by VictorioBerra** [comment]
Right. I wanted to use it so I can keep my audit trail in a separate more
locked down database.

Also, I was wondering if there were any strategies for sharing the same EF
models between my audit table and my regular entity. For example, if I have
to maintain a Customer and Audit_Customer that seems like a lot of code
duplication.

**Comment by thepirat000** [comment]
You could probably make your Audit entities inherit from the audited entities or from a common base. I see no other option to avoid duplication but any suggestion is welcome

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
