### ISSUE TITLE
Multitenancy?

### ISSUE THREAD

**Issue by Eneuman** [thepirat000/Audit.NET#15]
Hi!
Is there a way to set the connection string to the azure storage per request?

Our customers have there own azure storage accounts and we want to be able to store there own audit logs in there own azure storage. (They are using our SAAS webapi)

Regards
Per

**Comment by thepirat000** [comment]
You can add a custom action for each scope created, and change the connection string from there.

Something like this:
```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	var azProv = (scope.DataProvider as AzureBlobDataProvider);
	azProv.ConnectionString = "x";
});
```

**Comment by thepirat000** [comment]
Added a ConnectionStringBuilder
