### ISSUE TITLE
EntityFrameworkCore documentation says I can get TransactionId on the output, but I cannot find it.

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#153]
**Describe the bug**
Documentation shows things like a `ConnectionId`, and `TransactionId` [available on output](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/EntityFrameworkEvent.cs). But for 
`AuditEntityAction<T>` I am only given the following: `AuditEvent`, `Audit.EntityFramework.EventEntry`, `T`.

**To Reproduce**
```csharp
Audit.Core.Configuration.Setup()
    .UseEntityFramework(x => x                    
        .AuditTypeNameMapper(typeName => "Audit")                    
        .AuditEntityAction<IAudit>((auditEvent, eventEntry, auditEntity) =>
        {
            // auditEvent.TransactionId?
            // eventEntry.TransactionId?
        }));
```

**Expected behavior**
One of the `AuditEntityAction` params should be an [EFEntry](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/EntityFrameworkEvent.cs).

**Libraries (specify the Audit.NET extensions being used including version):**
 - Core 2.1.3
- Audit.EFC 12.3.5

**Comment by thepirat000** [comment]
For EF events, the actual `AuditEvent` type you will get, is `AuditEventEntityFramework`, so you can just access the EF events with:

```
.AuditEntityAction<IAudit>((auditEvent, eventEntry, auditEntity) =>
{
    var tId = (auditEvent as AuditEventEntityFramework).EntityFrameworkEvent.TransactionId;
}));
```

Or even shorter with:

```
using Audit.EntityFramework;
//...

.AuditEntityAction<IAudit>((auditEvent, eventEntry, auditEntity) =>
{
    var tId = auditEvent.GetEntityFrameworkEvent().TransactionId;
}));
```

**Comment by thepirat000** [comment]
You can also access the EF entity entry (`Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry`) with: 

`var entry = auditEvent.GetEntityFrameworkEvent().Entries[0].GetEntry();`

**Comment by VictorioBerra** [comment]
Documented via PR https://github.com/thepirat000/Audit.NET/pull/154

**Comment by VictorioBerra** [comment]
@thepirat000 How is that different than this?

.AuditEntityAction<IAudit>((auditEvent, eventEntry, auditEntity) =>
{
    eventEntry.Entity; // <----- this vs `auditEvent.GetEntityFrameworkEvent().Entries[i].GetEntry()`

**Comment by thepirat000** [comment]
oh, you're right. I got confused with the general Custom Actions... For the Entity Action, you could get the same with `eventEntry.GetEntry()`
