### ISSUE TITLE
EFCore docs say `IgnoreMatchedProperties` defaults to true, but code shows its false. Also no docs on how to use it.

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#155]
**Describe the bug**
My auditEntity has an auto incrementing Id which is causing an error. I went to learn how to enable IgnoreMatchedProperties and couldnt find any docs on how to, except for the docs that said it is true by default.

I was able to get things working with:
```csharp
(Audit.Core.Configuration.DataProvider as Audit.EntityFramework.Providers.EntityFrameworkDataProvider).IgnoreMatchedProperties = true;
```

**To Reproduce**
Try and use EFC core with an audit entry with a [Key] int Id.

**Expected behavior**
Docs should show IgnoreMatchedProperties is set to false, and an example on how to enable it.

**Comment by thepirat000** [comment]
sorry... the documentation was WRONG...
It is standard for this library to leave the default of all the configuration types with it .NET default.

i.e. all the boolean configuration defaults to false

**Comment by VictorioBerra** [comment]
Well, I'm still experimenting. But for now I'm copying over a ton of NON entity properties. Entity framework demands you have a primary key, and if you have `int Id` it's automatically an auto incrementing primary key but that is the issue, the code will try and set that on an insert which causes any error. But I think it's as easy as setting Id to 0.

Did I set that correctly above? I'm surprised I had to cast to do it.

**Comment by thepirat000** [comment]
You don't need to the casting. If you use the fluent API for the configuration, you could have something like this:

```c#
Audit.Core.Configuration.Setup()
  .UseEntityFramework(ef => ef
    .AuditTypeNameMapper(typeName => $"Audit_{typeName}")
    .AuditEntityAction((auditEvent, eventEntry, auditEntity) => 
    {
      // ...	
    })
    .IgnoreMatchedProperties());
```

Or:

```c#
Audit.Core.Configuration.DataProvider = new EntityFrameworkDataProvider()
{
	IgnoreMatchedProperties = true,
	// ...
};
```
