### ISSUE TITLE
[Audit.EntityFramework] Breaking the dependency on Microsoft.AspNet.Identity packages

### ISSUE THREAD

**Issue by hainguyenthanh** [thepirat000/Audit.NET#156]
Hi,

Thanks for the excellent work.

I'm thinking of one suggestion. Could you move the dependency on Microsoft.AspNet.Identity and Microsoft.AspNet.Identity.EntityFramework packages out of the Audit.EntityFramework? I guess the dependency exists because `AuditIdentityDbContext` needs it. But many projects using Audit.EntityFramework don't use ASP.NET Identity, and the dependency becomes redundant.

I suggest that the `AuditIdentityDbContext` implementation should be placed in its own package, Audit.EntityFramework.AspNet.Identity for example, for better separation of concerns.

Thank you.

**Comment by thepirat000** [comment]
Nice suggestion, thanks. The only downside is that it will break backwards compatibility, but I will take a look to move the identity part to a different package.

Get Outlook for Android<https://aka.ms/ghei36>



________________________________

**Comment by thepirat000** [comment]
The AuditIdentityDbContext integration was extracted to a different package starting on version 13.0.0 

Packages:
- [Audit.EntityFramework.Identity](https://www.nuget.org/packages/Audit.EntityFramework.Identity/)
- [Audit.EntityFramework.Identity.Core](https://www.nuget.org/packages/Audit.EntityFramework.Identity.Core/)
