### ISSUE TITLE
.NET core web API and invalid data format

### ISSUE THREAD

**Issue by PiGi78** [thepirat000/Audit.NET#157]
I see that if someone calls my .NET core web api with an invalid data format, the API responds with a BadRequest, but nothing appears on the log.

I suppose it depends from the ASP engine that validates the input before any filter.

There is a way to have it in the log?

Thank you in advance

**Comment by thepirat000** [comment]
Hi, I will work on providing a Middleware for that purpose on the next version, thanks for the suggestion

**Comment by thepirat000** [comment]
A middleware is provided now starting on version 13.1.0, please upgrade your references and check the documentation [here](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.WebApi#middleware).

You should be able to configure the [AuditMiddleware](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/AuditMiddleware.cs) to log requests that doesn't get into the MVC action.

If you are still having problems, please reply to this.
