### ISSUE TITLE
No GetCurrentAuditScope for ControllerBase

### ISSUE THREAD

**Issue by PiGi78** [thepirat000/Audit.NET#158]
I see that there are many extensions for have the current AuditScope in a controller.

Unfortunately there is no Extensions for the ControllerBase.
How can I have the current AuditScope within a ControllerBase?

Thank you in advance

**Comment by thepirat000** [comment]
I will change the extension method to be for `ControllerBase` instead. In the meantime you could get the scope by the extension method on `HttpContext`

On your controller: `var scope = this.HttpContext.GetCurrentAuditScope()`

**Comment by thepirat000** [comment]
Extension method moved to the ControllerBase, upgrade to version >= 13.1.2
