### ISSUE TITLE
failed to parse [action.responseBody.value]

### ISSUE THREAD

**Issue by henkosch** [thepirat000/Audit.NET#159]
**Describe the bug**

I'm using the global WebApi Action Filter to audit rest api requests into elasticsearch. 

I want to include the response body in the audit event, but I get a strange json exception when it tries to save the event.

**To Reproduce**

I have a controller like this for testing:
```c#
[ApiVersion("2.0")]
[Route("v{version:apiVersion}/admin/audit")]
public class AuditController : Controller
{
    [HttpPost("test")]
    public ActionResult Test()
    {
        return Ok(new
        {
            Success = true
        });
    }
}
```

I configured Audit.Net the following way:

```c#
services.AddMvc(options =>
{
    options.AddAuditFilter(config => config
        .LogRequestIf(rq => rq.Method != "GET" && rq.Path.Value.Contains("/admin/"))
        .WithEventType("api-action-admin-change")
        .IncludeHeaders()
        .IncludeRequestBody(c => !c.HttpContext.Request.HasFormContentType)
        .IncludeResponseBody()
        .IncludeModelState());
})
```

When I call the above endpoint with audit.net enabled, I get the following exception:

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLGNQINT0NNP", Request id "0HLGNQINT0NNP:00000001": An unhandled exception was thrown by the application.
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. ServerError: Type: mapper_parsing_exception Reason: "failed to parse [action.responseBody.value]" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a START_OBJECT at 1:960""
   at Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEventAsync(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
   at Audit.Core.AuditScope.SaveAsync()
   at Audit.WebApi.AuditMiddleware.AfterInvoke(HttpContext context, Boolean includeResponseBody, Exception exception)
   at Audit.WebApi.AuditMiddleware.InvokeNextAsync(HttpContext context, Boolean includeResponseBody)
   at Audit.WebApi.AuditMiddleware.InvokeAsync(HttpContext context)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

```
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. ServerError: 
Type: mapper_parsing_exception 
Reason: "failed to parse [action.responseBody.value]" 
CausedBy: 
Type: illegal_state_exception 
Reason: "Can't get text on a START_OBJECT at 1:960"
```

It seems that it somehow cannot process the ObjectResult from the response.

I have tried to add the following workaround:

```c#
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var action = (scope.Event as AuditEventWebApi)?.Action;
    action.ResponseBody.Value = JsonConvert.SerializeObject(action.ResponseBody.Value, Audit.Core.Configuration.JsonSettings);
});
```

This way it saves the audit event successfully, but the original api response becomes empty.

**Expected behavior**
Saves an Audit Event into Elasticsearch successfully containing the responseBody.value = {"success": true}

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET: 13.1.1
 - Audit.NET.Elasticsearch: 13.1.1
 - Audit.WebApi: 13.1.1

**Additional context**
I have checked that you are using BodyContent in AuditApiAction like this:
```c#
        [JsonProperty(Order = 42, NullValueHandling = NullValueHandling.Ignore)]
        public BodyContent RequestBody { get; set; }
        [JsonProperty(Order = 43, NullValueHandling = NullValueHandling.Ignore)]
        public BodyContent ResponseBody { get; set; }
```

The BodyContent of the request body contains a string value with the input json but the ResponseBody contains the actual returned object as a value. That is why I tried the workaround above which worked but the http response contained nothing after that.

I want to use the ActionFilter and not the middleware to have context information like ActionName.

**Comment by thepirat000** [comment]
I guess the problem is on the BodyContent.Value **object**, since elasticsearch will create an index for it  the first time a record is processed, and the engine will assume the object type received on that field will be the same for all the request.

Check this out https://github.com/thepirat000/Audit.NET/issues/152 for a workaround

**Comment by thepirat000** [comment]
Oh I see you already tried overriding the object type... Anyway I didn't understand what do you mean by  _the original api response becomes empty_, could you please explain?

Did you tried adding an _EnableRewind_ middleware?

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Use(async (context, next) => {  // <----
        context.Request.EnableRewind();
        await next();
    });
    
    app.UseMvc();
}
```

**Comment by henkosch** [comment]
I meant that the response that was received by the http client at the end was empty when I added the workaround. It was very strange. Not the audit event, but the response at the end of the http request.

Yes I have added EnableRewind, but that was only needed to mvc to be able to get the request body after the audit middleware read it. So it does not help.

Isn't it possible to let mvc create the response body string and use that in the audit event?

**Comment by thepirat000** [comment]
Oh I see... You were referring to the **Response** Body, sorry...

Maybe the problem is that the ResponseBody.Value is just a reference to the object generated by MVC [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/AuditApiAdapter.Core.cs#L148), so changing the ResponseBody.Value will change the MVC representation..

But I wonder why that affects the response you receive on the client. I'm still unable to fully reproduce this, but if I'm right, maybe I can provide a PreSerialization option for the ResponseBody on the audits.

**Comment by henkosch** [comment]
I’m using asp.net core 2.1 with .net core 2.1. Ok, I’ll try to create a minimal project.

**Comment by thepirat000** [comment]
Maybe you can share the client code first... I'm making tests with PostMan but cannot reproduce.

Also if you want, we can use the chat room here for faster response https://gitter.im/Audit-NET/Lobby

**Comment by henkosch** [comment]
You were right, the issue was that I was using the same eventType for every action that resulted in a locked schema mapping to the first responseBody that was written to the audit log. And when an other action was called with a different responseBody schema it was not possible to write it to the same index.

So firstly I chose to give a different eventType for every action based on the controller full namespace name and the action name. 

The difficulty was that I cannot use the built in {controller} and {action} templates because elasticsearch needs lowercase index names or I get: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. ServerError: Type: invalid_index_name_exception Reason: "Invalid index name [api-admin-User-UpdateUser], must be lowercase"

And also the {controller} is not enough for me, as I have many controllers with the same name in different areas and namespaces, even assemblies. So I need to generate a custom eventType.

I ended up with the following config:

```c#
// Add action audit
options.AddAuditFilter(config => config
    .LogRequestIf(rq => rq.Method != "GET" && rq.Path.Value.Contains("/admin/"))
    .WithEventType(e =>
    {
        var controller = e.Controller.GetType().FullName.CreateSlug();
        var action = (e.ActionDescriptor as ControllerActionDescriptor)?.ActionName.CreateSlug();
        var date = DateTime.UtcNow.Date.ToString("yyyy-MM-dd");
        return $"api-admin-{controller}-{action}-{date}";
    })
    .IncludeHeaders()
    .IncludeRequestBody(c => !c.HttpContext.Request.HasFormContentType)
    .IncludeResponseBody()
    .IncludeModelState());
```

And also I don't want to have the ResponseBody and the ActionParameters included as a document if it contains cascaded object values, so I added json serialization as an event filter.

```c#
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var action = (scope.Event as AuditEventWebApi)?.Action;
    
    // Serialize ResponseBody to json string
    if (action?.ResponseBody?.Value != null)
    {
        action.ResponseBody.Value = JsonConvert.SerializeObject(
            action.ResponseBody.Value,
            Audit.Core.Configuration.JsonSettings);
    }

    // Serialize ActionParameters to json string
    if (action?.ActionParameters != null)
    {
        var actionParameters = new Dictionary<string, object>();
        foreach (var param in action.ActionParameters)
        {
            actionParameters.Add(param.Key,JsonConvert.SerializeObject(
                action.ActionParameters[param.Key],
                Audit.Core.Configuration.JsonSettings));
        }
        action.ActionParameters = actionParameters;
    }
});
```

Also there is this strange bug that I got an empty http response. It was not because of the AddOnSavingAction, but because I was using the UseAuditMiddleware too, and it also has IncludeResponseBody. It seems that if both the AddAuditFilter and the UserAuditMiddleware has IncludeResponseBody turned on, the http response becomes empty.

I have created a sample project to reproduce the problem:
https://github.com/henkosch/auditnet-elasticsearch-bug-sample

See:
https://github.com/henkosch/auditnet-elasticsearch-bug-sample/blob/master/Startup.cs#L117

I will open a new bug report for that. Besides it would be great if there would be an option if I want to searialize the ResponseBody and ActionParameters to json or want to include them in the elasticsearch document, because it generates an exception when different schema is written to the same index.

**Comment by thepirat000** [comment]
Ok, but I guess the custom actions, the custom data providers and the elasticsearch dynamic mappings are enough to allow deciding what to include and how to serialize it. 

I still don't see a way to be specific for elasticsearch but generic for the audit event. I mean, different extensions (EF, WCF, WebApi, ...) logs different things on the audit event and it should contemplate any schema violation case.

Anyway if you have any suggestion for the implementation of the option you mentioned, please please let me know.
