### ISSUE TITLE
Improvement: Provide a migration to create the table automatically

### ISSUE THREAD

**Issue by facundofarias** [thepirat000/Audit.NET#166]
Hey hi,

I am just testing the project, I will be using it on .NET Core. The thing is that, for the SQL databases, I think it would be a good idea to include the migration file, that we can use on our projects, to create the events table, mostly because otherwise, when doing the initial setup, we have to:
1. Run migrations on the project,
2. Run manually the script to create the Events table.

Will try to provide a migration that works, what do you think? Would it be a good idea?
BTW, we are using EF Code First approach.

Thanks,
Facundo

**Comment by thepirat000** [comment]
I guess you are referring to the [`Audit.NET.SqlServer`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.SqlServer/README.md#table-constraints) extension.

The audit table schema is not imposed by the library, it's up to you, so I don't see a way to provide a generic migration. Do you?

Thanks

**Comment by thepirat000** [comment]
Closing this for now. If you have any suggestion please reply to this and I'll reopen the issue.
