### ISSUE TITLE
SaveChangesAsync Infinite Loop when Insert with DbUpdateException

### ISSUE THREAD

**Issue by ubeyou** [thepirat000/Audit.NET#168]
**Describe the bug**
SaveChangesAsync Infinite Loop when DbUpdateException.
Only happens in AuditDbContext, DbContext can't reproduce the bug.

**To Reproduce**
Adding an entry with the same primary key & save changes.

**Expected behavior**
It should return DbUpdateException just like how It works on DbContext

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET: 13.1.2
 - Audit.EntityFramework: 13.1.2

**Additional context**
1. I've tried to debug line by line, apparently the code itself loop back to the SaveChangesAsync.
When first received an exception, it went into SaveScopeAsync
https://github.com/thepirat000/Audit.NET/blob/34280b99348741bf713ec2f038947cea0a0b0dfe/src/Audit.EntityFramework/DbContextHelper.cs#L458

2. AuditScope.SaveAsync ()
https://github.com/thepirat000/Audit.NET/blob/34280b99348741bf713ec2f038947cea0a0b0dfe/src/Audit.EntityFramework/DbContextHelper.cs#L147

3. AuditScope.SaveEventAsync ()
https://github.com/thepirat000/Audit.NET/blob/929493b4360f5f792dffddaef2963ab715b8e1c1/src/Audit.NET/AuditScope.cs#L340

4.  await this._dataProvider.InsertEventAsync(this._event);
https://github.com/thepirat000/Audit.NET/blob/929493b4360f5f792dffddaef2963ab715b8e1c1/src/Audit.NET/AuditScope.cs#L433

5. await (auditDbContext as IAuditBypass).SaveChangesBypassAuditAsync()
https://github.com/thepirat000/Audit.NET/blob/09ca474a40995c3b0661bccc3fef4765f5972b39/src/Audit.EntityFramework/Providers/EntityFrameworkDataProvider.cs#L161

6. int num = await base.SaveChangesAsync();
https://github.com/thepirat000/Audit.NET/blob/f2264fe7f1a89909731262396e3d14d6af5ef78c/src/Audit.EntityFramework/AuditDbContext.cs#L196

step 6 will loop back to the SaveChangesAsync again & formed an infinite loop.

**Comment by thepirat000** [comment]
I was not able to reproduce exactly, but I I've found a problem and I think that's the cause of the issue. 

I'm assuming you use the `EntityFrameworkDataProvider` to save the audits on the same `DbContext` who has the audited entities.

Say you are saving a change on your context. If the change fails (i.e. DbUpdateException) then the framework still tries to save the audit before throwing the exception, but since you use the exact same context, the audit saving fails because the context detects the previous change and try to re-apply it.

Fortunately you could workaround it by indicating the framework you want to create a new context instance for each audit operation, with the `.UseDbContext<T>()` extension on the configuration api.

For example :

```C#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .UseDbContext<BlogsContext>()    // <---- ADD THIS LINE 
        .AuditTypeExplicitMapper(m => m
            .Map<Blog, BlogAudit>()
            .Map<Post, PostAudit>()
            .AuditEntityAction<IAuditEntity>((ev, entry, entity) =>
            {
                entity.AuditAction = entry.Action;
                entity.Exception = ev.GetEntityFrameworkEvent().ErrorMessage;
            })));
```

**Comment by ubeyou** [comment]
Thanks. It works after applied your workaround above.

Based on my observations, after applied the solution, 
The second time it loop SaveChangesAsync, EntityFrameworkEvent will become null & it will stop right there. The infinite loop stopped.
https://github.com/thepirat000/Audit.NET/blob/34280b99348741bf713ec2f038947cea0a0b0dfe/src/Audit.EntityFramework/DbContextHelper.cs#L444

**Comment by penihel** [comment]
I had the same problem. 

But, when i used UseDbContext i had another problem. Because i use transactions with System.Transactions on dotnet core 2.2. Two instances of my DbContext  throws this exception:

"This platform does not support distributed transactions."


So, i solved like this:

```c#
           
            Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
            {

                if (scope.Event.Environment.Exception != null)
                {
                    scope.Discard();
                }

            });
`

**Comment by Den4ikzxcv** [comment]
@penihel for me it doesn't work, but worked this approach:

```
 Audit.Core.Configuration.Setup()
     .UseEntityFramework(_ => _
     .AuditTypeMapper(t => typeof(AuditLog))
     .AuditEntityAction<AuditLog>((ev, entry, entity) =>
     {
         // To fix audit infinity cycle in case of DbUpdateException
         if (ev.Environment.Exception != null)
         {
             return false;
         }
         ...
    }).IgnoreMatchedProperties(true));
