### ISSUE TITLE
Audit.EntityFramework.Core: audit log still created on changes of ignored properties.

### ISSUE THREAD

**Issue by LUS1N** [thepirat000/Audit.NET#169]
**Describe the bug**
`AuditDataProvider.InsertEvent` gets called even though the only modified property is the ignored one. The `EntityFrameworkEvent` entry has 'Update' action but the changes list is empty. 

**To Reproduce**
FluentAPI setup, that I call in `Startup.cs` when configuring services:
```
Audit.EntityFramework.Configuration.Setup()
     .ForContext<ApplicationDbContext>(config =>
     {
          config.ForEntity<Invoice>(_ => _.Ignore(i => i.ModifiedAt));
       
      })
      .UseOptIn()
      .Include<Invoice>();
  
```

Then whenever I pull Invoice from the context, modify the `ModifiedAt` property and `context.SaveChanges();` my custom `InsertEvent` implementation gets invoked.

**Expected behavior**
I expect the insertEvent to not be called as if nothing on the entity was changed and context saved (which works as intended).

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework.Core: 13.1.2

**Comment by thepirat000** [comment]
This is by design. The audit saving is triggered for any call to `SaveChanges()` that causes a change in the database. 

But you can setup a custom action to be triggered after the event creation, so you have chance to `Discard` the event for those cases.

I think something like this could work:

```c#
Audit.Core.Configuration.AddOnCreatedAction(scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    if (!efEvent.Entries.Any(e => e.Action == "Insert" || e.Action == "Delete")
        && !efEvent.Entries.SelectMany(e => e.Changes).Any())
    {
        scope.Discard();
    }
});
```

**Comment by LUS1N** [comment]
@thepirat000 alright, thanks for the answer and it totally makes sense!

Maybe it could be documented though? In the part where the ignoring of properties is explained, could also have a note mentioning that the audit will still be triggered and link to the section with the piece of code you provided in the configuration part.

I could probably make a pull request next week for it if you are open to that.

**Comment by thepirat000** [comment]
yes please. appreciate that

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thepirat000** [comment]
Not sure if understand, I guess you are using the Audit.EntityFramework library to audit a `DbContext`.
 
The data providers (sqlserver, the ef provider, etc) are not responsible of determining what is going
to be logged, its purpose is to save audit events.

Anyway if you want to have custom logic on your data provider, you can create your own by inheriting from the base class `AuditDataProvider`, or from any of the existing data providers.

Another option you have to configure the output, is to manipulate the `AuditEvent` object before it is passed to the configured data provider, by using [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions), for example:

```c#
Audit.Core.Configuration.AddOnCreatedAction(scope =>
{
    var efEvent = scope.Event.GetEntityFrameworkEvent();
    foreach(var entry in efEvent.Entries)
    {
        // override the changes (only let those changed)
        entry.Changes = entry.Changes.Where(ch => ch.NewValue != ch.OriginalValue).ToList();
    }

    if (efEvent.Entries.All(entry => entry.Changes.Count == 0))
    {
        // completely discard the event if there are no changes
        scope.Discard();
    }

});
```
