### ISSUE TITLE
Only write changed properties to output with Audit.NET.SqlServer provider

### ISSUE THREAD

**Issue by ricodp** [thepirat000/Audit.NET#171]
Using the Audit.NET.SqlServer provider will successfully record changes to objects, but is it possible to only log those changed properties, and not every other property of the object?  Currently the entire object graph is written to the log, even when just one property changed.

I don't think using the EF provider is an option due to retrofitting to a large legacy project.  Though it could be worth looking at if output with the EF provider can also be made to JSON, not shadow tables - is this possible?

**Comment by thepirat000** [comment]
Not sure if understand, I guess you are using the Audit.EntityFramework library to audit a `DbContext`.
 
The data providers (sqlserver, the ef provider, etc) are not responsible of determining what is going
to be logged, its purpose is to save audit events.

Anyway if you want to have custom logic on your data provider, you can create your own by inheriting from the base class `AuditDataProvider`, or from any of the existing data providers.

Another option you have to configure the output, is to manipulate the `AuditEvent` object before it is passed to the configured data provider, by using [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions), for example:

```c#
Audit.Core.Configuration.AddOnCreatedAction(scope =>
{
    var efEvent = scope.Event.GetEntityFrameworkEvent();
    foreach(var entry in efEvent.Entries)
    {
        // override the changes (only let those changed)
        entry.Changes = entry.Changes.Where(ch => ch.NewValue != ch.OriginalValue).ToList();
    }

    if (efEvent.Entries.All(entry => entry.Changes.Count == 0))
    {
        // completely discard the event if there are no changes
        scope.Discard();
    }

});
```

**Comment by ricodp** [comment]
Thanks, to further clarify, if I had the following code:
  ```
 class AuditExample
    {
        var person = new Person() 
        {
            Name = "Bill",
            Address = "123 The Street",
            PhoneNumber = "08 080909"
        }

        using (AuditScope.Create("Person:Update", () => person))
        {
            person.Address = "321 The Road";
        }

    }
```
And was *not* using Audit.EntityFramework, instead using the Audit.NET.SqlServer.  Is it then possible to *only* log the Address Field in the log?  e.g. :

```
	"Target": {
		"Type": "Event",
		"Old": {
			"Address": "123 The Street"
		},
		"New": {
			"Address": "321 The Road"
		}
	}
```

If not, I'll look at customising the EF extension to write JSON to a single table, instead of shadow tables.

**Comment by thepirat000** [comment]
I see... There is no built-in mechanism for such thing (compare objects and get diffs), but you could probably complement with any comparer library, like [Compare-Net-Objects](https://github.com/GregFinzer/Compare-Net-Objects).

**Comment by thepirat000** [comment]
Just some thoughts...

Maybe you could implement your own audit event to hold the differences, inheriting from `AuditEvent`. Store the object getter and a snapshot of the value, so then you can compare the object with the updated version:

```c#
public class DiffAuditEvent : AuditEvent
{
    public DiffAuditEvent(Func<object> objectGetter)
    {
        ObjectGetter = objectGetter;
        var initialValue = objectGetter.Invoke();
        ObjectInitialCopy = JsonConvert.DeserializeObject(JsonConvert.SerializeObject(initialValue, Configuration.JsonSettings), initialValue.GetType(), Configuration.JsonSettings);
    }

    [JsonIgnore]
    public Func<object> ObjectGetter { get; set; }
    [JsonIgnore]
    public object ObjectInitialCopy { get; set; }

    public Dictionary<string, string> Old { get; set; } = new Dictionary<string, string>();
    public Dictionary<string, string> New { get; set; } = new Dictionary<string, string>();
}
```

`ObjectGetter` is a Func that returns the object to track, `ObjectInitialCopy` is a clone of the initial tracked object and `Old`/`New` are the dictionaries to be filled with the differences and to be serialized as part of the audit event.

In order to check the differences you can use the [Compare-Net-Objects](https://github.com/GregFinzer/Compare-Net-Objects) or any other library. The logic can be attached to a global [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) on the audit scopes:

```c#
private static CompareLogic _compareLogic = new CompareLogic() { Config = new ComparisonConfig() { MaxDifferences = 1000, ExpectedName = "Initial", ActualName = "Final" } };

static void Main(string[] args)
{
    Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
    {
        var diffEvent = scope.Event as DiffAuditEvent;
        foreach (var diff in _compareLogic.Compare(diffEvent.ObjectInitialCopy, diffEvent.ObjectGetter.Invoke()).Differences)
        {
            diffEvent.Old[diff.PropertyName] = diff.Object1Value;
            diffEvent.New[diff.PropertyName] = diff.Object2Value;
        }
                        
    });
}                
```

Then you can use any of the `AuditScope.Create` overloads that accepts a custom `AuditEvent`:

```c#
var options = new AuditScopeOptions() { EventType = "Person:Update", AuditEvent = new DiffAuditEvent(() => person) };
using (AuditScope.Create(options))
{
    person.Address = "321 The Road";
}
```

**Comment by thepirat000** [comment]
Closing this for now, if you're still having problems please reply to this.
