### ISSUE TITLE
Mongodb Datetime serialization

### ISSUE THREAD

**Issue by NTTLuke** [thepirat000/Audit.NET#173]
**Describe the bug**
Using version 12.1.6 I have the same issue described here https://github.com/thepirat000/Audit.NET/issues/114 (closed)

I have an external dll (with Audit.Net nuget reference) and a Web Api that uses it

**To Reproduce**
This is my setup inside Web Api 
```
 services.AddScoped( _ => {
                return new MongoDataProvider()
                {
                    ConnectionString = Configuration.GetSection("ConnectionStrings").GetValue<string>("Database"),
                    Database = "myAuditDb",
                    Collection = "myAuditCollection"
                     }
                };
            });
```

**Expected behavior**
Having the **Datetime UTC format** inside Mongodb instead of **String**
This is what I have when audit.net saves the document : 
```
{
 "start_date" : "2018-10-12T13:38:26.1469615+02:00", 
  "end_date" : "2018-10-12T13:38:26.1469744+02:00", 
}
```
this is the expected behaviour
```
{
 "start_date" : ISODate("2018-10-12T11:38:26.146+0000"), 
  "end_date" : ISODate("2018-10-12T11:38:26.146+0000")
}
```
I want to understand if I'm missing something inside the configuration

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.Net: 12.1.6
 - Audit.Net.MongoDb: 12.1.6

**Additional context**
n/a

**Comment by NTTLuke** [comment]
Hi you can close it .

I looked at the code reported into https://github.com/thepirat000/Audit.NET/issues/114  and I found the properly Converters.

Thank you

**Comment by thepirat000** [comment]
Can you share where do you set the "start_date" and "end_date" properties? 

Anyway I'm about to fix an issue on the deserialization of the custom fields for mongoDB provider, maybe it's related to that.

**Comment by thepirat000** [comment]
Please try with the latest version 13.1.4 and reply to this if you're still having problems.

**Comment by alejandrojrey** [comment]
Hi, i'm having this same issue.

The StartDate and EndDate properties are beeing saved as strings.

![image](https://user-images.githubusercontent.com/12596957/133635852-ce710da1-ac11-4e0f-b4bc-03a1fe3572e2.png)

This even happen with customs date properties.

Libraries:

Audit.Net: 18.1.5
Audit.Net.EntityFramework.Core
Audit.Net.MongoDb: 18.1.5
