### ISSUE TITLE
Schema Name Casing Issue

### ISSUE THREAD

**Issue by RKennedy9064** [thepirat000/Audit.NET#174]
**Describe the bug**
I've noticed that when specifying a schema name for PostgreSql and Audit.NET, it doesn't respect the casing of the schema. I've configured my application, but when Audit.NET tries to create the history, I get an error "PostgresException: 42P01: relation "ivrmm.Events" does not exist". Is there a way to get the schema to respect casing like TableName does? My configuration code looks like this.

`
Audit.Core.Configuration.Setup()
                .UsePostgreSql(config =>
                {
                    config.ConnectionString(GetDbConnectionString());
                    config.Schema("Ivrmm");
                    config.TableName("Events");
                    config.IdColumnName("Id");
                    config.DataColumn("Data", DataType.JSONB);
                    config.LastUpdatedColumnName("UpdatedDate");
                });
`

**Expected behavior**
I would expect the AuditContext to look generate the schema and table like so. "Ivrmm"."Events" instead of "ivrmm"."Events".

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 13.0.0
 - Audit.EntityFramework: 13.0.0

**Comment by thepirat000** [comment]
You're right, the schema was not being Quoted and that caused the issue. This was fixed on the latest version, please upgrade to the version 13.1.5 and try again.

If you're still having problems please reply to this
