### ISSUE TITLE
Document: Audit.EntityFramework and Audit.EntityFramework.Core: Allow mapping multiple entity types to the same audit type with independent actions. (#175)

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#176]
Help Wanted

Document examples of mapping multiple entity types to the same audit type with independent actions.

**Comment by thepirat000** [comment]
I've added an example on the [README file](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#map-multiple-entity-types-to-the-same-audit-type-with-independent-actions) and also there are some unit tests you can check:

[EF](https://github.com/thepirat000/Audit.NET/blob/master/test/Audit.EntityFramework.UnitTest/EfTestsCodeFirst.cs#L76)
[EF Core](https://github.com/thepirat000/Audit.NET/blob/master/test/Audit.EntityFramework.Core.UnitTest/EfCore21Tests.cs#L29)
