### ISSUE TITLE
Exception throws when 2 different foreign keys have same key name.

### ISSUE THREAD

**Issue by optivolveiqbal** [thepirat000/Audit.NET#178]
@thepirat000 

**Describe the bug**
The Audit.NET will throw an exception "An item with the same key has already been added. Key: xxxxxxx" (You may refer to below stack trace) 
The issue was found only occurs when any database change occurs to any table that has multiple foreign keys & these foreigns keys combine the same key.

Basically, the code at GetForeignKeys function will iterate each of the foreign keys retrieved from Metadata & add it up to the Dictionary. When a 2 combined foreign key ([FK1: EmployeeId, TenantId], [FK2: EmployeeTrusteeId, TenantId]) go through this iteration, the exception will be thrown at 2nd foreign key.

`  at System.Collections.Generic.Dictionary 2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary 2.Add(TKey key, TValue value)
   at Audit.EntityFramework.DbContextHelper.GetForeignKeys(DbContext dbContext, EntityEntry entry)
   at Audit.EntityFramework.DbContextHelper.UpdateAuditEvent(EntityFrameworkEvent efEvent, IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.SaveScopeAsync(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func 1 baseSaveChanges)`

**To Reproduce**
1. Create a 3 table as below relationship & perform a new creation to PettyCashTransaction table

![image](https://user-images.githubusercontent.com/42335678/48543013-8627f100-e8fb-11e8-8989-b3f6245f7643.png)

Script to create a table as below

USE [Demo]
GO

/****** Object:  Table [dbo].[Employee]    Script Date: 15/11/2018 5:26:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employee](
	[Id] [int] NOT NULL,
	[TenantId] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Employee] PRIMARY KEY CLUSTERED 
(
	[Id] ASC,
	[TenantId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK_Employee_Tenant] FOREIGN KEY([TenantId])
REFERENCES [dbo].[Tenant] ([Id])
GO

ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK_Employee_Tenant]
GO

USE [Demo]
GO

/****** Object:  Table [dbo].[PettyCashTransaction]    Script Date: 15/11/2018 5:26:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PettyCashTransaction](
	[Id] [int] NOT NULL,
	[EmployeeId] [int] NULL,
	[TrusteeId] [int] NULL,
	[TenantId] [int] NULL,
 CONSTRAINT [PK_PettyCashTransaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PettyCashTransaction]  WITH CHECK ADD  CONSTRAINT [FK_PettyCashTransaction_Employee] FOREIGN KEY([EmployeeId], [TenantId])
REFERENCES [dbo].[Employee] ([Id], [TenantId])
GO

ALTER TABLE [dbo].[PettyCashTransaction] CHECK CONSTRAINT [FK_PettyCashTransaction_Employee]
GO

ALTER TABLE [dbo].[PettyCashTransaction]  WITH CHECK ADD  CONSTRAINT [FK_PettyCashTransaction_EmployeeTrustee] FOREIGN KEY([TrusteeId], [TenantId])
REFERENCES [dbo].[Employee] ([Id], [TenantId])
GO

ALTER TABLE [dbo].[PettyCashTransaction] CHECK CONSTRAINT [FK_PettyCashTransaction_EmployeeTrustee]
GO

USE [Demo]
GO

/****** Object:  Table [dbo].[Tenant]    Script Date: 15/11/2018 5:26:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Tenant](
	[Id] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Tenant] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

**Expected behavior**
Audit trail record created without an exception thrown

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 13.2.1
 - Audit.EntityFramework: 13.2.1

**Additional context**
N/A

**Comment by thepirat000** [comment]
Do you target .NET Core and EntityFramework Core?

**Comment by optivolveiqbal** [comment]
Do you mean that what reference that I used in my project?

The Nuget package that is used is as below:

assemblyref://Audit.WebApi.Core (13.2.0)
assemblyref://Audit.EntityFramework.Core (13.2.0)

**Comment by thepirat000** [comment]
Can you share the classes on your EF model?

**Comment by thepirat000** [comment]
I was able to reproduce.. Will fix this soon

**Comment by thepirat000** [comment]
This was fixed on version 13.2.2, please upgrade package version and try again. Feel free to commend/re-open if you have any problem.

**Comment by optivolveiqbal** [comment]
Thanks @thepirat000!

The fix works like charm!
