### ISSUE TITLE
You can provide a .NET Framework demonstration？

### ISSUE THREAD

**Issue by BootsShu** [thepirat000/Audit.NET#179]
**Describe the bug**

**To Reproduce**
Steps or code to reproduce the behavior.

**Expected behavior**

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 13.0.0
 - Audit.EntityFramework: 13.0.0

**Additional context**

**Comment by thepirat000** [comment]
Not sure what do you mean, could you please elaborate on your issue?

**Comment by BootsShu** [comment]
I mean, I hope you can provide a Audit.NET Demo in the .NET Framework. please！
