### ISSUE TITLE
Use DateTime.UtcNow instead of DateTime.Now.

### ISSUE THREAD

**Issue by Xavier-Plasma** [thepirat000/Audit.NET#181]
`Event.StartDate` is assign with` DateTime.Now`. `DateTime.UtcNow` should be used instead, because this date is intended to be stored and not displayed to be read by a human being.
(PS: Thank you for this very usefull library)

**Comment by thepirat000** [comment]
You're right, all the dates should be UTC... I will fix that for the event Start and End dates and generate a new major version 14.0.0

**Comment by thepirat000** [comment]
This was fixed on version 14.0.0 please upgrade your references.
