### ISSUE TITLE
Add Schema property to EventEntry for EntityFramework

### ISSUE THREAD

**Issue by briancroth** [thepirat000/Audit.NET#182]
Would it be possible to add a Schema property to the EventEntry object for the EntityFramework output?  We use multiple schemas in our application, and some identical table names appear across schemas, so we need a way to differentiate them.

**Comment by thepirat000** [comment]
Yes, I think I can add that.. Will take a look. Do you use EntityFramework core?

Also note you can actually do it with a custom action (I didn't tested this code but I guess it should work):

```c#
Audit.Core.Configuration.AddOnCreatedAction(scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    efEvent.Entries.ForEach(entry =>
    {
        var schema = entry.Entry.Metadata.DefiningEntityType.Relational().Schema;
        entry.Table = $"{schema}.{entry.Table}";
    });
});
```

**Comment by briancroth** [comment]
Yes, we're using EF Core.  Thanks for the custom action - I'll give that a shot for now!  Long-term, I think it'd be nice to have Schema as a separate property from Table, but the logic to parse out the two is easy enough.  Thanks again!

**Comment by thepirat000** [comment]
The `Schema` property was added on version 14.0.1, please upgrade your references. Reply to this if you're still having problems.

**Comment by briancroth** [comment]
Works great!  Thanks for the quick turnaround!
