### ISSUE TITLE
.net core 2.1 version code for mysql as provider

### ISSUE THREAD

**Issue by KamranShahid** [thepirat000/Audit.NET#183]
In the sample and test code i can't find .net core 2.1 version code for mysql as provider.
Is there apdate available or i needed to compile whole code with .net core 2.1 version

**Comment by thepirat000** [comment]
I think this is fixed on vesion 14.0.1, now the `Audit.NET.MySql` library targets the same frameworks as the `MySqlConnector` library: netstandard1.3, netstandard2.0, netcoreapp2.1, net45 and net461. Please upgrade your references and reply to this if you're still having problems with the latest version.
