### ISSUE TITLE
ForEntity<T>.Format Still Includes in ToSJson

### ISSUE THREAD

**Issue by iamwyza** [thepirat000/Audit.NET#185]
**Describe the bug**
If you Specify an Entity to format a column value, it will *not* format that columns value when using ToJson()

**To Reproduce**

Configure The DbContext

```csharp
Configuration.Setup().ForContext<ApplicationDbContext>(config =>
                    config.IncludeEntityObjects()
                        .AuditEventType("{context}:{database}")
                        .ForEntity<ApplicationUser>(x => x
                            .Ignore(user => user.ConcurrencyStamp)
                            .Format(user => user.PasswordHash, pass => new string('*', pass.Length))
                            .Format(user => user.SecurityStamp, stamp => new string('*', stamp.Length))
                        )
                    )
                .UseOptOut()
```

Then Configure Logging:

```csharp
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .AuditTypeMapper(t => typeof(AuditLog))  
        .AuditEntityAction<AuditLog>((ev, entry, entity) =>
        {
            entity.AuditData = entry.ToJson();
            entity.EntityType = entry.EntityType.Name;
            entity.AuditDate = DateTime.Now;
            entity.AuditUser = Environment.UserName;
        })
	.IgnoreMatchedProperties(true));
```

Then do an update to ApplicationUser.  The Entity entry of the Json in AuditLog.AuditData will contain the unformatted version of PasswordHash and SecurityStamp and will include ConcurrentStamp.  The Changes and ColumnValues columns will be properly formatted/ignored however.

**Expected behavior**
Entity should also be modified to not contain these ignored or formatted properties.  The point of documentation is to mask sensitive things like passwords and yet it fails at doing exactly that.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 14.0.1

[Edit: fixing formatting]

**Comment by thepirat000** [comment]
Another option could be to mark the properties to ignore with [JsonIgnore](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonIgnoreAttribute.htm) from JSON.NET

**Comment by thepirat000** [comment]
Closing this considering this should be solved via custom actions / JsonIgnore attribute.

Feel free to reply if you're still facing problems.
