### ISSUE TITLE
Audit Log creates duplicate entries 

### ISSUE THREAD

**Issue by chiranthaw** [thepirat000/Audit.NET#187]
I have been using the AuditLog.Net for MongoDB in my project. I noticed that it saves duplicate audit entries when I use it as below. I am using Asynchronous methods.

`AuditScope auditScope = null;
            Department d = null;

            try
            {
                auditScope = await AuditScope.CreateAsync(AuditAction.Create.ToDescriptionString(), () => d);

                d = department;

                await _context.Departments.InsertOneAsync(department);
                await auditScope.SaveAsync();
            }
            finally
            {
                await auditScope?.DisposeAsync();
            }
            return department;`

Am I doing anything wrong here?

Thanks.

**Comment by thepirat000** [comment]
By default, the creation policy is set to _InsertOnEnd_ meaning that the events will be automatically saved when the `AuditScope` is disposed, but you are also calling the explicit `SaveAsync()` method, so you are seeing the audit saved twice.

Please read the Event Creation Policy documentation [here](https://github.com/thepirat000/Audit.NET#event-creation-policy).

- If you are going to use Manual creation policy, don't worry about disposing the audit scope, just call the `Save`/`SaveAsync` methods.
- If you are going to use the automatic saving (policy=InsertOnEnd) don't call the `Save`/`SaveAsync` methods unless you really want to save multiple times. You can rely on the disposal mechanism or explicitly call `Dispose`/`DisposeAsync` methods.

**Comment by chiranthaw** [comment]
@thepirat000 Thank you for your response. That explains. I got confused with below I guess.

[https://github.com/thepirat000/Audit.NET#asynchronous-operations](url)

**Comment by thepirat000** [comment]
You're right, I should probably remove the SaveAsync from that example.. That sample was more to show the async methods than to provide something usable.

Thanks
