### ISSUE TITLE
Support for .NETStandard version 1.0

### ISSUE THREAD

**Issue by Assisting** [thepirat000/Audit.NET#188]
I may be misunderstanding how this works, but if you can install Audit.Net in .NET Framework 4.5, shouldn't it work fine on anything targeting [.NET Standard 1.0 and above](https://immo.landwerth.net/netstandard-versions/)?

I just ask because the requirement for .NET Standard 1.3 would seem to correspond to Framework 4.6, but I'm sort of new to this whole Standard/Core thing.

**Comment by thepirat000** [comment]
There is no real correlation between the core and the full framework version

The library is currently only compatible with the net standard starting on version 1.3

**Comment by Assisting** [comment]
Ah, I see. In that case I'll target my custom dataprovider for 4.5. Thanks!
