### ISSUE TITLE
[Question] Response Header

### ISSUE THREAD

**Issue by MAliM1988** [thepirat000/Audit.NET#189]
Hi There 

How can save i log Response Header With Audit.WebApi? By default Request Header log and Response Header is Ignored.

**Comment by thepirat000** [comment]
Request Headers can currently be activated with [IncludeHeaders](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#settings-action-filter) option set to true.

I will work to add the Response headers, also optionally.

**Comment by thepirat000** [comment]
This was added on version 14.0.2, please upgrade your references and set the `IncludeResponseHeaders` configuration to _true_

**Comment by MAliM1988** [comment]
thanks a lot.
