### ISSUE TITLE
Audit.WebApi can`t work in selfhost webapi

### ISSUE THREAD

**Issue by pianzide1117** [thepirat000/Audit.NET#19]
Audit.WebApi can`t work in selfhost webapi , because use System.Web.dll as a reference.
It will fire a ArguementNullException, because HttpContext.Current is null.
I think using owinContext as a "WebContext" environment will make it more extensional.

**Comment by thepirat000** [comment]
Hi

Thanks for your comments!

This should be fixed now on version 4.9.0.

Feel free to re-open if you still have issues.
