### ISSUE TITLE
[Question] Does Audit.NET also manage Change Data Capture info?

### ISSUE THREAD

**Issue by weitzhandler** [thepirat000/Audit.NET#190]
Is [Change Data Capture](https://docs.microsoft.com/en-us/sql/relational-databases/track-changes/track-data-changes-sql-server?view=sql-server-2017#Capture) supported in Audit.NET?  
Any future plans on implementing that?

Thanks for this awesome library!

**Comment by thepirat000** [comment]
Hi, thanks for your comments.

CDC is an internal mechanism on SQL server, I can't see how it can be related to the library. Could you please give more details about your use case?

**Comment by weitzhandler** [comment]
Thanks for your quick response!
CDC audits and stores a record of the actual data that was stored upon each change. It's then possible to retrieve the historic data records and manipulate/restore them. This can be achieved by a set of [dedicated SQL functions](https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/change-data-capture-functions-transact-sql?view=sql-server-2017).

My suggestion is to implement this functionality in Audit.NET (EF), so that it provides features like:

- Enable CDC upon DB generation, by having the DB call the [appropriate functions](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sys-sp-cdc-enable-db-transact-sql?view=sql-server-2017) when EF has finished generating the DB.
- Allow defining a stamp column for the entity-audit record to be identified with, maybe this should work by having the entities implement an `IAuditable` interface, or having the audit columns configured via fluent API, for example: `builder.Entity<Person>().IsAuditable(stampCol: p.Stamp, creationDateCol: p.CreationDate, updateDateCol: p.UpdateDate);`
- Add extension methods to each `DbSet` for obtaining its CDC records, i.e. `dbContext.People.GetAuditEntities(p => p.Id == id && p.UpdateTime > DateTime.Now.AddDays(-3));`
- Add ex. methods that allows reverting an entity to its previous state/specific state, for example: `dbContext.People.RevertToLastState(p => p.Id == id);`

**Comment by thepirat000** [comment]
Looks like you are asking for an Entity Framework extension, or a CDC helper but not an Audit.NET extension. Audit.NET works for events that happens on .NET side and it generates the audits and decide when and where to save them. But CDC is completely handled at database level on the SQL server.

**Comment by weitzhandler** [comment]
I think you're right, and I'm closing this issue.  

However I'm hoping you could help me. I'm trying to intercept the action of EF finishing to create the database (either by `Database.EnsureCreated()` or `Database.Migrate()`. Is there a fair way to achieve that?
