### ISSUE TITLE
do not make the functions static

### ISSUE THREAD

**Issue by hiwjcn** [thepirat000/Audit.NET#191]
i prefer different audit instance with differnet data provider.
and works well with dependency injection components like servicecollection/autofac..........

api will be look like:

_userAudit.Log("user event")//save to es or mongodb
_orderAudit.Log("order event")//save to mysql(data more valueable)

thanks

**Comment by thepirat000** [comment]
Hi

Take into account this is not a simple logging library, if you are looking to log unrelated strings, I would recommend [Serilog](https://serilog.net/) or any other logging framework.

Also I don't think the static configuration is a problem for your use case. Assuming you want to log different event classes to different providers, one option is to use the `CreateAndSave` method passing the custom provider.

For example you could create your non:

```
// Uses Mongo
public class UserAudit
{
    private MongoDataProvider _mongoProvider;
    public UserAudit(MongoDataProvider mongo)
    {
        _mongoProvider = mongo;
    }
    public void Log(UserAuditEvent ev)
    {
        AuditScope.CreateAndSave("User", new { UserAudit = ev }, _mongoProvider);
    }
}

// Uses MySql
public class OrderAudit
{
    private MySqlDataProvider _mySqlProvider;
    public OrderAudit(MySqlDataProvider mySql)
    {
        _mySqlProvider = mySql;
    }
    public void Log(OrderAuditEvent ev)
    {
        AuditScope.CreateAndSave("Order", new { OrderAudit = ev }, _mySqlProvider);
    }
}
```

And you could configure your DI mechanism like this, for example:

```
services.AddSingleton<UserAudit>(new UserAudit(new MongoDataProvider(mongo => mongo
    .ConnectionString("mongo cnn string").Database("database"))));

services.AddSingleton<OrderAudit>(new OrderAudit(new MySqlDataProvider(mysql => mysql
    .ConnectionString("mysql cnn string").TableName("table"))));
```

**Comment by hiwjcn** [comment]
@thepirat000 thanks very much,wish you a good day
