### ISSUE TITLE
EfCore AuditScope in Transaction Scope

### ISSUE THREAD

**Issue by frkndmrts** [thepirat000/Audit.NET#192]
I'm using for Audit Log - EF Dbcontext - asp.net core api
But I have a problem and I need your help.

My Code :
`  try
            {
                _uow.BeginNewTransaction();
                var mesaj = new Mesajlar
                {
                    Mesaj = "new message",
                    UserName = "9900"
                };
                var entitiy1 = _repository.Add(mesaj);
                _uow.SaveChanges();

                var mesaj2 = new Mesajlar
                {
                    Mesaj = "new message2",
                    UserName = "8888",
                    UserNameTo = entitiy1.MesajId.ToString()
                };
                var entitiy2 = _repository.Add(mesaj2);
                _uow.SaveChanges();
                _uow.Commit();
            }
            catch (Exception)
            {
                _uow.RollBackTransaction();
            }`

my problem is  the first record is being saved.the whole transaction is rolled back if an error occurs while saving the second record.but in this case the log file is written.how do i get into a transaction AuditScope  using asp.net core api.Thanks.

**Comment by frkndmrts** [comment]
I UseElasticsearch provider.And not rollback

**Comment by thepirat000** [comment]
I still don't understand what are you trying to do. 

Also your code is very incomplete. You should include the configuration code and clarify what is __eow_

**Comment by frkndmrts** [comment]
OK. In summary,

My config is :
```
Audit.Core.Configuration.Setup()
                .UseElasticsearch(config => config
                    .ConnectionSettings(new Uri("http://localhost:32769/"))
                    .Index(auditEvent => auditEvent.EventType.ToLower())
                    .Id(ev => Guid.NewGuid()))
                .WithCreationPolicy(EventCreationPolicy.InsertOnEnd);
```
```
// Entity framework audit output configuration
            Audit.EntityFramework.Configuration.Setup()
                .ForContext<BapDbContext>(_ => _
                    .AuditEventType("{context}"))
                .UseOptOut();
```

```
 using (TransactionScope ts = new TransactionScope())
            {
                try
                {
                    //first entity insert
                    var message = new Mesajlar
                    {
                        Mesaj = "new message1",
                        UserName = "9900"
                    };
                    //_repository.add is Ef add generic method
                    var entitiy1 = _repository.Add(message);

                    //for example second insert
                    var message2 = new Mesajlar
                    {
                        Mesaj = "new message3",
                        //Use entity1 return Id
                        UserName = entitiy1.MesajId.ToString()
                    };
                    var entitiy2 = _repository.Add(message2);

                    ts.Complete();
                }
                catch (Exception)
                {
                    //Error
                   ts.Dispose();
                }
            }
```
As I said before,In transactionScope whole transaction is rolled back if an error occurs while saving the second record but first entity log to elasticsearch.Can we get them into the auditscope as in TransactionScope.in short I don't want to save log the savechanges method run.I want the log taken when the transaction is terminated .

**Comment by thepirat000** [comment]
I see. Problem is that Elasticsearch does not support transactions or the C#'s `TransactionScope`, so I see no way it can rollback automatically just by being under the `TransactionScope` scope. The EF audit mechanism triggers the event saving as soon as the `DbContext.SaveChanges()` is completed.

The only feasible solution could be to provide a mechanism for a delayed saving in some way, but cannot see a simple solution at the moment.

Anyway, it looks like on your transaction, you are doing just two operations on the same repository, probably on the same DbContext, so why do you use a system scoped `TransactionScope`?

**Comment by prasanthdasika** [comment]
is this issue resolved.?I am in the same situation. I have a series of transactions I save (save changes) and i only commit them in the end otherwise i roll them back.. audit should also rollback in the same situation.
