### ISSUE TITLE
Custom Data Providers and Dependency Injection

### ISSUE THREAD

**Issue by adamtay** [thepirat000/Audit.NET#194]
Hi, is there an example of how we could use dependency injection with our custom data providers? For example, injecting in `IHttpContextAccessor` or any services that may have many dependencies themselves?

Perhaps something along the lines of registering the custom data provider using:
```
Audit.Core.Configuration.Setup()
	.UseCustomProvider<MyCustomDataProvider>();
```

**Comment by thepirat000** [comment]
If you can resolve the data provider instance at startup (when you call `Audit.Core.Configure.Setup()`) then you should be able to provide an instance from the DI framework.

For example if you use ASP.NET you could do something like this on your startup code:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
    services.AddSingleton<AuditDataProvider, CustomDataProvider>();
    //...

    var svcProvider = services.BuildServiceProvider();
    Audit.Core.Configuration.Setup()
        .Use(svcProvider.GetService<AuditDataProvider>());
}
```

Another way could be to provide a way to pass a factory of Data Provider that resolves the instance right before the event saving, That is currently not implemented and I will need to take a look if it's feasible, so you could do something like: 

```
Audit.Core.Condiguration.Setup()
    .UseFactory(() => svcProvider.GetService<AuditDataProvider>());
```

but with the current version you have another option that is using a _dynamic data provider_ that allows to define the Insert and Replace methods at runtime, so you could do:

```
Audit.Core.Configuration.Setup()
    .UseDynamicProvider(x => x
        .OnInsert(ev =>
        {
            return svcProvider.GetService<AuditDataProvider>().InsertEvent(ev);
        })
        .OnReplace((id, ev) =>
        {
            svcProvider.GetService<AuditDataProvider>().ReplaceEvent(id, ev);
        });
```

**Comment by adamtay** [comment]
Great, thanks for the detailed explanation @thepirat000.

We've had to implement using the `UseDynamicProvider` option so that the service can be resolved during runtime given that out solution has a middleware that instantiates our _applications authentication provider_ based on the headers provided by the `HttpContextAccessor.`

From our authentication provider, we then write to various S3 buckets (custom data provider) based on the tenant of the http request.

**Comment by bdaniel7** [comment]
I'm working on a custom provider that just publishes the AuditEvent further, using IMediatr, to be processed.

So I need to inject IMediatr in the CustomAuditProvider. However, because the way Audit.Core.Configuration.Setup() is done, Mediatr loses some internal reference to IServiceProvider.

services.AddTransient<AuditDataProvider, CustomAuditProvider>();
or services.AddSingleton<AuditDataProvider, CustomAuditProvider>(); are not working either.

**Comment by bdaniel7** [comment]
I ended up injecting Autofac.IComponentContext in the CustomAuditProvider, and resolving the mediator in the calls to InsertEvent and InsertEventAsync.

**Comment by OriginatorStar** [comment]
> `nt`. An example of a custom field added via a custom action:
> 
> ```
> Audit.Core.Configuration.AddOnCreatedAction(scope =>
> {
>     var httpContext = svcProvider.GetService<IHttpContextAccessor>().HttpContext;
>     // Add extra information as custom fields to the event:
>     scope.SetCustomField("Headers", httpContext.Request.Headers);
> });
> ```
> 
> So all the audit events will include the Headers field.

Hi @bdaniel7 
How did you injected Autofac.IComponentContext in the CustomAuditProvider ?
Thanks.
