### ISSUE TITLE
Why does UseAuditCorrelationId exist when Action.TraceId is already available?

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#197]
The [output sample](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#output-sample) shows `Action.TraceId`.

The [WebApi Template shows](https://github.com/thepirat000/Audit.NET/blob/master/templates/WebApi/content/Audit.WebApi.Template/AuditConfiguration.cs#L69-L77) creating a `CorrelationIdField` custom field with `httpContext.TraceIdentifier`. Why would we want to do this twice?

**EDIT:** I think I see now. It looks like with EF, the `OnScopeCreated` override for AuditDbContext wont have that `AuditApiEvent` it will instead be a type of `EntityFrameworkEvent`. So I need a custom field to reach across events. Right?

**Comment by thepirat000** [comment]
Yes, that's correct. The WebAPI events already includes the trace identifier, but the EF events does not, so you could add a validation to only add the custom field if the event is an EF event:

```
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    if (scope.Event is AuditEventEntityFramework)
    {
        var httpContext = ctxAccesor.HttpContext;
        scope.Event.CustomFields[CorrelationIdField] = httpContext.TraceIdentifier;
    }
});

```

**Comment by VictorioBerra** [comment]
Oh I see, so if I go this route I am not getting anything out of `Audit.WebApi.Core`.

So there is no way to just snag the `Action.TraceId` in the `AuditDbContext` `override void OnScopeCreated()` . When you suggested using Audit.WebApi [here](https://github.com/thepirat000/Audit.NET/issues/196#issuecomment-458283549) I assumed it would provide a way to get the trace identifier automatically inside OnScopeCreated or on `EntityFramework.Configurastion.Api.AuditEntityAction`.
