### ISSUE TITLE
Using DisplayName attribute

### ISSUE THREAD

**Issue by Bykiev** [thepirat000/Audit.NET#201]
Hello, I'm new to EF audit and I have some questions:

1. How can I use property's DisplayName attribute instead of property name?
2. How can I set DisplayMember value for foreign key (ie: statusName instead of statusId)&
3. If I want to use 1 log table for all messages, what is the best way to analyze log then (ie: I have a list of products and I want to analyze price change)?

Thanks!

**Comment by thepirat000** [comment]
please try to be more specific, explain what are you trying to do. I cannot answer those questions, specially the last one since it totally depends on your design.

**Comment by Bykiev** [comment]
@thepirat000, sorry, I'll try to be more specific.
Let's imagine we have a simple Product model with 3 properties: Name, Count, CategoryId.
1. If I'll use AuditNET.EF as is, in the log old and new values will be this property's names. But I want to set DisplayName's attribute text (ie. Description instead of Name).
2. I don't want to save CategoryId in the log, instead I need a way to specify Category's Name property (ie: smth like DisplayMember(_=>_.Category.Name))
3. Seems it really depends and it's what I need to solve by myself

Thanks!

**Comment by thepirat000** [comment]
1. The Audit Event output for EF includes:

- The real Column Names and values on `EventEntry[].ColumnValues`
- The entity Property names and values on `EventEntry[].Entity` (Only when [`IncludeEntityObjects`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#settings) is set to `true`).

Depending on the [Data Provider](https://github.com/thepirat000/Audit.NET#data-providers) used, if you rely on the default JSON.NET serialization of the audit event, you could manipulate the serialized property names for the `EventEntry[].Entity`, with the [`[JsonProperty]` attribute](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonPropertyAttribute.htm) on your entity class:

```
class Product
{
    [JsonProperty("Description")]
    public string Name { get; set; }
    // ...
}
```

2. I think a plausible solution is to have the `.Category.Name` on the Product entity, so it's serialized as part of `EventEntry[].Entity`.

Also you have the [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions) to attach any logic you need before saving the event:

```
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    // you can modify the event here, bdefore it's saved...
    foreach (var entry in efEvent.Entries)
    {
        if (entry.Changes != null)
        {
            //...
        }

    }
});

```

**Comment by Bykiev** [comment]
1. Sorry, my example wasn't clear enough.. JsonProperty doesn't suits me, because I want to use DisplayMember attribute to log localized name of property
2. What about if user sends CategoryId, instead of Category entity? Do I need manually retrieve Category entity from database?

**Comment by thepirat000** [comment]
1. In that case you will need to implement the logic to retrieve and update the display name value. 

You can create a [custom data provider](https://github.com/thepirat000/Audit.NET#data-providers) inheriting from the built-in data provider you consider, overriding the `InsertEvent` methods to retrieve and update the DisplayName value there. Or do the same on a custom action.

I don't know which DataProvider fits your needs (EF data provider, SQL data provider, etc...) or where do you want to store your audit output, but you could create a new data provider class inheriting from the built-in Data Provider.

For example a helper to get the display name value for the properties:

```
public static void FixEvent(AuditEvent auditEvent)
{
    var efEvent = auditEvent.GetEntityFrameworkEvent();
    foreach (var entry in efEvent.Entries)
    {
        var localized = GetLocalizedPropertyValues(entry.GetEntry().Entity);
        entry.CustomFields["LocalizedProps"] = localized;
    }
}
private static Dictionary<string, object> GetLocalizedPropertyValues(object entity)
{
    var result = new Dictionary<string, object>();
    var props = entity.GetType().GetProperties();
    foreach(var prop in props)
    {
        var displayName = prop.GetCustomAttribute<DisplayNameAttribute>()?.DisplayName ?? prop.Name;
        result.Add(displayName, prop.GetValue(entity));
    }
    return result;
}
```

Then you can do:
```
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    FixEvent(scope.Event);
});
```

Or:

```
public class MyCustomProvider : EntityFrameworkDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        FixEvent(auditEvent);
        return base.InsertEvent(auditEvent);
    }
    public override async Task<object> InsertEventAsync(AuditEvent auditEvent)
    {
        FixEvent(auditEvent);
        return await base.InsertEventAsync(auditEvent);
    }
}

//...
Audit.Core.Configuration.Setup()
    .Use(new MyCustomProvider()
    {
        AuditTypeMapper = ...,
        AuditEntityAction = ...
    });
```
