### ISSUE TITLE
Audit.WebApi custom 

### ISSUE THREAD

**Issue by elincognito** [thepirat000/Audit.NET#202]
This is not a bug.

Is it possible to extend the Audit.Web to include an extra Property ?
Like stated in the doc `Extending AuditEvent`

**Comment by thepirat000** [comment]
Yes, you have the [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions) and the [Custom Fields](https://github.com/thepirat000/Audit.NET#custom-fields-and-comments) for that purpose. 

For example, on your WebApi startup:

```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, IHttpContextAccessor contextAccessor)
    {
        app.UseMvc();
        Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
        {
            var httpContext = contextAccessor.HttpContext;
            scope.GetWebApiAuditAction().CustomFields["CertName"] = httpContext.Connection.ClientCertificate.FriendlyName;
        });
    }
}
```

**Comment by elincognito** [comment]
Nice, thats exactly what i need,
But how would i do it in ASP.NET  Web Api ? I am not using .Net Core

**Comment by thepirat000** [comment]
It's almost the same. On your global.asax you could do for example:

```
        Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
        {
            scope.GetWebApiAuditAction().CustomFields["xxxx"] = HttpContext.Current...;
        });
}
```

**Comment by elincognito** [comment]
@thepirat000 thanks it works perfectly 👌
