### ISSUE TITLE
Request: Support Managed Identity on Azure Storage data providers

### ISSUE THREAD

**Issue by Eneuman** [thepirat000/Audit.NET#203]
Hi and thanks for your awsome library.

Since most of Azure services are moving over to supporting Managed Identities, it would be awsome if the dataproviders for azure storage would support this :)

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi

In short it works liks this:

```
// Get access token
var azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://management.azure.com/");

// Create storage credentials from your managed identity access token.
TokenCredential tokenCredential = new TokenCredential(accessToken);
StorageCredentials storageCredentials = new StorageCredentials(tokenCredential);

// Create a block blob using the credentials.
CloudBlockBlob blob = new CloudBlockBlob(new Uri("https://storagesamples.blob.core.windows.net/sample-container/Blob1.txt"), storageCredentials);
```

**Comment by thepirat000** [comment]
Support for Azure Active Directory for the BLOB data provider was added on version 14.1.0.

Note that the minimal .NET framework version support was changed for the `Audit.NET.AzureStorage` library: from netstandard1.3/net45 to netstandard1.4/net452.

Now you can do as follows:

```
Audit.Core.Configuration.Setup()
    .UseAzureBlobStorage(config => config
        .UseAzureActiveDirectory(adConfig => adConfig
            .AccountName("storagesamples")
            .TenantId("your tenant ID"))
        .ContainerName("event")
        .BlobNameBuilder(ev => $"{Guid.NewGuid()}.json"));
```

You can check the updated [documentation](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.AzureStorage/README.md#configuration-examples).

**Comment by Eneuman** [comment]
That's perfect :)
Thank you for your quick reply.
