### ISSUE TITLE
Query JSON Field and Get Results

### ISSUE THREAD

**Issue by klimentpetreski** [thepirat000/Audit.NET#206]
Not a issue but a question.

I Want to query the JSON Field in the MS SQL Database to filter result by using Audit.Net EntityFramework extension.
So far i was using T-SQL to query and get the results but was unable to map them properly.

Does The library provides methods for this or should i use LINQ .FromSql and map it manualy?

What approach should i use?

 - Audit.EntityFramework
 - Audit.MVC

**Comment by thepirat000** [comment]
Here is an example of how to query JSON on a SQL server:
https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.SqlServer/README.md#table-constraints
