### ISSUE TITLE
Unable to use Fluent API for Audit.EntityFramework without inheritance

### ISSUE THREAD

**Issue by Thorarin** [thepirat000/Audit.NET#207]
I'm trying to use the fluent API to configure my auditing for an EF Core DbContext, but I went for the no-inheritance option introduced in https://github.com/thepirat000/Audit.NET/issues/140. It seems the two cannot work together, due to generic type constraints not being met.

Am I missing something? In that case, it could be helpful to add it to the documentation.
I should still be able to use the workaround described in the aforementioned issue, but it's a bit of a shame :slightly_smiling_face:

**Comment by thepirat000** [comment]
The configuration of the audited Db contexts can be set via fluent API provided by:

`Audit.EntityFramework.Configuration.Setup()...`

And the output configuration can be set sia fluent API provided by:

`Audit.Core.Configuration.Setup().UseEntityFramework(config => config...)`

For example:

```
Audit.EntityFramework.Configuration.Setup()
    .ForAnyContext()
	.UseOptOut()
	.Ignore<AuditLog>();

Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .AuditTypeNameMapper(s => s + "Audit"));
```

Do you any specific problem?

**Comment by Thorarin** [comment]
I would like to set it up for a specific context, not for any context. However, I'm *not inheriting* from `AuditDbContext`, which seems to make that impossible using the fluent interface, due to generic type constraints.

I'm looking for the easiest way to accomplish this. While I'm typing I'm thinking that defining a separate class inheriting from `DefaultAuditContext` and setting up configuration for that is probably the least coding?

In any case, it might be good to mention the limitation and perhaps the workarounds for this specific case in the documentation?

**Comment by thepirat000** [comment]
Yes, the option you mention inheriting from `DefaultAuditContext` seems the more concise.

Anyway, why don't you inherit from `AuditDbContext` or why don't you want to use `ForAnyContext()`?

**Comment by simirajsp** [comment]
I would like to know whether there are any improvements on this lately. I don't prefer to inherit from DefaultAuditContext as I already have an inheritance hierarchy for my Contexts. Also, I couldn't use ForAnyContext as I have multiple contexts in my project and I would like to configure the OptIn strategy to configure entities to be audited. This should be set on individual contexts. Please let me know if there are any options other than inheriting context.

**Comment by thepirat000** [comment]
I think I can remove the type constraint with minimal impact, so you should be able to call `ForContext<T>` multiple times with your different DbContexts like this:

```c#
Audit.EntityFramework.Configuration.Setup()
    .ForContext<ContextOne>(_ => _
        .IncludeEntityObjects()
        .AuditEventType("Type 1"))
    .UseOptIn();

Audit.EntityFramework.Configuration.Setup()
    .ForContext<ContextTwo>(_ => _
        .IncludeEntityObjects(false)
        .AuditEventType("Type 2"));
```

**Comment by thepirat000** [comment]
The type constraint was changed to be `where T : DbContext` on version 16.5.4, please upgrade your references and re-test

**Comment by simirajsp** [comment]
Thanks a lot for the quick turnaround. I tried the latest update and it works perfectly!!!
