### ISSUE TITLE
Audit Web Api with Entity Framework

### ISSUE THREAD

**Issue by nfdevil** [thepirat000/Audit.NET#210]
I've succesfully implemented the Entity Framework Provider as provider for AuditLog entities by using the SaveChanges() override. These are also succesfully being saved to my database using the EF setup:

Startup.cs:
`
Configuration.Setup()
                .UseEntityFramework(config => config.AuditTypeMapper(mapper => typeof(AuditLog))
                    .AuditEntityAction<AuditLog>((auditEvent, entry, entity) =>
                    {
                        entity.EntityId = entry.GetEntry().Entity is IIdentifiable<int> identifiable
                            ? identifiable.Id
                            : (int?)null;
                        entity.EntityType = entry.EntityType.Name;
                        entity.Date = DateTime.UtcNow;
                        entity.UserId = auditEvent.CustomFields.GetValueOrDefault("UserId", null)?.ToString()
                            .ToNullableInt();
                        entity.EventType = auditEvent.EventType;
                        entity.Action = entry.Action;
                        entity.ComputerName = auditEvent.Environment.MachineName;
                        if (entry.Changes != null)
                        {
                            entity.Changes = JsonConvert.SerializeObject(entry.Changes.Where(e =>
                                !(e.NewValue == null && e.OriginalValue == null) && !e.NewValue.Equals(e.OriginalValue)));
                        }
                    }).IgnoreMatchedProperties());
`
DbContext:
`public override int SaveChanges()
        {
            AuditDbManager.SetCreatedModified(ChangeTracker.Entries());
            var result = _helper.SaveChanges(_auditContext, () => base.SaveChanges());
            AuditDbManager.IsCreatedOrModifiedBySystem = false;
            return result;
        }`

However, now I'm trying to add the WebApi provider. I've tried the AuditApi attribute on my controller and the AuditApiGlobalFilter configuration. When I set a breakpoint in the code of the WebApi attribute, I can see that it is called perfectly. Though it seems that it won't be saved in my database using the EntityFramework provider.

`                mvcBuilder.AddMvcOptions(options =>
                {
                    options.AddAuditFilter(config => 
                        config
                            .LogAllActions()
                            .WithEventType("{verb}.{controller}.{action}")
                        );
                });`

When I set a breakpoint in my `.AuditEntityAction` in the setup, it is called when I Insert or Update, using the EF Provider. But the save AuditLog is not being called when I call my Get() functions in my controller.

Is there something I am missing?

**Comment by thepirat000** [comment]
The problem is that the [Entity Framework Data Provider](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider) only works for Entity Framework Events. Any other event type (like WebApi events, etc) will be ignored by the EF Data Provider.

Check https://github.com/thepirat000/Audit.NET/issues/48, https://github.com/thepirat000/Audit.NET/issues/118 and https://github.com/thepirat000/Audit.NET/issues/139

**Comment by nfdevil** [comment]
So to get both events (EF and WebApi) logged in the same way, I have to setup a custom provider globally using SqlProvider that does the same as the EF provider is doing now, post to a Sql database table ‘AuditLog’. Both with the same configuration. This CustomProvider will be used by both then?

**Comment by thepirat000** [comment]
That's correct, if you use a single table for the audit EF events, it's almost the same than using the Sql DataProvider. Another option could be to implement your own custom data provider that selects the provider to use for each event.
