### ISSUE TITLE
Common implementation for multiple API in .NET Core

### ISSUE THREAD

**Issue by anandrajput007** [thepirat000/Audit.NET#212]
I am working in .NET Core application I have multiple API, I want to implement log for all API. Right now i have to write these code in all startup.cs file and also need to install Nuget package. 

             app.UseAuditMiddleware(_ => _
            .FilterByRequest(rq => !rq.Path.Value.EndsWith("favicon.ico"))
            .WithEventType("{verb}:{url}")
            .IncludeHeaders()
            .IncludeResponseHeaders()
            .IncludeRequestBody()
            .IncludeResponseBody());

            Audit.Core.Configuration.Setup()
            .UsePostgreSql(config => config
            .ConnectionString("Server=localhost;Port=5432;User Id=postgres;Password=1234;Database=postgres;")
            .TableName("auditlog")
            .IdColumnName("id")
            .DataColumn("data", DataType.JSONB)
            .Schema("log")
            .LastUpdatedColumnName("updated_date")
            .CustomColumn("module", ev => env.ApplicationName));

            Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
            {
                scope.SetCustomField("LoggedUserName", "ANAND");
            });
How can I do common implementation for all API?

Version I am using:
 - Audit.WebApi: 14.2.2

**Comment by thepirat000** [comment]
I guess you could simply create a common project with that initialization code and reference to the nuget packages... then just reference the common project on your different APIs.

For example, on the common project, an extension method:

```c#
public static void UseAudit(this IApplicationBuilder app)
{
    app.UseAuditMiddleware(_ => _
	.YourConfig()...);

    Audit.Core.Configuration.Setup()
        .YourConfig()...);

    Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
    {
        scope.SetCustomField("LoggedUserName", "ANAND");
    });
}
```

And on your API projects's startup:
```c#
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, IHttpContextAccessor contextAccessor)
    {
        //...
        app.UseAudit();
    }
```

**Comment by thepirat000** [comment]
I'm closing this. If you are still having problems regarding this, please reply here
