### ISSUE TITLE
ASP.NET Core Action Parameters

### ISSUE THREAD

**Issue by JaronrH** [thepirat000/Audit.NET#213]
**Describe the bug**
Controller Action Parameter serialization is trying to serialize services that are passed in using the [FromServicesAttribute].

**To Reproduce**
Import a service into a Controller Action using DI (Ex: your application DB context) then using ToJson() to serialize the event.

**Expected behavior**
I would expect services tagged with [FromServices] to be ignored.

**Comment by thepirat000** [comment]
makes sense! will work on that fix. In the meantime you could workaround with [AuditIgnore] attribute

**Comment by thepirat000** [comment]
This was added on version 14.2.3, please update your references and try again. Feel free to reply to this if you are still having problems.

**Comment by JaronrH** [comment]
Thank you!  Once I figured out that you targeted WebAPI instead of MVC, I was all set.  Thanks again for the quick turn-around!
