### ISSUE TITLE
This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.

### ISSUE THREAD

**Issue by danilovulovic** [thepirat000/Audit.NET#217]
**Describe the bug**
I use .NET Framework. I get this error:

> This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.

This error occurs when I include request body

**To Reproduce**
Only initial setup:

`config.Filters.Add(new AuditApiGlobalFilter(cfg => cfg
                .LogAllActions()
                .WithEventType(x => x.Request.RequestUri.PathAndQuery)
                .IncludeHeaders()
                .IncludeRequestBody()
                .IncludeResponseBody()));`

**Expected behavior**
Audit.NET should be able to read the request body

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 14.3.3

**Additional context**
`at System.Web.HttpRequest.get_InputStream()
↵   at Audit.WebApi.AuditApiAdapter.GetRequestBody(IContextWrapper contextWrapper)
↵   at Audit.WebApi.AuditApiAdapter.<BeforeExecutingAsync>d__1.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
↵   at Audit.WebApi.AuditApiGlobalFilter.<OnActionExecutingAsync>d__19.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()`

**Comment by thepirat000** [comment]
Did you see the following [NOTE](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#note) on the documentation?

> When **IncludeRequestBody** is set to true (or when using **IncludeRequestBodyFor** / **ExcludeRequestBodyFor**), make sure you enable rewind on the request body stream, otherwise the controller won't be able to read the request body since, by default, it's a forwand-only stream that can be read only once. You can enable rewind on your startup logic with the following code:

```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.Use(async (context, next) => {  // <----
        context.Request.EnableRewind();
        await next();
    });
    
    app.UseMvc();
}
```

**Comment by danilovulovic** [comment]
Thanks for super fast response.

I saw it, but I do not use .net core and there is no Rewind

**Comment by thepirat000** [comment]
Check this: https://stackoverflow.com/a/31395692/122195

`EnableRewind` is an extension on the package `Microsoft.AspNet.Http`

**Comment by danilovulovic** [comment]
I have tried but was not able to figure out how to set it up.

I have been searching through Github for similar approaches, and all found are for AspNetCore. There is no example for .NET Framework.

https://github.com/thepirat000/Audit.NET/blob/4d9e80f04e2cd1ee1cea2a57b7dc230e4dbeedd5/src/Audit.WebApi/AuditApiAdapter.cs#L121 
I'm wondering, will change in this method fix it. To set context.Request.InputStream.Position = 0 after reading it.

I will try to create sample project as reference

**Comment by thepirat000** [comment]
I'm trying to reproduce this, what .net framework version do you target? can you share the code of an action method that fails?

**Comment by thepirat000** [comment]
I was able to reproduce, but **only** if I explicitly set a _bufferless_ request body stream, for example via a [`BufferPolicySelector`](https://docs.microsoft.com/en-us/previous-versions/aspnet/hh995292(v%3Dvs.118)):

```c#
public class NoBuffer : WebHostBufferPolicySelector
{
    public override bool UseBufferedInputStream(object hostContext)
    {
        return false; // use a forward only (read only once) stream for the request body
    }
    public override bool UseBufferedOutputStream(HttpResponseMessage response)
    {
        return base.UseBufferedOutputStream(response);
    }
}
```

If I replace the default policy with the following code:

```c#
public static class WebApiConfig
{
    public static void Register(HttpConfiguration config)
    {
        config.Services.Replace(typeof(IHostBufferPolicySelector), new NoBuffer());
    }
}
```

So you get that exception when trying to access to the request body stream for the second time.

Are you overriding the `IHostBufferPolicySelector`? What type of hosting are you hosting? self-host, webhost, owin?

**Comment by danilovulovic** [comment]
No, I do not override IHostBUfferPolicySelector. 

I'm using owin.

I have tried to created new project from scratch and it is working as expected. It looks like there are some issues in middleware configuration.

`public void Configuration(IAppBuilder app)
        {
            //enable host of angular app within webapi project
            var root = AppDomain.CurrentDomain.BaseDirectory;

            var wwwroot = Path.Combine(root, "wwwroot");

            if (!Directory.Exists(wwwroot))
                Directory.CreateDirectory(wwwroot);

            var physicalFileSystem = new PhysicalFileSystem(wwwroot);

            var options = new FileServerOptions
            {
                RequestPath = PathString.Empty,
                EnableDefaultFiles = true,
                FileSystem = physicalFileSystem,
                StaticFileOptions =
                {
                    FileSystem = physicalFileSystem,
                    ServeUnknownFileTypes = true
                }
            };

            options.StaticFileOptions.FileSystem = physicalFileSystem;
            options.StaticFileOptions.ServeUnknownFileTypes = true;

            app.UseDefaultFiles();
            app.UseFileServer(options);

            //general configuration
            var config = new HttpConfiguration();

            FontFactory.RegisterDirectories();            

            ConfigureAuth(app);

            WebApiConfig.Register(config);
            app.UseCors(CorsOptions.AllowAll);
            app.UseWebApi(config);

            app.UseAutofacWebApi(config);

            app.MapSignalR();

            Audit.Core.Configuration.Setup().UseCustomProvider(new EZHomeDataProvider());

            Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
            {
                var currentUser = DependencyResolverInitializer.ResolveForWebApi<ICurrentUserProvider>().GetUser();

                scope.Event.CustomFields.Add("CurrentUser", currentUser);
                scope.Event.CustomFields.Add("Id", Guid.NewGuid());
            });
        }`

**Comment by thepirat000** [comment]
The project from scratch you created and worked fine, was also owin-hosted?

**Comment by danilovulovic** [comment]
No, webhost. I will try owin for project from scratch

**Comment by thepirat000** [comment]
if you get the exception, please share the project so I can check, but I'm afraid this is not an issue on the library but on your configuration

**Comment by thepirat000** [comment]
Maybe this can help: https://stackoverflow.com/questions/21805362/rewind-request-body-stream

**Comment by danilovulovic** [comment]
I'm not sure what is wrong with configuration, I need to spend some time to figure out.

What is interesting:

`public class NoBuffer : WebHostBufferPolicySelector
{
    public override bool UseBufferedInputStream(object hostContext)
    {
        return true;
    }
    public override bool UseBufferedOutputStream(HttpResponseMessage response)
    {
        return base.UseBufferedOutputStream(response);
    }
}`
If I return true, it works :)

**Comment by thepirat000** [comment]
I guess that is overriding some other middleware behavior you have, that is setting a non-buffered stream. Maybe try removing parts of your configuration/extensions and see if it works

**Comment by danilovulovic** [comment]
I will investigate the issue and let you know.

Anyway, thanks for help and effort to build this library. It is amazing.

**Comment by MfsiSumits** [comment]
> I will investigate the issue and let you know.
> 
> Anyway, thanks for help and effort to build this library. It is amazing.

What was the solution? I am also facing the same issue

Thanks,
Sumit
