### ISSUE TITLE
Audit.MVC CreationPolicy weirdness

### ISSUE THREAD

**Issue by jrlost** [thepirat000/Audit.NET#22]
Setting CreationPolicy to InsertOnEnd is behaving the same as setting it to InsertOnStartInsertOnEnd.  Specifically it appears to be firing the Insert event for OnActionExecuted and OnResultExecuted.  It is my understanding that InsertOnEnd should cause it to only fire the insert event when the scope is disposed, which happens in OnResultExecuted.

This is what I'm attempting to use:
```
Configuration.Setup()
	.UseDynamicProvider(config => config.OnInsert(auditEvent =>
		//Do something
	))
	.WithCreationPolicy(EventCreationPolicy.InsertOnEnd);
```

The result of this is that I'm getting nearly duplicate log entries. 

Thoughts?

**Comment by thepirat000** [comment]
Hi

Thanks! yes, there was a bug on mvc extension for creation policies other than manual, sorry.

It should be fixed now on v.4.10.0-*

Please use the [latest package](https://www.nuget.org/packages/Audit.Mvc/)
