### ISSUE TITLE
AuditInclude ignored when previously unmodified property is changed

### ISSUE THREAD

**Issue by nologinatgit** [thepirat000/Audit.NET#220]
I started to use _v14.3.4_ and I have the following model :

```csharp
  [Table(nameof(DataItem))]
  [AuditInclude]
  public partial class DataItem : IBaseItem
  {
    public DataItem()
    {
      Date = new DateTime(1900, 1, 1);
      VerifiedEntity = true;
    }
    private static string[] ranges = {"AA", "AB", "AABBCC"};
   
    private string subType;

    [StringLength(6)]
    public string SubType
    {
      get { return subType; }
      set
      {
        if (value == null 
          || ranges.Contains(value))
          subType = value;
        else
          throw new ArgumentException("Invalid range.", value);
      }
    }
...
}
```

I use the following audit configuration:

```csharp
Audit.Core.Configuration.Setup()
.UseEntityFramework(_ => _.AuditTypeMapper(t => typeof(DBInfo))
.AuditEntityAction<DBInfo>(async (ev, entity, auditEntity) =>
{
 auditEntity.ID = Guid.NewGuid();
 auditEntity.Time = DateTime.UtcNow;           
 auditEntity.Table = entity.Table;
 auditEntity.EventType = entity.Action;
 auditEntity.User = staticProperties.GetCurrentUser(); 
}).IgnoreMatchedProperties(true));
```

When I inserted a new entity, it was saved into a `DBInfo` entity without problems.

My model has some special property (like `SubType`), that can be changed via the UI, indirectly.
It is not a direct binding: the binding viewmodel property sets the value of the entity property.

```csharp
public class StoreItem
{
  public IBaseItem ActualDataItem { get; set;};
}
...
public string SelectedRangeItem
{
   get
   {
     return ranges[storeItem.ActualDataItem.SubType];
   }
   set
   {
      storeItem.ActualDataItem.SubType = ranges[value].Key;
   }
}
```
   

Whenever I change this `SelectedRangeItem` property and so changing the `SubType` indirectly , the audit code is _no longer called_ upon the save of the `DataItem` (though the `SaveChanges` override is hit). 

I can't see any exception.

I also examined the `DbContextHelper` instance on save, and I found the following.

When I don't set the special property, the `SaveChangesAsync` method is called twice and I see this on save:

![alt text](https://imgur.com/uGpEHLx.png "Without setting the property")

When I set, the `SaveChangesAsync` method is called twice and I see this on save:

![alt text](https://imgur.com/2KuBfj8.png "With setting the property")

What could cause this? Does it matter that the property is set via its interface?

**UPDATE**

I checked and even simpler entities are ignored when that particular UI component is used. The code is running on Android and when the `SubType` value is set, it is done with an _Activity_ navigation. So I presume, when the current Activity is _paused_, it somehow loses the Audit "instance" and it is gone when the user navigates back to set `SubType`. Am I correct?

**Comment by thepirat000** [comment]
I can't tell what the problem is... 

But having validations on the property getters of EF entities is a bad practice. 

Could you share a minimal project that reproduces the problem?

**Comment by nologinatgit** [comment]
Validations are on the setters, to avoid setting invalid values. I hope that is not that bad 🙂
I figured out what caused the anomaly.

I unintentionally reset the repository that handles the audit on navigation so when the UI was used, it _created a new repository (hence a new audit)_, so I lost all the modifications.

After fixing this, auditing works as expected 🙂
