### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames'

### ISSUE THREAD

**Issue by zacuke** [thepirat000/Audit.NET#225]
**Describe the bug**
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.2.4.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

**To Reproduce**
Deploy to Azure App Service

**Expected behavior**
No error

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.SqlServer: 14.5.2
 - Audit.EntityFramework.Core: 14.5.2
 - Audit.EntityFramework.Identity.Core: 14.5.2
 - Audit.NET: 14.5.2

**Additional context**
Microsoft has removed RelationalFullAnnotationNames from latest .net core libraries. Some info on this: https://github.com/aspnet/EntityFrameworkCore/issues/10759

The reference in file src\Audit.NET.SqlServer.csproj needs to to be updated to get it to stop using older .net core. I tested this and was able to deploy our app to Azure App Service with no further changes. I'm not sure why it works local and breaks on Azure, but probably differences in the installed .net core versions.

**Old reference, which needs Microsoft.EntityFrameworkCore.SqlServer.Design removed**
` <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="2.0.0-preview1-final" />
</ItemGroup>`

**Fixed reference**
`  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
  </ItemGroup>`

**Comment by thepirat000** [comment]
Thanks, this was fixed on version 14.5.3, please upgrade your references and try again with the new version.

**Comment by zacuke** [comment]
Thanks, it's working fine now.
