### ISSUE TITLE
Inject system time instead of hard-coding DateTime.UtcNow

### ISSUE THREAD

**Issue by justsquire** [thepirat000/Audit.NET#227]
Many of the components in dotnet now take an injected ISystemClock instead of hard coding the date to DateTime.UtcNow.  For my use cases, I often have a need for making time entries testable and have now started using ISystemClock as well.  Is there a way to modify the Start/End date of the events?  I tried using overriding OnScopeSaving on the AuditContext to update the Event StartDate but I couldn't find a reliable way to change the Event EndDate and have the duration calculated correctly still.

**Comment by thepirat000** [comment]
Sadly, there is no standarized `ISystemClock` interface, it's defined in multiple places, (check [this](https://github.com/aspnet/Extensions/issues/151) and [this](https://github.com/aspnet/Extensions/issues/745)) so I guess the best option will be to define a new `ISystemClock` as part of Audit.NET with the possibility to set the implementation as a static configuration.

**Comment by justsquire** [comment]
Yes, I ended up just defining my own ISystemClock interface as well.  Is there a better set of entry points to update/set the StartDate and EndDate until these changes could be implemented?

**Comment by thepirat000** [comment]
Yes, you should be able to change the `EndDate` and `Duration` from an [OnSaving Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions)

```
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    scope.Event.EndDate = DateTime.UtcNow;
    scope.Event.Duration = 1234;
});

```

**Comment by thepirat000** [comment]
The new version 14.5.5 now includes a static property `Audit.Core.Configuration.SystemClock` you can set with a custom implementation of [ISystemClock](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET/ISystemClock.cs)

**Comment by justsquire** [comment]
Wow, awesome!  Thank you so much!
