### ISSUE TITLE
CallingMethod and Assembly are one frame too high when using extensions

### ISSUE THREAD

**Issue by jrlost** [thepirat000/Audit.NET#23]
When using some extensions which implement attributes(currently at least Audit.Mvc and Audit.WebApi) and an action is audited, the record that is created contains something like this

```
        "AssemblyName": "Audit.Mvc, Version=4.10.0.0, Culture=neutral, PublicKeyToken=null",
        "CallingMethodName": "Audit.Mvc.AuditAttribute.OnActionExecuting()"
```

If you explicitly create the auditScope, it works as expected(meaning it references my assembly and calling method)

Guessing it's breaking because AuditScope.cs is hardcoded to 2, when, if coming from an attribute in this case, the stack would be one level deeper.
```
var callingMethod = new StackFrame(2).GetMethod();
```

This is super low priority however, I'm getting beautiful audits and they currently include the correct Controller and Action.  Having the assembly and method would simply be sugar on top.

Thanks again for an awesome product.

**Comment by thepirat000** [comment]
Hi @jrlost

Thanks a lot for your comments!

Following up on this, invokers like the Web Api or MVC Action Filters will not include the calling method on the Stack, so it cannot be used forthat purpose. Even for WCF this is not possible. 

![image](https://cloud.githubusercontent.com/assets/9836380/21671914/75067d12-d2e4-11e6-995a-d02ebf7242cb.png)

The only extension that could be fixed to include the real calling method is the Audit.EntityFramework, will work on fixing that one at least...

For MVC/WebAPI/WCF the solution could be to override the calling method and assembly on the [enviroment object](https://github.com/thepirat000/Audit.NET#environment-object).

**Comment by thepirat000** [comment]
Now this is fixed for MVC, WebApi and WCF.

Enviroment _CallingMethodName_ and _AssemblyName_ should have the right method.

Please use version >= 5.0.0
