### ISSUE TITLE
GetCurrentAuditScope null

### ISSUE THREAD

**Issue by Jacquers** [thepirat000/Audit.NET#230]
I have a common controller base which my other controllers inherit from. There are some things I want to set automatically, e.g. user info and some custom fields on the audit context.

I have an override method, but the audit scope is always null in there. If I get the audit scope in the actual controller method (after the override) it is there. But I would prefer not having to duplicate the setting of the custom fields in every controller method or to have to call a method in my common base controller as this can easily be forgotten when adding a new method.

This is in a .net core project.

Any ideas? Thanks :)

public override void OnActionExecuting(ActionExecutingContext context)
        {
            _userInfo = new UserInfo();

            _controllerName = context.Controller.GetType().Name;
            
            SetUserInfo();
            
            var auditScope = this.GetCurrentAuditScope(); // null

            base.OnActionExecuting(context);

            auditScope = this.GetCurrentAuditScope(); // still null
        }

**Comment by Jacquers** [comment]
I tried setting the custom fields on the audit scope in the following method: public override void OnActionExecuted(ActionExecutedContext context) but by then the InsertEvent has already fired. public override object InsertEvent(AuditEvent auditEvent)

I assume this has something to do with the life cycle, etc.

**Comment by Jacquers** [comment]
Just a bit more info. I've read up a bit about ActionFilters and I can see from the order that the Audit Attribute has a lower order. 

![ActionFilter Debugging](https://user-images.githubusercontent.com/31434053/61446169-0b621a80-a94f-11e9-85a2-487ae038760a.png)

**Comment by thepirat000** [comment]
Did you tried with:

```
[AuditApi(Order = int.MinValue)]
public class YourController : Controller
```

**Comment by thepirat000** [comment]
Hi, the default order was changed to be `int.MinValue` starting on version 14.5.7.
