### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations' not found using .net core 3.0 preview

### ISSUE THREAD

**Issue by alanwales** [thepirat000/Audit.NET#231]
**Describe the bug**
Exception thrown by Audit.Net library when saving changes using latest .net core 3.0 preview (3.0.100-preview6-012264).

**To Reproduce**
Add Audit.Net to library target netcoreapp3.0. I tried with both approaches of deriving from AuditDbContext and without inheritance.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework 14.5.7

**Additional context**
Stacktrace:

Unhandled Exception: System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.IRelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Audit.EntityFramework.DbContextHelper.GetEntityName(DbContext dbContext, EntityEntry entry)
   at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChangesAsync(CancellationToken cancellationToken)

**Comment by thepirat000** [comment]
Hi, I will take a look, but in general, I try to avoid giving support to MS preview releases since they are too volatile and I end up working in vain with things that quickly and completely changes :(

**Comment by thepirat000** [comment]
Problem is that many of the Relational* classes (such as [RelationalMetadataExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.relationalmetadataextensions?view=efcore-2.1) where the [`Relational()`](https://github.com/thepirat000/Audit.NET/blob/03617192e5ca3c005fbd5a46f26077a47e4d5d12/src/Audit.EntityFramework/DbContextHelper.Core.cs#L148) extension lives) are not defined on the 3.0 preview version of `Microsoft.EntityFrameworkCore.Relational`... I cannot find any useful documentation (as usual with MS) but I guess they will be deprecating them without notice on the final release, so I'll need to change the logic to obtain the entity name for this use case.

I'm still checking for workarounds/solutions, but don't expect this to be fixed until the final EF Core 3 version is released.

**Comment by thepirat000** [comment]
The temporal workaround is to directly reference 2.2.* version of `Microsoft.EntityFrameworkCore` on your application, i.e.:

```
  <ItemGroup>
    <PackageReference Include="Audit.EntityFramework" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
  </ItemGroup>
```

**Comment by bankian** [comment]
Just wanted to give a +1 on this.  

I'm getting the same error (as you'd probably expect) with preview7.
We're wedded to Blazor for the project we're currently working on, and so  are having to be on the bleeding edge, using all the preview releases; so I don't think the workaround above will work for us.

I've been tasked with investigating auditing options and audit.net seems like it could be a great solution for us - just hope you're able to find a solution to this issue before we have to implement something :-)

Thanks for all your work on this.

Ian

**Comment by thepirat000** [comment]
I've added EF Core 3 support on version 14.6.0, but in order to use the 3.0 preview version of EF Core, you **must** reference `Audit.EntityFramework.Core` instead of `Audit.EntityFramework`.

I'm letting it like this to support the two use cases:
- Target Net Core 3 but want to use EF Core 2 (reference `Audit.EntityFramework`)
- Target Net Core 3 and use EF Core 3 preview (reference `Audit.EntityFramework.Core`)

This is subject to change once MS releases EF Core 3.

FYI: [This](https://github.com/aspnet/EntityFramework.Docs/blob/master/entity-framework/core/what-is-new/ef-core-3.0/breaking-changes.md#forsqlserverhasindex-replaced-with-hasindex) was very useful for the implementation change

**Comment by bankian** [comment]
Now working.  I hadn't spotted the new version that arrived yesterday.
Thank you!  
Ian

**Comment by trikk86** [comment]
Hi
I have the same issue:
Audit,EntityFramework,Core  15,2.3
Why does it reference EF 2.2.4.0?

or am I missing something?

**Comment by trikk86** [comment]
I have a similar issue with Audit,Entityfranework.Core 15.2.3 with Microsoft,EF 3.1.3
