### ISSUE TITLE
SqlParameterCollection error

### ISSUE THREAD

**Issue by Psimatrix** [thepirat000/Audit.NET#234]
**Describe the bug**
System.InvalidCastException: 'The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.'

**To Reproduce**
using NETCORE 3 preview7 within a blazor application, I am getting this error when I simply configure the Audit setup and execute the most basic command to save data to audit table

AuditScope.CreateAndSave("Hello World", new { ExtraField = "Hello World" });

**Expected behavior**
Expect a audit entry in my database.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
Audit.net
audit.net.sqlserver
audit.webapi.core

**Additional context**
setup is as follows
Audit.Core.Configuration.Setup()
                .UseSqlServer(config => config.ConnectionString(connectionString)
                    .Schema("dbo")
                    .TableName("Logs_Audit")
                    .IdColumnName("EventId")                    
                    .JsonColumnName("JsonData")
                    .LastUpdatedColumnName("LastUpdatedDate"));

NOTE: if I setup a simple console application that isn't representing Audit libraries with Netcore3 preview7 everything works as expected. I get a audit entry to save to database. However with preview 7 I get the mentined error. For grins I added the call stack.

![image](https://user-images.githubusercontent.com/5118386/62346542-1cb53600-b4bc-11e9-8725-9cb5f872b70d.png)

**Comment by thepirat000** [comment]
Yeah, I guess `Audit.SqlServer` does not support net core 3 preview (actually the problem is with the library `Microsoft.EntityFrameworkCore.Relational`). I've provided a similar fix for Audit.EntityFramework issue #231 and will take a look

**Comment by thepirat000** [comment]
New `Audit.SqlServer` version (14.6.1) supporting Entity Framework 3 preview 7 was released, please upgrade your references.

**Comment by Psimatrix** [comment]
Your last updates for preview7 has fixed my problem as well. Thanks for getting this up and running so quickly. hopefully there won't be so many breaking changes with preview8 when it comes out. :)
