### ISSUE TITLE
EventEntry.ToJson() tracks all properties at changes when Entity.State sets to Modified

### ISSUE THREAD

**Issue by arslanaybars** [thepirat000/Audit.NET#235]
Hey Federico 👋

I realize one thing. It may work as expected fine but I don't think so.

Before we are updating an entity. If we set our entity object's EntityState as Modified. Audit writes as all the properties into Json's changes array. Actually, I only changed 1 or 2 property.

Let's see with an example;

```
public class Category : AuditableEntity<int>
{
    public string Title { get; set; }

    public string Description { get; set; }

    // .. more prop goes ..
}
```

```
// Let's say I retrieved category object from the data source in the category variable
category.Title = "new updated title"; 
// We don't updated any other props.
_context.Entry(category).State = EntityState.Modified;
await _context.SaveChangesAsync()
```

My expectation to see only category title in the Json's changes array but all of the category property will be there. 😔

Thanks for the great projects and helps! 🚀🚀🚀

**Comment by thepirat000** [comment]
Have you seen #53 ?

**Comment by arslanaybars** [comment]
First I inspired about something from #53 but it didn't solve my problem. 😔

I found a way to solve my issue. I don't know how is logical or effective but for now, it solves the problem. please review and let me know if something goes wrong with the way.

Solution: 🚀
I realize when we set the entity.state as modified ef sets all entry property's modified flag as true except PK. So I looped the props and checked which modified, if the prop is not modified, changed the IsModified as false. 

Before base.SaveChanges()
 ```
// we can add this logic to another method to make cleaner overrided SaveChanges method
foreach (var entityEntry in ChangeTracker.Entries())
{
    foreach (var e in entityEntry.Properties.Where(x => x.IsModified))
    {
        e.CurrentValue = e.CurrentValue ?? "null";
        e.OriginalValue = e.OriginalValue ?? "null";
        e.IsModified = !e.CurrentValue.Equals(e.OriginalValue);
     }
}

base.SaveChanges();
```

**Comment by thepirat000** [comment]
I'm not sure about that code... But if you retrieve the category object from the data source just before the update, that shouldn't be needed, and EF should keep track of the modified properties (no need to set the State to Modified explicitly). How do you retrieve the category in the first place?

**Comment by arslanaybars** [comment]
I retrieved by using dbcontext. 

> var category = context.Categories.FirstOrDefault()

then I changed the only Title property.

> _context.Entry(category).State = EntityState.Modified;

and SaveChanges();

**Comment by thepirat000** [comment]
I don't get it... If you _only_ change the Title property, why would you want to track the unmodified properties?

This should be enough;

```
var category = context.Categories.FirstOrDefault()
category.Title = "new title";
context.SaveChanges();
```

**Comment by arslanaybars** [comment]
Yes, you are right. But if I don't set Entity State as modified (I think even if we set it should not break changes), somehow changeTracker.Entries() elements are not set to modified. 
I also override SaveChanges. If my entity updated I need to know it to update run some internal logic.

But to anyone usage, I solve it by using the following lines before called base.SaveChangesAsync(cancellationToken);

```
foreach (var e in changedEntity.Properties.Where(x => x.IsModified))
{
    e.CurrentValue = e.CurrentValue ?? "null";
    e.OriginalValue = e.OriginalValue ?? "null";
    e.IsModified = !e.CurrentValue.Equals(e.OriginalValue);
}
```

I also don't get it why it is happening. I can close the issue, probably it is a specific case don't know why? 

Thanks for your time.
