### ISSUE TITLE
Number and Date Ignore Malformed

### ISSUE THREAD

**Issue by bturner1273** [thepirat000/Audit.NET#236]
So I am trying to use Audit.EntityFramework and Audit.Net.Elasticsearch with an asp.net core 2.2 web app and am having trouble with mapper parsing. It seems to get hung up on dates and numbers. I would like to add ignore malformed, or if there is any better option to get the mapper to recognize my objects but don't know if there is a spot to do it.

I am editing my dbcontext code and am not inheriting form AuditDbContext so I have an IAuditDbContext object and a DbContextHelper object that I am trying to get to use the ElasticsearchDataProvider correctly, here is some code:

```
public MyContext(DbContextOptions<Database.MyContext> options) : base(options)
        {
            Audit.Core.Configuration.DataProvider = new ElasticsearchDataProvider()
            {
                ConnectionSettings = new AuditConnectionSettings(new Uri("http://localhost:9200")),
                IndexBuilder = ev => "auditlog",
                IdBuilder = ev => Guid.NewGuid()
            };
            _auditContext = new DefaultAuditContext(this);
            _helper.SetConfig(_auditContext);
        }
```
some things like inserts and deletes and various other operations are working fine but some of the things I need to do with dates and numbers are giving map parser illegal argument exceptions like such:

![image](https://user-images.githubusercontent.com/32464706/62562568-6355b800-b84f-11e9-82da-c58d6e5a814a.png)

**Comment by thepirat000** [comment]
Please check [this issue](https://github.com/thepirat000/Audit.NET/issues/152#issuecomment-415560498)

**Comment by bturner1273** [comment]
So I added your code from #152:
![image](https://user-images.githubusercontent.com/32464706/62624105-56d56c00-b8f0-11e9-92a2-4f22f829e91c.png)

The action seems to be running 10 times per save and the output of the print in the last nested foreach is as follows **when updating one entity**: 
![image](https://user-images.githubusercontent.com/32464706/62624246-acaa1400-b8f0-11e9-825b-036b55d4fdbd.png)

I think the ToJson function is probably adding the backslashes and quotes because it is running multiple times. This is causing an illegal argument exception:
![image](https://user-images.githubusercontent.com/32464706/62624547-5093bf80-b8f1-11e9-9e54-4530d33df906.png)

The exception is because quotes are added to the string later on and it ends up being an invalid string with extra quotes at the beginning and a few extra quotes at then end. Have you ever encountered this?

**Comment by bturner1273** [comment]
I put a counter in the foreach loop just to check if anything weird was going on but it only runs through once as expected for one entry, the action is just being called a bunch of times for whatever reason. I only save context changes once in that action in the controller.

**Comment by bturner1273** [comment]
I couldn't recreate the issue of the action executing multiple times but I did recreate those weird backslashes and double quotes everywhere:
[example.zip](https://github.com/thepirat000/Audit.NET/files/3477401/example.zip)

Data for person change in Kibana:
![image](https://user-images.githubusercontent.com/32464706/62629849-f6e4c280-b8fb-11e9-9364-d2f8cb9b1674.png)

This seems like it could be a problem if you are trying to query for certain field values^^

**Comment by thepirat000** [comment]
Where are you calling the `AddCustomAction` method? That should be called **only once**

**Comment by bturner1273** [comment]
That must have been where I am going wrong. Where is the best place to add this? Startup?

**Comment by thepirat000** [comment]
Yes, startup is the place

Glad it works!
