### ISSUE TITLE
optIn/optOut modes and auditInclude/auditIgnore attributes not working

### ISSUE THREAD

**Issue by bturner1273** [thepirat000/Audit.NET#238]
I am using an elasticsearch data provider for audit.entityframework and the auditInclude attribute I have (I am in optIn mode) is only on one model type, but all of my models end up being audited. Is there a way to do this with the elasticsearch data provider without hardcoding table names to ignore?

**Comment by bturner1273** [comment]
[elasticAudit.zip](https://github.com/thepirat000/Audit.NET/files/3497784/elasticAudit.zip)

^if you run this solution you will see that even if you remove the [AuditInclude] on the Person model with PeopleContext in optIn mode the Person model changes will still be included in the audits.

**Comment by thepirat000** [comment]
Problem is that when not using inheritance, the `AuditDbContextAttribute` will not be read from your  DbContext, but from the context you pass to the `_helper.SetConfig(context)`...

So you'll need to configure the mode in a different way, i.e. you can configure the behavior on your startup with:

```
Audit.EntityFramework.Configuration.Setup()
    .ForAnyContext()
    .UseOptIn();
```

**Comment by bturner1273** [comment]
That's awesome! Thank you so much!
