### ISSUE TITLE
Audit.WebApi Support for Request Body

### ISSUE THREAD

**Issue by ExileBLR** [thepirat000/Audit.NET#24]
Include the raw request body as an optional field

**Comment by thepirat000** [comment]
no problem, I don't like number 24 anyway

**Comment by ExileBLR** [comment]
Here's the text from gitter:
Target:  include the raw request body as an optional field
Providing the raw request body will not be trivial, mostly because the action filters runs after model binding.
By design, the body content in ASP.NET is a forward-only stream (read only once) and since model binding has already run, the action filter will not be able to read the request stream again.

**Comment by thepirat000** [comment]
Now the request body can be included as an optional field on the output for WebApi targeting the full .NET framework (not available for .NET core version)

```
[AuditApi(IncludeResponseBody = true, IncludeRequestBody = true)]
public class ValuesController : ApiController
{ ...
```

**Comment by ExileBLR** [comment]
@thepirat000 Could you please make it body + type, just as in response?

**Comment by thepirat000** [comment]
I don't think we can have similar output for request body type as in the response

![image](https://cloud.githubusercontent.com/assets/9836380/22272029/68bc8eb0-e25d-11e6-9af0-0664a4ebb4d4.png)

We'll get values like "System.Web.Http.WebHost.HttpControllerHandler.LazyStreamContent", will that be useful for you?

**Comment by ExileBLR** [comment]
Nope, I just meant that response has content type + content but we have no possibility to get request body content type

**Comment by thepirat000** [comment]
and what kind of value are you expecting on that property?

**Comment by ExileBLR** [comment]
"",  "application/xml; charset=utf-8", "application/json; charset=utf-8", "application/x-www-form-urlencoded" and so on. I think this value could be found in actionContext.Request.Content.Headers.ContentType

**Comment by thepirat000** [comment]
That is currently logged if you use the `IncludeHeaders = true` option on the attribute.

https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.WebApi#output-sample

**Comment by ExileBLR** [comment]
As you can see, there's no Content-Type header

**Comment by thepirat000** [comment]
Oh, you're totally right. That info is part of the request "content" headers. Will work on extracting that.

**Comment by thepirat000** [comment]
I think this is fixed, added the content type to the RequestBody object.
