### ISSUE TITLE
Is it possible to disable file output?

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#240]
Is there a null/no-op data provider possibly?

I need to stop files from being written until we get a propr sink in place.

**Comment by thepirat000** [comment]
yes: https://github.com/thepirat000/Audit.NET/blob/d4dc9cdb0e429e6ed4ee623f8420c336d0dae717/src/Audit.NET/Providers/NullDataProvider.cs#L8

**Comment by thepirat000** [comment]
you can also globally disable/enable audit with Audit.Core.Configuration.AuditDisabled static property
