### ISSUE TITLE
Is it possible to extend the ef core extension audit output with mediatr request name?

### ISSUE THREAD

**Issue by atresnjo** [thepirat000/Audit.NET#245]
Hi, first of all great job! Thank you for your work.

I am using MediatR and I would like to extend the EF Core audit actions with another field which contains the Request name that triggered the insert / update / delete action. The ef core extension works good, but I have no information about which method triggered the action. Any ideas? Thanks! 👍

**Comment by thepirat000** [comment]
If I understand you, that doesn't depend on Audit.NET library, but on MediatR being able to provide information about the publisher of a request

**Comment by atresnjo** [comment]
> 
> 
> If I understand you, that doesn't depend on Audit.NET library, but on MediatR being able to provide information about the publisher of a request. And I'm not sure if that's possible

Let's say you wanted to do it without MediatR. So you had your usual repository class with an InsertAsync method. If you were calling your repository class from your service layer then in the audit output "CallingMethodName" would be InsertAsync, and not the method which triggered the Insert action. It would be nice if it were somehow possible to combine the WebApi extension with the EF extension to audit which API call lead to which EF action. I see that AuditDbContext has AddAuditCustomField - couldn't we technically get the HttpRequest.Url from the current HttpContext.Request and then add it as Custom field?

**Comment by thepirat000** [comment]
The `Audit.EntityFramework` extension has no knowledge of your API pipeline (I guess it's an ASP.NET Core?). So it's not possible to automagically add information from the originating HttpRequest.

But you can add [custom fields](https://github.com/thepirat000/Audit.NET#custom-fields-and-comments) on a [custom action](https://github.com/thepirat000/Audit.NET#custom-actions), like this on your asp.net startup:

```
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddHttpContextAccessor();
        ...
    }

    public void Configure(IApplicationBuilder app, IHttpContextAccessor contextAccessor)
    {
        Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
        {
            var httpContext = contextAccessor.HttpContext;
            scope.Event.CustomFields["CorrelationId"] = httpContext.TraceIdentifier;
            scope.Event.CustomFields["Url"] = httpContext.Request.GetDisplayUrl();
        });

        ...
    }
}
```

That will add the custom fields for each audit event that is created, so it depends on which data provider are you using, but you should be able to access the `AuditEvent.CustomFields[]` from the data provider.

**Comment by atresnjo** [comment]
> 
> 
> The `Audit.EntityFramework` extension has no knowledge of your API pipeline (I guess it's an ASP.NET Core?). So it's not possible to automagically add information from the originating HttpRequest.
> 
> But you can add [custom fields](https://github.com/thepirat000/Audit.NET#custom-fields-and-comments) on a [custom action](https://github.com/thepirat000/Audit.NET#custom-actions), like this on your asp.net startup:
> 
> ```
> public class Startup
> {
>     public void ConfigureServices(IServiceCollection services)
>     {
>         services.AddHttpContextAccessor();
>         ...
>     }
> 
>     public void Configure(IApplicationBuilder app, IHttpContextAccessor contextAccessor)
>     {
>         Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
>         {
>             var httpContext = contextAccessor.HttpContext;
>             scope.Event.CustomFields["CorrelationId"] = httpContext.TraceIdentifier;
>             scope.Event.CustomFields["Url"] = httpContext.Request.GetDisplayUrl();
>         });
> 
>         ...
>     }
> }
> ```
> 
> That will add the custom fields for each audit event that is created, so it depends on which data provider are you using, but you should be able to access the `AuditEvent.CustomFields[]` from the data provider.
> 
> Also check the [`Audit.WebApi`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md) extension. Maybe you want to audit both things (API requests and EF changes). You could relate the audit outputs with a common custom field (i.e. the `CorrelationId` on the code sample)
> 
> You can even create a new ASP.NET Core Web API sample project from scratch with [this template](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#web-api-template-dotnet-new) that includes both: `Audit.WebApi` and `Audit.EntityFramework` configuration for ASP.NET Core and EF Core. Just run the following on an empty folder:
> 
> ```
> dotnet new -i Audit.WebApi.Template
> dotnet new webapiaudit -E
> ```

That is perfect, thank you very much!
