### ISSUE TITLE
Mongo DB Storage broken with dot net core 3.0 with EF Core 2

### ISSUE THREAD

**Issue by nick-milner** [thepirat000/Audit.NET#246]
**Describe the bug**
When using Dot Net Core 3.0, the Mongo storage provider now fails with "The type initializer for 'MongoDB.Bson.Serialization.BsonClassMap' threw an exception System.ArgumentNullException: Value cannot be null." upon app start up

**To Reproduce**
Use the Mongo storage provider to store audit events in a Mongo database using an app compiled with netcoreapp3.0 in the .csproj file

**Expected behavior**
The Mongo storage provider should not throw an exception on app startup

**Libraries (specify the Audit.NET extensions being used including version):**

"Audit.NET" Version="14.3.4" 
"Audit.NET.MongoDB" Version="14.3.4"

**Additional context**
I believe this is related to https://github.com/mongodb/mongo-csharp-driver/pull/372 but the Audit.NET.MongoDB is referencing an older version of the Mongo C# Driver (2.5) instead of the latest version with dotnet core 3.0 support

**Comment by thepirat000** [comment]
This is fixed on version 14.6.5, please upgrade and re test

**Comment by nick-milner** [comment]
All good now - Thanks very much!
