### ISSUE TITLE
Issue with using a separate dbContext for saving audit data

### ISSUE THREAD

**Issue by nunesrui** [thepirat000/Audit.NET#247]
I am trying to implement a generic approach to auditing by using the OptIn option. Our system will be distributed across databases, but I want audit data to all go to the same database, thus the separate context. This is proven to be working fine if I save audit to a table in the same context, but not in a different context.

So, for our purposes we have a BaseContext which extends DbContext like so:

`[AuditDbContext(Mode = AuditOptionMode.OptIn)]
    public class BaseContext : AuditDbContext
`

And auditing is being configured to use EntityFramework this way:

            Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                .UseDbContext(CreateAuditContext)
                .AuditTypeNameMapper(typeName => "Audit_" + typeName)
                .AuditEntityAction((evt, entry, auditEntity) =>
                {
                    var record = (dynamic)auditEntity;
                    record.Action = entry.Action; // Insert, Update, Delete
                    record.UserName = evt.Environment.UserName;
                    record.AuditDate = DateTime.UtcNow;
                }));

```
   Func<AuditEventEntityFramework, DbContext> CreateAuditContext = (AuditEventEntityFramework aeef) =>
        {
            var context = new waterline2_auditContext();
            var result = context.Database.CanConnect(); //just to check, this is returning true

            return context;
        };
```

The "waterline2_auditContext is mapped to the audit database and holds only one table, with the name Audit_WaterCompany. For the purposes of this exercise, I am creating a WaterCompany object, adding it to the DbSet and saving changes. On saving changes, everything seems to run normally and there are no exceptions being thrown, but also no audit record is created on the Audit_WaterCompany table. Am I missing something?

The waterline2_auditContext is basically empty apart from setting up the connection to the relevant database.

**Comment by thepirat000** [comment]
Are you [explicitly including](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#includeignore-entities-tables) the WaterCompany entity? i.e. with the `[AuditInclude]` attribute?

```
[AuditInclude]
public class WaterCompany
{
    ...
}
```

Or via [fluent-api configuration](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#fluent-api) for `Audit.EntityFramework.Configuration.Setup()` ?

**Comment by nunesrui** [comment]
Yes, forgot to mention, but I am. I have managed to successfully get auditing to work IF the audit table is in the same database as the WaterCompany one. But if I try to audit to a different database, I can't get it to work.

**Comment by thepirat000** [comment]
Can you share a minimal sample project code having this issue? 

I am not able to reproduce with the information given. The configuration you shared is looking good.

 Do you call `Audit.EntityFramework.Configuration.Setup()...` on your startup code?

Do you hit this line `var context = new waterline2_auditContext();` with a breakpoint?

**Comment by nunesrui** [comment]
Sure, so this is what my base context looks like. The "water companies" context will then extend this one:

```
namespace Common.Base
{
    /// <summary>
    /// Extension of <see cref="Audit.EntityFramework.AuditDbContext"/>,
    /// this class provides a overrides for each method to allow for
    /// custom auditiing and logging.
    /// </summary>
    [AuditDbContext(Mode = AuditOptionMode.OptIn)]
    public class BaseContext : AuditDbContext
    {
        public BaseContext([NotNull] DbContextOptions<BaseContext> options)
        : base(options)
        {
            SetupAuditing();
        }
        public BaseContext()
        {
            SetupAuditing();
        }

        Func<AuditEventEntityFramework, DbContext> CreateAuditContext = (AuditEventEntityFramework aeef) =>
        {
            var context = new waterline2_auditContext();
            var result = context.Database.CanConnect();

            return context;
        };

        //Func<AuditEventEntityFramework, DbContext> CreateAuditContext = aeef => new waterline2_auditContext();
        /// <summary>
        /// Set the auditing configuration to run attached to the base context.
        /// By default, data will be logged a table that will be called Audit_[table name] on the auditing database.
        /// </summary>
        private void SetupAuditing()
        {

            Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                .UseDbContext(CreateAuditContext)
                .AuditTypeNameMapper(typeName => "Audit_" + typeName)
                .AuditEntityAction((evt, entry, auditEntity) =>
                {
                    var record = (dynamic)auditEntity;
                    record.Action = entry.Action; // Insert, Update, Delete
                    record.UserName = evt.Environment.UserName;
                    record.AuditDate = DateTime.UtcNow;
                }));
        }
    }
}
```

This is the water companies context:

```
    public partial class waterCompaniesContext : BaseContext
    {
        public waterCompaniesContext()
        {
        }

        public waterCompaniesContext(DbContextOptions<BaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<WaterCompany> WaterCompany { get; set; }
        public virtual DbSet<WaterCompanyMarketType> WaterCompanyMarketType { get; set; }
        public virtual DbSet<WaterCompanyType> WaterCompanyType { get; set; }

//OnModelCreating has the table creation code
}
```

The water company class is defined like so:


```
    [AuditInclude]
    public partial class WaterCompany
    {
        public WaterCompany()
        {
        }

        public Guid WaterCompanyId { get; set; }
        public Guid WaterCompanyTypeId { get; set; }
        public Guid WaterCompanyMarketTypeId { get; set; }
        public Guid AddressId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public string Website { get; set; }
        public string Portal { get; set; }
        public Guid? BankingDetailId { get; set; }
        public Guid? BillingDetailsId { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public Guid? ModifiedBy { get; set; }

        public virtual Address Address { get; set; }
        public virtual WaterCompanyMarketType WaterCompanyMarketType { get; set; }
        public virtual WaterCompanyType WaterCompanyType { get; set; }
    }
```

And the auditing context to connect to the different database, like so:

```
 public partial class waterline2_auditContext : AuditDbContext
    {
        public waterline2_auditContext()
        {
        }        

        public waterline2_auditContext(DbContextOptions<BaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AuditWaterCompany> AuditWaterCompany { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            //connection string goes here
            }
        }

//additional mapping code below this point
}
```

Finally, the water companies context is being created and I'm attempting to insert a new entry in the water companies table this way:

```
var wco = new WaterCompany();

            var address = new Address()
            {
                City = "city",
                Country = "country",
                County = "county",
                PhoneNumber = "0123456789",
                PostalCode = "XYZ123AB",
                Line1 = "address1",
                Line2 = "address2"
            };

            wco.Address = address;
            wco.Name = "first water company";
            wco.Portal = "www.portal.com";
            wco.Website = "www.website.com";
            wco.WaterCompanyMarketTypeId = Guid.Parse("099ea320-2073-4d5c-8c74-ba500dd61617");
            wco.WaterCompanyTypeId = Guid.Parse("e4324a0d-b275-4b54-9245-e25c9c97ffb9");
            wco.CreatedBy = Guid.Parse("e4324a0d-b275-4b54-9245-e25c9c97ffb9");
            wco.CreatedDate = DateTime.Now;

            _context.WaterCompany.Add(wco);
            _context.SaveChanges();
```

For reference, I have tried moving the Audit.EntityFramework.Configuration.Setup() call from the BaseContext to the actual startup class of the project - it didn't seem to make a difference.

> Do you hit this line var context = new waterline2_auditContext(); with a breakpoint?

Yes, that line gets hit, and the one below checking if CanConnect returns true.

**Comment by thepirat000** [comment]
Your configuration call to `Audit.Core.Configuration.Setup()` should be done only once, at the startup of your application. Doing it on the context constructor will make the configuration to change each time a context is created.

**Comment by thepirat000** [comment]
Did you tried adding the `[AuditDbContext(Mode = AuditOptionMode.OptIn)]` to your actual `waterCompaniesContext` instead of the `BaseContext`?

**Comment by nunesrui** [comment]
Thank you for your suggestions. I have tried them all, still no luck. I have put a breakpoint inside the section:

```
 .AuditEntityAction((evt, entry, auditEntity) =>
         {
             var record = (dynamic)auditEntity;
             record.Action = entry.Action; // Insert, Update, Delete
             record.UserName = evt.Environment.UserName;
             record.AuditDate = DateTime.UtcNow;
         }));
```
which gets hit on same context mode, but nothing happens with the separate audit context one, it's like no call is being triggered at all. I have also set Visual Studio to break on all exceptions but nothing is being thrown.

Do you have a sample project that can be shared, using something like the AdventureWorks database or similar? Just to see if I'm not missing something immediately obvious.

Also, for reference, on the readme file when it says to setup audit this way:

```
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .Map<Order, Audit_Order>()
            .Map<OrderItem, Audit_OrderItem>()
            .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
            {
                auditEntity.AuditDate = DateTime.UtcNow;
                auditEntity.UserName = evt.Environment.UserName;
                auditEntity.AuditAction = entry.Action; // Insert, Update, Delete
            })
        )
    );
```

the IAudit interface is not recognized, I'm guessing it's no longer being included in the package? In my case I removed the <IAudit> block to get it working.

**Comment by nunesrui** [comment]
Managed to find the problem. If I map the tables explicitly like so:

`         .AuditTypeExplicitMapper(m => m.Map<WaterCompany, AuditWaterCompany>()`

it works fine. It just doesn't work with the generic prefix mapping like I had before:

`.AuditTypeNameMapper(typeName => "Audit_" + typeName)`

**Comment by thepirat000** [comment]
Glad you managed to fix your problem.

The mapper maps types, not table names. So you need to pass the type name (class name) to the TypeNameMapper like `.AuditTypeNameMapper(typeName => "Audit" + typeName)`

**Comment by nunesrui** [comment]
Sorry to be a pain byt I did try that, because I want the solution to be as generic as possible, but sadly it still doesn't work. Keeping everything unchanged,

`.AuditTypeExplicitMapper(m=> m.Map<WaterCompany, AuditWaterCompany>()`

works whereas

`.AuditTypeNameMapper(typeName => "Audit" + typeName)`

doesn't work.

The audit class doesn't have any transformations that I can, it is simply declared like this:


```
namespace Common.Auditing
{
    public partial class AuditWaterCompany
    {
        public Guid WaterCompanyId { get; set; }
        public Guid WaterCompanyTypeId { get; set; }
        public Guid WaterCompanyMarketTypeId { get; set; }
```

And the context generated it like this:

```
     protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AuditWaterCompany>(entity =>
            {
                entity.HasKey(e => e.WaterCompanyId)
                    .HasName("PK_waterCompany");

                entity.ToTable("Audit_WaterCompany");
```

**Comment by thepirat000** [comment]
Also the TypeNameMapper assumes the audit class is defined on the same assembly and namespace as the audited class. I guess you have them defined on different namespaces.

From the documentation on https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#map-by-type-name: 

> This assumes both entity types are defined on the same assembly and namespace


Check this line: https://github.com/thepirat000/Audit.NET/blob/349344548ed41ac2a08082ac9016e4118116f1ce/src/Audit.EntityFramework/ConfigurationApi/EntityFrameworkProviderConfigurator.cs#L46

So you could simply use the TypeMapper and set it like this: 

`.AuditTypeMapper(t => Type.GetType($"Your.Audit.Namespace.Audit{t.Name}"))`

**Comment by nunesrui** [comment]
Oh, that did it. Thank you. This way I can keep it fully generic :)
