### ISSUE TITLE
NEST 7.X compatibility missing

### ISSUE THREAD

**Issue by kollerdroid** [thepirat000/Audit.NET#248]
**I get the following error at creating event:**

`System.TypeLoadException: Could not load type 'Nest.ICreateResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
   at Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEvent(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEvent(Boolean forceInsert)
   at Audit.Core.AuditScope.End()
   at Audit.Core.AuditScope.Dispose()
   at ...`

Because `Nest.ICreateResponse` has been deleted from NEST 7.x.

**To Reproduce**
Just update NEST 6.x to NEST 7.x..

**Expected behavior**
It should be compatible with NEST 7.x.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET.Elasticsearch: 14.6.5
 - NEST: 7.3.1

**Additional context**
When will be NEST 7.x supported?

**Comment by thepirat000** [comment]
This is fixed starting on version v14.6.6. Plase upgrade your references and re-test.
