### ISSUE TITLE
Using EntityFramework 6.3 with net core 3

### ISSUE THREAD

**Issue by oruchreis** [thepirat000/Audit.NET#249]
I want to use Audit.Net in net core 3 but with ef 6.3 which supports .net core now. If I use Audit.EntityFramework nuget package, and if I set TargetFramework to netstandard2.1 or netcoreapp3.0, it sees EFCore, and it can't find references of EFCore because AuditDbContext derives form EFCore not EF 6.3. We need Ef 6 only package like Core package.

**Comment by eduardomhg** [comment]
I also think this is necessary so we can migrate our code to .NET Core 3 without having to port all the EF code to EF Core. I guess we would need to different Audit NuGet packages, one depending on EF Core and another depending on EF 6.3, but both targeting .NET Standard (at least).

**Comment by thepirat000** [comment]
I think I will not add a new package, but make the Audit.EntityFramework package to point EntityFrameork 6.3.0 if the target framework is >= Net Standard 2.1

Like this:

| <sub>Target</sub> \ <sup>Library</sup> | `Audit.EntityFramework` | `Audit.EntityFramework.Core` | 
| ------------ | ---------------- |  -------------- |
| **≥ .NET 4.5** | EntityFramework 6.1.3 | x |
| **≥ .NET 4.6.1** | EntityFramework 6.1.3 | Microsoft.EntityFrameworkCore 2.2.4 |
| **≥ .NET Standard 1.5** | Microsoft.EntityFrameworkCore 1.1.2 | Microsoft.EntityFrameworkCore 1.1.2 |
| **≥ .NET Standard 2.0** | Microsoft.EntityFrameworkCore 2.2.4 | Microsoft.EntityFrameworkCore 2.2.4 |
| **≥ .NET Standard 2.1** | EntityFramework 6.3.0 | Microsoft.EntityFrameworkCore 3.0.0 |

**Comment by thepirat000** [comment]
This is fixed starting on version 14.7.0. Please upgrade your references and re-test

**Comment by oruchreis** [comment]
Thanks, I confirm that it was fixed. We can choose these nuget packages now with conditions in csproj.
