### ISSUE TITLE
Audit.EntityFramework does not work with the latest version of IdentityDbContext

### ISSUE THREAD

**Issue by Xavier-Plasma** [thepirat000/Audit.NET#250]
**Describe the bug**
With `Microsoft.AspNetCore.Identity.EntityFrameworkCore` version 3.0, if the context inherits from `IdentityDbContext<...>`, the behavior is what is excepted. 
However, if it inherits from `AuditIdentityDbContext<...>`, then there is an exception when loading the application: 

```
System.TypeLoadException : 'Method 'get_DbContext' in type 'AuditEntityFramework.Persistence.MyContext' from assembly 'AuditEntityFramework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```

**To Reproduce**
See the example project in attachment : the `Persistence\MyContext.cs` file more specifically.
[AuditEntityFramework.zip](https://github.com/thepirat000/Audit.NET/files/3725490/AuditEntityFramework.zip)

**Expected behavior**
The same behavior with `IdentityDbContext` and `AuditIdentityDbContext` : no System.TypeLoadException.

**Libraries (specify the Audit.NET extensions being used including version):**
- Audit.NET (14.7.0)
- Audit.EntityFramework (14.7.0)
- Audit.EntityFramework.Identity (14.7.0)

**Additional context**
- Microsoft.AspNetCore.Identity.EntityFrameworkCore (3.0.0)
- Microsoft.EntityFrameworkCore (3.0.0)

**Comment by thepirat000** [comment]
Since you are using Microsoft.EntityFrameworkCore and targeting NET STANDARD 2.1, you must reference the package `Audit.EntityFramework.Identity.Core` instead of Audit.EntityFramework.Identity`

Take a look at this table: https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#ef-library-version

**Comment by Xavier-Plasma** [comment]
Oh, I see, that's why it is working with Core 2 but not Core 3. Thanks for your help.
