### ISSUE TITLE
We cannot use Audit.EntityFramework with Entity Framework Core when targeting .NET Framework 

### ISSUE THREAD

**Issue by eduardomhg** [thepirat000/Audit.NET#251]
**Describe the bug**
When using  .NET Framework (in my case version 4.8), we can choose whether to use EF 6 or EF Core. However, the current version of Audit.EntityFramework (14.7.0) restricts us to use EF 6.

The reverse can also happen with .NET 3.0 (which is compatible with both EF 6.3 and EF Core), which would restrict us to EF Core.

This is related to bug #249 

**Expected behavior**
I would expect to be able to choose which of EF6 or EF Core to use, and then simply use Audit.EntityFramework and it would just work for either of them. Maybe the solution would be to split the package into an EF 6 version and an EF Core version.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 14.7.0

**Comment by thepirat000** [comment]
Can you please explain your use case that doesn't fit in the following chart?

| <sub>Target</sub> \ <sup>Library</sup> | `Audit.EntityFramework` | `Audit.EntityFramework.Core` | 
| ------------ | ---------------- |  -------------- |
| **≥ .NET 4.5** | EntityFramework 6.1.3 | x |
| **≥ .NET 4.6.1** | EntityFramework 6.1.3 | Microsoft.EntityFrameworkCore 2.2.4 |
| **≥ .NET Standard 1.5** | Microsoft.EntityFrameworkCore 1.1.2 | Microsoft.EntityFrameworkCore 1.1.2 |
| **≥ .NET Standard 2.0** | Microsoft.EntityFrameworkCore 2.2.4 | Microsoft.EntityFrameworkCore 2.2.4 |
| **≥ .NET Standard 2.1** | **EntityFramework 6.3.0** | Microsoft.EntityFrameworkCore 3.0.0 |

If you target .net framework 4.8, you can use EF 6 by importing the package Audit.EntityFramework. Or use EF Core by importing the package Audit.EntityFramework.Core.

**Comment by eduardomhg** [comment]
Sorry, I searched for Audit.EntityFramework.Core package and for some reason didn't find it. This is exactly what I was proposing, I got it working already in my solution.

Apologies again and great job.
