### ISSUE TITLE
Would like to disable auditing at last second.

### ISSUE THREAD

**Issue by klanglie** [thepirat000/Audit.NET#252]
I am using AuditEntityAction to do last second house cleaning chores using CustomFields. The object I pass in has everything I need relevant to the current context. These are set prior to SaveChanges() in my repository layer. I am using the same dbcontext everywhere. I would like to be able to disable auditing on a case by case basis based on my Custom object stored in CustomFields. e.g. pass a Disabled flag in custom object. Is this possible?

IEntityFrameworkProviderConfiguratorExtra AuditEntityAction<T>(Action<AuditEvent, EventEntry, T> action)

**Comment by thepirat000** [comment]
AuditEntityAction can be defined as a Func that returns a boolean value indicating whether to include the entity on the output log. Check the docs [here](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#ef-provider-options). So you could just return true/false depending on your AuditEvent.CustomFields.

Another option to ignore the entire event (and not by entity) is to use a global custom action:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
	if (scope.Event.CustomFields["Ignore"] == "Yes")
	{
		scope.Discard();
	}
}
```
