### ISSUE TITLE
System.ArgumentException: 'Property set method not found.' for get-only properties

### ISSUE THREAD

**Issue by koryphaee** [thepirat000/Audit.NET#256]
**Describe the bug**
I have an interface with a get-only property. Both the entity class as well as the audit class implement it with a computed property. Even though I mark this property as ignored Audit.NET still tries to audit it and fails because the property cannot be set.

**To Reproduce**
Since there are multiple classes involved I have created a minimal working example here:  
https://github.com/koryphaee/MinimalExample/tree/master
You should be able to just execute the project and get the error.

**Expected behavior**
The property should be ignored. Either automatically because it does not have a setter or explicitly because of the attribute.

**Libraries**
 - Audit.NET: 14.7.0
 - Audit.EntityFramework.Core: 14.7.0

My reposity contains further explanation in the readme.

**Comment by thepirat000** [comment]
You're right, the library will need to filter out the properties without Setter.
Will fix this soon

**Comment by thepirat000** [comment]
This is fixed on version 14.8.0, please upgrade your references and re-test.

Note: I'm having problems pushing to GitHub packages, so please use nuget.org as the source (if you are not).

**Comment by koryphaee** [comment]
I can confirm that it's working correctly in version 14.8.0.
Big thanks for the quick response and fix.

**Comment by thepirat000** [comment]
FYI just confirming GitHub packages problem was fixed, you can now use nuget.org or github packages indistinctly
