### ISSUE TITLE
Feature Request - add ActionExecutingContext parameters to Audit.WebApi

### ISSUE THREAD

**Issue by ofir-shapira-como** [thepirat000/Audit.NET#257]
Not sure if it's possible, I didn't find a way.

I have a use case where I would like to add some ActionExecutingContext data to the Audit event, it seems like the current interface doesn't allow it.

Something like that can work:

```
options.AddAuditFilter(config => config.LogAllActions()
            .WithEventType("{verb}.{controller}.{action}")
            .IncludeExtraParameteras(actionExecutingContext => actionExecutingContext.HttpContext["customParameter"]);
```

What do you think?

**Comment by thepirat000** [comment]
I think it would be providing a property (or method) on the `AuditApiAction` to get the `ActionExecutingContext`, so you can configure a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) that sets a [Custom Field](https://github.com/thepirat000/Audit.NET#custom-fields-and-comments) on the `AuditEvent`.

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    var actionExecutingContext = scope.GetWebApiAuditAction()?.GetActionExecutingContext();
    if (actionExecutingContext != null)
    {
        scope.SetCustomField("ActionId", actionExecutingContext.ActionDescriptor.Id);
    }
});
```

What do you think?

**Comment by ofir-shapira-como** [comment]
I think your suggestion is more appropriate because it is more correct to have it on the `AuditApiAction` object, rather than in the configuration part (`AddAuditFilter`)

Should I open a PR if I get the chance?

**Comment by thepirat000** [comment]
no need to create a PR, I'll work on the change and let you know.

**Comment by thepirat000** [comment]
This was added on version 14.8.1, please upgrade and re-test.

**Comment by ofir-shapira-como** [comment]
Thanks @thepirat000, it works well, please note that I am using it in `AddOnSavingAction` but I tested it in `AddCustomAction` as well:

```
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var actionExecutingContext = scope.GetWebApiAuditAction()?.GetActionExecutingContext();
    if (actionExecutingContext != null)
    {
        scope.SetCustomField("User", actionExecutingContext.HttpContext.GetCurrentHubUser());
    }
});
```

You may close, thanks!

**Comment by gsrmf** [comment]
ActionExecutingContext is always null when using middleware. the `AuditApiAction` is created in the middleware and only the 'action' related parameters get updated when using the attribute or global filters.
