### ISSUE TITLE
Audit.WebApi.Core and ASP.NET core 3.0 problem

### ISSUE THREAD

**Issue by kbr-ucl** [thepirat000/Audit.NET#258]
Hi.
I have an AspNetCore version 3.0 project.

When I want to add  Audit.WebApi.Core, I get a list of updates.
I am not sure, but it seems to me that Audit.WebApi.Core wants to install older versions.

So I want to ask you if I am wrong before adding your great package.

Best regards, Kaj Bromose

P.s. The update / installing list from Audit.WebApi.Core

Updates:

Microsoft.AspNetCore.Authorization.Policy.2.0.0 -> Microsoft.AspNetCore.Authorization.Policy.2.0.4
Microsoft.AspNetCore.Mvc.Core.2.0.0 -> Microsoft.AspNetCore.Mvc.Core.2.0.4
Microsoft.AspNetCore.ResponseCaching.Abstractions.2.0.0 -> Microsoft.AspNetCore.ResponseCaching.Abstractions.2.0.3
Microsoft.AspNetCore.Routing.2.0.0 -> Microsoft.AspNetCore.Routing.2.0.3
Microsoft.DotNet.PlatformAbstractions.2.0.0 -> Microsoft.DotNet.PlatformAbstractions.2.0.3
Microsoft.Extensions.DependencyModel.2.0.0 -> Microsoft.Extensions.DependencyModel.2.0.3

Installing:

Audit.NET.14.8.1
Audit.WebApi.Core.14.8.1
Microsoft.AspNetCore.Antiforgery.2.0.3
Microsoft.AspNetCore.Authentication.Cookies.2.0.4
Microsoft.AspNetCore.Cors.2.0.3
Microsoft.AspNetCore.Diagnostics.Abstractions.2.0.3
Microsoft.AspNetCore.Html.Abstractions.2.0.2
Microsoft.AspNetCore.Identity.2.0.4
Microsoft.AspNetCore.Localization.2.0.3
Microsoft.AspNetCore.Mvc.2.0.4
Microsoft.AspNetCore.Mvc.ApiExplorer.2.0.4
Microsoft.AspNetCore.Mvc.Cors.2.0.4
Microsoft.AspNetCore.Mvc.DataAnnotations.2.0.4
Microsoft.AspNetCore.Mvc.Formatters.Json.2.0.4
Microsoft.AspNetCore.Mvc.Localization.2.0.4
Microsoft.AspNetCore.Mvc.Razor.2.0.4
Microsoft.AspNetCore.Mvc.Razor.Extensions.2.0.3
Microsoft.AspNetCore.Mvc.RazorPages.2.0.4
Microsoft.AspNetCore.Mvc.TagHelpers.2.0.4
Microsoft.AspNetCore.Mvc.ViewFeatures.2.0.4
Microsoft.AspNetCore.Razor.2.0.3
Microsoft.AspNetCore.Razor.Language.2.0.3
Microsoft.AspNetCore.Razor.Runtime.2.0.3
Microsoft.CodeAnalysis.Analyzers.1.1.0
Microsoft.CodeAnalysis.Common.2.3.1
Microsoft.CodeAnalysis.CSharp.2.3.1
Microsoft.CodeAnalysis.Razor.2.0.3
Microsoft.Extensions.FileProviders.Composite.2.0.1
Microsoft.Extensions.Localization.2.0.3
Microsoft.Extensions.Localization.Abstractions.2.0.3
Microsoft.Extensions.PlatformAbstractions.1.1.0
System.Diagnostics.FileVersionInfo.4.3.0
System.Diagnostics.StackTrace.4.3.0
System.Reflection.Metadata.1.4.2
System.Threading.Tasks.Parallel.4.3.0
System.Threading.Thread.4.3.0
System.ValueTuple.4.3.0
System.Xml.XPath.4.3.0
System.Xml.XPath.XDocument.4.3.0

**Comment by thepirat000** [comment]
Hi Kaj

Now that you mention it I've realized there are two references that are no longer needed by the Audit.WebApi library (`Microsoft.AspNetCore.Identity` and `Microsoft.Extensions.PlatformAbstractions`)
I'll remove those on the next version and update to the latest `Microsoft.AspNetCore.Mvc` that **is**  actually needed.

Anyway you shouldn't have problems since (from your _Updates:_ list) it's not downgrading your package versions, but referencing newer.

Will let you know when this change is tested and deployed

**Comment by thepirat000** [comment]
The unneeded references were removed on version 14.9.0, please upgrade and re-test

**Comment by kbr-ucl** [comment]
Everything  vent well. The only update in the project file was:
    <PackageReference Include="Audit.WebApi.Core" Version="14.9.1" />

Thank You for Your help.
