### ISSUE TITLE
Hiding certain for fields or action parameters

### ISSUE THREAD

**Issue by alandillon** [thepirat000/Audit.NET#26]
I have some sensitive information that comes across in form fields and action parameters that I would like to either remove from the log or encrypt.

I see no way of doing this without a custom policy creation.
I was hoping (for example the MVC extension) I could hook into it and remove different fields I did not want to log at all?

Is this possible?

**Comment by thepirat000** [comment]
Hi

You should be able to accomplish this with a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions). 

For example:

```c#
Audit.Core.Configuration.AddCustomAction(Audit.Core.ActionType.OnEventSaving, action =>
{
    var mvc = action.Event.GetMvcAuditAction();
    if (mvc.ControllerName == "Home" && mvc.ActionName == "Sensitive")
    {
        mvc.FormVariables.Clear();
        mvc.ActionParameters["password"] = Encrypt(mvc.ActionParameters["password"]);
    }
});
```

The `OnEventSaving` action is fired each time an audit event is about to be saved, so you have the chance to modify the audit data before it's persisted.

In the example above I'm clearing the form variables and modifying the reported action parameter value for a specific action in a controller.

**Comment by kyurthich** [comment]
Awesome! I will give that a shot!

Thanks!

**Comment by kyurthich** [comment]
My solution:

`public static void Custom()
        {
            Audit.Core.Configuration.AddCustomAction(Audit.Core.ActionType.OnEventSaving, action =>
            {
                var mvc = action.Event.GetMvcAuditAction();

                
                if(mvc.FormVariables.ContainsKey("Password"))
                    mvc.FormVariables["Password"] = string.Empty;

                //nested dictionairy with model.
                if (mvc.ActionParameters.ContainsKey("model"))
                {
                    dynamic x = mvc.ActionParameters["model"];

                    mvc.ActionParameters["model"] = RemoveSensitiveData(x);
                }
            });
        }

        private static object RemoveSensitiveData(object vm)
        {
            return vm;
        }

        private static LoginViewModel RemoveSensitiveData(LoginViewModel vm)
        {
            vm.Password = string.Empty;
            return vm;
        }`

**Comment by Tony427** [comment]
Is this possible using filter or fluent api to handle the override in ActionParameters ?
for example.

```
    public async Task<ActionResult<int>> Create(CreateUserCommand command)
    {
        ...
    }

    public class Ctx1CreateEntity1Command
    {
        public string Text { get; set; }

        public string AuditText { get; set; }

        [AuditIgnore]
        public string NonAduitText { get; set; }

        [AuditFormat]
        public string AuditMaskedPassword { get; set; }

        [AuditOverride(null)]
        public string AuditOverrideText { get; set; }

        [AuditOverride(convensiontoString)]
        public AuditEnum AuditEnum { get; set; }
    }
```

**Comment by thepirat000** [comment]
> Is this possible using filter or fluent api to handle the override in ActionParameters ?

Not sure if I undestand, but the AuditOverride/AuditFormat are part of the Audit.EntityFramework library, so it will work only if `Ctx1CreateEntity1Command` is an entity on your EF DbContext and you are auditing the DbContext with Audit.EntityFramework

**Comment by Tony427** [comment]
in my case I would like to log the http request as well. So I will using Audit.WebApi for this purpose. It will automatically log everything into Action parameters. I was thinking if there has an graceful way to hide or format some of the parameters. (e.g. if there has password in the request)

`CreateUserCommand ` is not he entity. it's a dto for mapping  request parameters.

**Comment by thepirat000** [comment]
You can ignore Controllers, Actions or Action Parameters with [`Audit.WebApi.AuditIgnoreAttribute`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#audit-ignore-attribute), but you cannot Ignore particular fields inside one action parameter with this attribute.

For that kind of behavior you will need to implement the logic by yourself. You can always remove, ignore, or change the values of your audit entities by using [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions)

**Comment by Tony427** [comment]
Create my own attribute to handle the ignore OnEventSaving ...

```csharp
private static void CustomizeAuditEventWebApi(AuditEventWebApi webApiEvent)
{
    // ignore, format and override with ActionParameters and RequestBody
    var parameters = webApiEvent.Action?.ActionParameters;
    foreach (var item in parameters.ToList())
    {
        var obj = item.Value;
        var type = item.Value.GetType();

        var objJsonString = JsonConvert.SerializeObject(obj, type, new JsonSerializerSettings());
        var cloneJObject = JsonConvert.DeserializeObject(objJsonString) as JObject;

        foreach (var property in type.GetProperties())
        {
            // convert Enum as string
            if (property.PropertyType.IsEnum)
            {
                var enumType = property.PropertyType;

                var originalEnum = Enum.ToObject(enumType, property.GetValue(obj));
                cloneJObject[property.Name] = originalEnum.ToString();
            }

            // handle ignore
            if (property.CustomAttributes.Any(a => a.AttributeType == typeof(AuditEventWebApiIgnoreAttribute)))
            {
                cloneJObject.Remove(property.Name);
            }
        }

        // override object with the clone object
        parameters[item.Key] = cloneJObject;
    }
}
```
