### ISSUE TITLE
Very minor issue in Readme

### ISSUE THREAD

**Issue by TheArPee** [thepirat000/Audit.NET#260]
Typo: "Asynchoronous" should be "Asynchronous"

Excellent package - I am reviewing to convert all of my current software auditing to this suite. Fantastic job!

**Comment by thepirat000** [comment]
Thanks!
Fixed that.

Sorry for the typos... English is not my native language.

Regards

**Comment by TheArPee** [comment]
Do not be sorry - it was such a minor issue!
Thank you for responding so quickly!
