### ISSUE TITLE
Is it possible to omit attributes from the audit?

### ISSUE THREAD

**Issue by superkat1111** [thepirat000/Audit.NET#262]
This lib is great!

However, we have certain GDPR issues and while it is great to have all of the data, some of them need to be removed for legal reasons. 

For example, would it be possible to omit the Authorisation header from headers?
Is it possible to decorate an attribute on a model to omit it from being recorded in the audit?

Basically, looking for a way to omit PII data but still keep all the good stuff.

Thanks

**Comment by thepirat000** [comment]
There are many ways, but really depends on which data provider are you using to store the audit events... i.e. if you depend on `Newtonsoft.Json` serialization, you could use `[JsonIgnore]` attribute on the model properties.

But for the headers, (guessing you are referring to the `Audit.WebApi` library) you can use a custom action that removes the personal info from the audit event, for example:

```c#
using Audit.WebApi;
// On your startup code:
Audit.Core.Configuration.AddCustomAction(Audit.Core.ActionType.OnScopeCreated, scope =>
{
    scope.GetWebApiAuditAction().Headers.Remove("Authorization");
});

```
