### ISSUE TITLE
Audit Trail for NoSQL CRUD

### ISSUE THREAD

**Issue by alberk8** [thepirat000/Audit.NET#264]
I know that you can Audit log the output to MongoDB but how can I log CRUD operations of MongoDB data collections ?  Thank you.

**Comment by thepirat000** [comment]
You can audit at the database level: https://docs.mongodb.com/manual/tutorial/configure-auditing/

**Comment by alberk8** [comment]
Thank you.  Can I then say that Audit.Net is not the appropriate tool for logging CRUD changes of  MongoDB database?.

**Comment by thepirat000** [comment]
Well, there is no extension for auditing an elasticsearch NEST client. Is that what you mean?

I think it's possible with the [OnRequestCompleted](https://github.com/elastic/elasticsearch-net/blob/4e322e504f4c6c1f103db148b3b3a9bd656286b4/src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs#L440).

Will take a deeper look.

**Comment by thepirat000** [comment]
That's correct. 
Are you looking for auditing the [MongoDB.Driver](https://www.nuget.org/packages/mongodb.driver) calls?

I guess that can be done with the [driver events](https://olepetterdahlmann.com/2016/08/10/mongodb-driver-events/).
