### ISSUE TITLE
Some more tiny typo's in Readme.md

### ISSUE THREAD

**Issue by TheArPee** [thepirat000/Audit.NET#265]
First of all may I say Happy New Year to all the team! :-)

In the spirit of wanting this wonderful project to succeed and become even more perfect, I would like to suggest a couple of very minor adjustments to the "Readme.md"

Under Changelog heading: - missing "G" in link!

Under "Usage" - may I suggest that the following rewording is slightly clearer?
      "It is not mandatory to use a `using` block, but it simplifies the syntax when the code to audit is in a single block, allowing the detection of exceptions and calculating the duration by implicitly saving the event on disposal. "

and in the following paragraph - "beggining" should be "beginning"

Thank you!

I will let you know if I find any more!

**Comment by ovidiaconescu** [comment]
Happy new year 2 u 2 :) 
Good catch, can you do a PR?

**Comment by thepirat000** [comment]
Happy new year folks

If you could create a new PR with the changes, that would be great. My native language is Spanish, I'm aware the readme(s) needs corrections and rewording so thanks for the suggestions.

**Comment by TheArPee** [comment]
I have submitted my PR :-)
