### ISSUE TITLE
Implementation for IdentityDbContext? :)

### ISSUE THREAD

**Issue by trnelson** [thepirat000/Audit.NET#27]
Love the tool, and wondering if you have plans to implement for IdentityDbContext? I've been working my way through a [messy] implementation, and you can see the issue I've run into here: http://stackoverflow.com/questions/42168013/third-party-implementation-of-dbcontext-how-to-also-implement-identitydbcontext

Thank you!

**Comment by thepirat000** [comment]
I'm on it

**Comment by thepirat000** [comment]
This is fixed starting on version 6.1.0

A new class [`AuditIdentityDbContext`](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/AuditIdentityDbContext.cs) is provided so you can change your context to inherit from that one.

Feel free to re-open this issue or create a new one if you still have problems.

Regards
