### ISSUE TITLE
Empty or null fields in main object when it inserts in mongoDB

### ISSUE THREAD

**Issue by awilliansd** [thepirat000/Audit.NET#270]
I trying to insert an object in database, however, this object only have empty or null fields. The other objects reference works, but I don't know this behavior. I used only "using", class with create and, try and catch, nothing change.

![Sem título](https://user-images.githubusercontent.com/4139802/73488318-1c202e00-437f-11ea-96d9-c9d86d1b85da.jpg)
![Semtítulo1](https://user-images.githubusercontent.com/4139802/73488322-1de9f180-437f-11ea-8425-8fe80313fdbd.jpg)
![Semtítulo2](https://user-images.githubusercontent.com/4139802/73488329-204c4b80-437f-11ea-99b5-2fd06ae6b4b3.jpg)

It's the last update of Audit.NET

**Comment by thepirat000** [comment]
I don't understand what the problem is. If you prefer support is spanish, you could try [Gitter's Audit.NET-Spanish channel](https://gitter.im/Audit-NET/Audit.NET-Spanish)

**Comment by awilliansd** [comment]
I don't speak Spanish, sorry. I'll try to explain better my problem. I'm sending images with my code. First image, it's my class, with fields and references. Second image, it's my service class. This method updates my "fichasanitaria", so, I need to log this changes. Third image, it's my Auditor Class, with Init method and End method. Finally, the last image is a session factory, with audit initials configuration. If you can see in my first question, when I'm debbuging "fichasanitariaservice", it's values in my class, but when audit persists this information, I don't know what happens. In mongoDB, all fields is empty or null, however, just in main class "fichasanitaria". If you can see in "ocorrencias", it's values both in class and in database. I don't know if I was clear. I appreciate your help.

![Classe](https://user-images.githubusercontent.com/4139802/73569777-784b8680-4441-11ea-811d-5821df05073c.png)
![AtualizaFicha](https://user-images.githubusercontent.com/4139802/73569790-7bdf0d80-4441-11ea-9b20-53b238836a3e.png)
![Auditor](https://user-images.githubusercontent.com/4139802/73569799-7f729480-4441-11ea-917a-054fe94e6227.png)
![SessionFactory](https://user-images.githubusercontent.com/4139802/73569803-83061b80-4441-11ea-8687-67a74618d0f1.png)

**Comment by awilliansd** [comment]
Someone??

**Comment by AntonyCorbett** [comment]
@awilliansd I think you'll need to add a small code sample that can be used to reproduce the problem please. Few will have the time to examine screenshots of isolated code. Regards.

**Comment by awilliansd** [comment]
My app code in my repositories

https://github.com/awilliansd/Cadastro

**Comment by AntonyCorbett** [comment]
@awilliansd any instructions to reproduce the problem please?

**Comment by awilliansd** [comment]
No, just build and execute. But, you don't reproduce exactly the same, because you don't have the database. So, you can see an error, when you persist the data. It's only a API, with layers and swagger as front-end

**Comment by AntonyCorbett** [comment]
Please provide some simple instructions to reproduce the issue. For example, is there a failing unit test?

**Comment by awilliansd** [comment]
There is no problem in Unit Test(it's problem in two unit tests, but doesn't matter to described problem). The problem is in FichaSanitariaService when it persist the data as you can see in images above. You don't reproduce the problem, because you don't have the same data, only the code. I sent the images to show the real problem, in my environment, with the real data.

**Comment by AntonyCorbett** [comment]
The lifetime of your Auditor instance seems odd. It is injected as a singleton yet it includes an auditScope field (which incidentally should be private) that is updated on each Init(). In AtualizaFichaSanitaria - between the Init() and the End() - you have a call to AtualizaDadosFichaSanitariaCNAECAE which also includes your Auditor! I think you are overwriting the original auditScope.

**Comment by awilliansd** [comment]
I saw the problem. You're right. I need to change my service to doesn't lost the original reference.
