### ISSUE TITLE
Audit.MVC not logging on exception (.NET Framework)

### ISSUE THREAD

**Issue by thepirat000** [thepirat000/Audit.NET#274]
Audit.Mvc is not saving the audit events when an unhandled exception occurs.

Original question from SO: https://stackoverflow.com/questions/60356248/audit-net-mvc-not-logging-on-exception

Apparently the problem is that the audit scope is being saved on the [`IResultFilter.OnResultExecuted`](https://github.com/thepirat000/Audit.NET/blob/74f3ee292d5b23dff9d0bc00593c9cccefb7b2b5/src/Audit.Mvc/AuditAttribute.cs#L158), but result filters are only executed when the action method has executed successfully.

Note: This is already fixed for ASP.NET Core version, as part of #72

**Comment by thepirat000** [comment]
Fixed on version 15.0.3, please upgrade your references and re-test

**Comment by alexanlp** [comment]
> Fixed on version 15.0.3, please upgrade your references and re-test

Thanks, solved!
