### ISSUE TITLE
Update to ASP.NET 3.x  dependencies

### ISSUE THREAD

**Issue by ErikEJ** [thepirat000/Audit.NET#275]
**Describe the bug**
Basically I am facing this:
https://github.com/dotnet/aspnetcore/issues/14723

Analyzer 'Microsoft.AspNetCore.Mvc.Analyzers.TopLevelParameterNameAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	

**To Reproduce**

`<PackageReference Include="Audit.WebApi.Core" Version="15.0.4" />`

**Expected behavior**

Analyzers can run.

**Additional context**

I think updating the ASP.NET Core dependencies to 3.0 would fix the issue.

**Comment by thepirat000** [comment]
Can you share a minimal sample to reproduce this issue? Or at least share the content of your csproj

**Comment by ErikEJ** [comment]
Of course:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  
  <PropertyGroup>
   <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audit.WebApi.Core" Version="15.0.4" />
    <PackageReference Include="Audit.NET.AzureStorage" Version="15.0.4" />
  </ItemGroup>
</Project>

```

![image](https://user-images.githubusercontent.com/4169187/77039801-fabee400-69b6-11ea-89f3-518bea00a319.png)

**Comment by ErikEJ** [comment]
As I understand the related aspmetcore issue, updating to 3.0 dependencies should resolve the issue.

**Comment by thepirat000** [comment]
Sorry, cannot reproduce the issue.
 
I've Tested with your csproj (with and without the `RunAnalyzersDuringBuild`) and I don't get the exception.

Please add more information on how to reproduce

**Comment by ErikEJ** [comment]
I will close, assume it is external

**Comment by phobos04** [comment]
@ErikEJ please, did you manage to solve the issue, or to identify the root cause? I'm facing a similar issue, and I cannot get rid of those .NET Core 2.2 references.
Thanks!

**Comment by ErikEJ** [comment]
I solved it like this, but would still prefer no dependencies on 2.2 in a 3.x project, to be honest:

```
  <PropertyGroup>
   <RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
  </PropertyGroup>

```
