### ISSUE TITLE
Support for `UseInMemoryDatabase`?

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#276]
I haven't set up a reproduction repo yet, but I think my issue is related to inheriting from `AuditDbContext`.

I get the following error when I switch my integration tests from SQLite to InMem:

```
    System.InvalidOperationException : No database provider has been configured for this DbContext. A provider can be configured by overriding the DbContext.OnConfiguring method or by using AddDbContext on the application service provider. If AddDbContext is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

My context looks like this:

```csharp
    public partial class MyDbContext : AuditDbContext
    {

        public MyDbContext (
            DbContextOptions<MyDbContext > options)
            : base(options)
        {
        }
```

I AM using `AddDbContext`, as proved by the following:

```csharp
               services.AddDbContext<MyDbContext>(options =>
                {
                    options
                        //.UseSqlite("Data Source=InMemoryDbForTesting.db") // WORKS!!!
                        .UseInMemoryDatabase(databaseName: "MyDbContextName") // DOESNT WORK!!!
                        .UseInternalServiceProvider(dbContextInternalServiceProvider);
                });
```

**Comment by thepirat000** [comment]
do you have two DB contexts?
`WuitCMDBDbContext` and `MyDbContext`?

**Comment by VictorioBerra** [comment]
No. Sorry I forgot to remove that. Ill edit now.

**Comment by VictorioBerra** [comment]
So I whipped up a repro and it is working perfectly with in-memory. Something else must not be right with my code. Ill keep working at it.

**Comment by VictorioBerra** [comment]
I believe my issue was the call to `UseInternalServiceProvider`.

**Comment by hisuwh** [comment]
@VictorioBerra how did you fix this?  I'm trying to test my auditing but I'm not getting any audit logs saved despite this working with a real database

**Comment by VictorioBerra** [comment]
@hisuwh Did you try to remove the call to `.UseInternalServiceProvider()`?

**Comment by VictorioBerra** [comment]
Also, you confirmed it worked when using UseSqlite? Otherwise you may want to make sure you set everything up correctly.

**Comment by hisuwh** [comment]
Without `.UseInternalServiceProvider()` my tests break.  I haven't tried with SqlLite I meant when using full SQL when running the application

**Comment by VictorioBerra** [comment]
Does your code work with full SQL when running without `UseInternalServiceProvider`? If so, you might have to add that during testing if you are using a [custom WebApplicationFactory.](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-3.1#customize-webapplicationfactory)

**Comment by hisuwh** [comment]
So I'm configuring EF in my startup like this:

```csharp
public void ConfigureContainer(ServiceRegistry services) // using lamar IOC
{
    var connStr = this.Configuration.GetConnectionString("ApplicationConnectionString");

    services.AddDbContext<ApplicationDbContext>(options =>
        options.UseSqlServer(connStr));
```

Then in my tests I do have custom WebApplicationFactory where I'm doing this to change EF to inmemory
```csharp
builder.ConfigureServices(services =>
{
    var descriptor = services.SingleOrDefault(
            d => d.ServiceType ==
                    typeof(DbContextOptions<ApplicationDbContext>));

    services.Remove(descriptor);

    var provider = services
        .AddEntityFrameworkInMemoryDatabase()
        .BuildServiceProvider();

    services.AddDbContext<ApplicationDbContext>(options =>
    {
        var databaseName = $"database-{this.GetType().Name}";
        options.UseInMemoryDatabase(databaseName);
        options.UseInternalServiceProvider(provider);
    });
});
```

If I remove `UseInternalServiceProvider` then my data does not persist between my setup and my test run.

**Comment by VictorioBerra** [comment]
So, I just looked and in my WAF I am not using UseInternalSP. Im not using that in my Startup either. Do you think this might be related to Lamar IOC compared to using the default?

**Comment by hisuwh** [comment]
It's possible
