### ISSUE TITLE
AuditDbContext SaveChanges(Async) overrides wrong overload in EFCore 

### ISSUE THREAD

**Issue by npnelson** [thepirat000/Audit.NET#277]
I just starting trying out Audit.NET (which I think is awesome) and noticed some odd behavior when calling EF Core's ```SaveChangesAsync(bool acceptAllChangesOnSuccess,CancellationToken cancellationToken = default)``` overload on the AuditDbContext.

When using that overload on a context inherited from AuditDbContext, the EF events were not being audited. 

A test demonstrating this with the synchronous version of SaveChanges can be found here:

https://github.com/npnelson/Audit.NET/commit/82e9563fc60aea57cd3b03ed5849aa51a56bb3bf#diff-5bc620a37f549c7f4a41cd8e4db570c9

Using the synchronous version as an example, I think that the right thing to do is to have the AuditDbContext (for EF Core) overload ```SaveChanges(bool acceptAllChangesOnSuccess)``` instead of ```SaveChanges()``` since all ```SaveChanges()``` does is call ```SaveChanges(acceptAllChangesOnSuccess: true)```. Something similar applies for the async methods.

DbContext code https://github.com/dotnet/efcore/blob/master/src/EFCore/DbContext.cs#L420-L498

By overriding the overload with all the meat in it in the parent, the convenience overloads are automatically covered. 

You can see my proposed fix to AuditDbContext here:

 https://github.com/npnelson/Audit.NET/commit/82e9563fc60aea57cd3b03ed5849aa51a56bb3bf

I didn't want to submit a pull request because I don't have my machine set up to run all the tests and I'm less certain of the overloads for the EF6 version in addition to I'm not sure where the best place to test this is.

Also note that the proposed AuditDbContext:

1) Removes the unnecessary ```using System.Linq```
2) Makes ```DbContextHelper _helper``` readonly
3) Removes the comments on the SaveChanges(Async) overloads because Visual Studio picks up the comments from the parent class.
4) Removes the ```await``` on ```SaveChangesAsync```  and ```SaveChangesBypassAuditAsync``` since I think the awaiting can be safely done by the caller.

I wanted to get this on the table now, but I can submit (and refine) a pull request if that interests you.

**Comment by thepirat000** [comment]
A pull request will be appreciated!

**Comment by npnelson** [comment]
I'm not sure if I like how I did the tests and I couldn't run all of the existing tests because I don't have SQL running as localhost on my computer.

Feel free to suggest changes and I will do my best
