### ISSUE TITLE
Prevent crashes with large payloads and Azure Table Storage

### ISSUE THREAD

**Issue by ErikEJ** [thepirat000/Audit.NET#279]
**Describe the bug**
Azure Table Storage provider crashes, if the payload is too large (over 64 K for a column)

**To Reproduce**
Have a large auditevent, with a large request body.

**Expected behavior**
Throw better error?

**Comment by thepirat000** [comment]
Could you share the error message and stack trace?

You could use a custom action in order to check the size and take further action:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
	if (scope.Event.ToJson().Length > 65535)
	{
		// fix the event, for example remove the request body
		var webApiEvent = scope.Event as Audit.WebApi.AuditEventWebApi;
		webApiEvent.Action.RequestBody.Value = null;

		// Or.. discard the event (avoid saving)
		scope.Discard();
	}
});

```

**Comment by ErikEJ** [comment]
I am simply getting error 400 (Bad Request) from Azure Table storage - but I will try the "custom action" - overlooked that possibility!
