### ISSUE TITLE
Default Configuration for ASP MVC

### ISSUE THREAD

**Issue by weedkiller** [thepirat000/Audit.NET#28]
Hi,

I was looking at your help for the [APS MVC 4 / 5](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.Mvc/README.md), the picture really helped.

Is there default configuration on startup to just audit all actions/or atleast by controller, rather than putting on each action(by roles)? to profile things like number of times a password was failed/ reset etc

thanks

**Comment by thepirat000** [comment]
The [Audit] attribute can be used at Controller level
