### ISSUE TITLE
TransactionScope around the AuditScope error

### ISSUE THREAD

**Issue by bhudpapp** [thepirat000/Audit.NET#281]
**Describe the bug**
If there is a TransactionScope around the AuditScope, it throw error when the AuditScope dispose itself. 
Exception: "An exception occurred while initializing the database. See the InnerException for details."
Inner Exception: "The underlying provider failed on Open."
Inner Exception: "The partner transaction manager has disabled its support for remote/network transactions. (Exception from HRESULT: 0x8004D025)"

**To Reproduce**
- Open a db connection.
- Create a transaction scope with that connection
- Create AuditScope (sync) with using
- Run the sql statement what we want to auditing inside the using statement.
- When the using end, we got the exceptions above.

**Code example:**
```
private void Debug()
        {
            try
            {
                using (var connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    using (var transactionScope = BeginTransactionScope(connection))
                    {
                        var dummy = new { Name = "Dummy", Counter = 1 };

                        using (var audit = AuditScope.Create("Insert", () => dummy, new { Table = "Dummy" }))
                        {
                            // SQL statement
                            string sql = "INSERT INTO Dummy (Name, Counter) Values (@Name, @Counter);";
                            var affectedRows = connection.Execute(sql, new { dummy.Name, dummy.Counter });
                        }
                        transactionScope.Complete();
                    }
                    connection.Close();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        public TransactionScope BeginTransactionScope(SqlConnection connection)
        {
            var options = new TransactionOptions
            {
                IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted,
            };

            var transactionScope = new TransactionScope(TransactionScopeOption.Required, options);

            ((DbConnection)connection).EnlistTransaction(Transaction.Current);

            return transactionScope;
        }
```

**Expected behavior**
Don't throw any exception and work together with the exists transaction. So if the sql command fail, we don't want any auditing record as well.
It would be good if I could configure the Audit.SqlServer with an exists connection not just with a connection string.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET: 15.0.4
 - Audit.NET.SqlServer: 15.0.4

**Additional context**
![image](https://user-images.githubusercontent.com/35230804/78777486-e8264200-7999-11ea-9e53-cf965c312e0f.png)

**Comment by thepirat000** [comment]
I think this is a DTC service issue, not an issue with Audit.NET library.

Please check: 

- https://stackoverflow.com/a/10131344/122195
- https://support.pitneybowes.com/VFP06_KnowledgeWithSidebarTroubleshoot?id=kA280000000CiHmCAK&popup=false&lang=en_US

**Comment by bhudpapp** [comment]
Hi,

Enable the DTC solved the problem in my test environment, but unfortunately I don't have influence to configure it in production. My app can install to multiple servers, so I need to solve this from the code.
That's why I inherited some custom class to setup with an existing connection, not a connection string.  Its worked, but I hope the core Audit.Net will have such an option.

**Code example:**
```
Audit.Core.Configuration.Setup()
                    .UseCustomSqlServer(config => config
                        .Connection((SqlConnection)dummy.Session.Connection)
                        //.ConnectionString(connectionString)
                        .Schema("dbo")
                        .TableName("Event")
                        .IdColumnName("Id")
                        .JsonColumnName("JsonData")
                        .CustomColumn("Table", ev => ev.CustomFields["Table"])
                        .CustomColumn("EventType", ev => ev.EventType)
                        .CustomColumn("User", ev => ev.Environment.UserName));
```
I would really appreciate if I can get this functionality from the core solution. 
Thank you in advance!
