### ISSUE TITLE
Audit.NET.DynamoDB - EventType should of string type and not number type in the read me file

### ISSUE THREAD

**Issue by adrianiftode** [thepirat000/Audit.NET#282]
**Describe the bug**
I was following the [instructions](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.DynamoDB#constraints) for DynamoDB provider and got some issues with the table usage, as it created the *EventType* as a number, when the provider sends a string.

So to make it work, I changed from

```
AttributeDefinitions = new List<AttributeDefinition>()
    {
        new AttributeDefinition("EventId", ScalarAttributeType.S),
        new AttributeDefinition("EventType", ScalarAttributeType.N)
    },
```
to
```
AttributeDefinitions = new List<AttributeDefinition>()
    {
        new AttributeDefinition("EventId", ScalarAttributeType.S),
        new AttributeDefinition("EventType", ScalarAttributeType.S)
    },
```

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET:  14.7.0
 - Audit.WebApi: 14.7.0
 - Audit.NET.DynamoDB: 14.7.0

**Comment by thepirat000** [comment]
Just fixed the README file, thanks!
