### ISSUE TITLE
Issue while using Audit.Net.MongoDB

### ISSUE THREAD

**Issue by vanivk** [thepirat000/Audit.NET#292]
Hello, 
I am facing JSON Serialization exception, when I try to use the AuditScope.Create method. Attached is the exception I get. What am I missing?

![image](https://user-images.githubusercontent.com/16716754/80599012-dfc8a080-8a47-11ea-9c83-53c8de73077c.png)

Startup.cs file: below is code used:

```
public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
			Audit.Core.Configuration.DataProvider = new Audit.MongoDB.Providers.MongoDataProvider()
			{
				ConnectionString = "mongodb://localhost:27017",
				Database = "Audit",
				Collection = "Event"
			};
		}
```

I tried moving the dataprovider configuration to ConfigureServices method as well. I get the same error. Anything I am missing?

Thanks, 
Vani

**Comment by thepirat000** [comment]
Could you try by changing the `Id` property on `UserProfiles`class to be a string instead of an objectId?

```
[BsonRepresentation(BsonType.ObjectId]
public string Id{ get;set; }
```

I will try to get some time to take a closer look at this, but it would help if you can try that before.
