### ISSUE TITLE
I get a missing method error when saving

### ISSUE THREAD

**Issue by sanderkollerie** [thepirat000/Audit.NET#296]
**Describe the bug**
When i save a new record with mvc I get an error:

MissingMethodException: Method not found: 'System.Threading.Tasks.Task Audit.Core.AuditScope.DisposeAsync()'.

**To Reproduce**
In the controller:

[Audit(EventTypeName = "InsertOrderAction", IncludeHeaders = true, IncludeModel = true)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Naam")] Administratie administratie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(administratie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(administratie);
        }

In startup.cs

public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = Configuration.GetConnectionString("BBGDataContext");

            Audit.Core.Configuration.Setup()
        .UseSqlServer(config => config
        .ConnectionString(connectionString)
        .Schema("dbo")
        .TableName("Events")
        .IdColumnName("Id")
        .JsonColumnName("JsonData")
        .LastUpdatedColumnName("LastUpdatedDate")
        .CustomColumn("EventType", ev => ev.EventType)
        .CustomColumn("User", ev => ev.Environment.UserName));
Audit.Mvc 15.2.0
Audit.NET.SQLServer 15.2.0

**Comment by thepirat000** [comment]
please share your .csproj, or at least the target framework version

**Comment by sanderkollerie** [comment]
[Website.zip](https://github.com/thepirat000/Audit.NET/files/4617021/Website.zip)

Target framework is .net Core 3.1

**Comment by thepirat000** [comment]
It's a conflict with the framework versions. 

The core Audit.NET uses `IAsyncDisposable` insterface when targeting NETSTANDARD >= 2.1, but Audit.MVC was targeting up to NETSTANDARD 2.0

This will be fixed by adding the netstandard 2.1 as a target framework on Audit.MVC (and also Audit.WebApi)

**Comment by thepirat000** [comment]
Fixed on version 15.2.1, please upgrade your references and re-test

**Comment by sanderkollerie** [comment]
Thank you very much for the super quick fix! It works.
