### ISSUE TITLE
Is there any way to include/exclude properties for an Audit?

### ISSUE THREAD

**Issue by kalpeshsatasiya** [thepirat000/Audit.NET#30]
Hi,

I want to exclude some properties which are not required for an Audit.

**Comment by thepirat000** [comment]
You need to provide more info. What are you auditing? Are you using any Audit.NET [Extension](https://github.com/thepirat000/Audit.NET#extensions) ?

**Comment by kalpeshsatasiya** [comment]
I am an auditing of the object. 
Here is the example of the country class with properties.
```javascript
public class Country
    {
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string Code2 { get; set; }
        public string Code3 { get; set; }
	public DateTime CreatedDate { get; set; }
        public Guid CreatedBy { get; set; }
    }
```

From the country object, I want to exclude CreateDate and CreatedBy properties for the audit. 

I am using https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.SqlServer#auditnetsqlserver extension.

**Comment by thepirat000** [comment]
One option is to use the [Newtowsoft.Json](http://www.newtonsoft.com/json)'s [`JsonIgnore`](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonIgnoreAttribute.htm) attribute.
That will avoid the property being serialized on the audit json output.

```c#
using Newtonsoft.Json;
...
public class Country
{
    public int CountryId { get; set; }
    public string Name { get; set; }
    public string Code2 { get; set; }
    public string Code3 { get; set; }
    [JsonIgnore]
    public DateTime CreatedDate { get; set; }
    [JsonIgnore]
    public Guid CreatedBy { get; set; }
}
```

**Comment by kalpeshsatasiya** [comment]
Thanks for the suggestion.

That will exclude for the entire project not only for Audit functionality. So Audit.Net or any Extension support to exclude only specific properties for Audit.

**Comment by thepirat000** [comment]
Another wa y is by using a Custom Action, take a look al the following [issue](https://github.com/thepirat000/Audit.NET/issues/26)
