### ISSUE TITLE
Sql for creating postgress event table does not match the schema needed by the library

### ISSUE THREAD

**Issue by PhyDataDBA** [thepirat000/Audit.NET#302]
**Describe the bug**

**To Reproduce**
Steps or code to reproduce the behavior.

**Expected behavior**

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 13.0.0
 - Audit.EntityFramework: 13.0.0

**Additional context**

**Comment by thepirat000** [comment]
I think this is already fixed. Otherwise please add relevant comments.
