### ISSUE TITLE
Support for multiple logging providers?

### ISSUE THREAD

**Issue by dochoss** [thepirat000/Audit.NET#304]
Is there a way to configure Audit.NET to utilize mutiple providers?  I'd like to send audit events to Elasticsearch and SQL, for instance.  The Fluent syntax doesn't seem to support that, and I don't see any examples of that in the Readme.

**Comment by thepirat000** [comment]
Please check this [SO answer](https://stackoverflow.com/a/58206408/122195) on how to implement and configure a custom data provider that wraps other data providers.
