### ISSUE TITLE
How to configure AuditIdentityDbContext without inheritance

### ISSUE THREAD

**Issue by cakriwut** [thepirat000/Audit.NET#306]
**Describe the bug**
I am trying to use AuditIdentityDbContext without inheritance.  Is there any sample code that I can follow?

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Identity

**Target .NET framework:**
 - .NET Framework 4.6.2

**Additional context**
Sample request

**Comment by richagain** [comment]
You can use the library without inheriting from DbContext/AuditIdentityDbContext. In order to to that, you can define your DbContext in the following way:

public class MyContext : DbContext
{
    private static DbContextHelper _helper = new DbContextHelper();
    private readonly IAuditDbContext _auditContext;

    public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
        _auditContext = new DefaultAuditContext(this);
        _helper.SetConfig(_auditContext);
    }

    public override int SaveChanges()
    {
        return _helper.SaveChanges(_auditContext, () => base.SaveChanges());
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
    {
        return await _helper.SaveChangesAsync(_auditContext, () => base.SaveChangesAsync(cancellationToken));
    }
}

**Comment by cakriwut** [comment]
Thanks.
