### ISSUE TITLE
EventEntry does not show changes from owned entities

### ISSUE THREAD

**Issue by Amarus** [thepirat000/Audit.NET#308]
**Describe the bug**
One of the entity types we're auditing has some nested owned entities (without table splitting).
When changing a property on an owned entity, the audit action is called as expected but the the Audit.EntityFramewok.EventEntry.Changes list is always empty and doesn't allow detecting what changed.

**Expected behavior**
EventEntry.Changes should contain the changes that occured on owned entities.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 15.2.2

**Target .NET framework:**
 - .NET Core 3.1
 - Microsoft.EntityFrameworkCore 3.1.5
 - Npgsql.EntityFrameworkCore.PostgreSQL 3.1.4

**Additional context**
I took a quick glance to see if a workaround is possible, and I think it should be possible to add the changes of owned entities by looping on the Microsoft.EntityFrameworkCore.ChangeTracking.Navigations list.

I'm sorry that I can't provide reproduction code at the moment. Login to GitHub from my work's network is blocked so I'm creating the issue on my phone.
If needed, I'll try to reproduce from home later. Probably not before the weekend though.

**Comment by thepirat000** [comment]
Please add the code to reproduce

**Comment by Amarus** [comment]
Sorry for the delay, here's a reproduction test project: [Audit.OwnedEntitiesTest.zip](https://github.com/thepirat000/Audit.NET/files/5017057/Audit.OwnedEntitiesTest.zip)
I'll also add the code, for a quick view, to the end of this post.

While trying to write the minimal reproduction code, I've noticed that the default behaviour is actually different from what I thought it was. It seems that, by default, changing the property of an owned entity, does not trigger an audit on the parent entity.
The audit is happening in our project because of the the `LastModificationDate` property that gets touched on the `ChangeTracker.StateChanged` event (replicated in the attached code).

Is there a clean way to have changes of `order.ShippingAddress.City` to trigger an audit of the parent `Order` entity and list the changes?


---
Reproduction code:

The dbos:
```c#
    public class Order
    {
        [Key]
        public int Id { get; set; }
        public int Quantity { get; set; }
        public Address ShippingAddress { get; set; }
        public DateTime LastModificationDate { get; set; }
    }

    [Owned]
    public class Address
    {
        public string City { get; set; }
    }

    public class OrderAudit
    {
        [Key]
        public int Id { get; set; }
        public string Changes { get; set; }
    }
```

The DbContext:
```c#
    public class OrdersContext : AuditDbContext
    {
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderAudit> OrdersAudits { get; set; }

        public OrdersContext()
            : base()
        {
            ChangeTracker.StateChanged += ChangeTracker_StateChanged;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseNpgsql("Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=auditdotnet;");
            }

            Audit.Core.Configuration.Setup()
                .UseEntityFramework(x =>
                x.AuditTypeMapper(dboType =>
                {
                    if (dboType == typeof(Order))
                    {
                        return typeof(OrderAudit);
                    }

                    return null;
                })
                .AuditEntityAction((auditEvent, auditedEntity, auditEntity) =>
                {
                    if (auditEntity is OrderAudit orderAudit
                        && auditedEntity.Changes != null)
                    {
                        orderAudit.Changes = JsonConvert.SerializeObject(auditedEntity.Changes);
                    }
                }).IgnoreMatchedProperties());
        }

        private void ChangeTracker_StateChanged(object sender, Microsoft.EntityFrameworkCore.ChangeTracking.EntityStateChangedEventArgs e)
        {
            if (e.Entry.Entity is Order order)
            {
                order.LastModificationDate = DateTime.Now;
            }
        }
    }
```
And the unit test:
```c#
        [Test]
        public void ShouldAuditOwnedEntities()
        {
            using (var ctx = new OrdersContext())
            {
                var order = new Order()
                {
                   Quantity = 11,
                   ShippingAddress = new Address
                   {
                       City = "Pqris"
                   }
                };
                ctx.Orders.Add(order);
                ctx.SaveChanges();

                order = ctx.Orders.Single();
                order.Quantity = 10;
                ctx.SaveChanges();

                order = ctx.Orders.Single();
                order.ShippingAddress.City = "Paris";
                ctx.SaveChanges();

                var audits = ctx.OrdersAudits.ToList();
                Assert.Multiple(() =>
                {
                    Assert.That(audits.Count, Is.EqualTo(3)); // OK
                    Assert.That(audits[0].Changes, Is.Null, audits[0].Changes); // OK
                    Assert.That(audits[1].Changes, Does.Contain(nameof(Order.Quantity)), audits[1].Changes); // OK
                    Assert.That(audits[2].Changes, Does.Contain(nameof(Address.City)), audits[2].Changes); // Fails
                });
            }
        }
````

**Comment by thepirat000** [comment]
I think the problem is with your type mapper. When you change the address, the change will be triggered for an `Address` dbo type. So you should also allow auditing the Address entity:


```c#
Audit.Core.Configuration.Setup()
  .UseEntityFramework(x => x
    .AuditTypeMapper(dboType =>
    {
      if (dboType == typeof(Order) || dboType == typeof(Address))
      {
        return typeof(OrderAudit);
      }
      return null;
    })
```
