### ISSUE TITLE
Audit.EntityFramework with  Scaffold-DbContext not able to Setup

### ISSUE THREAD

**Issue by SudhirMangla** [thepirat000/Audit.NET#311]
Hi

I am using a database first approach with EF Core 3.0  and using  Scaffold-DbContext command to generate by my DB context.

Now the problem is that I can not use Audit.EntityFramework as my DB context is Autogenerated from command and any changes in change inheritance or adding a variable in my DB Context get overridden when I use the Scaffold-DbContext command again. 

Please suggest how to solve this issue. 

Inherit from AuditDbContext  requires a change in MyDb Context  this get overridden on next  Scaffold-DbContext 

using private readonly IAuditDbContext _auditContext;
this get overridden on next  Scaffold-DbContext  as my DB context is regenerated. 

Please share how to solve these issues.

**Comment by thepirat000** [comment]
What not to just manually change the inheritance after the scaffold-dbcontext completes?

**Comment by SudhirMangla** [comment]
> Why not just manually change the inheritance after the scaffold-dbcontext completes?

When the project is in development we request changes in DB and every time changing inheritance is a practical solution.  Moreover when we give the project to the maintenance team and again need to have that manual code change in DB context for every db change. We want to remove this manual step of code change in the DB context every time.

**Comment by thepirat000** [comment]
I don't think this library should take care of that.

Actually the scaffold-dbcontext *is* a manual step, right? Why is impractical to add the inheritance change. You could have a script that runs the scaffold and then changes dbcontext inheritance on the .cs file.
