### ISSUE TITLE
 Could not load type 'Elasticsearch.Net.IInternalSerializerWithFormatter' from assembly 'Elasticsearch.Net, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.

### ISSUE THREAD

**Issue by aramdata** [thepirat000/Audit.NET#313]
hello , 
when i update all packege of project Audit.net ElasticsearchDataProvider raise this error .
in my project exist package like 'Serilog.Sinks.Elasticsearch' , 'Elastic.Apm.NetCoreAll' .

Audit.NET version :
- Audit.NET.Elasticsearch:15.3.0
- Audit.NET:15.3.0

**Comment by thepirat000** [comment]
Include the code or attach a project that reproduces the error

**Comment by aramdata** [comment]
`
<PackageReference Include="Audit.NET.Elasticsearch" Version="15.3.0" />`
  `  <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.6.1" />`
`<PackageReference Include="Serilog.Sinks.Elasticsearch" Version="8.2.0" />`
`<PackageReference Include="Audit.NET" Version="15.3.0" />`
** and in staurtup.cs : **

`            Audit.Core.Configuration.DataProvider = new ElasticsearchDataProvider()
            {
                ConnectionSettings = new AuditConnectionSettings(new Uri(Configuration["ConnectionStrings:ElasticsearchAuditlogConnection"])),
                IndexBuilder = ev => $"auditlog-{Assembly.GetExecutingAssembly().GetName().Name.ToLower().Replace(".", "-")}-{ev.EventType.ToLower()}",
                IdBuilder = ev => Guid.NewGuid()
            };`

**Comment by thepirat000** [comment]
Add the following reference on your csproj:

`<PackageReference Include="Nest" Version="7.8.1" />`

I'll probably update the reference on Audit.Elasticsearch to a newer version of Nest on the next release, but in the meantime you can do it from your csproj.

**Comment by aramdata** [comment]
thank you

**Comment by thepirat000** [comment]
This was fixed on version 16.0.1 please upgrade your Audit.NET references
