### ISSUE TITLE
EventEntry.Entity in EntityFrameworkEvent is null when Action is insert or delete

### ISSUE THREAD

**Issue by Tony427** [thepirat000/Audit.NET#317]
I would like to get Entity Type from EventEntry. But it was null when Action is insert or delete.
Is this a feature or a bug?
I can get Type only when update.
![image](https://user-images.githubusercontent.com/20748537/89009042-5ffbec00-d33e-11ea-88f4-692d4a99e678.png)

**Comment by thepirat000** [comment]
Entity is not included by default, you must enable the setting `IncludeEntityObjects = true`, you can check the docs [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#settings)

**Comment by Tony427** [comment]
@thepirat000 Thanks so much. I didn't notice about that. 👍👍👍
