### ISSUE TITLE
Rolling file support

### ISSUE THREAD

**Issue by dbones** [thepirat000/Audit.NET#324]
**Describe the feature request**
I would like to run this audit solution with the Kubernetes sidecar pattern for logging https://kubernetes.io/docs/concepts/cluster-administration/logging/#streaming-sidecar-container

the idea here is the dotnet app would need to provide a rolling file, in its container
a sidecar container would read the tail of the file and then output this to its standard out
then fluentD will read the stdout of the sidecar container for audit only logs

in the above scenario, the main application container would still use its own standard out for its application logs

if the service has been running for some time, i would like this library to cycle, remove old entries from the audit file (otherwise this file is going to get insanely large)

**To Reproduce**
https://kubernetes.io/docs/concepts/cluster-administration/logging/#streaming-sidecar-container - shows the idea

**Expected behavior**
a way to set a max size and number of files

**Libraries (specify the Audit.NET extensions being used including version):**
NA

**Target .NET framework:**
For example:
 - .NET Core 3

**Additional context**

**Comment by thepirat000** [comment]
Maybe no need to reinvent the wheel and you can use the [Audit.NET log4net extension](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.log4net/README.md) and configuring a [RollingFileAppender](https://logging.apache.org/log4net/release/config-examples.html#RollingFileAppender)

**Comment by dbones** [comment]
cannot use log4net, it's officially dormant https://logging.apache.org/log4net/index.html, it's a shame as I really like the project

we need something with a guaranteed write, for every auditable entry. ATM we are looking at alternatives loggers (but want to keep your formatting of the output)

**Comment by thepirat000** [comment]
And what about using [Audit.NET.NLog](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.NLog/README.md) with [NLog](https://github.com/nlog/NLog) and its [File-target](https://github.com/NLog/NLog)?

**Comment by DemetriouJohn** [comment]
> we have to test it
> 
> we currently use Serilog as our logging framework, which also has an AuditTo setup (for guaranteed writes). however, it does not look like it fully supports the File logging API ([serilog/serilog-sinks-file#113](https://github.com/serilog/serilog-sinks-file/issues/113))
> 
> we are looking into a file watch, where Audit.NET writes to a folder called Audit, and a simple .NET app watches it, reads the file to the STDOUT and then deletes it (this looks to work as a concept)

so how was this resolved? I need audit.net logs to end up into serilog for a datadog sink
