### ISSUE TITLE
ControllerExtensions.Core.GetCurrentAuditScope() only support Controller

### ISSUE THREAD

**Issue by mattlangis** [thepirat000/Audit.NET#326]
**Describe the bug**
`GetCurrentAuditScope()` is only supported by `Controller` (MVC) and not by `ControllerBase` (WebAPI)

**To Reproduce**
```
public class TestAttribute : Attribute, IResultFilter
    {
        public void OnResultExecuting(ResultExecutingContext context)
        {
            // Not supported
            //if (context.Controller is ControllerBase controllerBase)
            //{
            //    var auditScope = controllerBase.GetCurrentAuditScope();
            //}

            if (context.Controller is Controller controller)
            {
                var auditScope = controller.GetCurrentAuditScope();
            }
        }

        public void OnResultExecuted(ResultExecutedContext context)
        { }
    }
```

**Expected behavior**
Since `Microsoft.AspNetCore.Mvc.Controller` is a child of `Microsoft.AspNetCore.Mvc.ControllerBase`, `ControllerExtensions.Core.GetCurrentAuditScope()` should work with `Microsoft.AspNetCore.Mvc.ControllerBase`. Also, the base is the one keeping `HttpContext`.

`ControllerBase` is also mostly used when doing `WebAPI` while `Controller` is for `MVC`

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.Mvc: 16.1.0

**Target .NET framework:**
 - ASP.NET Core 2.1+

**Additional context**
None, but keep the good work 😄

**Comment by thepirat000** [comment]
Fixed on version 16.1.1
