### ISSUE TITLE
Responce Body + Client IP ADDRESS

### ISSUE THREAD

**Issue by lumisoftusa** [thepirat000/Audit.NET#33]
Hello,

We have 4 apps which are already in production but for auditing we have to write a lot of code so we were looking for some robust mechanism with same functionality but with less code.

I am loving it to use AUDIT.NET believe me it only takes one day to attach to all apps.
Thanks.

Well i am looking for two things 
1) Is there any way to store client IP in Insert-event Method.
2) I want to store both client request JSON and response body JSON .

Thanks

**Comment by thepirat000** [comment]
Are you auditing a Web API using Audit.WebApi ?

**Comment by lumisoftusa** [comment]
Yes Iam auditing a WebApi using Adit.WebApi

**Comment by lumisoftusa** [comment]
Can anybody help me.

**Comment by thepirat000** [comment]
Sorry, I didn't have time to take a look, but the Audit.WebApi extension already includes the client IP on its default [output](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#output-sample).

**Comment by lumisoftusa** [comment]
Thanks
I want to apply globally according to documentation I made global settings like that

 public static void Register(HttpConfiguration config)
{
    config.Filters.Add(new AuditApiAttribute());
}
But my question is where I would get the Filter result I want to handle all request response in one class for all controllers  is that possible.

**Comment by thepirat000** [comment]
Yes you can.
Actually you have many options:
1- You want to completely handle the audit events -> Customize your [DataProvider](https://github.com/thepirat000/Audit.NET#data-providers)
2- You want to only intercept the audit event before being handled by the data provider --> Use a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions).

An example for option 1:
```c#
public static void Register(HttpConfiguration config)
{
    config.Filters.Add(new AuditApiAttribute() 
    { 
        IncludeRequestBody = true, 
        IncludeResponseBody = true, 
        IncludeHeaders = true 
    });

    Audit.Core.Configuration.Setup()
        .UseCustomProvider(new MyDataProvider());
}
```

```c#
public class MyDataProvider : AuditDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        var webApiAction = auditEvent.GetWebApiAuditAction();
        var request = webApiAction.RequestBody;
        var response = webApiAction.ResponseBody;
        // ... insert event to a database, etc
        return Guid.NewGuid(); // return an identifier for the event
    }
}
```

An example for option 2:
```c#
public static void Register(HttpConfiguration config)
{
    config.Filters.Add(new AuditApiAttribute() 
    { 
        IncludeRequestBody = true, 
        IncludeResponseBody = true, 
        IncludeHeaders = true 
    });

    Audit.Core.Configuration.AddCustomAction(
        ActionType.OnEventSaving, 
        scope => MyAuditHandler.HandleScope(scope));
}
```

```c#
public class MyAuditHandler
{
    public static void HandleScope(AuditScope scope)
    {
        var webApiAction = scope.Event.GetWebApiAuditAction();
        var request = webApiAction.RequestBody;
        var response = webApiAction.ResponseBody;
        // ...
    }
}
```

**Comment by lumisoftusa** [comment]
I am already doing the same approach following is my code but only problem is Response/request always null.

   public static void Register(HttpConfiguration config)
        {
            config.Filters.Add(new AuditApiAttribute()
            {
                IncludeRequestBody = true,
                IncludeResponseBody = true,
                IncludeHeaders = true
            });
            Audit.Core.Configuration.Setup()
    .UseCustomProvider(new PCSK9AuditDataProvider());

}


using Audit.Core;
using Audit.WebApi;
using LUMISOFT_PCSK9_Api.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;

namespace LUMISOFT_PCSK9_Api.Controllers
{
    public class PCSK9AuditDataProvider :  AuditDataProvider
    {
        private string _connectionString;
        private string _schema = null;
        private string _tableName = "Event";
        private string _idColumnName = "EventId";
        private string _jsonColumnName = "Data";
        private string _ControllerName = "ControllerName";
        private DateTime _lastUpdatedDateColumnName;
        public string ConnectionString
        {
            get { return _connectionString; }
            set { _connectionString = value; }
        }
        public string TableName
        {
            get { return _tableName; }
            set { _tableName = value; }
        }
        public string JsonColumnName
        {
            get { return _jsonColumnName; }
            set { _jsonColumnName = value; }
        }
        public DateTime LastUpdatedDateColumnName
        {
            get { return _lastUpdatedDateColumnName; }
            set { _lastUpdatedDateColumnName = value; }
        }


        public string ControllerName
        {
            get { return _ControllerName; }
            set { _ControllerName = value; }
        }
        public string IdColumnName
        {
            get { return _idColumnName; }
            set { _idColumnName = value; }
        }
        public string Schema
        {
            get { return _schema; }
            set { _schema = value; }
        }
        private string FullTableName
        {
            get
            {
                return _schema != null
                    ? string.Format("[{0}].[{1}]", _schema, _tableName)
                    : string.Format("[{0}]", _tableName);
            }
        }
 
        public override object InsertEvent(AuditEvent auditEvent)
        {
             
            var webApiAction = auditEvent.GetWebApiAuditAction();
            var request = webApiAction.RequestBody;
            var response = webApiAction.ResponseBody;

            string body = auditEvent.ToJson();
            dynamic jsonData = JObject.Parse(body);
            var json = new SqlParameter(parameterName: "json", value: body);
            var ControllerName = new SqlParameter("ControllerName", jsonData.Action.ControllerName.Value);
            var ResponseStatusCode = new SqlParameter("ResponseStatusCode", "200");
            var ActionName = new SqlParameter("ActionName", jsonData.Action.ActionName.Value);
            var EventType = new SqlParameter("EventType", jsonData.EventType.Value);
            var MethodName = new SqlParameter("MethodName", jsonData.Action.HttpMethod.Value);
 
            using (var ctx = new PCSK9AuditEntities())
            {
                try
                {
                    var Sql = string.Format("INSERT INTO {0} (Data,ControllerName,ResponseStatusCode,ActionName,EventType,MethodName) OUTPUT CONVERT(NVARCHAR(MAX), INSERTED.[{2}]) AS [Id] VALUES (@json,@ControllerName,@ResponseStatusCode,@ActionName,@EventType,@MethodName)", FullTableName, _jsonColumnName, _idColumnName, ControllerName, ResponseStatusCode, ActionName, EventType, MethodName);
                    var result = ctx.Database.SqlQuery<string>(Sql, json, ControllerName, ResponseStatusCode, ActionName, EventType, MethodName);
                    return result.FirstOrDefault();
                }
                catch
                {
                    return null;
                }
            }
        }

        public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
        {

            var fileName = eventId.ToString();
            var data = auditEvent.ToJson();
           File.WriteAllText( @"D:\Log\"+eventId, auditEvent.ToJson());
        }
    }
}

**Comment by thepirat000** [comment]
Does the same happens if you use the Attribute on the controller/action ?

You're doing different things on the `InsertEvent` and `ReplaceEvent` (inserting into a database vs creating a file). Depending on which Creation Policy do you use, that could be wrong.

**Comment by M2xAy** [comment]
Hi, firstly thank oyu very much for your Project.

I have also a proiblem with my .net core 1.1 MVC Webapplication. If I host local on to IIS the it Shows under Clinet Ip my computername but if I publish to IIS Server the it Shows the ip from publish iis ip but not ip from Client. Iis this issue some as the other ? I triyed in Startup Project add the following code but it does not work.

            Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
            {
                if (scope.Event.Environment.Exception != null)
                {
                    scope.SetCustomField("Fehler", true);
                }
                scope.Event.Environment.MachineName = System.Environment.MachineName;
           
            });

**Comment by thepirat000** [comment]
`System.Environment.MachineName` is the name/IP of the machine where the code is running, not the client IP.

[Here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.Mvc/AuditAttribute.Core.cs#L50) is the client IP retrieval for MVC Net Core library.

**Comment by M2xAy** [comment]
Hi,
thank you very much for your answer.

I use Audit.EntityFramework and can also not use the mode httpcontext in Startup.

Client ip Attribute is not in entityframework

is possible use together ? I receive error message.

Best regards
