### ISSUE TITLE
No Error Message Text for Http Status 422

### ISSUE THREAD

**Issue by Jacquers** [thepirat000/Audit.NET#332]
I'm using it with .Net Core API 3.1 15.2.2 (so a bit outdated)
I only get the error message text when I return status code 500
e.g.
return StatusCode(500, new { success = false, error });
If I return e.g. 422 then the error message is blank (in the database entry)

Is there a way to configure this so I can get the error message text for other status codes?

Thanks.

**Comment by thepirat000** [comment]
The message should be part of the response body. You just need to set the `IncludeResponseBody` setting to `true`, and the event will include the object:

![image](https://user-images.githubusercontent.com/9836380/92624538-3dd68180-f28d-11ea-92c8-29dfa7dd4e27.png)
