### ISSUE TITLE
Original value does not report previous value during update

### ISSUE THREAD

**Issue by tessierp** [thepirat000/Audit.NET#335]
**Describe the bug**
Original value does not report previous value during update. Basically OriginalValue has the same value as NewValue.

**To Reproduce**
Supplied my own Audit Model and configured using the following code
`
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .AuditTypeMapper(t => typeof(IO.Database.Models.Audition.Audit))
        .AuditEntityAction<IO.Database.Models.Audition.Audit>((ev, entry, entity) =>
        {
             entity.AuditId = Guid.NewGuid();
             entity.DateTime = DateTime.Now;
             entity.TableName = entry.EntityType.Name;
             entity.KeyValues = JsonSerializer.Serialize(entry.PrimaryKey);
             entity.NewValues = entry.ToJson();
             entity.Operation = (Operation)Enum.Parse(typeof(Operation), entry.Action);
             //entity.AuditData = entry.ToJson();
             //entity.EntityType = entry.EntityType.Name;
             //entity.AuditDate = DateTime.Now;
             //entity.TablePk = entry.PrimaryKey.First().Value.ToString();
             entity.PerformedBy = GetUserFromContext(contextAccessor);
        })
       .IgnoreMatchedProperties(true));
`

Everything works as expected except for what I store in "NewValues" during an update. The OriginalValue is reporting the same value as NewValue. So if what I add is "Test1" and I update field to "Test2", both OriginalValue and NewValue will report "Test2" which is wrong.

**Expected behavior**
OriginalValue should display the previous value stored in the database during an update and not the new value.

**Libraries (specify the Audit.NET extensions being used including version):**
- Audit.EntityFramework.Core : 16.1.3

**Target .NET framework:**
For example:
 - .NET Standard 2.1

**Comment by thepirat000** [comment]
How are you updating the entities? I guess you are not retrieving the entity first but executing a direct Update.

Check this #53 and this #167

The issue is related to how the EF ChangeTracker tracks the changes.

**Comment by tessierp** [comment]
Indeed, changes need to be tracked in order for this to work. In a library that is way more modest than what your team developed, I did that and it works, I am able to get the old values from the database by calling the following code on active DbContext, dbContext.ChangeTracker.DetectChanges();

It would be way more practical if you would do this inside your library for Update cases, that way we wouldn't need to call this ourselves. Any chance this could be done from your side?

**Comment by tessierp** [comment]
From the posts you sent, I was able to modify my repository library by doing this

`
                var set = context.Set<TEntity>();
                var entry = set.Attach(entity);
                var updated = entry.CurrentValues.Clone();
                await entry.ReloadAsync();
                entry.CurrentValues.SetValues(updated);
                entry.State = EntityState.Modified;
`
which is of course followed by a save. It is a lot more code that is needed as opposed to what I had before which was : 
`
context.UpdateRange(entities);
await context.SaveChangesAsync().ConfigureAwait(false)
`
It is a bit slower now but at least it works. Of course, if I have multiple entities, I have to iterate through each of them so I presume this will translate at a cost in speed but hey, it is what it is.

**Comment by bcornpi** [comment]
Hi all,

I just logged a similar issue - should have looked here first.  I guess I'm confused as to why this is not default behavior.  It seems the point of auditing an Update is to capture state before the change and then state after the change.  Unless I'm missing something here, this seems like a fair amount of code to be added to ensure Updates behave as expected.  

Thanks!
Brian

**Comment by tessierp** [comment]
I couldn't agree more with you, this should be abstracted without the need for external intervention yet it is not.

**Comment by thepirat000** [comment]
Starting from version 21.0.2, the Audit.EntityFramework and Audit.EntityFramework.Core libraries introduce a new feature. 

The setting called `ReloadDatabaseValues` can be globally or individually configured for a DbContext instance. It determines whether the original values of audited entities should be fetched from the database prior to saving the audit event.

Consider the following examples of update and delete operations:

```c#
using (var context = new MyAuditedContext())
{
    //context.ReloadDatabaseValues = true;

    context.Cars.Update(new Car() { Id = 123, Name = "New name" });
    await context.SaveChangesAsync();
}
```

```c#
using (var context = new MyAuditedContext())
{
    //context.ReloadDatabaseValues = true;

    context.Entry(new Car() { Id = 123 }).State = EntityState.Deleted;
    await context.SaveChangesAsync();
}
```

If the ReloadDatabaseValues is not set to true, the EF Change Tracker will lack knowledge of the original values. 

Enabling the `ReloadDatabaseValues` setting triggers an extra database query to retrieve the original values prior to the update operation. As a result, the audit event will contain the original values.
