### ISSUE TITLE
Support for netcoreapp3.1

### ISSUE THREAD

**Issue by tapiokulmala** [thepirat000/Audit.NET#336]
Hi,

I have a weird issue with a a web project that targets netcoreapp3.1.
I added references to Audit.Mvc and Audit.WebApi packages and our CI pipeline is not happy about it. The nuget restore fails with error 

NU1202: Package x.x.x 2.0.2 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package x.x.x 2.0.2 supports: netstandard2.1 (.NETStandard,Version=v2.1)

I don't know what really is going on but the only reasonable explanation for this is that packages  Audit.MVC and Audit.WebApi do not have a targetframework netcoreapp3.1 

Am I on the right track or do you have any other explanation for this?

I can create a pull request for netcoreapp3.1 support if needed. There should'n be any real code changes. Only a bunch of csproj -changes and quite a few #if preprocessor tweaks

/Tapio

**Comment by thepirat000** [comment]
could you share your .csproj or al least the relevant parts?

**Comment by tapiokulmala** [comment]
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <TypeScriptToolsVersion>3.7</TypeScriptToolsVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCoreRateLimit" Version="3.0.5" />
    <PackageReference Include="Audit.Mvc" Version="16.1.4" />
    <PackageReference Include="Audit.NET" Version="16.1.4" />
    <PackageReference Include="Audit.NET.SqlServer" Version="16.1.4" />
    <PackageReference Include="Audit.WebApi" Version="16.1.4" />
    <PackageReference Include="EvoPdf.HtmlToPdf.NetCore" Version="8.0.0" />
    <PackageReference Include="Innofactor.EfCoreJsonValueConverter" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.1" />
    <PackageReference Include="nClam" Version="4.0.1" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.0" />
    <PackageReference Include="NServiceBus.Callbacks" Version="3.0.0" />
    <PackageReference Include="NServiceBus.MicrosoftLogging.Hosting" Version="1.3.1" />
    <PackageReference Include="NServiceBus.Persistence.Sql" Version="4.6.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0" />
  </ItemGroup>

</Project>

**Comment by thepirat000** [comment]
I mean a compilable or at least understandable portion of your csproj, not random values from it...

**Comment by tapiokulmala** [comment]
Sorry, for some reason the code didn't show up correctly...

**Comment by thepirat000** [comment]
I was unable to reproduce. The csproj restores the packages without any warning or error. I tried with both `nuget restore` (nuget 5.0.2) and `dotnet restore`

**Comment by tapiokulmala** [comment]
Thank you very much. The problem was the nuget version on our ci-server. I tested with newer versions and the last 4.* version had the same problem. 5.0.2 fixed it.

It's just weird that this hasn't happened before.
