### ISSUE TITLE
Setting Custom Field values from ambient context

### ISSUE THREAD

**Issue by arindamdat** [thepirat000/Audit.NET#337]
This is actually not an issue, rather a question. How to set Custom Field values from an ambient context, say for example from another `Scoped` service or HttpContext etc?

**Comment by thepirat000** [comment]
You can use Custom Actions. 

[Here](https://stackoverflow.com/a/63975193/122195) is an example:

```
public class Startup
{
	public void Configure(IApplicationBuilder app, IHttpContextAccessor contextAccessor)
	{
		// ...
		Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
		{
			var httpContext = contextAccessor.HttpContext;
			// Add a new field
			scope.Event.CustomFields["CorrelationId"] = httpContext.TraceIdentifier;
			// reuse an existing field
			scope.Event.Environment.UserName = GetUserFromContext(httpContext);
		});
	}
}
```

**Comment by arindamdat** [comment]
Hi @thepirat000 , I am facing a issue, which might be related to this. I am trying to add the UserId to the metadata of the AuditEvent, as shown below. But on the event, I see different UserIds other than the one who was acting. It seems like randomly other logged-in user ids are being added. The `AuthorizationContext` basically gets the information from `httpContextAccessor.HttpContext`.

```
public void ConfigureServices(IServiceCollection services)
{
  services.AddScoped<IAuthorizationContext, AuthorizationContext>();
}

public void Configure(IApplicationBuilder app)
{
  Audit.Core.Configuration.AddCustomAction(Audit.Core.ActionType.OnEventSaving, scope =>
  {
     var authContext = app.ApplicationServices.GetRequiredService<IAuthorizationContext>();
     scope.SetCustomField("user", authContext.GetUserId());
  });
}
```
