### ISSUE TITLE
Support for custom database credentials provision with PostgreSql

### ISSUE THREAD

**Issue by VladimirNedoroslev** [thepirat000/Audit.NET#340]
Hi everyone! Following my [stackoverflow question](https://stackoverflow.com/questions/64168845/audit-net-obtain-database-credentials-dynamically) I am creating an issue as suggested by [thepirat000](https://stackoverflow.com/users/122195/thepirat000).

As I described on the stackoverflow there seems to be no way to configure custom database credentials builder for **PostgreSql**. [PostgreSqlDataProvider](https://github.com/thepirat000/Audit.NET/blob/a476cacfa33aef73e54f85240af17ef3fc0b03a6/src/Audit.NET.PostgreSql/Providers/PostgreSqlDataProvider.cs) sets the connection string once when the configuration happens.
It would be convenient if it was possible to inject some service into the Audit.NET configuration which provides the credentials whenever they are needed.

The use case is when the application needs to figure out the credentials at runtime (e.g. when there is a mechanism of database credentials rotation).

**Comment by thepirat000** [comment]
which dotnet framework do you target?
just asking because I'll need to upgrade the npgsql driver version, and the latest supports .NET >= 4.6.1 and .NET Core >= 2

**Comment by thepirat000** [comment]
With latest version yow can setup the configuration values as Functions, so the values will be retrieved when the audit events are created. For example:

```C#
Audit.Core.Configuration.Setup()
	.UsePostgreSql(config => config
		.ConnectionString(_ => serviceProvider.GetRequiredService<IDbConnectionStringProvider>().GetConnectionString())
		.Schema("")
		.TableName("")
		.IdColumnName("")
		.DataColumn("", DataType.JSONB)
		.LastUpdatedColumnName("");
	);
```
