### ISSUE TITLE
OriginalValue set to NewValue for EntityFramework and log4Net DataProvides in some cases

### ISSUE THREAD

**Issue by bcornpi** [thepirat000/Audit.NET#341]
Hi,

We recently implemented the Audit.NET library within our framework.  Awesome project and very easy to implement, so thank you for that!  For the EF implementation, we are using a single audit table to capture all audits rather than separate tables per auditable table.  We are also storing this data in the same database as the auditable tables.

However, we are noticing in some cases, for Update ActivityTypes specifically, the OriginalValue within the JSON data is set to the same value as the NewValue, meaning we loose the original value.  This is occurring for both the EF and log4net implementations.  Could there be some configuration detail we are missing?  Our implementation is fairly straightforward and out-of-the-box; we don't really need anything out of the ordinary here.  I'd be happy to provide code if that helps.  Just let me know.

We are using version 16.1.3 if that helps.  I'm hoping that this issue has been reported and that a work-around, if not solution, exists.

Thanks!
Brian

**Comment by thepirat000** [comment]
This is probably because the EF changetracker does not have information of the previous state (i.e. the object was not retrieved from the database prior to an Update)

Please check #53, #167 and #335

**Comment by bcornpi** [comment]
Hey Federico,

This makes sense.  Thanks for the explanation!

Thanks!

Brian Corn
Chief Technology Officer / Chief Product Officer
PlanIT Impact
913-909-8038
bcorn@planitimpact.com
www.planitimpact.com
