### ISSUE TITLE
SAS connection string with Table Storage

### ISSUE THREAD

**Issue by ps-tb** [thepirat000/Audit.NET#342]
I'd like to restrict access to the Table Storage that I have configured for logging so that only logs may be added. Is it possible to use a SAS connection string with Table Storage? It's mentioned in Blob storage but not in Table Storage. I've tried with multiple combinations of connection string but can't seem to get a connection. If supported, do you happen to have an example?

**Comment by thepirat000** [comment]
I think that's not supported by Microsoft.

check [this](https://stackoverflow.com/questions/53564739/access-azure-table-storage-with-azure-msi)
and [this](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-storage-blobs-and-queues)

I've tried to authenticate in the same way the Blob extension does, but for Azure Tables I get `System.InvalidOperationException: 'Token credential is not supported for this service.'`

**Comment by ps-tb** [comment]
@thepirat000 Thanks for the response. I was going to ask about AAD access as well but that's been answered in one of your links as well. Thanks for your help and this great tool.
