### ISSUE TITLE
Fully Qualified Type Name in AuditTarget.Type

### ISSUE THREAD

**Issue by sharakouze** [thepirat000/Audit.NET#343]
It would be nice if there was a way to store the fully qualified type name (Type.FullName instead of Type.Name) in the property Type of the AuditTarget class.
Maybe via a configuration option if you want to avoid a breaking change, or by adding a Namespace property ?

Thank you for reading me and for this great project !
Sharak

**Comment by thepirat000** [comment]
I think the namespace property is not enough since a composed type can have multiple namespaces, i.e. `System.Collections.Generic.List<System.IO.File>`

 But I think I can add a configuration to optionally include the namespaces on the FullName

**Comment by thepirat000** [comment]
On latest version `16.2.0` you can set the global `IncludeTypeNamespaces` configuration to `true`:

`Audit.Core.Configuration.IncludeTypeNamespaces = true;`

Please upgrade your references and re-test.
