### ISSUE TITLE
UseEntityFramework still outputs to json file

### ISSUE THREAD

**Issue by vukasinpetrovic** [thepirat000/Audit.NET#344]
**Describe the bug**
I did not understand how to disable logging to json file. I setup logging via EF (image below) and it works as I expected, but it also outputs to .json file. How can I disable logging to file?

![image](https://user-images.githubusercontent.com/23005422/97303557-d4b9c600-185a-11eb-897f-81e73330d043.png)

**To Reproduce**

**Expected behavior**
Logging via EF to specified table works, but it also logs to json file.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET 16.2.0
 - Audit.NET.MySql 16.2.0
 - Audit.EntityFramework.Core 16.2.0
 - Audit.EntityFramework.Identity.Core 16.2.0

**Target .NET framework:**
For example:
 - .NET Core 3.1
 - .NET

**Additional context**

**Comment by thepirat000** [comment]
I guess you are generating audits before the `Audit.Core.Configuration.Setup()` call, since log to json file is the default. 
You should setup the audit config _before_ any audit event generation, ideally on your startup code.

**Comment by vukasinpetrovic** [comment]
@thepirat000 You're right, I had call for script that generates user roles, that was before audit setup.
