### ISSUE TITLE
Entity Framework - ObjectContext SaveChanges not being caught

### ISSUE THREAD

**Issue by alexcherka** [thepirat000/Audit.NET#349]
**Describe the bug**
ObjectContext SaveChanges not being caught for Updating of an audited entity. **EDIT - This seems to being able to detect any changes for some reason when saving with ObjectContext.

**To Reproduce**
Contextual save - called from a service project within master project.
```
var objContext = ((IObjectContextAdapter)_dbContext).ObjectContext;
_dbContext.Entry(user).State = EntityState.Modified;
objContext.SaveChanges();
```

Data provider:
```
using Audit.Core;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TMS.Util
{
    public class PulseDataProvider : AuditDataProvider
    {
        public override object InsertEvent(AuditEvent auditEvent)
        {
            var fileName = $"Log{Guid.NewGuid()}.json";
            File.WriteAllText(@"D:\Logs\" + fileName, auditEvent.ToJson());
            return fileName;
        }
        public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
        {
            var fileName = eventId.ToString();
            File.WriteAllText(@"D:\Logs\" + fileName, auditEvent.ToJson());
        }
        public override T GetEvent<T>(object eventId)
        {
            var fileName = eventId.ToString();
            return JsonConvert.DeserializeObject<T>(File.ReadAllText(fileName));
        }
    }
}
```

DB context
```
[AuditDbContext(Mode = AuditOptionMode.OptIn, AuditEventType = "{database}_{context}", ExcludeValidationResults = true, IncludeIndependantAssociations = true)]
    public class DBContext : AuditIdentityDbContext<User, Role, int, UserLogin, UserRole, UserClaim>, IObjectContextAdapter
```

Startup
```
Audit.Core.Configuration.Setup()
                .UseCustomProvider(new PulseDataProvider());
            Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(config => config
                    .IncludeIndependantAssociations()
                    .IncludeEntityObjects());`

```
**Expected behavior**
Excepting the creation of an entry within my data provider.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 16.2.0.0

**Target .NET framework:**
For example:
 - .NET Standard 2.1
 - .NET Framework 4.7.2
 - EntityFramework 6.4.4

**Additional context**
This issue only seems to be when executing a savechanges on a objectcontext level and works fine when executed on DBContext level.

**Comment by thepirat000** [comment]
Not sure how if this can be solved since the framework depends on the call to `DbContext.SaveChanges()` which calls
its internal ObjectContext's `SaveChanges()`

An option that comes to my mind is that we could intercept the internal `ObjectContext` and hook into its `SavingChanges` event, but the audit framework needs the `DbContext` to proceed with the audit and I think there is no easy way to retrieve the `DbContext` from the `ObjectContext`.

```C#
public class YourContext : AuditDbContext
{
    public YourContext()
    {
        (this as IObjectContextAdapter).ObjectContext.SavingChanges += ObjectContext_SavingChanges;
    }

    private void ObjectContext_SavingChanges(object sender, EventArgs e)
    {
        // trigger the audit, but how? sender is the ObjectContext
    }
}
```

If you have any other approach or proposal please let me know

**Comment by thepirat000** [comment]
I see one approach that could work but I haven't fully tested all the use cases.

You have to use the audit library without inheriting from `AuditIdentityDbContext` (based on [this example](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#without-inheritance)), and call the audit on the internal `ObjectContext.SavingChanges` event:

```c#
public class YourContext : IdentityDbContext<User, Role, int, UserLogin, UserRole, UserClaim>
{
    private static DbContextHelper _helper = new DbContextHelper();
    private readonly IAuditDbContext _auditContext;

    public YourContext()
    {
        _auditContext = new DefaultAuditContext(this);
        _helper.SetConfig(_auditContext);
        (this as IObjectContextAdapter).ObjectContext.SavingChanges += ObjectContext_SavingChanges;
    }

    private void ObjectContext_SavingChanges(object sender, EventArgs e)
    {
        _helper.SaveChanges(_auditContext, () => 1);
    }

    // ...
}
```

Note you cannot use the `[AuditDbContext]` attribute to specify the audit settings, but you can use the fluent configuration API for that purpose:

```c#
    public void On_Your_Startup()
    {
        Audit.EntityFramework.Configuration.Setup()
            .ForAnyContext(_ => _.ExcludeValidationResults().IncludeIndependantAssociations().AuditEventType("{database}_{context}"))
            .UseOptIn();
    }
}
```

**Comment by alexcherka** [comment]
You got it exactly correct, I actually has transitioned to the non inheritance version today earlier and was just about to do what you suggested. It works flawlessly, A few minor quirks(thinking its the basis of my program design) to work out, Ill be testing with this extensively over the next week, so if I find any issues ill report them here! Awesome work and thanks for the help!

**Comment by alexcherka** [comment]
@thepirat000 Everything is looking so far so good, only thing is by using the non inheritance approach, I think I lose access to adding custom methods within the db context class. Looking to set a few things here, any ideas on approach?

**Comment by alexcherka** [comment]
I suppose just calling the _auditContext.ExtraFields.Add() would be a solution.

**Comment by thepirat000** [comment]
That's correct. 

Another solution, if you have to set a common/contextual value for all the audits, is to use a [custom action](https://github.com/thepirat000/Audit.NET#custom-actions). For example, on your startup:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    scope.SetCustomField("LoggedUsed", GetLoggedUser());
});
```

**Comment by alexcherka** [comment]
I took your approach and it worked flawlessly! I'm going to go ahead and close the ticket, its working perfectly and exactly as intended! Thanks for the help @thepirat000 !
