### ISSUE TITLE
Is there any way to improve performance?

### ISSUE THREAD

**Issue by xiaoxin01** [thepirat000/Audit.NET#35]
I have tried Audit.Mvc with FileDataProvider and made a performance test as shown below:

```c#
Audit.Core.Configuration.Setup()
                .UseFileLogProvider(config => config
                    .DirectoryBuilder(_ => $@"C:\Logs\{DateTime.Now:yyyy-MM-dd}")
                    .FilenamePrefix("Event_"));
```

```c#
    [Audit]
    public IActionResult Index()
```

result:

```
Speed=34177 pages/min
```

```c#
    //[Audit]
    public IActionResult Index()
```

result:

```
Speed=137437 pages/min
```

I think that wrote audit data immediately, or into independent files will cause performance issue. Is there any way to write all audit data into one file or make a batch writing?

**Comment by thepirat000** [comment]
The [File Data Provider](https://github.com/thepirat000/Audit.NET#data-providers-included) does not supports batch writing.
But nothing stops you to create your own [Data Provider](https://github.com/thepirat000/Audit.NET#data-providers) with your own audit events handling.

**Comment by xiaoxin01** [comment]
Thank you a lot.

Now I'm considering store  the data in the mysql database. But there is only a SqlDataProvider. Do you have a plan to add a mysql provider?

**Comment by thepirat000** [comment]
No, but if I have some time I will try to implement something. 
Would it help a dataprovider similar to the SqlDataProvider but for MySql?

**Comment by thepirat000** [comment]
Implemented [Audit.NET.MySql](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.MySql/README.md) extension to store audit events on MySQL

**Comment by xiaoxin01** [comment]
Thank you. I will try it later~
