### ISSUE TITLE
Allow Custom Exception Message

### ISSUE THREAD

**Issue by Tsukasa42** [thepirat000/Audit.NET#350]
**Describe the bug**
Assigning your own value to Environment.Exception is overwritten when the event ends.

**To Reproduce**
scope.Event.Environment.Exception = $"{ex.GetType().Name}: {ex.Message}";

**Expected behavior**
We should be allowed to set a custom exception message. While testing out the library on MacOS, the exception data is returned as a COMException with no actual details on the error.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.Net 16.2.0

**Target .NET framework:**
For example:
 - .NET Core 3.0

**Comment by thepirat000** [comment]
Note you can have extra fields on the `AuditEvent` or the `AuditEventEnvironment` by using the `CustomFields` property, for example:

```c#
scope.Event.Environment.CustomFields["ExceptionMessage"] = $"{ex.GetType().Name}: {ex.Message}";
```

If you use JSON serialization, that will be serialized as another property of the Environment object
