### ISSUE TITLE
AuditScope.CreateAsync throws EntryPointNotFoundException 

### ISSUE THREAD

**Issue by vaecors** [thepirat000/Audit.NET#354]
**Describe the bug**

We are attempting to leverage the `AuditScope.CreateAsync` method being called by a method that resides in a .netstandard2.0 class library targeting C# 8 that returns a `ValueTask` and utilizes `await using`. When the method in question is called by another method that resides in a project scoped for .NET Framework 4.8 (also targeting C# 8) a `EntryPointNotFoundException` is being thrown.

We have also attempted the fallback behavior of using a `try/finally` block and calling `DisposeAsync`. This also failed with a `MissingMethodException`.

**To Reproduce**

A sample project has been attached to this issue to facilitate reproduction of both issues.

[WpfApp1.zip](https://github.com/thepirat000/Audit.NET/files/5758320/WpfApp1.zip)

**Expected behavior**

The operation should complete successfully without any exceptions being thrown. 

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.NET: 16.3.1

**Target .NET Frameworks:**
 - .NET Framework 4.8
 - .NET Standard 2.0

**Additional context**

We have a number other implementations that sucessfully leverage `IAsyncDisposable` and execute cross-frameworks calls and **do not** do not experience this same issue.

**Comment by thepirat000** [comment]
This was fixed on version 16.3.2, please upgrade your references and re-test.

Now it should not fail because of the `MissingMethodException` since I added compatiblity with `IAsyncDisposable` for .net >= 4.6.1, otherwise please let me know

**Comment by vaecors** [comment]
Just updated the references and ran the unit tests. Everything is green now so we're good to go.
