### ISSUE TITLE
Dynamic audit include of entity framework properties

### ISSUE THREAD

**Issue by alexcherka** [thepirat000/Audit.NET#359]
**Describe the bug**
Looking for a way to dynamically include properties on startup based via string. In the same way you can include a table dynamically like this:

```
Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(_ => _.ExcludeValidationResults()
                                     .AuditEventType("{database}_{context}")
                ).UseOptIn()
                .IncludeAny(t => t.Name == "User");`
```
So for example something along the lines of:
```
Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(_ => _.ExcludeValidationResults()
                                     .AuditEventType("{database}_{context}")
                                     .ForEntity(t => t.Name == "User").Include(p => p.Name == "Email")
                                                                                           .Include(p => p.Name == "UserName")
                ).UseOptIn();
```

The reason for all of this, is on startup i want to be able to specify a list of strings for tables and properties I want to include without code changes. So I would pull this list from another data point in memory and use it on startup.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 16.3.0

**Target .NET framework:**
For example:
 - .NET Framework 4.7.2

**Additional context**
Any insight on how to achieve this if possible. Thanks!

**Comment by thepirat000** [comment]
An alternative solution could be to use a Custom Action when the audit event is created so you can fix the EF audit by discarding the info you don't need.

For example

```c#
using Audit.EntityFramework;

Audit.Core.Configuration.AddOnCreatedAction(scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    // Remove entries for not included tables
    efEvent.Entries.RemoveAll(e => !included.ContainsKey(e.Table));
    foreach (var entry in efEvent.Entries)
    {
        // Remove changes for not included properties
        entry.Changes.RemoveAll(e => !included[entry.Table].Contains(e.ColumnName));
        // Remove columnvalues for not included properties
        foreach (var cv in entry.ColumnValues.Where(e => !included[entry.Table].Contains(e.Key)).ToList())
        {
            entry.ColumnValues.Remove(cv.Key);
        }
    }

    if (efEvent.Entries.Count == 0)
    {
        // Completely discard the event is there are no entries left
        scope.Discard();
    }
});
```

Assuming you have the include information like this:

```c#
var included = new Dictionary<string, List<string>>()
{
    {"User", new List<string>{"Name", "Email"} },
    {"Department", new List<string>{"Name", "Email"} }
};
```

**Comment by alexcherka** [comment]
That's an awesome way to approach it! Ill implement it and let you know how it goes, I like this solution a lot better if im honest. Great work as always!
