### ISSUE TITLE
Mark Audit.NET CLS Compliant

### ISSUE THREAD

**Issue by rick-putnam** [thepirat000/Audit.NET#36]
Would it be possible to mark the Audit.NET assembly CLS compliant by adding the ClsCompliantAttribute to the assembly.info file?

[assembly: CLSCompliant(true)]

Thanks for considering.

**Comment by thepirat000** [comment]
Marked the assemblies as CLSCompliant since version 7.0.5

Regards

**Comment by rick-putnam** [comment]
Thank you. The project is very easy to use and meets our needs quite well.

Regards.
