### ISSUE TITLE
Many-to-many relationship - ArgumentNullException: Value cannot be null. (Parameter 'name')

### ISSUE THREAD

**Issue by pergerch** [thepirat000/Audit.NET#360]
**Describe the bug**
`ArgumentNullException` is thrown when entities have a [many-to-many relationship](https://docs.microsoft.com/en-us/ef/core/modeling/relationships#many-to-many).

**To Reproduce**
Here is a repository with a ready-to-run project that demonstrates the issue: [AuditExample](https://github.com/pergerch/AuditExample)

We have two entities: `Person` and `Department` that have a many-to-many relationship via two navigation properties `Person.Departments` and `Department.Persons`:

```csharp
public class Person
{
    public int Id { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Department> Departments { get; set; }
}

public class Department
{
    public int Id { get; set; }
    public string Name { get; set; }
    public virtual ICollection<Person> Persons { get; set; }
}
```

The relationship is explicitely configured the following:

```csharp
public class PersonsContext : AuditDbContext
{
    // ...
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>().HasMany<Department>(x => x.Departments).WithMany(x => x.Persons);
    }
}
```

However, omitting the fluent configuration doesn't change the behavior. But deriving from `DbContext` instead of `AuditDbContext` __fixes the problem__.

Here is the part of the main method with the issue:

```csharp
// ...
context.Departments.Add(new Department() { Id = 1, Name = "Development" });
context.Departments.Add(new Department() { Id = 2, Name = "Research" });

context.SaveChanges();

context.Persons.Add(new Person() { Id = 1, Name = "Alice", Departments = context.Departments.ToList() });
context.Persons.Add(new Person() { Id = 2, Name = "Bob", Departments = context.Departments.ToList() });

// ArgumentNullException will be thrown here: Value cannot be null. (Parameter 'name')
context.SaveChanges();
```

**Expected behavior**
No exception should be thrown and the audit information should be written.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 16.4.0

**Target .NET framework:**
 - .NET 5.0

**Comment by thepirat000** [comment]
First of all I want to thank you for your cooperation sharing a project that reproduces the issue, I wish all the issues were described as you did...

The problem was because of EF Core changes on the latest version that, as usually, affects the libraries that depends on the representation of the EF ChangeTracker. 

Anyway I've fixed the issue on version 16.4.1, please upgrade your references and re-test.

**Comment by pergerch** [comment]
Thank you for your quick response. No worries about the demo project, it should anyway be the standard in my opinion.

Thanks a lot. The new version works like a charm.

**Comment by pergerch** [comment]
Please hold on before closing the issue. It works fine in my demo project but not in the real solution. Same error as before. Trying to figure out what the issue is. 
Again, when using DbContext instead of AuditDbContext it works.

**Comment by pergerch** [comment]
The new issue is related to owned types. When two entities have the same owned type defined, I get the same exception as above. Please find the live sample in the [corresponding branch of my sample](https://github.com/pergerch/AuditExample/tree/bug/owned-type-multiple).

We have a class `Address`:

```csharp
public class Address
{
    public string City { get; set; }
    public string Street { get; set; }
}
```

Both `Person` and `Department` have defined the address as an owned type:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Person>().OwnsOne(x => x.Address);
    modelBuilder.Entity<Department>().OwnsOne(x => x.Address);
}
```

The exception is thrown in `SaveChanges`, after inserting just one `Department` with an `Address`:

```csharp
context.Departments.Add(new Department()
{
    Id = 1, Name = "Development", Address = new Address { City = "Vienna", Street = "First Street" },
});

// ArgumentNullException will be thrown here: Value cannot be null. (Parameter 'name')
context.SaveChanges();
```

**Comment by thepirat000** [comment]
The owned entities issue should be fixed on version 16.4.2, please upgrade and re-test.

I'm not sure if there will be more issues with EF Core 5, I hope not, but the breaking changes on new versions of EF Core always had  big impact on libraries that depends on some internals of the framework, specially since MS doesn't provide documentation beyond the minimum for the EF DbContext clients.

Good luck

**Comment by pergerch** [comment]
Thanks again for the quick bugfix. It works now :)

**Comment by richagain** [comment]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.Buffers.ReadOnlySequence`1.TryGet(SequencePosition& position, ReadOnlyMemory`1& memory, Boolean advance)
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at Audit.WebApi.AuditApiHelper.GetRequestBody(HttpContext httpContext)
   at Audit.WebApi.AuditApiAdapter.CreateOrUpdateAction(ActionExecutingContext actionContext, Boolean includeHeaders, Boolean includeRequestBody, Boolean serializeParams, String eventTypeName)
   at Audit.WebApi.AuditApiAdapter.BeforeExecutingAsync(ActionExecutingContext actionContext, Boolean includeHeaders, Boolean includeRequestBody, Boolean serializeParams, String eventTypeName)
   at Audit.WebApi.AuditApiGlobalFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Cache-Control: no-cache
Connection: Keep-Alive
Pragma: no-cache
Content-Type: application/json;charset=UTF-8
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-SG,zh;q=0.9,en-SG;q=0.8,en;q=0.7,zh-CN;q=0.6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBdXRob3JpemF0aW9uIFNlcnZlciIsImF1ZCI6WyJlMDc3ODczNDMyMTM0ZjMwYjE4MzUxZjBjNWE5YjM5MyIsIlJlc291cmNlIFNlcnZlciJdLCJqdGkiOiJkMzRmYWFhNi0zNTI0LTQ1NTItYjMzYS04NGFhMmM2M2U1OTUiLCJpYXQiOiIxLzI2LzIwMjEgOToxNToxNiBBTSIsInN1YiI6ImFkbWluaXN0cmF0b3IiLCJQZXJtaXNzaW9uIjpbIkFkbWluaXN0cmF0aW9uLlVzZXJzLkNyZWF0ZSIsIkFkbWluaXN0cmF0aW9uLlJvbGVzLkRlbGV0ZSIsIkFkbWluaXN0cmF0aW9uLlJvbGVzLlVwZGF0ZSIsIkFkbWluaXN0cmF0aW9uLlJvbGVzLkFzc2lnblVzZXJzIiwiQWRtaW5pc3RyYXRpb24uUm9sZXMuUmVtb3ZlVXNlcnMiLCJBZG1pbmlzdHJhdGlvbi5Vc2Vycy5MaXN0IiwiQWRtaW5pc3RyYXRpb24uVXNlcnMuRGVsZXRlIiwiQWRtaW5pc3RyYXRpb24uUm9sZXMuQ3JlYXRlIiwiQWRtaW5pc3RyYXRpb24uVXNlcnMuQ2hhbmdlUGFzc3dvcmQiLCJBZG1pbmlzdHJhdGlvbi5Vc2Vycy5VcGRhdGVSb2xlcyIsIkFkbWluaXN0cmF0aW9uLlVzZXJzLlVwZGF0ZSIsIkFkbWluaXN0cmF0aW9uLlJvbGVzLlJlYWQiLCJBZG1pbmlzdHJhdGlvbi5Sb2xlcy5VcGRhdGVQZXJtaXNzaW9ucyIsIkFkbWluaXN0cmF0aW9uLlJvbGVzLlBlcm1pc3Npb25zIiwiQWRtaW5pc3RyYXRpb24uVXNlcnMuVW5sb2NrIiwiQWRtaW5pc3RyYXRpb24uVXNlcnMuTG9ja291dCIsIkFkbWluaXN0cmF0aW9uLlVzZXJzLlJlYWQiLCJBZG1pbmlzdHJhdGlvbi5Sb2xlcy5MaXN0Il0sIm5iZiI6MTYxMTY1MjUxNiwiZXhwIjoxNjExNjU5NzE2fQ.2Ht47nC2RDCVNzEdRcLY3Y106Qxwxe_zna4E2Kc2lXs
Cookie: Global.CurrentUICulture=zh-SG; __gads=ID=4ad620e83fda263a-22ee9dfc4fc50044:T=1608714045:RT=1608714045:S=ALNI_MbD_6DXDktTH254l6bzOEYsOZO5pg
Host: localhost:44389
Referer: http://localhost:8000/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Origin: http://localhost:8000
Content-Length: 10
sec-fetch-site: cross-site
sec-fetch-mode: cors
sec-fetch-dest: empty
MS-ASPNETCORE-TOKEN: 9fcce34d-7507-4397-a905-4783b5265131
X-Original-Proto: http
X-Original-For: 127.0.0.1:65136
