### ISSUE TITLE
AuditEvent.Target is always null

### ISSUE THREAD

**Issue by stefanos-tsesmetzis** [thepirat000/Audit.NET#361]
Hi, 

I use this setup:

           Audit.Core.Configuration.Setup()
                    .UseAzureTableStorage(_ => _
                                    .ConnectionString(appSettings.AzureFileStorageConnectionstring)
                                    .TableName("auditevents")
                                    // .EntityMapper(ev => new AuditEventTableEntity(ev))
                                    .EntityBuilder(e => e
                                                    .PartitionKey(ev => $"Events {ev.StartDate:MMddyyyy}")
                                                    .RowKey(ev => Guid.NewGuid().ToString())
                                                    .Columns(c => c.FromObject(ev => new { 
                                                                Date = ev.StartDate, 
                                                                TableName = ev.Target,
                                                                AuditEvent = ev.ToJson()
                                                                }
                                                                )
                                                            )
                                                )
                                    );

TableName is never populated.
I would like to have the tablename in the rows, so I can query all changes on a single table historically.

Thanks,

**Comment by thepirat000** [comment]
That's the configuration of the audit output. 
Could you share your audited code?

**Comment by stefanos-tsesmetzis** [comment]
This is the code I've added in the DBContext:

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DataAccess.Models;
using Audit.EntityFramework;
using System.Threading.Tasks;
using System.Threading;
using Audit.Core;
using Audit.Core.Providers;

namespace DataAccess.Context
{
    [AuditDbContext(Mode = AuditOptionMode.OptOut,
     IncludeEntityObjects = true,
     AuditEventType = "DataContext")]
    public partial class DataContext : DbContext
    {
        private static DbContextHelper _helper = new DbContextHelper();
        private readonly IAuditDbContext _auditContext;

        public DataContext()
        {
        }

        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
            _auditContext = new DefaultAuditContext(this);
            _helper.SetConfig(_auditContext);
        }

        public override int SaveChanges()
        {
            return _helper.SaveChanges(_auditContext, () =>
base.SaveChanges());
        }

        public override async Task<int> SaveChangesAsync(CancellationToken
cancellationToken = default(CancellationToken))
        {
            return await _helper.SaveChangesAsync(_auditContext, () =>
base.SaveChangesAsync(cancellationToken));
        }

        public void OnScopeCreated(IAuditScope auditScope)
        {
            Database.BeginTransaction();
        }

        public void OnScopeSaving(IAuditScope auditScope)
        {
            try
            {
                // ... custom log saving ...
            }
            catch
            {
                // Rollback call is not mandatory. If exception thrown, the
transaction won't get commited
                Database.CurrentTransaction.Rollback();
                throw;
            }
            Database.CurrentTransaction.Commit();
        }

**Comment by thepirat000** [comment]
So you are using `Audit.EntityFramwork`, in that case you can access the specific EF audit event with the extension method `GetEntityFrameworkEvent()`, for example:

```c#
using Audit.EntityFramework;
...
TableName = ev.GetEntityFrameworkEvent().Entries[0].Table
```

**Comment by stefanos-tsesmetzis** [comment]
Dude,  you rock!!!!

I'll try it.
