### ISSUE TITLE
How to appends logs to a single file?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [thepirat000/Audit.NET#365]
Right now with the following it always replaces in the file:
```
                var auditPath = Path.Combine(Directory.GetCurrentDirectory(), "logs");
                Audit.Core.Configuration.Setup()
                    .UseFileLogProvider(_ => _.Directory(auditPath))
                    .WithCreationPolicy(EventCreationPolicy.InsertOnStartInsertOnEnd);
                _logger.LogInformation($"Setup audit file logger : {auditPath}");   
```

**Comment by thepirat000** [comment]
The default FileLogProvider doesn't allow appending.
For that you can use the [NLog extension](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.NLog/README.md) and configure the [NLog File-Target](https://github.com/nlog/NLog/wiki/File-target)
or use the [Log4Net extension](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.log4net/README.md) and configure its [File-Appender](https://logging.apache.org/log4net/release/config-examples.html#FileAppender) or create your own [Data Provider](https://github.com/thepirat000/Audit.NET#data-providers)

Refernce: https://github.com/thepirat000/Audit.NET/issues/324
