### ISSUE TITLE
Can this library can be used in MVC application using .Net Framework 4.0/3.5 ?

### ISSUE THREAD

**Issue by DhavalLimbad** [thepirat000/Audit.NET#37]
Firstly, Thanks a lot for creating this Awesome Library. I love using it.
I am new to package and have came across below issue while using this in one my application.
I added reference of Audit.net 6.2.0 in my MVC application built on .Net Framework 4.0. 
In Global.asax Start_Application event when i use below configuration, it gives me System.Object error:

 Audit.Core.Configuration.DataProvider = new Audit.SqlServer.Providers.SqlDataProvider()
            {
                ConnectionString = System.Configuration.ConfigurationManager.ConnectionStrings["AuditDBConnection"].ConnectionString,
                Schema = "odb",
                TableName = "LOG_JSON",
                IdColumnName = "LOG_JSON_ID",
                JsonColumnName = "JSON_STRING",
                LastUpdatedDateColumnName = "CREATED_DATE" ,
              
            };

Error i get while using "Audit.Core.Configuration" in first line :

The type 'System.Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by thepirat000** [comment]
Thanks for your comments.

Sorry, but unfortunately the library is only compatible with MVC 5 and MVC 6, and not compatible with MVC 4, since it targets framework NET 4.5 (or NET STANDARD 1.6),

**Comment by DhavalLimbad** [comment]
Thanks for your Quick reply. would really help me if i can get this working for .Net Framework 4.0.

Thanks in Advance :)

**Comment by thepirat000** [comment]
Will take some more time.. I need to set up a virtual machine for testing this :(

**Comment by thepirat000** [comment]
Sorry, this is undocumented since I didn't have time to test, but I've added Framework 4.0 support on version 7.0.6.
I'm not sure this is going to work, but please give a try with version 7.0.6 and let me know.

Regards
