### ISSUE TITLE
Feature Request: Make Audit.HttpClient work with HttpClientFactory

### ISSUE THREAD

**Issue by adnang** [thepirat000/Audit.NET#374]
https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.HttpClient/README.md#usage

This doesn't play too nicely with HttpClients injected through HttpClientFactory, as the `AuditHttpClientHandler` is a `HttpClientHandler` rather than a `DelegatingHandler`

It would be good to be able to set up Audit.NET as an extension method on [HttpClientBuilderExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configurehttpclient?view=dotnet-plat-ext-5.0) in DI

Steve Gordon has created a good blog post on how this works https://www.stevejgordon.co.uk/httpclientfactory-aspnetcore-outgoing-request-middleware-pipeline-delegatinghandlers

**Comment by thepirat000** [comment]
I think it should be enough to make `AuditHttpClientHandler` inherit from `DelegatingHandler` instead of `HttpMessageHandler`, so you can do something like this on the startup:

```c#
services.AddHttpClient("GitHub", c =>
{
    c.BaseAddress = new Uri("https://api.github.com/");
})
.AddHttpMessageHandler<Audit.Http.AuditHttpClientHandler>();
```

What do you think?

**Comment by thepirat000** [comment]
The extension method `AddAuditHandler` was added on version 16.5.2

Please upgrade your references and re-test. 

Here is the doc https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.HttpClient#usage

For example:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpClient<ICatalog, Catalog>(c =>
    {
        c.BaseAddress = new Uri("https://api.github.com/");
    })
    .AddAuditHandler(_ => _
        .IncludeRequestBody()
        .IncludeResponseBody());
}
```

**Comment by adnang** [comment]
@thepirat000  thats great! thanks
