### ISSUE TITLE
Support for logging changes to collections in EF Core?

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#376]
Does the [EF Core logging](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md) support logging changes to collections such as `List<NavigationProperty>`, such as `Features` below?

e.g.
```C#
public class Bicycle
{
    public int Id { get; set; }
    public List<Feature> Features { get; set; }
}

public class Feature
{
    public int Id { get; set; }
    public string Name { get; set; }
}

```

**Comment by thepirat000** [comment]
Do you mean owned entities? yes.

Did you tried and encountered any specific issue?

**Comment by mrlife** [comment]
Hi @thepirat000, thank you. Not necessarily owned, but tracking which items are added/removed from a list such as `List<Feature> Features` (which is a many to many relationship) above?

I have not tried it but will start using this if it can track collections.

**Comment by thepirat000** [comment]
Yes, it will track the changes that the Entity Framework ChangeTracker is aware of.

**Comment by mrlife** [comment]
@thepirat000 Thanks for letting me know. May I ask a few setup questions here?

- When using the Fluent API to setup `Configuration`, it refers to `IAudit`. It looks like this is something I need to define, however I'm having some trouble determining what this needs to be.

i.e.

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .Map<Order, Audit_Order>()
            .Map<OrderItem, Audit_OrderItem>()
            .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
            {
                auditEntity.AuditDate = DateTime.UtcNow;
                auditEntity.UserName = evt.Environment.UserName;
                auditEntity.AuditAction = entry.Action; // Insert, Update, Delete
            })
        )
    );
```
- When mapping a model, it looks like I need to create the audit model (not created automatically) in order to set up the audit tables in the database. e.g. `Audit_Order` for `Order` in `.Map<Order, Audit_Order>()`. I would add any audit data I want here, i.e. `AuditDate`, `AuditAction`, and `UserName` in the above code.

**Comment by thepirat000** [comment]
For the first question refer to [this](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#common-action). In this casei `IAudit` is just an interface example of a common interface for your audited entities, assuming you have one.

For the second, please note the model will not be created automatically by the audit library, is up to you how do you want to structure the audit tables, i.e. One table for all the audits, one audit table per audited entity, and so on. [Here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#ef-provider-options) are multiple examples of the EF provider configuration.

**Comment by mrlife** [comment]
@thepirat000 Thank you so much.

**Comment by mrlife** [comment]
@thepirat000 Hi, I just want to confirm that EF Core tracking with this library requires a join entity for many to many relationships. EF Core no longer requires a join entity, but the library needs one in order to do its logging.
