### ISSUE TITLE
Scope nesting and db schema

### ISSUE THREAD

**Issue by eliteappdev** [thepirat000/Audit.NET#38]
Hi, 
I'm find your library very promising for my project, but I have couple of q's:
1)  Can this library provide nested audit scopes? How I can do that? 
I need to track all things in http request boundary and I interested in writing single event to store, 
this event should hold data entries smth like:
(Request) -> (Application scope) -> (Business scope) -> (EF scope)
where Request and EF holding data which already implemented in your extensions(Mvc,Sql),
Application and Business holding custom audit data

2) How to make custom DB schema for storing event not in json?

Thanks in advance!
P.S: You making good stuff 👍

**Comment by thepirat000** [comment]
Hi, thanks for your comments

For 1, nesting audit scopes has no special meaning, each one will be isolated. So each scope will trigger its own (or shared) data provider to save its output.
You could implement a shared [data provider](https://github.com/thepirat000/Audit.NET#data-providers), that is aware of the nesting, coordinates the outputs and saves only once. But I think you will be complicating too much.

Maybe you can accomplish what you want, maintaining some kind of RequestId along your call chain, so the same RequestId will be shared among the audit events that are part of the same request.
So you can identify the events belonging to the same request.

For 2, it really depends on where do you want to store the events, but basically you just need to create a class inheriting from `AuditDataProvider`, overriding the `InsertEvent` and optionally the `ReplaceEvent` methods:

```c#
public class MyCustomDataProvider : AuditDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        // Put a breakpoint here and watch what you have on `auditEvent` object
        var machine = auditEvent.Enviroment.MachineName;
        // If the event is an MVC audit, you can use the `GetMvcAuditAction` extension
        // (Each plugin has its own extension method like `GetEntityFrameworkEvent`, etc)
        var mvcAudit = auditEvent.GetMvcAuditAction();

        return inserted_id;
    }
}
```

**Comment by thepirat000** [comment]
Also check this other issue https://github.com/thepirat000/Audit.NET/issues/12

**Comment by eliteappdev** [comment]
Thanks, now things is more clear.

Agree with you about RequestId property.  

But let me clarify my case a little.

The thing is that I need a ms sql database where audit trail will be stored, also application should provide tracking capabilities of interested parts during http request like a triggering application services or domain logic impersonated with this request data. So in this case RequestId may work where i can group all relevant records in db, but than I need this field in db to be able to find it or filter as well as other properties for filtering and reporting capabilities.

1) Can I inherit from AuditEvent class and add my custom properties to store it through sql provider? 
2) How to specify such new properties to provider?
 
Now I only see how to specify default properties during configuration phase:
```csharp
Audit.Core.Configuration.DataProvider = new SqlDataProvider()
            {
                ConnectionString =@" ... ",
                Schema = "dbo",
                TableName = "Events",
                IdColumnName = "Id",
                JsonColumnName = "Data",
                LastUpdatedDateColumnName = "LastUpdatedDate"
           };
```

I assume in my case I'm also need to implement custom data provider with own storage mechanism and property mapping from extended AuditEvent class.

**Comment by thepirat000** [comment]
Yes, you can inherit from `AuditEvent`, actually that's what extensions does, for example see this file:
 [AuditEventEntityFramework]( https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/AuditEventEntityFramework.cs)

You can create your own audit event class:
```c#
public class YourAuditEvent : AuditEvent
    {
        public YourSecurityInfo SecInfo { get; set; }
        public YourApplicationInfo AppInfo { get; set; }
        //...
    }
```

Then you can pass an instance of your class when you create a scope with `AuditScope.Create`:
```c#
var ev = new YourAuditEvent();
ev.SecInfo = GetSecurityInfo();
var options = new AuditScopeOptions() { AuditEvent = ev };
using (var scope = AuditScope.Create(options))
{
	// ...
}
``` 

So, the data provider will get the instance of your class, here:
```c#
public class YourDataProvider : AuditDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        var ev = (YourAuditEvent)auditEvent; 
        // do what you need to store this object
    }
}
```
