### ISSUE TITLE
Nothing happening while using middleware

### ISSUE THREAD

**Issue by raffaeledoti** [thepirat000/Audit.NET#385]
Problem :

I'm trying to implement the middleware in my asp.net core web api project using postgreSql data provider in order to store the output in a cockroach db instance but , after configuring the service as described in the documentation section , no table was created in the db and nothing seems to happen. I don't know if the problem could be related to a configuration of the web api because i use endpoint routing instead of mvc but anyway i leave audit.net configuration code of my Startup.cs class :

```
//configure database output
Audit.Core.Configuration.Setup()
.UsePostgreSql(config => config
.ConnectionString("Server=dockerServerName;Port=port;User Id=user;Database=database;")
.Schema("Public")
.TableName("Audit")
.IdColumnName("Id")
.DataColumn("Data", Audit.PostgreSql.Configuration.DataType.JSONB)
.CustomColumn("User", ev => ev.Environment.UserName)
.LastUpdatedColumnName("Updated_date"));
//determine which http request must be logged
app.UseAuditMiddleware(options => options.FilterByRequest(httpReq => httpReq.Method.ToUpper().Equals("POST") || httpReq.Method.ToUpper().Equals("PUT")));
```

With this configuration i expect that all http requests with POST or PUT verbs will be logged to my Audit db table and
i also assume that the data provider will automatically create the tables in the database. Is that so or do I have to manually create them? 

Libraries :

 - Audit.WebApi.Core
 - Audit.Net.Postgres 

Target :

 - .NET Core 3.1

**Comment by thepirat000** [comment]
The PostgreSql data provider will not create the table, please check the [table contraints](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/README.md#table-constraints).

Could you share a minimal sample project that reproduces the issue?

**Comment by raffaeledoti** [comment]
> The PostgreSql data provider will not create the table, please check the [table contraints](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/README.md#table-constraints).
> 
> Can you check if you get file logs, by temporarily changing your configuration to something like this:
> 
> ```cs
> Audit.Core.Configuration.Setup()
>     .UseFileLogProvider(@"C:\TEMP\LOGS");
> ```
> 
> Could you share a minimal sample project that reproduces the issue?

I created the table with  ef migrations and now the middleware seems to work properly. Anyway custom fields aren't populated as expected but i will open a new issue for that. Thank you!
