### ISSUE TITLE
DbSet declaration required for audit entity when used with MapTable() but not with Map()

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#386]
In the following setup, the `Audit_Post` and `Audit_Tag` tables are created automatically without a `DbSet` declaration in the context. I assume this is happening as a result of their inclusion in `Map<TSource,TAudit>`. `Audit_PostTag` requires the `DbSet` in the context.

For parity, is it possible, and does it make sense, to automatically create the table for `Audit_PostTag` as well?

**Context**
```c#
public class MyContext : AuditDbContext
{
    public DbSet<Post> Posts { get; set; }
    public DbSet<Tag> Tags { get; set; }
    public DbSet<Audit_PostTag> Audit_PostTags { get; set; }
}
```

**Model**
```c#
public class Post
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Tag> Tags { get; set; }
}

public class Tag
{
    public int Id { get; set; }
    public string Text { get; set; }
    public ICollection<Post> Posts { get; set; }
}

public class Audit_Post
{
    public int Id { get; set; }
    public string Action { get; set; } // Insert, Delete or Update
    public int PostId { get; set; }
    public string Name { get; set; }
}

public class Audit_Tag
{
    public int Id { get; set; }
    public string Action { get; set; }
    public int TagId { get; set; }
    public string Text { get; set; }
}

public class Audit_PostTag
{
    public int Id { get; set; }
    public string Action { get; set; }
    public int TagId { get; set; }
    public int PostId { get; set; }
}
```

**Configuration**
```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .Map<Post, Audit_Post>()
            .Map<Tag, Audit_Tag>()
            .MapTable("PostTag", (EventEntry ent, Audit_PostTag auditPostTag) =>
            {
                auditPostTag.PostId = (int)ent.ColumnValues["PostsId"];
                auditPostTag.TagId = (int)ent.ColumnValues["TagsId"];
            }
        )
    );
```

**Comment by thepirat000** [comment]
The library does not create any additional EF entity mapping. The `Map` method will only create an internal relation between the types, but does not interfere with the EF entity mapping.

EF will create the tables if they are mapped on your DbContext as a `DbSet<T>` property **or** if you configure the mapping for the entity on `OnModelCreating`, isn't that your case?

**Comment by mrlife** [comment]
@thepirat000 Thank you, you are absolutely right. I was unable to find anything in the official docs about `DbSet` being optional when they entity is configured in `OnModelCreating`. Thanks for clearing it up!
