### ISSUE TITLE
Update QLDB DataProvider to use the async API

### ISSUE THREAD

**Issue by adrianiftode** [thepirat000/Audit.NET#388]
QLDB Driver has been enhanced with [asynchronous APIs](https://github.com/awslabs/amazon-qldb-driver-dotnet/issues/28) so opening this issue to migrate Audit.NET to use it

@thepirat000 I can give it a try in the following days

**Comment by thepirat000** [comment]
would you work on this? thanks

**Comment by adrianiftode** [comment]
I would like to work on this one if you don't mind

**Comment by thepirat000** [comment]
I don't mind, I appreciate it !
