### ISSUE TITLE
Insertar datos en base de datos via .Setup()

### ISSUE THREAD

**Issue by reche31** [thepirat000/Audit.NET#389]
Hi, I'm trying to insert the data generated from the registered changes.
At the moment I have managed to generate a JSON with the information, but I also need to insert that information to my database.

In my code can there be a bad approach?

This is my AuditLog class

   public class AuditLog
    {
        public int AuditId { get; set; }
        public string TablePk { get; set; }
        public string AuditAction { get; set; }
        public string AuditUser { get; set; }
        public DateTime AuditDate { get; set; }
        public string AuditData { get; set; }
        public string EntityType { get; set; }
    }

This is the context that extends from AuditDbContext (just a little piece of it)

public RecruitmentContext(DbContextOptions options) : base(options)
        {
            
        }

        public DbSet<CompanyEntity> Companies { get; set; }
 protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new CompanyEntityConfiguration());
        }

These are the calls in the Startup.cs

using Audit.Core;
using AuditNet = Audit.Core;

 AuditNet.Configuration.Setup()
                   .UseEntityFramework(_ => _
                       .AuditTypeMapper(t => typeof(AuditLog))
                       .AuditEntityAction<AuditLog>((ev, entry, entity) =>
                       {
                           entity.AuditData = entry.ToJson();
                           entity.EntityType = entry.EntityType.Name;
                           entity.AuditAction = entry.Action;
                           entity.AuditDate = DateTime.Now;
                           entity.AuditUser = Environment.UserName;
                           entity.TablePk = entry.PrimaryKey.First().Value.ToString();
                       })
                       .IgnoreMatchedProperties(true));

            AuditNet.Configuration.Setup()
                .UseEntityFramework(x => x
                .UseDbContext<RecruitmentContext>()
                .AuditTypeExplicitMapper(m => m                     
                    .AuditEntityAction<AuditLog>((ev, entry, entity) =>
                    {
                        entity.AuditData = entry.ToJson();
                        entity.EntityType = entry.EntityType.Name;
                        entity.AuditAction = entry.Action;
                        entity.AuditDate = DateTime.Now;
                        entity.AuditUser = Environment.UserName;
                        entity.TablePk = entry.PrimaryKey.First().Value.ToString();
                    })));

            AuditNet.Configuration.Setup()
                .UseFileLogProvider(config => config
                    .FilenamePrefix("Event_")
                    .Directory(@"C:\Users\Cristian Reche\source\repos\people-back"))
                .WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd)
                .WithAction(x => x.OnScopeCreated(scope => scope.SetCustomField("ApplicationId", "Pepople-Back Auditoria")));

**Comment by thepirat000** [comment]
I don't understand what the problem is, but from your code I can say you should call `Audit.Core.Configuration.Setup().Use...` only once, otherwise the second call will override the configuration.

**Comment by reche31** [comment]
I have commented on the other Audit.Core.Configuration.Setup (). Use calls.

I think my problem is that I have the PersonEntity table where I am copying those values in the AuditLog table plus the values that I want it to have in my database, I show you the two classes.

RecruitmentContext.cs
` public class RecruitmentContext : AuditDbContext
    {
        public RecruitmentContext(DbContextOptions options) : base(options)
        {
            
        }
public DbSet<AuditLog> AuditLog { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
  modelBuilder.ApplyConfiguration(new AuditLogConfiguration());

        }
    }
}`

And their respective configurations (PersonEntity is simplified so that it does not become too extensive)
MultiEntityBase is an abstract class where it has ID property and other common properties

PersonEntity.cs
` public class PersonEntity : MultiEntityBase
    {
        public string Adress { get; set; }
        
        public DateTime? BirthDate { get; set; }
        
        public bool? Disability { get; set; }
        
        public byte[] DisabilityCertificate { get; set; }
        
        public string Email { get; set; }
  }
}`

AuditLog.cs
`public class AuditLog
    {
        public int Id { get; set; }

        public int OrganizationId { get; set; }

        public string Adress { get; set; }

        public DateTime? BirthDate { get; set; }

        public bool? Disability { get; set; }

        public byte[] DisabilityCertificate { get; set; }

        public string Email { get; set; }

        public int AuditId { get; set; }

        public string TablePk { get; set; }

        public string AuditAction { get; set; }

        public string AuditUser { get; set; }

        public DateTime AuditDate { get; set; }

        public string AuditData { get; set; }

        public string EntityType { get; set; }
    }
}`

AuditLogConfiguration.cs 
` public class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
    {
        public void Configure(EntityTypeBuilder<AuditLog> builder)
        {
            builder.ToTable("AuditLog");
            builder.HasKey(p => p.AuditId);            
            builder.Property(p => p.AuditId).UseMySqlIdentityColumn();
            builder.Property(p => p.TablePk).IsRequired();
            builder.Property(p => p.AuditAction).IsRequired();
            builder.Property(p => p.AuditUser).IsRequired();
            builder.Property(p => p.AuditDate).IsRequired();
            builder.Property(p => p.AuditData).IsRequired();
            builder.Property(p => p.EntityType).IsRequired();
        }
    }`

Call in StartUp.cs
`
using Audit.Core;
using AuditNet = Audit.Core;

        AuditNet.Configuration.Setup()              
             .UseEntityFramework(ef => ef             
              .AuditTypeExplicitMapper(m => m
             .Map<AuditLog, PersonEntity>()    
             .AuditEntityAction<AuditLog>((evt, entry, auditEntity) =>
             {
                 auditEntity.AuditDate = DateTime.UtcNow;
                 auditEntity.AuditUser = evt.Environment.UserName;
                 auditEntity.AuditAction = entry.Action; // Insert, Update, Delete
            })
            )
         );`

The problem now comes when making the call through postMan, when making a GET, POST or PUT the following error appears
"Resource with id 1 not found."

Falla al intentar mapear mi DTO de la clase PersonaEntity

**Comment by reche31** [comment]
AuditLog.cs also has the Id attribute, I forgot to copy it into the comment, sorry

**Comment by thepirat000** [comment]
Can you include the complete _exception_ and also the _call stack_ when the error happens?

**Comment by reche31** [comment]
I will abbreviate the routes with "X"
 Resource with id 1 not found. at "X". GetByIdAsync (Int32 personId, Boolean includeCustomFields) in "X" \ PersonService.cs: line 238

The problem is that when making the map of the query (in this case GET) when doing the return of my DTO it returns the person in null

Here is the method that is called when doing the GET

 public async Task <PersonDto> GetByIdAsync (int personId, bool includeCustomFields = true)
        {
            _logger.Debug ($ "Get Person by Id {personId}");

            PersonEntity person = await InternalGetPerson (personId);
            PersonDto personDto = _mapper.Map<PersonDto>(person);

            return personDto;
}

InternalGetPerson is a TASK where it includes the information to the object

private async Task <PersonEntity> InternalGetPerson (int id)
        {
            PersonEntity person = _recruitmentContext
                .Person.AsNoTracking ()
                .Include (p => p.Candidatures)
                .ThenInclude (p => p.RecruitmentProcess)
                .ThenInclude (p => p.Client)
                .ThenInclude (p => p.PeopleUsers)
                .ThenInclude (p => p.PeopleUser) .AsNoTracking ()
                .Include (p => p.Trainings)
                .ThenInclude (p => p.AcademicDegree) .AsNoTracking ()
                .Include (p => p.ExperienceProfessionals)
                .ThenInclude (p => p.Role) .AsNoTracking ()
                .Include (p => p.ProfessionalCategory) .AsNoTracking ()
                .Include (p => p. Skills)
                .ThenInclude (p => p.Skill) .AsNoTracking ()
                .Include (p => p. Skills)
                .ThenInclude (p => p.Seniority) .AsNoTracking ()
                .Include (p => p. Languages)
                .ThenInclude (p => p.Language) .AsNoTracking ()
                .Include (p => p. Languages)
                .ThenInclude (p => p.Seniority) .AsNoTracking ()
                .Include (p => p.Certifications)
                .ThenInclude (p => p.Certification) .AsNoTracking ()
                .Include (p => p.Status) .AsNoTracking ()
                .Include (p => p.Area) .AsNoTracking ()
                .Where (p => p.Id == id
                    && p.OrganizationId == CurrentUserLoggedOrganizationId)
                .Where (_securityLayerService.ApplyLayer)
                .FirstOrDefault ();

            return person;
        }
The return of the person object is null, this did not happen before when applying the mapping in the startup. I think it is because of the where that compares the id

**Comment by thepirat000** [comment]
I don't think this is related to Audit.NET library, but with your mapper code
