### ISSUE TITLE
Constructor missing in AuditIdentityDBContext

### ISSUE THREAD

**Issue by DhavalLimbad** [thepirat000/Audit.NET#39]
I am trying to use this in one of my MVC 4.5 application and my DB context is defined as below:
```c#
public class MyDBContext : AuditIdentityDbContext<User>
    {
        public MyDBContext()
            : base("MyDBContext", throwIfV1Schema: false)
        {
        }
          //Additional DbSets here...
     }
```

While compiling the application it throws error in Constructor for - base("MyDBContext", throwIfV1Schema: false). I identified that the below constructor is missing in AuditIdentityDbContext and AuditDBContext class:

```c#
 /// <summary>
        ///  Constructor which takes the connection string to use
        /// </summary>
        /// <param name="nameOrConnectionString"></param>
        /// <param name="throwIfV1Schema">Will throw an exception if the schema matches that of Identity 1.0.0</param>
        public AuditIdentityDbContext(string nameOrConnectionString, bool throwIfV1Schema)
            : base(nameOrConnectionString)
        {
            if (throwIfV1Schema)
            {
                _helper.SetConfig(this);
            }
        }  
```

I added this constructor in Audit.EntityFramework Source in both the classes and added a reference of that source in Project and it started working fine. 

Would you suggest to add this in this package?

Please let me know in case you need any additional details.

Thanks,
Dhaval Limbad

**Comment by thepirat000** [comment]
I don't get what you're trying to accomplish.

The call to _helper.SetConfig is needed in order to initialize the internal configuration.

What's your use case for skipping the SetConfig call?

**Comment by thepirat000** [comment]
Any update on this?
