### ISSUE TITLE
Custom Data Provider setup through Dependency Injection

### ISSUE THREAD

**Issue by leshma** [thepirat000/Audit.NET#390]
Hi, I'm trying to resolve an issue I currently have with my solution. I'm trying to combine WebApi and EntityFramework extensions.

Namely, I'm trying to insert my DbContext object into the CustomDataProvider I have. Now, I've already tried the solutions told in the issue #194 , but none of them worked.

Here's what my constructor needs in my CustomDataProvider class:
```
public CustomDataProvider(IMapper mapper, ApplicationDbContext context, EntityFrameworkDataProvider efDataProvider)
{
    EFDataProvider = efDataProvider;
    Context = context;
    Mapper = mapper;
}
```

And here's the current problem I'm facing (in Startup.cs):
```
public void Configure(...)
{
      EntityFrameworkDataProvider efdp = new EntityFrameworkDataProvider(...);

      Audit.Core.Configuration.DataProvider = new CustomDataProvider(serviceProvider.GetRequiredService<IMapper>(),
                      serviceProvider.GetRequiredService<ApplicationDbContext>(), efdp);
}
```

P.S. I need the DbContext instance inside the CustomDataProvider so I could insert custom data models into my database.

**Comment by thepirat000** [comment]
And what's the problem?

**Comment by vukasinpetrovic** [comment]
@thepirat000 Sorry it was late and we did not realize that we did not write what was the actual problem 😄 Context gets disposed before it can be used inside data provider, that is our current problem.

**Comment by vukasinpetrovic** [comment]
> And what's the problem?
> 
> If it's that you don't have the required services at startup, then you could use the DataProviderFactory instead, which get's called each time an audit scope is created, for example:
> 
> ```
> Audit.Core.Configuration.DataProviderFactory = () => new CustomDataProvider(serviceProvider.GetRequiredService<IMapper>(),
>                       serviceProvider.GetRequiredService<ApplicationDbContext>(), efdp);
> ```

I tried that option with DataProviderFactory, but I get exception that IServiceProvider cannot be accessed because it was disposed. IServiceProvider is user from Configure function parameter.

![image](https://user-images.githubusercontent.com/23005422/113399016-ccccf780-939f-11eb-88a8-8765b1814f0a.png)

**Comment by vukasinpetrovic** [comment]
This is what worked finally, using DataProviderFactory and getting dbContext/services via contextAccessor.HttpContext.RequestService method. Is that good approach or should I do it another way because it requests service on every webapi method call?

![image](https://user-images.githubusercontent.com/23005422/113400916-dd32a180-93a2-11eb-9361-a61ab454681b.png)

**Comment by thepirat000** [comment]
I think that's the right approach. Requesting services on each action is fine. Also instantiating DbContext is cheap.

But you could use the service provider to request the `CustomDataProvider` and the dependencies will get injected on the constructor, like:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<CustomDataProvider>();
    services.AddSingleton<EntityFrameworkDataProvider>(new EntityFrameworkDataProvider())
    // ...
}

public void Configure(IServiceProvider serviceProvider)
{
    Audit.Core.Configuration.DataProviderFactory = () => serviceProvider.GetRequiredService<CustomDataProvider>();
}
```
