### ISSUE TITLE
Entity Framework Core dynamic table access

### ISSUE THREAD

**Issue by leshma** [thepirat000/Audit.NET#392]
Hello there,

I'm trying to achieve a dynamic table access in Entity Framework Core. 
I'm currently using the approach of Auditing through EntityFrameworkDataProvider and it's TypeMapping ([seen here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#common-action)).

Is there a way to access the DbContext sets dynamically by the name of the set represented as a string?
E.g.
```
public async Task<string> SomeMethod(string table, string id)
{
         var object = await _context.Set(table).Where(x => x.Id == id).SingleOrDefaultAsync();
         ...
}
```

### Why am I trying to achieve this?
I have a lot of models/sets and I don't want to have an implementation for each model separately because they'll all be practically the same - just with a different class type.

### Important Info:
I'm trying to **retrieve auditing data** on my Web App for some **specific object** based on it's **ID**. 
I also want to retrieve **only the changes** (aka. the Difference method), **not** the **full rows of data** for that specific object.

**Comment by thepirat000** [comment]
Can you explain a little bit more? 

Your question seems to be about accessing DbSets from a DbContext, but how is this related to the audit library?

**Comment by leshma** [comment]
I'm wondering: how would you get Audit data from a database through this implementation?

Would you make a method for each DbSet separately or is there a way to make it generic (to access any DbSet based on a name given as a string)?

I'd be glad if there's a generic way to do it since my project contains a lot of models/classes that each has it's own equivalent Audit class.

**Comment by thepirat000** [comment]
That really depends on your configuration, on how are you saving the audits (do you have multiple audit tables or just one table for all?, do you store a JSON column or separated columns?, etc)

The event retrieval is out of the scope of this library

**Comment by leshma** [comment]
I previously used the one table approach.
Now I'm trying to implement the multiple table approach, but I'm struggling to find a generic way to retrieve the data.

Alas, thanks for commenting.
I guess we'll have to figure something out.

**Comment by thepirat000** [comment]
Yes, maybe for audit retrieval you need to consider a different approach instead of using EF. 

Or store the information in a different way so it can be easily queried via EF.
