### ISSUE TITLE
Support for async AuditEntityAction

### ISSUE THREAD

**Issue by janamtote** [thepirat000/Audit.NET#397]
Hello! We're currently using `UseEntityFramework` and we're looking into calling an `async` method inside of `AuditEntityAction` like so:

```
// in Startup.Configure(IApplicationBuilder app)

Audit.Core.Configuration
    .Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .AuditEntityAction<AuditBase>(async (evt, entry, auditBase) =>
            {
                var serviceProvider = app.ApplicationServices.GetRequiredService<IHttpContextAccessor>().HttpContext!.RequestServices;
                var testService = serviceProvider.GetRequiredService<ITestService>();
                auditBase.TestData = await testService.GetTestDataAsync();
            })
        )
    );
```

This does not work because the whole `AuditEntityAction` is not awaited by Audit.NET internals and thus the `await` inside of it are not actually awaited.

Is there a workaround for this or other ways for getting async data from a service? Thank you!

**Comment by thepirat000** [comment]
I will check this, I think we can provide an alternative config method for asynchronous calls, something like `AuditEntityAsyncAction`:

```c#
Audit.Core.Configuration
    .Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .AuditEntityAsyncAction<AuditBase>(async (evt, entry, auditBase) =>
            {
                ...
                auditBase.TestData = await testService.GetTestDataAsync();
            })
        )
    );
```

**Comment by thepirat000** [comment]
Support for async entity actions was added on version 17.0.3, now you can pass an asynchronous method and it will we awaited.

Please upgrade your references and re-test

**Comment by janamtote** [comment]
Works like a charm! Thank you for the fixing it so quickly!
