### ISSUE TITLE
object reference not set error in DbContextHelper.SetConfig

### ISSUE THREAD

**Issue by IainmXray** [thepirat000/Audit.NET#40]
Hi,

This great library has saved us ages in getting good auditing set up, so many thanks indeed!!

We have one small problem with it.  We are using a dotnet 452 mvc app and in the Startup.startup method we are configuring a SQLProvider as follows

```
        public Startup(IHostingEnvironment env)
        {
            //Load application config as the first step in the startup
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
            builder.AddEnvironmentVariables();
            Configuration = builder.Build();

            //Set up a storage provider for the audit infrastructure that we are using
            //See https://github.com/thepirat000/Audit.NET
            var sqlProvider = new Audit.SqlServer.Providers.SqlDataProvider();
            sqlProvider.ConnectionString = Configuration.GetConnectionString("Link.Core.Db");
            sqlProvider.Schema = "audit";
            sqlProvider.LastUpdatedDateColumnName = "LastUpdateTime";
            Audit.Core.Configuration.Setup().UseCustomProvider(sqlProvider);

        }
```

We then instantiate our AuditDbContext object in the  ConfigureServices method as per:

```
    public void ConfigureServices(IServiceCollection services) {
        //Other service setup omitted for brevity
        services.AddScoped(_ => new LinkContext(Configuration.GetConnectionString("Link.Core.Db")));
   }
```

The first time we hit the API service we are getting the following error raised:

```
System.NullReferenceException was unhandled by user code
Message=Object reference not set to an instance of an object
StackTrace:
    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
    at Audit.EntityFramework.DbContextHelper.SetConfig(IAuditDbContext context)
    at Audit.EntityFramework.AuditDbContext..ctor(String nameOrConnectionString)
    at Link.Data.LinkContext..ctor(String connString)
    at Link.Api.Startup.<ConfigureServices>b__4_2(ISeachProvider _)
    ........ Remaining stack trace omitted for brevity
```
It appears to work subsequent to this so wondering if we are starting up something in the wrong order?

Thanks in advance

Iain

**Comment by thepirat000** [comment]
Hi, thanks for your comments.

 I was unable to reproduce, but it could be a synchronization issue with the auditAttributeCache on `DbContextHelper`. Do you get this error always? or sometimes it passed ok?

Will add a lock there and let you know so you can test.

Also, if you use the SqlDataProvider, you don't need to set it up as a Custom Provider, you can use the configuration API for SqlServer:

```c#
Audit.Core.Configuration.Setup()
    .UseSqlServer(config => config
        .ConnectionString(cnnString)
        .Schema("audit")
        .LastUpdatedColumnName("LastUpdateTime"));
```

**Comment by IainmXray** [comment]
Hi,
Yes the error happens every time but then subsequent calls are fine.  Happy to test any fix.

Thanks for the tip on setting up the configuration will make that change straight away as I love the fluent API.  Very easy to understand.

Really appreciate such a quick answer.  
Iain

**Comment by thepirat000** [comment]
Hi I think this is fixed on version 7.0.6, please re-test with latest version and let me know.

**Comment by IainmXray** [comment]
Hi,

Just to follow up and let you know that after the upgrade we are not seeing any errors at startup.  Will monitor for a few days but looks like the fix did it.

Thanks for such a speedy response and for contributing such cool code!!

**Comment by thepirat000** [comment]
Thank you
