### ISSUE TITLE
(EF Core 6 preview support) result.Table = definingType.GetTableName();

### ISSUE THREAD

**Issue by murugaratham** [thepirat000/Audit.NET#400]
**Describe the bug**

System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.

There's symbols checking for EF3 || EF5, not sure if this is causing issues

https://github.com/thepirat000/Audit.NET/blob/14c754cd63616fe126ea0da1470776f4376bdf12/src/Audit.EntityFramework/DbContextHelper.Core.cs#L154
https://github.com/thepirat000/Audit.NET/blob/14c754cd63616fe126ea0da1470776f4376bdf12/src/Audit.EntityFramework/DbContextHelper.Core.cs#L155

**To Reproduce**
Change project to EFCore 6 preview

**Expected behavior**
Audit to continue performing audit trails

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET.SqlServer: 14.9.1
 - Audit.EntityFramework: 14.9.1

**Target .NET framework:**
For example:
 - .NET Core 6 preview

**Additional context**

**Comment by thepirat000** [comment]
EF core 6 preview is not supported yet

**Comment by rlgordey** [comment]
@thepirat000 have any steps been taken on this? I would love to help. I can write code but I think I could help the most as a tester.

**Comment by thepirat000** [comment]
Not yet. 
Audit.NET doesn't reference any library that is in a pre-release state, and EF Core 6 is still in preview. So you could work if you want to start fixing the incompatibilities on the current pre-release version, but it will not be merged until an alpha version of EF Core 6 is released

**Comment by mrlife** [comment]
@thepirat000 With EF Core 6 now in release candidate status, what do you anticipate as far as releasing support with Audit.NET?

**Comment by thepirat000** [comment]
A new pre-release version was published and it includes support for .NET 6.0 and EF Core 6

Please upgrade your references to the latest version (19.0.0-rc.net60.1) and re-test.

Feel free to comment here or open new issues if you found anything is missing for EF Core 6.

NOTE that you **MUST** reference **Audit.EntityFramework.Core** and NOT Audit.EntityFramework, please check the readme on the pre-release branch: https://github.com/thepirat000/Audit.NET/blob/rc.net60/src/Audit.EntityFramework/README.md

**Comment by thepirat000** [comment]
Support for .NET 6.0 and EF Core 6.0 was added on version 19.0.0, please upgrade your references and re-test
