### ISSUE TITLE
Audit.net with DynamoDB Saving old and new Target as same.

### ISSUE THREAD

**Issue by jainashish1711** [thepirat000/Audit.NET#402]
**Describe the bug**
Unable to track old and new target object .Currently I have created a separate class library where the code for audit log is written which saves to dynamo DB and I call that through my service class  as shown in code snippets below .

**To Reproduce**
Steps or code to reproduce the behavior.
ClassLibrary Code:

```c#
public  class DisAuditLog:IDISAuditLog
    {
        private readonly ILogger<DisAuditLog> _logger;
        public DisAuditLog(ILogger<DisAuditLog> logger)
        {
            _logger = logger;
        }
        public void Log(Guid auditKey,string eventType, object targetObject, string Identifier ,string userName,string centerNumber,string comments,DateTime CreationDate)
        {
           
            try
            {
                using var audit = AuditScope.Create(eventType, () => targetObject);
                audit.SetCustomField("EventId", auditKey);
                audit.SetCustomField("UserID", userName);
                audit.SetCustomField("EntityName", "Donor_tblDonors");
                audit.SetCustomField("CenterNumber", centerNumber);
                audit.SetCustomField("PDN", PDN);
                audit.SetCustomField("CreationDate", CreationDate);
                audit.Comment(comments);
            }
            catch(Exception ex) 
            {
                _logger.LogError(ex, "Error occured while creating audit logs");
            }
        }
    }
```

Service class code for calling the log. here donor input object is passed first:

```c#
                var auditkey = Guid.NewGuid();
                donor.FirstName = "TestAuditBefore";
                _auditLog.Log(auditkey, "Donor:Create", donor, test, "test", "test", "test", DateTime.Now);
                var addedDonor = await _donorRepository.AddOrGetDonorAsync(donor);

                _addedDonor.FirstName = "TestAuditAfter" + DateTime.Now; // This code is just to test if by modifying i get old and new objects.
                _auditLog.Log(auditkey,"Donor:Create", addedDonor,test, "test", "test", "test", DateTime.Now);
```

**Expected behavior**
Should log both old and new object under same EventId Key.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 ![image](https://user-images.githubusercontent.com/29275351/118110155-b171f500-b3ff-11eb-8ef7-7d63b9f128c4.png)
**Target .NET framework:**
For example:
  - .NET Core 5

**Additional context**
Reading Credential is done at Startup.cs. Please let me know what additionally is required to track old and new objects

@thepirat000 @bgrainger

**Comment by thepirat000** [comment]
Is your `addedDonor` of the same type as your `donor` variable? 

The object tracker (old/new value) is designed to be for the same object that changes between the audit event creation and the audit event ending.

If you want to audit a different object at the beginning and at the end of the event, you should probably use two different custom fields,

Anyway there are some errors on your code. The same `AuditScope` instance should be used to add further information to an AuditEvent, but you are creating a different scope on each `_auditLog.Log()` call.

For example, you could make your Log method to return the `AuditScope`, and remove the using statement from there, so:

```c#
public AuditScope Log(Guid auditKey, string eventType, object targetObject, string userName, string centerNumber, string comments, string pdn)
{
	var audit = AuditScope.Create(eventType, () => targetObject, new
	{
		EventId = auditKey,
		UserID = userName,
		EntityName = "Donor_tblDonors",
		CenterNumber = centerNumber,
		PDN = pdn
	});
	audit.Comment(comments);
	return audit;
}
```

And add a using statement within the tracked object changes:
 
```c#
using (var scope = _auditLog.BeginLog(auditkey, "Donor:Create", donor, "test", "test", "test", "test"))
{
	// change donor value
	donor = await _donorRepository.AddOrGetDonorAsync(donor);
	donor.FirstName = "TestAuditAfter" + DateTime.Now;
}
```

**Comment by jainashish1711** [comment]
Yes my both objects were same. Thanks this works. Btw I tried the below approach which also worked for me 
here I first created audit object with the Target and passed my audit object to my custom log method.
After the first line I changed FirstName in object which got tracked as new object.
Do you see any problem here which can cause in future.

Main Method which is calling 
{
using var audit = AuditScope.Create("Donor:Create", () => donor);
                var addedDonor = await _donorRepository.AddOrGetDonorAsync(donor);
                addedDonor.FirstName = "TestAuditAfter" + DateTime.Now;
_auditLog.Log(audit, Guid.NewGuid(), "Donor:Create", addedDonor, addedDonor.PDN, "PEY0083", 905, "AnyotherComments", DateTime.Now, donor.GetType().ToString());
}
Log method being same as above in my initial thread with just one change as passing now audit object.

public void Log(Guid auditKey,string eventType, object targetObject, string Identifier ,string userName,string centerNumber,string comments,DateTime CreationDate)
        {
           
            try
            {
                using var audit = AuditScope.Create(eventType, () => targetObject);
                audit.SetCustomField("EventId", auditKey);
                audit.SetCustomField("UserID", userName);
                audit.SetCustomField("EntityName", "Donor_tblDonors");
                audit.SetCustomField("CenterNumber", centerNumber);
                audit.SetCustomField("PDN", Identifier );
                audit.SetCustomField("CreationDate", CreationDate);
                audit.Comment(comments);
            }
            catch(Exception ex) 
            {
                _logger.LogError(ex, "Error occured while creating audit logs");
            }
    Thanks for all your support
@thepirat000

**Comment by thepirat000** [comment]
I don't understand your approach. Looks like you're creating two auditscopes which seems unnecessary

**Comment by jainashish1711** [comment]
Actually I forgot to put the update code of log method. I have Update it now above. And yes I am passing audit scope from main method and not creating a new one  in my updated code.
@thepirat000

**Comment by jainashish1711** [comment]
Thanks for the support. Closing the issue
@thepirat000
