### ISSUE TITLE
.NET 5 on MacOS - Specified argument was out of the range of valid values. (Parameter 'start')

### ISSUE THREAD

**Issue by vukasinpetrovic** [thepirat000/Audit.NET#404]
**Describe the bug**
When I upgraded the projects target framework to net5.0 I got a runtime exception that stated "Specified argument was out of the range of valid values. (Parameter 'start')". One thing I noticed is that this only happens on MacOS, on Windows it works just fine without exception. 

**To Reproduce**
On mac osx upgrade projects target framework from 3.1 to 5.0

**Expected behavior**
When audit is called, the exception occurs.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET: 17.0.4
 - Audit.EntityFramework.Core: 17.0.4
 - Audit.EntityFramework.Identity.Core: 17.0.4
 - Audit.NET.MySql: 17.0.4
 - Audit.WebApi.Core: 17.0.4

**Target .NET framework:**
For example:
 - .NET 5

**Additional context**
Runtime Environment:
OS Name: Mac OS X
OS Version: 11.0
OS Platform: Darwin
RID: osx.11.0-x64
Base Path: /usr/local/share/dotnet/sdk/5.0.203/

Host (useful for support):
Version: 5.0.6
Commit: 478b2f8c0e

.NET SDKs installed:
3.1.406 [/usr/local/share/dotnet/sdk]
3.1.407 [/usr/local/share/dotnet/sdk]
3.1.408 [/usr/local/share/dotnet/sdk]
3.1.409 [/usr/local/share/dotnet/sdk]
5.0.103 [/usr/local/share/dotnet/sdk]
5.0.201 [/usr/local/share/dotnet/sdk]
5.0.202 [/usr/local/share/dotnet/sdk]
5.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

The IDE: Jetbrains Rider 2021.1.2 and VS 8.9.9

**Comment by vukasinpetrovic** [comment]
@thepirat000 Here is my discussion on aspnetcore github about this issue. I narrowed it down to WebApiAudit. https://github.com/dotnet/aspnetcore/issues/32784

**Comment by thepirat000** [comment]
Can you share you audit configuration? I mean the `Audit.Core.Configuration` calls, etc?

The preblem is when the library is trying to get the request body from the body stream. Did you added a middleware to enable buffering? Check this [note](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#note)

**Comment by vukasinpetrovic** [comment]
@thepirat000 Ohh, I missed that part of documentation. I just added that line with context.Request.EnableBuffering() and now there is no exception. Thank you for that hint. I will post my config below just in case someone needs it.

![image](https://user-images.githubusercontent.com/23005422/118692549-7c541100-b80a-11eb-938c-94f876f832e8.png)
![image](https://user-images.githubusercontent.com/23005422/118692613-8bd35a00-b80a-11eb-91a4-86c0c327cc10.png)
![image](https://user-images.githubusercontent.com/23005422/118692662-942b9500-b80a-11eb-8436-316741a22894.png)

**Comment by davidfowl** [comment]
It still shouldn't fail with this exception. We might still have a bug 😄

**Comment by thepirat000** [comment]
Hi David, glad to see you over here ! 

This is the code where the request body is read for audit puposes:

https://github.com/thepirat000/Audit.NET/blob/8d410cb919f09d0c35f7c622d2e21913bcc46c59/src/Audit.WebApi/AuditApiHelper.cs#L90

The `CopyToAsync` call is failing with `ArgumentOutOfRangeException` when buffering is not enabled on macOS.

**Comment by davidfowl** [comment]
For any request? Is the request a get/post request?

**Comment by vukasinpetrovic** [comment]
For me it happened only on POST requests (didn't test PUT requests but I can if needed).

**Comment by davidfowl** [comment]
Right, I was trying to narrow down the repro without this library. So a basic application that reproduces the problem with a POST and a call to CopyToAsync.

**Comment by thepirat000** [comment]
@vukasinpetrovic can you provide a minimal sample app that reproduces the issue on your environment?

**Comment by vukasinpetrovic** [comment]
@thepirat000 @davidfowl Here si a test .net 5 API project in which I was able to reproduce the issue. Audit.WebAPI was setup in Startup.cs file. There is a controller with GET and POST methods. Exception occurs only on POST method. Tell me if you need any more info from my side.

https://mega.nz/file/SY0SQAgZ#cH-6qk0hGQ3E4xQwGsYC0sW7monfEKTzaK1TCQkKVSY

**Comment by thepirat000** [comment]
It doesn't throw exception on Windows, but you get an empty request body if you don't add the `EnableBuffering()`

```
  "Action": {
    "TraceId": "8000000f-0000-fc00-b63f-84710c7967bb",
    "HttpMethod": "POST",
    "ControllerName": "WeatherForecast",
    "ActionName": "Post",
    "ActionParameters": {
      "forecase": {
        "Date": "2021-05-23T22:22:01.472Z",
        "TemperatureC": 0,
        "TemperatureF": 32,
        "Summary": "string"
      }
    },
    "RequestUrl": "https://localhost:44372/WeatherForecast",
    "IpAddress": "::1",
    "ResponseStatus": "OK",
    "ResponseStatusCode": 200,
    "RequestBody": {
      "Type": "application/json",
      "Length": 71,
      "Value": ""   <----------------------
    },
```

**Comment by thepirat000** [comment]
Starting on version 17.0.5, the request body stream will be read, only if the stream can be seek. 

https://github.com/thepirat000/Audit.NET/blob/532d3fd8b48750a12cdba8f2420a733d58a32e54/src/Audit.WebApi/AuditApiHelper.cs#L93

Please upgrade your references and re-test

**Comment by davidfowl** [comment]
What happens if the stream isn't seekable?

**Comment by thepirat000** [comment]
In that case the body stream will not be read and the audit output will not include the request body contents.
