### ISSUE TITLE
When update field to null, field NewValue is not in Changes Array

### ISSUE THREAD

**Issue by Evan7o** [thepirat000/Audit.NET#405]
**Describe the bug**
When the modified entity field to empty, the null NewValue is not in the Change Audit Log

**To Reproduce**
My Audit Config:
```cs
              Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
            {
                var httpContext = serviceProvider.GetService<IHttpContextAccessor>().HttpContext;
                scope.Event.Environment.UserName = httpContext.User.Identity.Name;
                var e = scope.Event.GetEntityFrameworkEvent();
                foreach (var item in e.Entries)
                {
                    if (item.Changes != null)
                        item.Changes = item.Changes.Where(a => a.NewValue != a.OriginalValue).ToList();
                }
                scope.Event.StartDate = DateTime.Now;
                scope.Event.EndDate = DateTime.Now;
            });
```
Update method:
```cs
  public async Task<T> Update<T>(T entity, bool isCommit = true) where T : EntityBase
        {

            var entry = _context.Attach(entity); 
            var updated = entry.CurrentValues.Clone();
            entry.Reload();
            entry.CurrentValues.SetValues(updated);

            if (isCommit)
            {
                await Commit();
            }

            return entity;
        }
```

Audit Logs:
```javascript
"Entries": [
            {
                "Table": "Sample",
                "Action": "Update",
                "PrimaryKey": {
                    "Id": "687690fd-cfd6-4196-8ca2-ad2f011a36e8"
                },
                "Changes": [
                    {
                        "ColumnName": "SamlingQty",
                        "NewValue": "Test"
                    },
                    {
                        "ColumnName": "SampleGetDate",
                        "OriginalValue": "2021-05-05T09:08:55.068"
                    },
...
```

**Expected behavior**
I update "SampleSetDate" to null, but Changes NewValue does not exist

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.Net: 15.1.1
 - Audit.Net.MongoDB: 15.1.1
 
**Target .NET framework:**
 - .NET Core 2.1

Thanks to everyone for any help and advice

**Comment by thepirat000** [comment]
I think this issue is related to how the EF ChangeTracker tracks the changes.

OriginalValue will only present the previous column value if and only if the entity to be updated is already being tracked by the EF context. 

Please Check https://github.com/thepirat000/Audit.NET/issues/53

**Comment by Evan7o** [comment]
Thanks for your reply,
But it correctly when I set it to not NULL. do I think I was ignored by the audit code in the case of NULL?
***@***.***D750A6.851443D0]
***@***.***D750A6.023AF350]
Best regards,
Evan You

发件人: Federico Daniel ***@***.***>
发送时间: 2021年5月22日 7:56
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [thepirat000/Audit.NET] When update field to null, field NewValue is not in Changes Array (#405)


I think this issue is related to how the EF ChangeTracker tracks the changes.

OriginalValue will only present the previous column value if and only if the entity to be updated is already being tracked by the EF context.

Please Check #53<https://github.com/thepirat000/Audit.NET/issues/53>

―

**Comment by Evan7o** [comment]
But it correctly when I set it to not NULL. do I think I was ignored by the audit code in the case of NULL?
![1](https://user-images.githubusercontent.com/12377284/119306577-f538ea00-bc9c-11eb-8a72-ec8e350ec551.png)
![2](https://user-images.githubusercontent.com/12377284/119306582-f66a1700-bc9c-11eb-9081-6b5b040b653e.png)

**Comment by thepirat000** [comment]
I guess you're using the default serialization mechanism which ignores the null valued properties:

https://github.com/thepirat000/Audit.NET/blob/8d410cb919f09d0c35f7c622d2e21913bcc46c59/src/Audit.NET/Configuration.cs#L73

So you could add the following on your startup logic to change the default behavior:

`Audit.Core.Configuration.JsonSettings.NullValueHandling = NullValueHandling.Include;`

**Comment by Evan7o** [comment]
> I guess you're using the default serialization mechanism which ignores the null valued properties:
> 
> https://github.com/thepirat000/Audit.NET/blob/8d410cb919f09d0c35f7c622d2e21913bcc46c59/src/Audit.NET/Configuration.cs#L73
> 
> So you could add the following on your startup logic to change the default behavior:
> 
> `Audit.Core.Configuration.JsonSettings.NullValueHandling = NullValueHandling.Include;`

Yes！ thank you very much！！
