### ISSUE TITLE
Audit.net DynamoDB: How to track an already changed object from UI

### ISSUE THREAD

**Issue by ashishjaintakeda** [thepirat000/Audit.NET#406]
**Describe the bug**
I am facing an issue to track the Changed object directly coming as an input from UI to API . I need to have value as old and new in Audit object. 
Earlier I spoke to you to how can i track old and new object which i am able to do with the below code snippet when the object is changed within the API itself
Below Donor Object would be linked to my EF table  but the audit logging is done in Dynamo DB.

**To Reproduce**
Steps or code to reproduce the behavior.

```c#
public DonorDto UpdateDonor(Donor donor)
{
  using (var scope = _auditLog.BeginLog(auditkey, "Donor:Create", donor, "test", "test", "test", "test"))
  {
	  // change donor value
	  donor = await _donorRepository.UpdateDonorAsync(donor);
  }
}
```

below Method is written is separate Class Lib:

```c#
public AuditScope Log(Guid auditKey, string eventType, object targetObject, string userName, string centerNumber, string comments, string pdn)
{
	var audit = AuditScope.Create(eventType, () => targetObject, new
	{
		EventId = auditKey,
		UserID = userName,
		EntityName = "Donor_tblDonors",
		CenterNumber = centerNumber,
		PDN = pdn
	});
	audit.Comment(comments);
	return audit;
}
```

**StartUp.cs**

```c#
Audit.Core.Configuration.Setup()
	.UseDynamoDB(_ => _.UseUrl("http://localhost:8000").Table("table"))
	.WithCreationPolicy(EventCreationPolicy.InsertOnEnd);
```

**Expected behavior**
Above donor object comes as an updated object directly to my API . But I need to track its old info also. 
Is there a way that to call Auditevent may be from  entitycontext class which would track this. Not sure if it may slow the performance of application 

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - ![image](https://user-images.githubusercontent.com/68368520/119219078-385e5600-bb01-11eb-95f7-cbfe13fbf62e.png)
**Target .NET framework:**
For example:
 - .Net Core 5

**Additional context**

@thepirat000

**Comment by thepirat000** [comment]
You should change you log method to receive a getter to the object, instead of the object itself:

```c#
public AuditScope Log(Guid auditKey, string eventType, Func<object> targetObject, string userName, string centerNumber, string comments, string pdn)
{
	var audit = AuditScope.Create(eventType, targetObject, new
	{
		EventId = auditKey,
		UserID = userName,
		EntityName = "Donor_tblDonors",
		CenterNumber = centerNumber,
		PDN = pdn
	});
	audit.Comment(comments);
	return audit;
}
```

Note the `Func<object> targetObject` instead of `object targetObject`, and note the change on the `AuditScope.Create` second argument.

Now you show call it like this:

```c#
using (var scope = _auditLog.BeginLog(auditkey, "Donor:Create", () => donor, "test", "test", "test", "test"))
```

**Comment by ashishjaintakeda** [comment]
Hi,

Thanks @thepirat000  for the response.

Issue what I am  facing is when I don't modify object  Inside the method (UpdateDonor). I already get the modified object as input and updatedonorasync method just calls the repository context to update the data. So is there a way where i can tie Audit event/AuditScope to my entity also so it will track whether it got the modified object or the same object and based on that new and old will be update.

@thepirat000

**Comment by thepirat000** [comment]
I don't understand the issue, did you tried with my suggestion and you're still getting the same output for new and old even if you modify the entity?

**Comment by ashishjaintakeda** [comment]
It is working now. thanks
