### ISSUE TITLE
Decrease Audit.Net time while creating audit entries

### ISSUE THREAD

**Issue by ahmed0304** [thepirat000/Audit.NET#414]
### Current Scenario
We have an endpoint and it has an entity and in that entity it has List of other entity.

- When we send request to it without Audit.Net configurations the response time can be 710ms to 723ms.
- But when we add Audit.Net, the response time increases to 1123ms i.e it comes in 4 digits value.

### Feature Requested
Any one of the following features can be added:

- Our main concern is to add such feature through which we just trigger it on starting and it keep tracking entities and creating their logs on background without increasing response time.
- Second one is to just reduce the Audit.Net time in creating audit logs
- Third one is to make it as a separate service, in which we just pass the url of running project which we want to track and it keep tracking logs of it.

**Comment by thepirat000** [comment]
The library was coded having performance in mind, so I think there is no much room for performance improvement on the code side. 

But which libraries are you using and which data provider do you use to store the data?

My question is where does it have bad performance? when _creating_ the audit event or when _saving_ the audit event?

If you want to save the audit logs in the background you could create you own data provider that inserts to a local Queue and have another process that insert the events from the Queue to whatever DB you are using.

**Comment by ahmed0304** [comment]
We are using `Audit.WebApi` and `Audit.NET.PostgreSql`

**Comment by thepirat000** [comment]
Try with a different data provider (maybe FileDataProvider, or UdpDataProvider) and compare the performance, at least for testing puposes. I guess the performance degradation is due to postgreSQL/network response time
