### ISSUE TITLE
Option to only Audit few fields instead of all fields

### ISSUE THREAD

**Issue by anandtpatel** [thepirat000/Audit.NET#416]
Instead of auditing all fields, May be decorate property that only needs to be audited?

**Comment by thepirat000** [comment]
Please mention to which extensions you're referring. What are you auditing and where do you store the audits

**Comment by anandtpatel** [comment]
I am auditing in MongoDB. I am auditing any field changes for now. But what if i want to audit 50% of fields.

Then I might want to decorate

[Audit]
public string Prop1

**Comment by thepirat000** [comment]
still need more information to provide help...
you are saving the audits to mongodb or you are auditing changes to mongodb?. Could you share your audit configuration (audit.core.configuration calls) and maybe a sample code?

Which audit.* libraries are you using?

**Comment by anandtpatel** [comment]
I am saving all my changes in MongoDB Audit Collection.

It store the json like this in collection

```
{
    "EventType": "Order:Update",
    "Environment": {
        "UserName": "Federico",
        "MachineName": "HP",
        "DomainName": "HP",
        "CallingMethodName": "Audit.UnitTest.AuditTests.TestUpdate()",
        "Exception": null,
        "Culture": "en-GB"
    },
    "StartDate": "2016-08-23T11:33:14.653191-05:00",
    "EndDate": "2016-08-23T11:33:23.1820786-05:00",
    "Duration": 8529,
    "Target": {
        "Type": "Order",
        "Old": {
            "OrderId": "39dc0d86-d5fc-4d2e-b918-fb1a97710c99",
            "Status": 2,
            "OrderItems": [{
                "Sku": "1002",
                "Quantity": 3.0,
                "field1" : "value1",
            }]
        },
        "New": {
            "OrderId": "39dc0d86-d5fc-4d2e-b918-fb1a97710c99",
            "Status": 3,
             "OrderItems": [{
                "Sku": "1002",
                "Quantity": 2.0,
                "field1" : "value1",
            }]
        }
    }
}
```

But what if only want it store this in Collection. Only the changed fields in **Old** and **New**.

```
{
    "EventType": "Order:Update",
    "Environment": {
        "UserName": "Federico",
        "MachineName": "HP",
        "DomainName": "HP",
        "CallingMethodName": "Audit.UnitTest.AuditTests.TestUpdate()",
        "Exception": null,
        "Culture": "en-GB"
    },
    "StartDate": "2016-08-23T11:33:14.653191-05:00",
    "EndDate": "2016-08-23T11:33:23.1820786-05:00",
    "Duration": 8529,
    "Target": {
        "Type": "Order",
        "Old": {
            "OrderId": "39dc0d86-d5fc-4d2e-b918-fb1a97710c99",
            "Status": 2,
            "OrderItems": [{
                "Quantity": 3.0
            }]
        },
        "New": {
            "OrderId": "39dc0d86-d5fc-4d2e-b918-fb1a97710c99",
            "Status": 3,
             "OrderItems": [{
                "Quantity": 2.0
            }]
        }
    }
}
```

**Comment by thepirat000** [comment]
I think a straightforward way to do it, is to attach a [custom action](https://github.com/thepirat000/Audit.NET#custom-actions) before saving, in order to override the AuditEvent's Target Old and New with new objects containing only the properties with different values.

So one way is to use reflection to enumerate and compare property by property, which could be complex to implement, specially for non-primitives types (arrays, nested classes). 

Another way is to use a library that depends on JSON.NET to get the differences.

Found one that I guess fits your needs: https://github.com/aminm-net/JsonDiffer.Netstandard

For example, you could setup like this:

```c#
Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var jtokenNew = JToken.FromObject(scope.Event.Target.New);
    var jtokenOld = JToken.FromObject(scope.Event.Target.Old);

    var diffsNew = JsonDiffer.JsonDifferentiator.Differentiate(jtokenNew, jtokenOld);
    var diffsOld = JsonDiffer.JsonDifferentiator.Differentiate(jtokenOld, jtokenNew);
                
    scope.Event.Target.Old = diffsOld;
    scope.Event.Target.New = diffsNew;
});
```

This is an example of use:

```c#
var target = new Order()
{
    OrderId = "1",
    Status = 2,
    OrderItems = new OrderItem[]
    {
        new OrderItem() { Sku = "100", Quantity = 1.5M, field1 = "name1" },
        new OrderItem() { Sku = "200", Quantity = 3M, field1 = "name2" }
    }
};
using (var scope = AuditScope.Create("test", () => target))
{
    target.Status = 3;
    target.OrderItems[0].Quantity++;
    target.OrderItems[1].field1 = "updated2";
}
```

And the output will look like this:
![image](https://user-images.githubusercontent.com/9836380/123461581-ddf85f80-d5ae-11eb-8e16-80a578a4b84b.png)

**Comment by anandtpatel** [comment]
Thanks @thepirat000

**Comment by rukshandangalla** [comment]
@thepirat000 I have came across the same requirement and followed what you have suggested.
But it's not creating the object in New & Old fields. When I debug I can see jtoken properly assigned to scope.Event.Target.New & scope.Event.Target.Old. But it's not saving to DB.
