### ISSUE TITLE
Filter Requests based on Response Status Code Audit.Net

### ISSUE THREAD

**Issue by ahmed0304** [thepirat000/Audit.NET#418]
I want to filter requests based on ResponseCode i.e requests with 500, 400, 401 etc response status codes should not be logged with Audit.Net.
I have used AuditMiddleware but it is not filtering 500, 400 and 401 requests responses.

Code:

     app.UseAuditMiddleware(_ => _
                    .FilterByRequest(r => !r.Path.Value.EndsWith("favicon.ico") && r.HttpContext.Response.StatusCode==StatusCodes.Status200OK)
                    .IncludeHeaders()
                    .IncludeRequestBody()
                    .IncludeResponseBody()
                    .WithEventType("HTTP:{verb}:{url}"));

Then i called it in ConfigureApp method in StartUp.cs but it does not filter.

**Comment by thepirat000** [comment]
The "FilterByRequest" config is a pre-filter that is called _before_ the action executes, so you don't have the response yet.

The option to discard events based on the response is to do a post-filter via a custom action, for example on your startup:

```c#
using Audit.WebApi;

Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var ev = scope.GetWebApiAuditAction();
    if (ev?.ResponseStatusCode == 500 || ev?.ResponseStatusCode == 400)
    {
        scope.Discard();
    }
});
```
