### ISSUE TITLE
Audit.EntityFramework.Core 16.2.1 not tracking Foreign Object changes

### ISSUE THREAD

**Issue by ahmed0304** [thepirat000/Audit.NET#422]
In `POST request` we sent a payload with its Foreign object data and audit GetEntityFrameworkEvent() show correct values.
But when we make a PUT request then `Audit.EntityFramework.Core 16.2.1` does not track Foreign Object changes i.e `Changes Array Field` has same values in every `New` and `Old` fields.

**Comment by thepirat000** [comment]
I guess that's because of the nature of the update operation. If you don't explicitly retrieve the object before the update, there is no way for EF to know the previous values.

Please check #53 and #167
