### ISSUE TITLE
Can't add custom field when manually overriding SaveChanges (non inheriting)

### ISSUE THREAD

**Issue by elylv** [thepirat000/Audit.NET#423]
I am experiencing the same issue as #254 

I can't inherit from AuditIdentityDbContext, so I have overridden the SaveChanges as instructed, with a context/helper created in the constructor.  I want to add a custom field, but of course the AddAuditCustomField procedure does not exist.  I have tried to replicate it with:

```
        public void AddAuditCustomField(string key, object value)
        {
            auditContext.ExtraFields[key] = value;
        }
```
but this fails because the ExtraFields property on the IAuditDbContext only has a GET and not a SET, so any attempt to write to it raises an exception.  The ExtraFields property appears as null at runtime, so I can neither add an item to it, or initialize it, since there is no setter.

I have a "save" function that takes the current HttpContext as a parameter, looks up the user ID for the authenticated user, and sets that as a custom field for auditing.  This works great if I inherit AuditIdentityDbContext, but I can no longer do that and need to replicate the functionality manually.

**Comment by thepirat000** [comment]
Note that here:

```c#
auditContext.ExtraFields[key] = value;
```

You are only accessing the Getter of `ExtraFields`, you're not assigning the `ExtraFields`, so that should be fine.

Complete example:

```c#
public class MyContext : DbContext
{
    private static DbContextHelper _helper = new DbContextHelper();
    private readonly IAuditDbContext _auditContext;

    public MyContext(DbContextOptions<MyContext> options) : base(options)
    {
        _auditContext = new DefaultAuditContext(this);
        _helper.SetConfig(_auditContext);
    }

    public override int SaveChanges()
    {
        return _helper.SaveChanges(_auditContext, () => base.SaveChanges());
    }

    public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = default(CancellationToken))
    {
        return await _helper.SaveChangesAsync(_auditContext, () => base.SaveChangesAsync(cancellationToken));
    }

    public void AddAuditCustomField(string key, object value)
    {
        _auditContext.ExtraFields[key] = value;
    }
}
```

What error do you get?

**Comment by elylv** [comment]
Yep, this was the secret sauce!
