### ISSUE TITLE
Sometimes incorrect user is logged

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#425]
**Describe the bug**
In a production environment with multiple users, sometimes the incorrect user is logged as having performed the audited action. The other information like the `AuditDate` and `AuditAction` are correct, but the incorrect user is saved.

For example:

1. User 1 is performing actions that are logged. They are logged as being performed by user 1.

2. User 2 performs the same (or possibly different) action that is logged. It is logged as being performed by user 2.

3. User 1 performs the same action from step 1 (or possibly a different action) that is logged. It is logged as being performed by _**user 2**_.

4. Another user may perform an audited action, then actions performed by user 1 will be saved as that user.

Here is the audit configuration.

```c#
.AuditEntityAction<AuditBase>((evt, entry, auditEntity) =>
{
    var user = userService.GetCurrentUser();
    auditEntity.AuditDate = DateTime.Now;
    auditEntity.UserId = user.Id;
    auditEntity.AuditAction = entry.Action;
})
```

`GetCurrentUser()` returns a `User` object based on the username of the currently logged in user.

**To Reproduce**
It is hard to reproduce in a development environment. I will try to figure out a way to do so in the test environment.

**Expected behavior**
Actions should be logged as being performed by the actual user.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 17.0.7

**Target .NET framework:**
 - ASP.NET Core 5.0.6

**Comment by mrlife** [comment]
A specific question that may help find a solution: does each user have a copy of the audit configuration or does the most recent person to use the app create a new audit configuration that replaces the previously created one?

**Comment by thepirat000** [comment]
The audit configuration is static, so it should be called only once, when the application starts.

I cannot tell about the user since it depends on your implementation of `userService.GetCurrentUser();`

**Comment by mrlife** [comment]
Yes, this is definitely it. Thank you for reminding me and clarifying again that it is static and once per application. I'm only calling it once but something in the `userService.GetCurrentUser()` was reflecting the last person to make an audited save.

**Comment by mrlife** [comment]
@thepirat000 I guess it is not as simple... I'm using `ClaimsPriniciapal`, but I think since this method is static, it's not able to get the actual, current user's `ClaimsPrincipal` but instead is getting whichever is the most recently loaded into the server's memory.

I noticed in the examples, that the `AuditEvent.Environment.UserName` is used as the value for the user that made the change. Since this method is static, where is this assigned to so that it gets the actual user?

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeExplicitMapper(m => m
            .Map<Order, OrderAudit>()
            .Map<Orderline, OrderlineAudit>()
            .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
            {
                auditEntity.AuditDate = DateTime.UtcNow;
                auditEntity.UserName = evt.Environment.UserName;
                auditEntity.AuditAction = entry.Action; // Insert, Update, Delete
            })
        )
    );
```

**Comment by mrlife** [comment]
I found this very helpful in ensuring the user name to be logged is statically assigned: https://github.com/thepirat000/Audit.NET/issues/299#issuecomment-636412816

**Comment by mrlife** [comment]
@thepirat000 It looks like for Blazor, using `IHttpContextAccessor` is [not recommended](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0#blazor-and-shared-state). As such, the value of `scope.Event.Environment.CustomFields["UserId"]` is sometimes `null`.

I can't think of another way to inject the current user into code that should only run once. Do you have any suggestion?

The `UserId` is stored in a `Claim`, but I can adapt if there's a way to make this work.

Here is the relevant code:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpContextAccessor();
    ...
}

public void Configure(IApplicationBuilder app, IHttpContextAccessor contextAccessor)
{
    Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
    {
        // right side of this statement must change for Blazor
        scope.Event.Environment.CustomFields["UserId"] = contextAccessor.HttpContext.User.FindFirstValue("UserId");
    });
    ...
}
```
