### ISSUE TITLE
Audit.Net log SOAP client webservice calls

### ISSUE THREAD

**Issue by thepirat000** [thepirat000/Audit.NET#427]
How do I use Audit.Net to log all the request/response made by my app, the SOAP client? Similar to Audit.HttpClient extension

From https://stackoverflow.com/questions/68407920/audit-net-log-soap-client-webservice-calls

This is to provide a new extension to audit SOAP calls on the client

**Comment by thepirat000** [comment]
A new extension [`Audit.WCF.Client`](https://www.nuget.org/packages/Audit.WCF.Client/) is provided for auditing client-side of WCF calls.  

Please check the docs [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WCF.Client/README.md)

**Comment by hanchoong** [comment]
Thanks! Tested it with FileProvider. Will test on SQL Server provider.
Noticed that the Action is empty, probably because the request Action does not contain a value.
Might need to use the calling method instead?
[hcchoi_637633704158729974.json.txt](https://github.com/thepirat000/Audit.NET/files/6911402/hcchoi_637633704158729974.json.txt)

**Comment by thepirat000** [comment]
Not sure what could be the problem with the empty action. I was unable to reproduce.

Can you share a minimal project that reproduces the issue?

**Comment by hanchoong** [comment]
Am unable to share the project as the service is not publicly available.
But it seems that in SOAP 1.2 the soapaction is not required.
And looking at the wsdl, it is empty. 

![image](https://user-images.githubusercontent.com/18526148/127793701-acc4f6a0-6bc2-4465-80f9-071b597a009f.png)
The operation to call is derived  from the request body  root element.

**Comment by thepirat000** [comment]
Oh I see...

So if you need a separate field, I guess you can add a custom action, parse the XML:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    var wcfEvent = scope.GetWcfClientAction();
    var doc = new XmlDocument();
    doc.LoadXml(wcfEvent.RequestBody);
    wcfEvent.Action = doc["wsdl:Envelope"].FirstChild["wsdl:operation"].GetAttribute("name");
});

```

**Comment by hanchoong** [comment]
Might not be able to use the wsdl as it is seperate definition file not in the request.
For now, I defined the eventtype per method.
`client.Endpoint.EndpointBehaviors.Add(new AuditEndpointBehavior() {
EventType = "SCCB2Report:CompanySearch",
IncludeResponseHeaders = true
});`
Btw, how do I specify a different log provider just for this audit eventtype i.e. global audit is saved to Event table but for this wcf client, the event is saved to Event_wcf table? Audit.Httpclient has a AuditDataProvider option.

**Comment by thepirat000** [comment]
You mean using Audit.HttpClient and Audit.Wcf.Client and each of them store in a different table both using Audit.NET.SqlServer? Otherwise specify the libraries being used

**Comment by hanchoong** [comment]
Yes, the app call various external webapi and audit using Audit.HttpClient or Audit.Wcf.Client. Would like to store these in different table from the app's own methods audits.

**Comment by thepirat000** [comment]
Yes you can do that since you can set the TableName as a function of the AuditEvent.
For example:

```c#
Audit.Core.Configuration.Setup()
    .UseSqlServer(config => config
        .ConnectionString("...")
        .TableName(auditEvent => auditEvent is Audit.Http.AuditEventHttpClient ? "Event" : "Event_wcf"));
```
or: 
```c#
Audit.Core.Configuration.Setup()
    .UseSqlServer(config => config
        .ConnectionString("...")
        .TableName(auditEvent => auditEvent is Audit.Wcf.Client.AuditEventWcfClient ? "Event_wcf" : "Event"));
```

**Comment by hanchoong** [comment]
I see. Thanks.
