### ISSUE TITLE
Audit.WebApi: audit \Token call

### ISSUE THREAD

**Issue by JamesItSolutionsLtd** [thepirat000/Audit.NET#43]
We have plugged in the Audit.WebApi via a global filter. but the authentication call to \Token is not being recorded.

I assume this is because it is not a ApiController call.

any idea how i could get this to work

**Comment by thepirat000** [comment]
Are you doing something like [this](http://www.dotnetcurry.com/aspnet/1223/secure-aspnet-web-api-using-tokens-owin-angularjs)?

If the /Token call is to a method on an ApiController, you shouldn't have problems. Can you try with a specific filter on the account/authentication controller?

like:

```c#
[AuditApi(EventTypeName = "{controller}/{action} ({verb})")]
public class AccountController : ApiController

```

**Comment by fickojuventino** [comment]
Hi Federico, I have the same problem. 
I am using the IdentityServer4 and calls to connect/token route are not recorded.
Can you help me to solve this problem?

**Comment by thepirat000** [comment]
Please add a minimal sample code that reproduces the issue
