### ISSUE TITLE
Owned entities issue on Entity Framework Data Provider

### ISSUE THREAD

**Issue by thepirat000** [thepirat000/Audit.NET#430]
When calling SaveChanges() on a DbContext with changes on an entity that **owns** another entity, if using the Entity Framework Data Provider with a Type -> Type mapping, an exception is thrown:

SYSTEM.REFLECTION.TARGETEXCEPTION: Object does not match 

Code to reproduce: https://github.com/Roger0x1/Web

**Comment by thepirat000** [comment]
Fixed OwnedEntities issue when using the EF data provider.

Upgrade to latest version and re-test

**Comment by Roger0x1** [comment]
Issue resolved. Thanks!!!
