### ISSUE TITLE
Ignore entities (tables) 

### ISSUE THREAD

**Issue by horseznguyen** [thepirat000/Audit.NET#431]
Hi,

I have configured as shown below:

![image](https://user-images.githubusercontent.com/28267489/127661191-5ce07ce9-23ba-486f-9bcb-3ad08820cbd4.png)

![image](https://user-images.githubusercontent.com/28267489/127661232-ea513567-6893-463a-8aab-22463e71d990.png)

![image](https://user-images.githubusercontent.com/28267489/127661271-3557f0e0-83f1-4d4f-86c0-5e32c5c3156b.png)

I don't want to track of UserDeviceDetail table but it still tracks then I work on it

![image](https://user-images.githubusercontent.com/28267489/127662360-12f8f1ac-5d91-418c-8464-ea963f162585.png)

**Comment by thepirat000** [comment]
Can you try with `IgnoreAny()` instead of `Ignore<T>()`, just to check if you are getting a different Type:

```c#
	.UseOptOut()
        .IgnoreAny(t => 
        { 
          System.Diagnostics.Debugger.Break(); // breakpoint here and inspect t.Name
          return t.Name.Contains("UserDevice"); 
        });
```

**Comment by horseznguyen** [comment]
Hi @thepirat000 

The debugger but don't jump into it when i run app.

![image](https://user-images.githubusercontent.com/28267489/127684506-be583c13-ff1f-4aa4-9c07-4d7a6ae7cb16.png)

But before publish the audit event to the channel, i can getting it, so i think the fluent API configuration not working.

![image](https://user-images.githubusercontent.com/28267489/127685237-866d2ac4-3c7c-4403-be1e-5b62da33cc21.png)

**Comment by thepirat000** [comment]
I think the problem is the inheritance on your dbcontext, can you try with `ForAnyContext()` instead of `ForContext<T>()` ?

**Comment by horseznguyen** [comment]
Hi @thepirat000 ,

Thanks you for support, You're right, the problem is the inheritance on my dbcontext.
I have a question, how to configure specific dbcontext when my project has many dbcontext?

**Comment by thepirat000** [comment]
You can call `ForContext<T>` multiple times, one for each DbContext, but it should be the class that have the `DefaultDbContext`, for example:

```c#
Audit.EntityFramework.Configuration.Setup()
    .ForContext<AuditEfCoreDbContext>()
    ...

Audit.EntityFramework.Configuration.Setup()
    .ForContext<AnotherContext>()
    ...
```

Check [this issue](https://github.com/thepirat000/Audit.NET/issues/207)
