### ISSUE TITLE
Ignore sensitive information

### ISSUE THREAD

**Issue by santuchitloor** [thepirat000/Audit.NET#433]
I'm using the SQL server configuration to setup the audit globally in .Net Core 3.1.

I need to filter out the sensitive information from both request and response before saving the sata to DB.

Which is the best place to filter out both request and response when using the SQL server configuration.

**Audit.Web.Api 15.0.2**

**Comment by santuchitloor** [comment]
I also tried to use the JsonIgnore attribute, but the service in which I'm am consuming the nuget is an intermediate layer so my request will ignore the fields and pass the request to next layer.

**Comment by thepirat000** [comment]
if you can't use JsonIgnore or the provided [AuditIgnore](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#audit-ignore-attribute), then I think the only option is to do it in a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) and have the logic to remvoe the sensitive information prior to saving, for example:
 
```c#
Audit.Core.Configuration.AddOnSavingAction(scope => 
{
	var apiAction = scope.GetWebApiAuditAction();
        if (someCondition) 
        {
	    apiAction.RequestBody.Value = null;
  	    apiAction.ResponseBody.Value = null;
        }
});
```
