### ISSUE TITLE
Audit.Net customfields placement bahaves differently between manual scope creation and action based scope creation

### ISSUE THREAD

**Issue by kanreddyjp** [thepirat000/Audit.NET#434]
When using Audit.Net in WebApi a scope is created on every controller action event and when we add custom fields they appear at root level in the json. But when we create audit scope manually and if you add any custom fields to audit scope then they are nested under 'customfields' tag. Not sure why this behaviour is different for both the scope type creation.

See the example below: This is generated by auditscope created when an action on controller is called: AuditInfo is added through auditScope.SetCustomField("AuditInfo",auditInfo);
``
{
    "EventType": "TestEvent",
    "Environment": {
        "DomainName": "IIS APPPOOL",
    },
    "Action": {
        "ActionParameters": {
            }
        },
        "RequestBody": {
            "Type": "application/json",
            "Length": 3191
        },
        "Headers": {
        },
        "ResponseHeaders": {
        }
    },
    "AuditInfo": {
        "UserIdentifier": "",
        "ClaimType": "iss",
        "AuditType": 0
    },
    "id": "",
    "_ts": 1627916814
}
``
Below json is produced when I created AuditScope manually using AuditScope.CreateAsync method:
``
  "EventType": "TestEvent",
  "CustomFields": {
        "AuditInfo": {
            "UserIdentifier": "",
            "ClaimType": "",
            "AuditType": 0
        }
    }
``
if you observe, AuditInfo is placed under 'CustomFields' tag. Can anyone explain me why it is placing under 'CustomFields' when audit scope is created manually?

**Expected behavior**
AuditInfo tag should be at the root level similar to auditscope created when controller action is executed

**Libraries (specify the Audit.NET extensions being used including version):**
Audit.Net v18
AzureCosmos extension
Audit.WebApi extension

**Application Codebase:**
.Net 5

**Comment by kanreddyjp** [comment]
Ref: https://stackoverflow.com/questions/68685056/audit-net-customfields-placement-bahaves-differently-between-manual-scope-creati

**Comment by thepirat000** [comment]
This was fixed on version 18.1.2, please upgrade your references and re-test.

Now when targeting .NET Standard 2.0 or .NET 5.0, the new client library Microsoft.Azure.Cosmos is used, and a custom serializer is set so the serializarion is hanlded by the default Audit.Core.Configuration.JsonAdapter

**Comment by kanreddyjp** [comment]
@thepirat000 it is working as expected now. Custom field is being stored at root level. Thanks for the quick response.
Now we need to find a way to make it respect JsonIgnore which is part of NewtonSoft as it is widely used in our application or migrate to System.Text.Json.
