### ISSUE TITLE
Multi-Tenant Support

### ISSUE THREAD

**Issue by doctordldh** [thepirat000/Audit.NET#439]
Good Day,

I am trying to achieve a multi-tenant environment(each tenant will have his own DB), where the client will pass in x-header and then .netcore dbcontext will rebuild the connection string accordingly.

i Try this in Audit.Core.Configure.Setup(); I am receiving weird behavior that the data will sometime store to the wrong database.
can you is the way i configured the application wrong?

sample code snipper below inside my AuditMiddleware.

                    var optionsBuilder = new Microsoft.EntityFrameworkCore.DbContextOptionsBuilder<DLDHLogContext>();

                    if (httpContext.Request.Headers["X-Header"].ToString() == "site1")
                    {
                        optionsBuilder.UseNpgsql("Host=localhost;Database=vega;Username=postgres;Password=sa");
                    }
                    else if (httpContext.Request.Headers["X-Header"].ToString() == "site2")
                    {
                        optionsBuilder.UseNpgsql("Host=localhost;Database=vega2;Username=postgres;Password=sa");
                    }

                    Audit.Core.Configuration.Setup()
                        .UseEntityFramework(ef => ef
                           .UseDbContext<DLDHLogContext>(optionsBuilder.Options)
                           .AuditTypeExplicitMapper(m => m
                              
                              .Map<GXMExecution, Audit_GXMExecution>()
                              .AuditEntityAction((evt, entry, auditEntity) =>
                               {
                                   ((dynamic)auditEntity).AuditDate = DateTime.UtcNow; 
                                   ((dynamic)auditEntity).UserID = evt.Environment.CustomFields["IdentityUserName"].ToString();
                                   ((dynamic)auditEntity).Tenant = evt.Environment.CustomFields["Tenant"].ToString();
                                   ((dynamic)auditEntity).AuditAction = entry.Action;
                               })
                           )
                        );

**Comment by thepirat000** [comment]
The problem is with calling `Audit.Core.Configuration.Setup().UseEntityFramework()` multiple times. You can't have multiple data providers. i.e. the call to `UseEntityFramework()` should be done only once, at your application's startup. 

So I guess an easier way to setup should be depending on something on the audit event to return the DbContext to use. You can do that with the non-generic overload of `UseDbContext()`

For example, on your application's startup:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(config => config
        .UseDbContext(ev => GetDbContext(ev))
        .AuditTypeExplicitMapper(...));

//...

static DbContext GetDbContext(AuditEventEntityFramework ev)
{
    var optionsBuilder = new DbContextOptionsBuilder<DLDHLogContext>();
    var tenant = ev.Environment.CustomFields["Tenant"].ToString();
    if (tenant == "x1")
    {
        optionsBuilder.UseNpgsql("Host=localhost;Database=vega;Username=postgres;Password=sa");
    }
    else 
    {
        optionsBuilder.UseNpgsql("Host=localhost;Database=vega2;Username=postgres;Password=sa");
    }
    return new DLDHLogContext(optionsBuilder.Options);
}
```

**Comment by doctordldh** [comment]
thank you, the solution work perfectly!
appreciate your help.
