### ISSUE TITLE
SQL Server Provider - Trigger on Event table

### ISSUE THREAD

**Issue by Thibaultce** [thepirat000/Audit.NET#44]
I tried to create a trigger on the Event table. Whenever I wanted to add an event log in the database (with the Audit.NET.SqlServer provider) I have an issue due to the way the log is inserted in the database.
I searched in the code of the provider (SqlDataProvider.cs) and found out that it use this query to insert a line in the table : 
`INSERT INTO {0} ([{1}]) OUTPUT CONVERT(NVARCHAR(MAX), INSERTED.[{2}]) AS [Id] VALUES (@json)`
But the trigger will always fail if the statement contains an OUTPUT.

Here is the exception : 
> An exception of type 'System.Data.SqlClient.SqlException' occurred in EntityFramework.SqlServer.dll but was not handled in user code
Additional information: The target table 'dbo.Event' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

I did work around this issue by replacing the INSERT statement by `INSERT INTO {0} ([{1}]) VALUES (@json)` in the SqlDataProvider.cs (I downloaded the source of the project) file and it works just fine for me.

**Comment by thepirat000** [comment]
In this case you will need to implement your own DataProvider that does the insert in a different way.
You should only be aware of returning the inserted row's primary key.

For example: 

```c#
public class CustomSqlDataProvider : AuditDataProvider
{
	public override object InsertEvent(AuditEvent auditEvent)
	{
		// Insert into SQL table
		// Return the inserted primary key
	}
	
	public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
	{
		// Update the SQL table given the id and the event
		// This override is only needed when you use Creation Policies "Manual" or "InsertOnStartReplaceOnEnd".
	}
}
```

**Comment by Thibaultce** [comment]
At the moment, the Creation Policy is always "InsertOnEnd" (it's the default, right ?) so I don't really need to return the primary key.
But good to know that the ID is required if I use another Creation Policy.
