### ISSUE TITLE
Tracking Raw Sql Queries in Audit.EntityFramework.Core

### ISSUE THREAD

**Issue by elfico** [thepirat000/Audit.NET#449]
Hello,

I just implemented Audit.NET and I am using the Audit.EntityFramework.Core library to track entity changes.

I noticed that any calls to `SaveChangesAsync` is tracked just as stated. The issue is any query executed using `DbContext.Database.ExecuteSqlRawAsync()` is not tracked.

Is there a way to track these kind of changes?

Thanks.

**Comment by thepirat000** [comment]
I don't think so, since Database commands like ExecuteSqlRaw do not affect the change tracker, and AFAIK there are no events or callbacks triggered when calling those methods.

**Comment by elfico** [comment]
> 
> 
> I don't think so, since Database commands like ExecuteSqlRaw do not affect the change tracker, and AFAIK there are no events or callbacks triggered when calling those methods.

Thanks for the quick response. Is there a way to audit this change manually?
We have a few places where use raw sql queries and it would be beneficial to track the changes.

Thanks.

**Comment by thepirat000** [comment]
Where are you storing the audits? Which data provider are you using?

**Comment by elfico** [comment]
> 
> 
> Where are you storing the audits? Which data provider are you using?

I am tracking changes for EFCore SQL Server. The audits are stored in CosmosDb.

**Comment by thepirat000** [comment]
Which version of EF core do you target?

**Comment by elfico** [comment]
EF Core 5
Audit.EntityFramework.Core: 18

**Comment by thepirat000** [comment]
For EF Core 5, I think one option is to use a `DbCommandInterceptor` that intercepts the `ExecuteSqlRaw` calls, but I'm afraid it will also intercept any other commands issued by EF internally.

Check this: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/

For example:
```c#
public class AuditCommandInterceptor : DbCommandInterceptor
{
    public override int NonQueryExecuted(DbCommand command, CommandExecutedEventData eventData, int result)
    {
        var parameters = new Dictionary<string, object>();
        foreach (DbParameter p in command.Parameters)
            parameters.Add(p.ParameterName, p.Value);
        using var scope = AuditScope.Create(new AuditScopeOptions()
        {
            EventType = "NonQueryExecuted:Success",
            IsCreateAndSave = true,
            ExtraFields = new
            {
                Command = new 
                {
                    Duration = (int)eventData.Duration.TotalMilliseconds,
                    Text = command.CommandText,
                    Params = parameters,
                },
                ConnectionId = eventData.ConnectionId,
                Result = result
            }
        });
        return base.NonQueryExecuted(command, eventData, result);
    }

    public override void CommandFailed(DbCommand command, CommandErrorEventData eventData)
    {
        var parameters = new Dictionary<string, object>();
        foreach (DbParameter p in command.Parameters)
            parameters.Add(p.ParameterName, p.Value);
        using var scope = AuditScope.Create(new AuditScopeOptions()
        {
            EventType = "NonQueryExecuted:Failure",
            IsCreateAndSave = true,
            ExtraFields = new
            {
                Command = new
                {
                    Duration = (int)eventData.Duration.TotalMilliseconds,
                    Text = command.CommandText,
                    Params = parameters,
                },
                ConnectionId = eventData.ConnectionId,
                Error = eventData.Exception.ToString()
            }
        });
        base.CommandFailed(command, eventData);
    }
}
```

Note you should also implement the Async version of the methods: `NonQueryExecutedAsync` and `CommandFailedAsync`.

**Comment by thepirat000** [comment]
I will evaluate the possibility of adding an optional intercept mechanism to the Audit.EF library to log these low-level commands. It was suggested some years ago on #100 but not viable at that time.

**Comment by elfico** [comment]
> 
> 
> For EF Core 5, I think one option is to use a `DbCommandInterceptor` that intercepts the `ExecuteSqlRaw` calls, but I'm afraid it will also intercept any other commands issued by EF internally.
> 
> Check this: https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/
> 
> For example:
> 
> ```cs
> public class AuditCommandInterceptor : DbCommandInterceptor
> {
>     public override int NonQueryExecuted(DbCommand command, CommandExecutedEventData eventData, int result)
>     {
>         var parameters = new Dictionary<string, object>();
>         foreach (DbParameter p in command.Parameters)
>             parameters.Add(p.ParameterName, p.Value);
>         using var scope = AuditScope.Create(new AuditScopeOptions()
>         {
>             EventType = "NonQueryExecuted:Success",
>             IsCreateAndSave = true,
>             ExtraFields = new
>             {
>                 Command = new 
>                 {
>                     Duration = (int)eventData.Duration.TotalMilliseconds,
>                     Text = command.CommandText,
>                     Params = parameters,
>                 },
>                 ConnectionId = eventData.ConnectionId,
>                 Result = result
>             }
>         });
>         return base.NonQueryExecuted(command, eventData, result);
>     }
> 
>     public override void CommandFailed(DbCommand command, CommandErrorEventData eventData)
>     {
>         var parameters = new Dictionary<string, object>();
>         foreach (DbParameter p in command.Parameters)
>             parameters.Add(p.ParameterName, p.Value);
>         using var scope = AuditScope.Create(new AuditScopeOptions()
>         {
>             EventType = "NonQueryExecuted:Failure",
>             IsCreateAndSave = true,
>             ExtraFields = new
>             {
>                 Command = new
>                 {
>                     Duration = (int)eventData.Duration.TotalMilliseconds,
>                     Text = command.CommandText,
>                     Params = parameters,
>                 },
>                 ConnectionId = eventData.ConnectionId,
>                 Error = eventData.Exception.ToString()
>             }
>         });
>         base.CommandFailed(command, eventData);
>     }
> }
> ```
> 
> Note you should also implement the Async version of the methods: `NonQueryExecutedAsync` and `CommandFailedAsync`.
> 
> Then you can add the interceptor when creating your DbContext, for example:
> 
> ```cs
> using (var ctx = new MyContext(new DbContextOptionsBuilder<MyContext>()
>     .UseSqlServer("...")
>     .AddInterceptors(new AuditCommandInterceptor())
>     .Options))
> {
>     var result = ctx.Database.ExecuteSqlRaw("INSERT INTO ITEMS (Name) VALUES ({0})", "test");
>     //...
> }
> ```

Running this throws the error.
```
System.InvalidOperationException: 'InterceptionResult.Result' was called when 'InterceptionResult.HasResult' is false.
   at Microsoft.EntityFrameworkCore.Diagnostics.InterceptionResult`1.get_Result()
   at WellaHealthCoreData.Interceptors.AuditCommandInterceptor.NonQueryExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult`1 result, CancellationToken cancellationToken) 
```

To fix,
I changed the line: `Result = result.Result` to `Result = result.HasResult ? result.Result : 0`

Thanks for the help. I don't know how common a problem this is, do you think maybe it will help to add it to the documentation?

**Comment by thepirat000** [comment]
A new command interceptor was provided that logs raw SQL queries, for EF Core 3.0 and EF Core 5.0 starting on version 18.1.5

More information on the readme [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#low-level-command-interception)
