### ISSUE TITLE
Unable to audit insert and delete events

### ISSUE THREAD

**Issue by RajanModha** [thepirat000/Audit.NET#454]
**Describe the bug**
Unable to audit insert and delete events in my project. Update logs are working fine

**To Reproduce**
I'm using Audit.EntityFramework.Identity.Core and configured it in my project using Inheriting from AuditIdentityDbContext. Also I have configured mySql as my data provider using fluent api. Update event logs are working fine I'm just unable to log insert and delete events

**Expected behavior**
I want to log all the events insert, update and delete 

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework.Identity.Core: 16.2.1

**Target .NET framework:**
For example:
 - .NET Core 3.1

**Comment by thepirat000** [comment]
Can you upgrade to the latest version of Audit.* libraries an re-test?

**Comment by RajanModha** [comment]
I have updated it and it's working thanks
