### ISSUE TITLE
Response body memory stream disposed

### ISSUE THREAD

**Issue by valera1181** [thepirat000/Audit.NET#459]
https://github.com/thepirat000/Audit.NET/blob/7f0df5359224a3ce87e7719b36848e35a91ff636/src/Audit.WebApi/AuditMiddleware.cs#L54

When exception is thrown somewhere in controller InvokeNextAsync catches and rethrows exception. After that responseBody variable is disposed also as a context.Response.Body. This creates problems in middlewares declared before AuditMiddleware so that I can't write to response body anymore.

**Comment by valera1181** [comment]
`            // Admin website exception and error handling
            app.UseWhen(context => !context.IsWebApi(), adminApp =>
            {
                adminApp.UseExceptionHandler("/error/500");
                adminApp.UseStatusCodePagesWithRedirects("/error/{0}");
            });

            // Web api exception and error handling
            app.UseWhen(context => context.IsWebApi(), apiApp =>
            {
                apiApp.UseMiddleware<ApiErrorHandlerMiddleware>();
            });

            app.UseAuditMiddleware(config =>
            {
                config.FilterByRequest(r => r.IsAuditable());
                config.WithEventType("{verb}:{url}");
                config.IncludeHeaders();
                config.IncludeResponseHeaders();
                config.IncludeRequestBody(/*c => c.IncludeRequestBody()*/);
                config.IncludeResponseBody();
            });`

**Comment by valera1181** [comment]
`   // Admin website exception and error handling
            app.UseWhen(context => !context.IsWebApi(), adminApp =>
            {
                adminApp.UseExceptionHandler("/error/500");
                adminApp.UseStatusCodePagesWithRedirects("/error/{0}");
            });

            // Web api exception and error handling
            app.UseWhen(context => context.IsWebApi(), apiApp =>
            {
                apiApp.UseMiddleware<ApiErrorHandlerMiddleware>();
            });

            app.UseAuditMiddleware(config =>
            {
                config.FilterByRequest(r => r.IsAuditable());
                config.WithEventType("{verb}:{url}");
                config.IncludeHeaders();
                config.IncludeResponseHeaders();
                config.IncludeRequestBody(/*c => c.IncludeRequestBody()*/);
                config.IncludeResponseBody();
            });`

**Comment by valera1181** [comment]
`            // Admin website exception and error handling
            app.UseWhen(context => !context.IsWebApi(), adminApp =>
            {
                adminApp.UseExceptionHandler("/error/500");
                adminApp.UseStatusCodePagesWithRedirects("/error/{0}");
            });

            // Web api exception and error handling
            app.UseWhen(context => context.IsWebApi(), apiApp =>
            {
                apiApp.UseMiddleware<ApiErrorHandlerMiddleware>();
            });`

**Comment by thepirat000** [comment]
I see where the bug is.

The AuditMiddleware temporarily copies the response body stream to a memory stream, and restores the original stream after invoking the next delagate, but when an exception was thrown invoking the next delegate, then the original body was not being restored.

I will fix that so the stream gets restored in any case

**Comment by thepirat000** [comment]
This was fixed on versions `18.1.6` and `19.0.0-rc.net60.2`, please upgrade your references and re-test.
