### ISSUE TITLE
Environment object on IIS is just the user running the IIS server

### ISSUE THREAD

**Issue by fmeira** [thepirat000/Audit.NET#46]
I'm running Audit.NET on an API deployed in IIS. The environment data for each call that gets audited is always the same and pretty much of no value, as follows:

    "Environment": {
        "UserName": "DotNet Core",
        "MachineName": "HOFFELL",
        "DomainName": "IIS APPPOOL",
        "CallingMethodName": "SomeController.Get()",
        "AssemblyName": "Api, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "Culture": "is-IS"
    },

Is it possible to pass in more useful information, and how to achieve it, related to the user that is calling the api?

**Comment by thepirat000** [comment]
If you are using the `Audit.WebApi` extension, you should see meaningful information on the [output](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.WebApi#output-details).

You can add information by creating a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions) and/or registering your own [DataProvider](https://github.com/thepirat000/Audit.NET#data-providers)
