### ISSUE TITLE
Supports .NET 6.0.0

### ISSUE THREAD

**Issue by KAJOOSH** [thepirat000/Audit.NET#464]
**Describe the bug**
Hi
I upgraded my projects to the official and final version .net 6, but unfortunately  Audit.NET does not support it
I have been waiting for this version for a long time
Please finalize as soon as possible
`
System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.RelationalEntityTypeExtensions.GetTableName(Microsoft.EntityFrameworkCore.Metadata.IEntityType)'.
`
**To Reproduce**

**Expected behavior**

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 18.1.6

**Target .NET framework:**
For example:
 - .NET 6.0.0

**Additional context**

**Comment by thepirat000** [comment]
Support for .NET 6.0 and EF Core 6.0 was added on version 19.0.0, please upgrade your references and re-test
