### ISSUE TITLE
Allow to set CreationPolicy with AuditApi attribute

### ISSUE THREAD

**Issue by pinggi** [thepirat000/Audit.NET#469]
Now, it's not possible to set CreationPolicy by AuditApi attribute. It would be great to allow it.

An example:
```
public class SomeController : ApiController
{
    [AuditApi(EventTypeName = "FooCalled"]
    public async IActionResult FooAction()
    {
       // the audit event is saved on dispose because scope's CreationPolicy is EventCreationPolicy.InsertOnEnd
   }

    [AuditApi(EventTypeName = "BarDone", CreationPolicy=EventCreationPolicy.Manual)] // <-- this isn't possible now
    public async IActionResult BarAction()
    {
       // the audit event is discarded by default
       ...
       if (done) {
         // the audit event is saved
          await this.GetCurrentAuditScope().Save();
       }
    }
}
```

**Comment by thepirat000** [comment]
I'm not sure if allowing manual events will help since your `Save()` call will be done before the audit event has the complete information: it will not be logging the response, for example.

I think a better approach could be to discard the events, with the `Discard()` method, so those events are not saved. For example:

```c#
[AuditApi(EventTypeName = "BarDone"]
public async IActionResult BarAction()
{
   ...
   if (!done) {
      this.GetCurrentAuditScope().Discard();
   }
}
```

**Comment by pinggi** [comment]
The point with the manual creation policy is that I am able to call save when needed. The Save() isn't called when there's a bad result returned or an exception thrown. I am able to set the manual policy but as a default for all actions. I want to be able to do that for just several actions while others have different creation policy. Imagine a custom data provider that doesn't save the data but sends them out on success.

Your example saves the data on an error or an exception, this I want to avoid.
I would have to do something like this:
```
[AuditApi(EventTypeName = "BarDone"]
public async IActionResult BarAction()
{
   this.GetCurrentAuditScope().Discard();
   ...
   if (done) {
      this.GetCurrentAuditScope().Save();
   }
}
```
...but calling Discard() in each action method is not good and actually it's not possible either I suppose - to be able to simulate the manual creation policy.

**Comment by pinggi** [comment]
I tried to inherit from AuditApi to create own attribute with the additional constructor param allowing to change the CreationPolicy to Manual but it's also not possible - CreationPolicy is getter (readonly) :-( The scope itself allows to change the creation policy, but the AuditApi that on background creates the scope doesn't.

**Comment by thepirat000** [comment]
ok, I can add that config. But note the webapi audit event will not have the response information at the moment of saving, with the approach you're suggesting.

That's why I thought it would be better to let the data provider decide which event should be sent/saved.

**Comment by pinggi** [comment]
You are right actually. There won't be the response info but there wouldn't be anyway with the manual policy configured globally by `Configuration.Setup().WithCreationPolicy(EventCreationPolicy.Manual)`.

I will leave it up to you. I think I can implement it like you mentioned that the provider will check the response status and whether there was an exception and based on this will decide about the sending.

Thank you.
