### ISSUE TITLE
With Audit.WebApi.Core, it is not capturing http 401 and 403 errors

### ISSUE THREAD

**Issue by jujinfu** [thepirat000/Audit.NET#470]
**Describe the bug**
When User is getting 401 or 403 on the WebApi request, the audit log is not capturing this 

**To Reproduce**
on the web API, register Authorization Filter and register Audit 

**Expected behavior**
When the user gets 401, the action should be logged 

According to MSFT 
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1

Authorization Filter has the highest order of execution and it will break the pipeline if authorization fails.
We need to find a way to plug the audit handler into the authorization filter 

And suggestion?

**Comment by thepirat000** [comment]
How do you register the audit, can you share the code?

Did you tried with AuditMiddleware ?

**Comment by jujinfu** [comment]
I was using global action filter. 
` services.AddControllers(MvcOptions =>
            {
                MvcOptions.Filters.Add(typeof(AddBuildVersionFilter));
                AuditConfiguration.ConfigureAudit(services, appConfig.DbCosmosEndpoint, appConfig.DbCosmosAccountKey, appConfig.DbCosmosDatabase, "AppAuditLog");
                AuditConfiguration.AddAudit(MvcOptions);
            })`

I will try again with middleware for that

**Comment by jujinfu** [comment]
tried with middleware. It did log more info like the visit of /swagger pages, which I don't want to see
However, it stopped logging MVC options. 

Which also it still doesn't log 401 and 403 errors as auth handler will not 
According to MSFT 
![image](https://user-images.githubusercontent.com/10210323/143305284-6fc23034-a2a9-42d8-96bb-5c14bfcec3a3.png)
![image](https://user-images.githubusercontent.com/10210323/143305313-9d6b1475-82fa-409f-9fc2-027be4479bb6.png)

the last thing I can think of is to manually add an entry in the authorization handler, do you guys have an example of that?

**Comment by thepirat000** [comment]
Please check the [usage section](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#usage) on the readme file.

The global action filter is just an action filter, it will log only those requests that get to the action filters processing step.

For auditing requests that don't reach the action filters, you can use the middleware. Actually, you can configure both, the action filter and the middleware (and that's the recommended approach), so those request that gets into the action, will have MVC specific information (like controller name, action name) and the request that doesn't reach the action, you will have the remaining information

**Comment by jujinfu** [comment]
it wasn't working at the beginning. 
turns out the order of middleware also matters

thanks, it works
