### ISSUE TITLE
Redis Database

### ISSUE THREAD

**Issue by VagyokC4** [thepirat000/Audit.NET#471]
How can I configure which redis database to use when using Audit.NET.Redis?

Also, can you bump your StackExchange.Redis to the latest version, it's very far behind, and I'm getting Ambiguous reference: StackExchange.Redis.ConnectionMultiplexer StackExchange.Redis.ConnectionMultiplexer match

**Comment by thepirat000** [comment]
Support for changing the database ID was added on version 19.0.2, please upgrade your references and re-test

**Comment by VagyokC4** [comment]
> Support for changing the database ID was added on version 19.0.2, please upgrade your references and re-test
> 
> For example:
> 
> ```cs
> Audit.Core.Configuration.Setup()
>     .UseRedis(redis => redis
>         .ConnectionString("...")
>         .AsList(s => s
>             .Key(ev => key)
>             .Database(3)));
> ```

That's looking better.  Thank-you for the quick response.  My next question is how hard would it be to support [KeyDb](https://keydb.dev/) in specific the [ExpireMember](https://docs.keydb.dev/docs/commands/#expiremember) command?

With Redis, (and with your current implementation) if I set a TTL using the Hash store, it expires the whole Key, whereas I would like it to only expire the specific hash member when I set a TTL on the audit log.

Thoughts?

**Comment by thepirat000** [comment]
I think something I can do is to provide a way to attach commands to the batch that is executed on Redis.

Something like this:

```c#
Audit.Core.Configuration.Setup()
    .UseRedis(redis => redis
        .ConnectionString(RedisCnnString)
        .AsHash(h => h
            .Key(ev => key)
            .HashField(ev => ev.EventType)
            .AttachTask((batch, ev) => batch.ExecuteAsync("EXPIREMEMBER", key, ev.EventType, 120))))
```

**Comment by VagyokC4** [comment]
> I think something I can do is to provide a way to attach commands to the batch that is executed on Redis when an audit event is saved, so you can add any command.
> 
> Something like this:
> 
> ```cs
> Audit.Core.Configuration.Setup()
>     .UseRedis(redis => redis
>         .ConnectionString(RedisCnnString)
>         .AsHash(h => h
>             .Key(ev => key)
>             .HashField(ev => ev.EventType)
>             .AttachTask((batch, ev) => batch.ExecuteAsync("EXPIREMEMBER", key, ev.EventType, 120))))
> ```
> 
> Will that work for you?

That would be beautiful.

**Comment by thepirat000** [comment]
The `AttachTask` support was added on version 19.0.3

Please upgrade your references and re-test

**Comment by VagyokC4** [comment]
Looks good!  Thank-you for your quick response!
