### ISSUE TITLE
user cannot be converted to type system.string

### ISSUE THREAD

**Issue by gbdrm** [thepirat000/Audit.NET#472]
Time to time I have a runtime exception about converting to system.string:
![image](https://user-images.githubusercontent.com/4364316/147606168-c49191b1-ac1a-48e1-8dac-a28167394283.png)

where ApplicationUser is the next class:
public class ApplicationUser : IdentityUser<int>
    {
    }

I can not find any particular steps to reproduce, it just occurs time to time.

I use:
Audit.NET 19.0.1
Audit.NET.MySql 19.0.1
Audit.EntityFramework.Core 19.0.1

with .NET 6 

and the next confugiration:
`Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
            {
                scope.SetCustomField("AuditUser", ctxAccessor.HttpContext?.User?.Identity?.Name ?? "guest");
            });

            Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                    .AuditTypeMapper(typeName => typeof(AuditLog))
                    .AuditEntityAction<AuditLog>((ev, ent, auditEntity) =>
                    {
                        auditEntity.User = ev.CustomFields["AuditUser"]?.ToString() ?? "guest";
                        auditEntity.Table = ent.Table;
                        auditEntity.AuditDate = DateTime.UtcNow;
                        auditEntity.Action = ent.Action;
                        auditEntity.Changes = JsonSerializer.Serialize(ent.Changes);
                        auditEntity.Entries = JsonSerializer.Serialize(ev.GetEntityFrameworkEvent().Entries);
                        auditEntity.Success = ev.GetEntityFrameworkEvent().Success;
                        auditEntity.ColumnValues = JsonSerializer.Serialize(ent.ColumnValues);
                        auditEntity.PrimaryKey = JsonSerializer.Serialize(ent.PrimaryKey);
                    }));`

Any ideas how can  I fix this issue?

**Comment by thepirat000** [comment]
I think you're missing the `IgnoreMatchedProperties(true)` configuration

```c#
Audit.Core.Configuration.Setup()
            .UseEntityFramework(x => x
                .AuditTypeMapper(typeName => typeof(AuditLog))
                .AuditEntityAction<AuditLog>((ev, ent, auditEntity) =>
                {
                    auditEntity.User = ev.CustomFields["AuditUser"]?.ToString() ?? "guest";
                    auditEntity.Table = ent.Table;
                    auditEntity.AuditDate = DateTime.UtcNow;
                    auditEntity.Action = ent.Action;
                    auditEntity.Changes = JsonSerializer.Serialize(ent.Changes);
                    auditEntity.Entries = JsonSerializer.Serialize(ev.GetEntityFrameworkEvent().Entries);
                    auditEntity.Success = ev.GetEntityFrameworkEvent().Success;
                    auditEntity.ColumnValues = JsonSerializer.Serialize(ent.ColumnValues);
                    auditEntity.PrimaryKey = JsonSerializer.Serialize(ent.PrimaryKey);
                }).IgnoreMatchedProperties());
```

Otherwise, the framework will try to match the Entity properties to the AuditLog properties automatically

**Comment by gbdrm** [comment]
didn't get any complaints recently, so it seems that this config helped. Thank you.

**Comment by thepirat000** [comment]
I guess one of your entity classes has a property called `User` of type `ApplicationUser`, and the property match was trying to set the ApplicationUser to the AuditLog.User string property
