### ISSUE TITLE
Azure Table Storage package's InsertAsync method does not use the EnsureTableAsync variant

### ISSUE THREAD

**Issue by cristian-eriomenco** [thepirat000/Audit.NET#474]
**Describe the bug**
Azure Table Storage package's (Audit.NET.AzureTableStorage) InsertEventAsync method does not use the EnsureTableAsync variant instead its using the EnsureTable synchronous call. This causing the thread to be blocked. Looks like an omission during development

**To Reproduce**
Please look at the source here: 

https://github.com/thepirat000/Audit.NET/blob/6d056c42e6fa6832117329b3584bb4c6309b19a5/src/Audit.NET.AzureStorage/Providers/AzureTableDataProvider.cs#L73

![image](https://user-images.githubusercontent.com/7792886/150680878-c2ea021d-d191-412d-bd23-9e119175a90d.png)

**Expected behavior**
Async methods must call their async variants if such are available.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET.AzureTableStorage all versions

**Target .NET framework:**
Any

**Additional context**

**Comment by thepirat000** [comment]
Thanks for fixing this issue.

Version 19.0.4 includes the fix, please upgrade your references and re-test
