### ISSUE TITLE
Multiple Data Providers

### ISSUE THREAD

**Issue by mdrewanz** [thepirat000/Audit.NET#48]
Is it possible to have multiple data providers, one to capture all the Web API activities and another to capture the Entity Framework (data layer) activities, on separate tables?

**Comment by thepirat000** [comment]
Yes, it should be a couple of ways of doing it. Can you provide more details?
Are both logging to SQL or where?

**Comment by thepirat000** [comment]
Maybe creating a custom provider like this works for you:

```c#
public class CustomProvider : AuditDataProvider
{
    private SqlDataProvider _provider1 = new SqlDataProvider();
    private SqlDataProvider _provider2 = new SqlDataProvider();

    public CustomProvider(string cnnString, string table1, string table2)
    {
        _provider1.ConnectionString = _provider2.ConnectionString = cnnString;
        _provider1.IdColumnName = _provider2.IdColumnName = "ID";
        _provider1.JsonColumnName = _provider2.JsonColumnName = "Data";
        _provider1.TableName = table1;
        _provider2.TableName = table2;
    }

    public override object InsertEvent(AuditEvent auditEvent)
    {
        if (auditEvent is AuditEventEntityFramework)
        {
            return _provider1.InsertEvent(auditEvent);
        }
        if (auditEvent is AuditEventWebApi)
        {
            return _provider2.InsertEvent(auditEvent);
        }
        return null;
    }
    public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
    {
        if (auditEvent is AuditEventEntityFramework)
        {
            _provider1.ReplaceEvent(eventId, auditEvent);
        }
        else if (auditEvent is AuditEventWebApi)
        {
            _provider2.ReplaceEvent(eventId, auditEvent);
        }
    }
}
```

And in your startup code:

```c#
Audit.Core.Configuration.Setup()
    .UseCustomProvider(new CustomProvider("the connection string", "EF_Table", "WebApi_Table"));
```

**Comment by mdrewanz** [comment]
Perfect! Exactly what I needed to address different recording needs. 

Many thanks. I will follow your sample.

**Comment by RichardTay** [comment]
Hi Dear audit.net master, 
I also have the same need to audit 2 different types of events using 2 providers. 

I will try the above way. 

but I was trying another method:

AuditScope.Create("Order:Update", () => order, EventCreationPolicy.Manual, new MyCustomDataProvider());

I thought this will allow me to audit to a customized provider. but when I did so, this audit record is missing although program did not report any error. 

is  that a issue or my usage is wrong? 


regards
Richard.

**Comment by thepirat000** [comment]
Take into account you are using a Manual policy, so the event will not be saved until you explicitly call the `auditScope.Save()` method.

**Comment by RichardTay** [comment]
hi Dear Daniel : 
I have added scope.Save() method, then I encountered the following error: 
Microsoft.Data.SqlClient.SqlException: 'Cannot insert the value NULL into column 'EventType', table 'ApplicationAudit.dbo.Event'; column does not allow nulls. INSERT fails.'
but when I looked at scope object, the eventtype property is populated correctly. 
May I know is this an issue? 
my code is listed below:
using (var audit = AuditScope.Create("PrinterBinary:Delete", () => bin, EventCreationPolicy.Manual, (new Settings()).AppLogProvider))
            {
                audit.SetCustomField("HttpAction", "HttpDelete");
                _context.PrinterBinaries.Remove(bin);
                _context.SaveChanges();
                audit.Save();
            }

**Comment by thepirat000** [comment]
You should share the code of your AppLogProvider. I guess there is a missing configuration

**Comment by RichardTay** [comment]
Hi Daniel, 
yes, you are right, 
I checked my AppLogProvider and added one line there: 
                logProvider.CustomColumns.Add(new CustomColumn("EventType", ev => ev.EventType));

and now it works. 
thank you very much for helping me. 
Cheers and have a nice day!
Richard.
