### ISSUE TITLE
Calling Audit.Core.Configuration.Setup() in scoped service

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#483]
I think I have a solution to an issue I've been facing -- how to access user id in `AuditEntityAction` in a Blazor application. I remember you saying that `Setup()` should only be called once, when the app starts, but the following seems to be the only solution I can find.

In Blazor, each user has a "circuit" assigned to them that has its own scope where services are created. I'm calling `Audit.Core.Configuration.Setup()` within that circuit scope, so it's specific to each app user. Using this approach, I send in the user id and use that in 

```c#
.AuditEntityAction<AuditBase>((evt, entry, auditEntity) => {});
```

Testing shows that the correct user id is used in the audit logs. Are there any potential issues with this approach?

Here is a full example:

```c#
public class MyService
{
    private string _userId;

    public void Init(string userId)
    {
        _userId = userId;

        Audit.Core.Configuration.Setup()
            .UseEntityFramework(ef => ef
                .UseDbContext<OrderDbContext>()
                .AuditTypeExplicitMapper(m => m
                    .Map<Order, OrderAudit>()
                    .Map<Orderline, OrderlineAudit>()
                    .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
                    {
                        auditEntity.UserId = _userId;
                        auditEntity.AuditDate = DateTime.UtcNow;
                        auditEntity.UserName = evt.Environment.UserName;
                        auditEntity.AuditAction = entry.Action; // Insert, Update, Delete
            })
                )
            );
    }
}
```

Audit.NET version:
```xml
<PackageReference Include="Audit.EntityFramework.Core" Version="19.0.6" />
```

**Comment by thepirat000** [comment]
I don't think that's correct since Audit.NET's configuration is stored statically; just one configuration is allowed for the entire app domain at any given point of time.

You will end up logging the wrong user in case there are two threads processing requests for two different users.

The recommendation is to call Audit.Core.Configuration.Setup() only once for the entire application lifetime.

Not sure about Blazor, but the user ID should be stored on some contextual object.

Have you tried injecting a AuthenticationStateProvider, like the point 2. of [this SO answer](https://stackoverflow.com/a/60264765/122195)

**Comment by mrlife** [comment]
I appreciate the suggestion from SO. The `AuthenticationStateProvider` only works within the Blazor circuit (calls originating from files ending in .razor), which are per user. Unfortunately, there is no contextual object in the case of Blazor that fulfills the purpose needed in this scenario. So, I'm trying to think of another way that could be possible. 

> I don't think that's correct since Audit.NET's configuration is stored statically; just one configuration is allowed for the entire app domain at any given point of time.

I see, so with users saving things at the same time, an incorrect user id could easily be used.

I'm really open to anything that will work. Do you think Blazor compatibility is a scenario that can be supported in Audit.NET?

**Comment by thepirat000** [comment]
I don't think there are incompatibilities, but the issue is how to store/retrieve contextual information per circuit.

Have you seen https://stackoverflow.com/a/70323692/122195?

**Comment by mrlife** [comment]
Thanks, I actually had upvoted that answer. I tried using the circuit handlers, but I didn't see how that allowed allowed a way to pull the user id while inside `Startup.cs` or `AuditEntityAction`. The answer author mentions saving the circuit id and user id in a dictionary. Any idea where I could save that dictionary that would make it available for Audit.NET?

**Comment by thepirat000** [comment]
Please clarify where your userId comes from?

I think saving the cirtcuitId->user relation in a dictionary should not be a problem (you can use a public static concurrent dictionary).  The problem is how to know which circuit has triggered the DbContext.Save operation.

The only solution I can see is storing the circuit id on the HttpContext, even though [is not recommended by MS](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#blazor-and-shared-state-1) since the HttpContext isn't guaranteed to be available.

So I'm not sure if this solution will work in any case or in future versions of blazor apps, but here it is:

1. Create a `CircuitHandler` that stores the circuit ID on the current `HttpContext`

```c#
public class MyCircuitHandler : CircuitHandler
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    public MyCircuitHandler(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }
    public override Task OnCircuitOpenedAsync(Circuit circuit, CancellationToken cancellationToken)
    {
        _httpContextAccessor.HttpContext.Items["CircuitId"] = circuit.Id;
        return base.OnCircuitOpenedAsync(circuit, cancellationToken);
    }
}
```

2. On your startup class, in the Configure method, inject the HttpContextAccessor and configure the Audit. Use the context accessor to get the circuit ID, etc:
 
```c#
public class Startup
{
    // ...
    public void Configure(IApplicationBuilder app, IHttpContextAccessor httpContextAccessor)
    {
        // ...
        Audit.Core.Configuration.Setup()
            .UseEntityFramework(ef => ef
                .UseDbContext<OrderDbContext>()
                .AuditTypeExplicitMapper(m => m
                    .Map<Order, OrderAudit>()
                    .Map<Orderline, OrderlineAudit>()
                    .AuditEntityAction<IAudit>((evt, entry, auditEntity) =>
                    {
                        // Use the context accessor to get HttpContext info
                        var circuitId = httpContextAccessor.HttpContext.Items["CircuitId"];
                        var traceIdentifier = httpContextAccessor.HttpContext.TraceIdentifier;
                        var userName = httpContextAccessor.HttpContext.User.Identity.Name;

                        // ...
                    })));
    }
}
```

**Comment by mrlife** [comment]
@thepirat000 Thank you for the suggestion. I had thought of this, but it ends up being the same issue of using HttpContext. The user id comes from the initial page load's HttpContext and is passed into the Blazor scope for services and is used from there.

As you linked to, the HttpContext isn't guaranteed to be available in `Startup.cs`. I've thought about a singleton and browser session storage, but I'm not sure those are options either. Any other ideas for this one roadblock in order to have Blazor work with Audit.NET?

**Comment by ashalkhakov** [comment]
I have a Blazor Server app and ended up making HTTP requests from within the circuit to the server (kinda like a loop, but it works). I can then use the standard `IHttpContextAccessor` approach to get the authenticated user. Any other solutions?

**Comment by mrlife** [comment]
> I have a Blazor Server app and ended up making HTTP requests from within the circuit to the server (kinda like a loop, but it works). I can then use the standard `IHttpContextAccessor` approach to get the authenticated user. Any other solutions?

Could you post some code of your solution?

**Comment by mrlife** [comment]
@ashalkhakov Thank you for sharing your code. I am doing something similar by getting the `IHttpContextAccessor` in `Startup.cs`. Since it is a Blazor application, I believe it is an [unsupported](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-3.1#blazor-and-shared-state-1) usage according to Microsoft. It's possible that the `HttpContext` will not be there or will be for a different user.

```
app.Services.GetRequiredService<IHttpContextAccessor>().HttpContext
```

**Comment by thepirat000** [comment]
Assuming you are only auditing EF Db contexts with `Audit.EntityFramework.Core`, then the audit will trigger whenever you call `SaveChanges` on the Db context. 

I can't tell if you're always calling `SaveChanges` from an HTTP request or from a Background service, a websocket request, etc

**Comment by mrlife** [comment]
@thepirat000 Just closing the loop here... [according to Microsoft](https://github.com/dotnet/AspNetCore.Docs/issues/25855#issuecomment-1134641810), `SaveChanges` runs on the server in a Blazor Server app, just like in any other ASP.NET Core app.
