### ISSUE TITLE
RavenDB Change Tracking

### ISSUE THREAD

**Issue by JoshZA** [thepirat000/Audit.NET#486]
Change tracking doesn't appear to work for new or updated objects

```json
"Target": {
    "Type": "Order",
    "Old": {
      "Id": [],
      "Title": [],
      "Requester": [
        [
          []
        ],
        [
          []
        ],
        [
          []
        ]
      ],
      "Status": [],
      "Priority": [],
      "DeliveryDate": [],
      "Project": [],
      "CreatedAt": [],
      "Rows": [],
      "ShortId": []
    },
    "New": {
      "Id": [],
      "Title": [],
      "Requester": [
        [
          []
        ],
        [
          []
        ],
        [
          []
        ]
      ],
      "Status": [],
      "Priority": [],
      "DeliveryDate": [],
      "Project": [],
      "CreatedAt": [],
      "Rows": [],
      "ShortId": []
    }
  },
```

Startup is configured as follows:
        

```csharp
 var cert = new X509Certificate2(Path.Combine(env.ContentRootPath, configuration["RavenSettings:CertFilePath"]),configuration["RavenSettings:CertPassword"]);
            
            Audit.Core.Configuration
            .Setup()
            .JsonNewtonsoftAdapter()
            .UseRavenDB(config => config
                .WithSettings(settings => settings
                    .Urls(configuration.GetSection("RavenSettings:Urls").Get<string[]>())
                    .Database(ev => "XYZ")
                    .Certificate(cert)));
```

Example item tracking:

```csharp
var db  = DocumentStore.OpenAsyncSession();
var Order = await db.LoadAsync<Order>($"orders/{Id}");
using (AuditScope.Create("Order:Update", () => Order)
{
    Order.Title =  "New Title";
}

await db.SaveChangesAsync();
```

Audit.Net.ravendb - 19.1.0

**Comment by thepirat000** [comment]
can you share the code for class Order?
which .net version are you targeting?

**Comment by JoshZA** [comment]
`
public class Order // audit trail
{
    public string Id { get; set; }
    [Required] public string Title { get; set; }
    public AzureTenantUser Requester { get; set; } // lucky
    public string AssignedToUser { get; set; } // ewan or happy
    public string ApprovedByUser { get; set; } // angelo

    public RequestionStatus Status { get; set; }
    public Priority Priority { get; set; }

    [Required] public DateTime? DeliveryDate { get; set; }
    [Required] public string Project { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    // desc + qty
    public List<OrderRow> Rows { get; set; }
    public string ShortId => Id.TrimStart("orders/");

    // public List<Comments> Comments { get; set; }
}

public class OrderRow
{
    public string Name { get; set; } = "";
    public float Quantity { get; set; } = 0f;
}

public enum RequestionStatus
{
    AwaitingAuth,
    Approved,
    Rejected,
}

public enum Priority
{
    Low,
    Medium,
    High
}
public class AzureTenantUser
{
    public string Oid {get; set; }
    public string Name {get; set; }
    public string Email {get; set; }
}`

Targeting .net6 win-x64

RavenDB Cloud 5.2.101

All CRUD operations succeed against the data, so I don't believe this is a serialization issue
![image](https://user-images.githubusercontent.com/136638/163256158-fdfe28f1-6129-476b-a408-3e4f94099a27.png)

**Comment by thepirat000** [comment]
yeah, but I mean the Audit documents on ravenDB "XYZ", do they look good or what you shared at the beginning is from Raven DB?
Are you setting up anything else like custom actions?

**Comment by JoshZA** [comment]
@thepirat000 My apologies - you're correct this is a serialization issue. I was using System.Json instead of using Newtonsoft. As soon as I used the latter the data displayed correctly
