### ISSUE TITLE
Simple Tracking Changes

### ISSUE THREAD

**Issue by EliveltonRepolho** [thepirat000/Audit.NET#487]
I have a question about it if is possible to track like only Date and User Created/Modified for example, inside classes.. Not creating a full history change.. example:

```C#
public abstract class AuditEntity {
    public DateTime? CreatedDate { get; set; }
    public DateTime? ModifiedDate { get; set; }  
    public string? CreatedBy { get; set; }
    public string? ModifiedBy { get; set; }
}

public class SimpleTrackEntity : AuditEntity {
    public string? Description { get; set; }
}
```

I did not find something related if this is possible to do using this `Audit.NET`... 

My use case is:
I should create a Trail Table, which I am using this `Audit.NET` to do it, but do want to set `Date and User Created/Modified` for some entities, so this way it is easy to get.

**Comment by thepirat000** [comment]
Please ass more context. 

Are you auditing changes on EF using Audit.EntityFramework?

**Comment by EliveltonRepolho** [comment]
Sorry, I am using `Audit.EntityFramework.Core`

Here is my Configs I am current using:

```
Audit.EntityFramework.Configuration.Setup()
    .ForContext<AppDbContext>(config => config
        .AuditEventType("EF:{context}"))
    .UseOptIn()
    ;

Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeMapper(t => typeof(AuditTrail))
        .AuditEntityAction<AuditTrail>((ev, entry, entity) =>
        {
            entity.JsonData = entry.ToJson();
            entity.TablePk = entry.PrimaryKey.ToJson();
            
            entity.Action = entry.Action.ToString();
            
            entity.ModifiedDate = DateTime.UtcNow;
            entity.TableName = entry.Table;
            entity.EventType = ev.EventType.ToString();
            
            entity.HostUserName = ev.Environment.UserName;
            entity.IdentityUserName = ev.CustomFields.GetValueOrDefault(IdentityUserName, IdentityUserNameDefault)?.ToString();
        })
        .IgnoreMatchedProperties()
    );

Configuration.JsonSettings = new JsonSerializerOptions
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
};
```

**Comment by thepirat000** [comment]
You can access the actual entity being modified from the audit action with `entry.Entity`. So I guess you could do something like this:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeMapper(t => typeof(AuditTrail))
        .AuditEntityAction<AuditTrail>((ev, entry, entity) =>
        {
            if (entry.Entity is AuditEntity auditEntity)
            {
                entity.ModifiedDate = auditEntity.ModifiedDate;
            }
            ....
```

**Comment by EliveltonRepolho** [comment]
My `entry.Entity` is null:

![image](https://user-images.githubusercontent.com/6267251/164312783-b9bdc45f-4081-4a56-9325-94196ade611c.png)

**Comment by EliveltonRepolho** [comment]
Change to :

```C#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeMapper(t => typeof(AuditTrail))
        .AuditEntityAction<AuditTrail>((ev, entry, entity) =>
        {
            if (entry.GetEntry().Entity is AuditEntity auditEntity)
            {
                entity.ModifiedDate = auditEntity.ModifiedDate;
            }
            ....
```

And Worked .. thanks a lot !!

**Comment by EliveltonRepolho** [comment]
Actually .. doing this way... this became an infinity loop...

Like, if I insert a new Item, next will be the Update triggered by my changes to Entity.. and so on...

**Comment by thepirat000** [comment]
You need set [IncludeEntityObjects setting](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#settings) to `true` for the entity to be included on the `entry.Entity` property.

Also try decorating with `[AuditIgnore]` attribute the entities that represent the Audits, so they are not tracked

**Comment by EliveltonRepolho** [comment]
Nice, let's double check.. if I am doing something wrong.

Now I have `entry.Entity` being populated correctly... 

Have decorated those:
```C#
[AuditIgnore]
public class AuditTrail { ... }

[AuditIgnore]
public abstract class AuditEntity { ... }
```

But still having infinity loop :/

**Comment by thepirat000** [comment]
I'm confused regarding your entities and configuration... 

If you could create a minimal project that reproduces the issue I would be able to help

Seems like you are using the same `DbContext` for the tracked entities and the audit entities, which is fine, but if your DbContext is not inheriting from AuditDbContext, then that could provoke the loop since you will be auditing the audit.

**Comment by thepirat000** [comment]
If that's the case (AppDbContext not inheriting from AuditDbContext), another option is to implement [IAuditBypass](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/IAuditBypass.cs) on your DbContext:

```c#
public class AppDbContext : DbContext, IAuditBypass
{
  public int SaveChangesBypassAudit()
  {
    return base.SaveChanges():
  }

  public Task<int> SaveChangesBypassAuditAsync()
  {
    return base.SaveChangesAsync();
  }
  // ...
}
```

In that way, any Audit entity will bypass the audited SaveChanges, and call the original DbContext's SaveChanges

**Comment by EliveltonRepolho** [comment]
Created this sample project: https://github.com/EliveltonRepolho/Audit.NET.Trail.Simple.Logs

You can check the infinity loop here: https://github.com/EliveltonRepolho/Audit.NET.Trail.Simple.Logs/blob/main/MiniDemo/Program.cs#L37

And thanks a lot for your attention !

**Comment by thepirat000** [comment]
So you are trying to modify the actual entity, not the audit entity. But the Audit Entity Action takes place **after** the entity is modified and saved, so **_you cannot update the actual entity in the Audit Entity Action_**.

The `auditEntity` on line 37 represents the entity already saved, and you are changing its properties again (CreateDate, ModifiedDate) after it was saved, so EF will interpret that entity has an unsaved change.

I still don't get the `AuditEntity` vs `AuditTrail` difference... I'm assuming `AuditEntity` is just a normal entity, like employees and so on.

But, I think you can still do what you want at the AuditEvent level, from a [Custom Action of type OnScopeSaving](https://github.com/thepirat000/Audit.NET#custom-actions), since the scope is created before the SaveChanges takes place:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    var efEvent = scope.GetEntityFrameworkEvent();
    foreach (var entry in efEvent.Entries)
    {
        var now = DateTime.UtcNow;
        if (entry.GetEntry().Entity is AuditEntity auditEntity)
        {
            if (entry.Action == "Insert")
            {
                auditEntity.CreatedDate = now;
            }
            auditEntity.ModifiedDate = now;
        }
    }
});
```

**Comment by EliveltonRepolho** [comment]
Humm .. undestood now.

`AuditTrail`: is my changes log table, all tables will be logged here, so I can track Before and After changes
`AuditEntity`: is a simple abastract class so I can inherit Fields like `Created/Modified Date/User` and automatically set these fields in same place (Audit Config)

Will try your suggestion today.. Thanks a lot

**Comment by EliveltonRepolho** [comment]
> So you are trying to modify the actual entity, not the audit entity. But the Audit Entity Action takes place **after** the entity is modified and saved, so **_you cannot update the actual entity in the Audit Entity Action_**.
> 
> The `auditEntity` on line 37 represents the entity already saved, and you are changing its properties again (CreateDate, ModifiedDate) after it was saved, so EF will interpret that entity has an unsaved change.
> 
> I still don't get the `AuditEntity` vs `AuditTrail` difference... I'm assuming `AuditEntity` is just a normal entity, like employees and so on.
> 
> But, I think you can still do what you want at the AuditEvent level, from a [Custom Action of type OnScopeCreated](https://github.com/thepirat000/Audit.NET#custom-actions), since the scope is created before the SaveChanges takes place:
> 
> ```cs
> Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
> {
>     var efEvent = scope.GetEntityFrameworkEvent();
>     foreach (var entry in efEvent.Entries)
>     {
>         var now = DateTime.UtcNow;
>         if (entry.GetEntry().Entity is AuditEntity auditEntity)
>         {
>             if (entry.Action == "Insert")
>             {
>                 auditEntity.CreatedDate = now;
>             }
>             auditEntity.ModifiedDate = now;
>         }
>     }
> });
> ```

Just one thing about using this solution, I am still testing and reading the docs if has another config the must be done. But in the example I sent (https://github.com/EliveltonRepolho/Audit.NET.Trail.Simple.Logs)... I updated with your suggestion, but if for example I try to insert same Employee ID (Forcing violating Primary Key) we have an infinity loop now in this portion of code :/

**Comment by thepirat000** [comment]
The Audit.EntityFramework.Core will trigger the audit even is the original SaveChanges fails.
I'm not sure why is could be looping, but If you don't want to save audits when SaveChanges fails, you can change your AuditEntityAction to return a boolean depending on the Success field of the EF event:

https://stackoverflow.com/a/71700459/122195

**Comment by thepirat000** [comment]
Also, the recommendation is to set up a different instance of your DbContext for the audit entities by calling `.UseDbContext()`
 
```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .UseDbContext<AppDbContext>() 
```

Check this https://github.com/thepirat000/Audit.NET/issues/168#issuecomment-425609685

**Comment by EliveltonRepolho** [comment]
thanks for the recommendation too, I've implemented and now everything looks good.

Closing this issue .. will leave [this example](https://github.com/EliveltonRepolho/Audit.NET.Trail.Simple.Logs) available if might be useful for someone else. 

Thanks a lot for helping with it !
