### ISSUE TITLE
Audit.EntityFramework logs to another DB

### ISSUE THREAD

**Issue by alberk8** [thepirat000/Audit.NET#489]
Is it possible to log EntityFramework (MS SQL) then log the audit in MySQL DB. ?

```
Audit.Core.Configuration.Setup()
                .UseEntityFramework(x => x
                .UseDbContext<AppAuditDbContext>(auditDbContextOptions)
```

**Comment by thepirat000** [comment]
I'm not sure what are you asking, could you clarify what are you auditing and where do you want to store the audits?

I'm assuming you're auditing some EF DbContext and you want to store the audits using the EntityFramework DataProvider (MSSQL) but you also want to store the audits on a MySQL DB.

If that's the case maybe this can help https://stackoverflow.com/questions/58203562/in-audit-net-is-there-a-way-to-use-multiple-output-provider/58206408#58206408

**Comment by alberk8** [comment]
Thanks. That is what I am looking for.
