### ISSUE TITLE
Track only crUD changes.

### ISSUE THREAD

**Issue by randeep80** [thepirat000/Audit.NET#49]
Is there a way I only track Update and Delete actions of my models?
And its also capture DBUpdate Exceptions, where changes were not successful. How can I exclude these as well?
`"Valid":true,"ValidationResults":[]}],"Result":0,"Success":false,"ErrorMessage":"(DbUpdateException) An error occurred while updating the entries. See the inner exception for details. `

**Comment by thepirat000** [comment]
Hi

I have to apply a small [fix](https://github.com/thepirat000/Audit.NET/commit/8fa7f2c50e727822d142ccf5871f71efc8d16543) to allow discard audit events on the EventSaving custom action. Please use latest version (>= 7.0.8)

So this can be accomplished with a custom action, like this:
```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var efEvent = scope.Event.GetEntityFrameworkEvent();
    if (!efEvent.Success || efEvent.Entries.Any(x => x.Action == "Insert"))
    {
        scope.Discard();
    }
});
```
Note that each EF event could contain more than one entry, I'm assuming that if there is at least one Insert operation, the event should be discarded.

Another solution (this whould work with any version) is to override the `AuditDbContext.OnScopeSaving`, for example:
```c#
public partial class YourDbContext : AuditDbContext
{
    public override void OnScopeSaving(AuditScope scope)
    {
       // same logic here..
       scope.Discard();
    }
}
```

Hope it helps
