### ISSUE TITLE
Get CurrentAuditScope in a MVC Action

### ISSUE THREAD

**Issue by alexanlp** [thepirat000/Audit.NET#492]
Based on [this thread](https://stackoverflow.com/questions/72222192/how-to-use-getcurrentauditscope-metthod-in-an-actionfilterattribute), it's possible implements the extension method GetCurrentAuditScope() for MVC actions to get AuditScope on MVC filters?

Thanks.

**Comment by thepirat000** [comment]
The `GetCurrentAuditScope(this HttpContext)` extension method was added on version 19.1.2, please upgrade your references and re-test

**Comment by alexanlp** [comment]
> The `GetCurrentAuditScope(this HttpContext)` extension method was added on version 19.1.2, please upgrade your references and re-test

Thats worked.
Thanks.
