### ISSUE TITLE
Audit.EntityFramework.Identity not working with .net 6

### ISSUE THREAD

**Issue by RickworkGit** [thepirat000/Audit.NET#495]
**Describe the bug**
After Install-Package Audit.EntityFramework.Identity, I change my ApplicationDbContext.cs

```
public class ApplicationDbContext : AuditIdentityDbContext<IdentityUser>
{
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.AddInterceptors(new AuditSaveChangesInterceptor());
        }
}

```
I don't see anything write to my Event table.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Identity: 19.1.4

**Target .NET framework:**
For example:
 - .NET 6

**Additional context**

**Comment by thepirat000** [comment]
Which data provider are you using? can you share the code?

If you are not configuring a data provider, by default it will use the FileDataProvider, saving the audits as JSON files on the application directory.

Please check [the docs](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#configuration)

**Comment by RickworkGit** [comment]
I figure it out
before I put:

Audit.EntityFramework.Configuration.Setup()
                .ForContext<SSAreaDbContext>(_ => _
                    .AuditEventType("EF:{context}"))
                .UseOptOut();

Now:

Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(x => x.IncludeEntityObjects(true)
                .AuditEventType("{context}:{database}"))
                .UseOptOut();

Everything is working now.
