### ISSUE TITLE
ElasticsearchDataProvider throws 400 error if customField name includes "Id"

### ISSUE THREAD

**Issue by paolovalladolid** [thepirat000/Audit.NET#499]
**Describe the bug**
I have Audit.NET configured to use ElasticsearchDataProvider.

I create an auditScope as follows
```
 auditScope = await AuditScope.CreateAsync("developer-api-portal",
                    () => item,
                    new { ServiceId = "ServiceDePaolo" });
```

Creating the auditScope results in a 400 error.  Below is the full stack trace:

ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /developer-api-portal/_doc/a69690ec-53da-40f7-8112-6bc8902fad8d. ServerError: Type: mapper_parsing_exception Reason: "failed to parse field [customFields.serviceId] of type [float] in document with id 'a69690ec-53da-40f7-8112-6bc8902fad8d'. Preview of field's value: 'ServiceDePaolo'" CausedBy: "Type: number_format_exception Reason: "For input string: "ServiceDePaolo"""
Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEventAsync(AuditEvent auditEvent)
Audit.Core.AuditScope.SaveEventAsync(bool forceInsert)
Audit.Core.AuditScope.EndAsync()
Audit.Core.AuditScope.DisposeAsync()
System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
POCAuditNet.Auditor.AuditAsync(Service item) in Auditor.cs
+
                await auditScope.DisposeAsync();
POCAuditNet.Pages.ServiceEditModel.OnGetAsync(string serviceId) in ServiceEdit.cshtml.cs
+
            await auditor.AuditAsync(Service);
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Expected behavior**
My understanding, based on the documentation, is that I should be able to use any field name I want for a Custom Field, as long as it does not include reserved words or anything like that.  We want to be able to assign a String value to a Custom Field called ServiceId, but we cannot because the data provider automatically parses the value as a double.

We cannot use double values with the ELK stack (Elasticsearch and Kibana) at present because Kibana cannot handle 64-bit values.  So we have to use string values as a workaround.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET.Elasticsearch 19.1.4
 - Audit.EntityFramework: 13.0.0

**Target .NET framework:**
For example:
 - .NET 5.0

**Comment by thepirat000** [comment]
I think that is because of Elasticsearch's [Dynamic Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html)

I guess the first document inserted actually had a ServiceId as a double, so Elasticsarch created the index for a double value. Can you try the same but changing the custom field name?
