### ISSUE TITLE
SQL Server Support for Schemas

### ISSUE THREAD

**Issue by cletisgipson** [thepirat000/Audit.NET#5]
I have a database with several schemas in it. I am currently using the API audit package and I want the event table to be stored in a certain schema.  How can I configure the Audit.NET to work with a specific schema?  Or is this something that will need to be coded into the application.

**Comment by thepirat000** [comment]
I've just added Schema configuration to [SqlServer provider](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.SqlServer#configuration) 

Not sure if this solves your problem.

Regards

**Comment by cletisgipson** [comment]
Thanks for the quick response.  The update does exactly what I need.
