### ISSUE TITLE
RavenDB audit provider is slow when writing a lot of events

### ISSUE THREAD

**Issue by scattered-code** [thepirat000/Audit.NET#507]
**Describe the bug**
The RavenDB provider writes to the database after every save, and in the case where I need a separate audit record for every record that was changed, it adds a very significant delay adding several minutes in some cases

**To Reproduce**
var parents = await session.LoadAsync<Parent>(ids, ct);
foreach (var parent in parents)
{
    using (var audit = await AuditScope.CreateAsync("Parents:Update", () => parent, new { parent.Value.Id }))
    {
        parent.Value.Health.InspectionDate = model.InspectionDate;
    }
}

await session.SaveChangesAsync(ct);

**Expected behavior**
Audit logs don't delay processing

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET: 19.1.4
 - Audit.NET.RavenDB: 19.1.4

**Target .NET framework:**
For example:
 - .NET 6

**Additional context**
RavenDB supports bulk inserts, which are significantly faster. Is there a way to batch audits? I'm happy to take it on and submit a PR with some guidance
https://ravendb.net/docs/article-page/5.4/csharp/client-api/bulk-insert/how-to-work-with-bulk-insert-operation

**Comment by scattered-code** [comment]
Next option I tried is using
https://gist.github.com/canton7/8504141

```
SingleAccessTaskScheduler _concurrencyScheduler;
TaskFactory _taskFactory;
```

in the constructor:
```
_concurrencyScheduler = new SingleAccessTaskScheduler();
_taskFactory = new TaskFactory(_concurrencyScheduler);
```

Then InsertEvent becomes
```
public override object InsertEvent(AuditEvent auditEvent)
{
    var task = _taskFactory.StartNew(() => InsertEvtAsync(auditEvent)).ConfigureAwait(false).GetAwaiter().GetResult();
    var id = task.ConfigureAwait(false).GetAwaiter().GetResult();
    return id;
}
```

And we move the insertion logic to a private method
```
private async Task<object> InsertEvtAsync(AuditEvent auditEvent)
{
    var databaseName = GetDatabaseName(auditEvent);

    if (!_bulkInsertTargets.ContainsKey(databaseName))
        _bulkInsertTargets.Add(databaseName, _documentStore.BulkInsert(databaseName));
    var bulkInsert = _bulkInsertTargets[databaseName];

    var id = await bulkInsert.StoreAsync(auditEvent);
    return id;
}
```

The problem with this is that we never close the bulk insert, and it flushes once enough records are inserted. We'd need to implement IDisposable and IAsyncDisposable 
```
public void Dispose()
{
    foreach (var target in _bulkInsertTargets)
        target.Value.Dispose();
}

public async ValueTask DisposeAsync()
{
    foreach (var target in _bulkInsertTargets)
        await target.Value.DisposeAsync().ConfigureAwait(false);
}
```

If I manually dispose the DataProvider, it flushes the events as expected, but without that I don't get all of them by the time I check
```
[Fact]
public async Task TestStoreParallel()
{
    Audit.Core.Configuration.Setup()
        .JsonNewtonsoftAdapter(new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore })
        .UseRavenDB(config => config
            .WithSettings(settings => settings
                .Urls(_store.Urls)
                .Database(ev => _store.Database)
                .Certificate(_store.Certificate)));

    var tasks = new List<Task>();
    for (int i = 0; i < 150; i++)
        tasks.Add(CreateEvent());
    await Task.WhenAll(tasks);

    await ((RavenDbDataProvider)Configuration.DataProvider).DisposeAsync();

    using (var session = _store.OpenAsyncSession())
    {
        var events = await session.Query<AuditEvent>().ToListAsync();

        Assert.Equal(150, events.Count);
        var ev = events[0];
        Assert.Equal("test", ev.EventType);
    }
}

private async Task CreateEvent()
{
    using (var scope = await AuditScope.CreateAsync(new AuditScopeOptions() { EventType = "test" }))
    {
        scope.SetCustomField("Test", "test");
        scope.SetCustomField("Test2", "test2");
    }
}
```

This is all in an attempt to return an id as expected. I'm not sure how this would perform under heavy load, if it would still add delay. The queue option with a periodic flush seems to offer the best solution, and document IDs can be generated on the client-side.

**Comment by thepirat000** [comment]
I don't think there is a generic way to handle bulk inserts since the AuditScope is limited to just one Audit Event and the library does not provide or force any relation between the independent scopes.

So the only way would be to provide an opinionated implementation (i.e the queue with periodic flush) which, I think, is too specific to be included as part of the library.

Also I don't think the locking mechanism will result in the same penalties, since the lock would be cheaper than the RavenDb insert.

**Comment by scattered-code** [comment]
It looks like InsertEventAsync isn't called at all, and the sync version seems to not need any special handling for parallelism based on some tests I ran.

I ran tests against a free ravendb cloud instance (to introduce some latency), writing 150 events both in parallel and sequentially, with the current implementation, and one using Bulk insert.

This takes 21.7 - 22 seconds to write 150 events
```
public override object InsertEvent(AuditEvent auditEvent)
{
    using (var session = _documentStore.OpenSession(GetDatabaseName(auditEvent)))
    {
        session.Store(auditEvent);
        session.SaveChanges();

        return session.Advanced.GetDocumentId(auditEvent);
    }
}
```

This takes 2.6-2.8 seconds to write the same 150 events
```
public override object InsertEvent(AuditEvent auditEvent)
{
    var databaseName = GetDatabaseName(auditEvent);

    if (!_bulkInsertTargets.ContainsKey(databaseName))
        _bulkInsertTargets.Add(databaseName, _documentStore.BulkInsert(databaseName));
    var bulkInsert = _bulkInsertTargets[databaseName];

    return bulkInsert.Store(auditEvent);
}
```

The only concern I have at this point is flushing in the case where the application writes very few events

**Comment by scattered-code** [comment]
The queue-based implementation is below if you choose to use it, otherwise feel free to close the ticket. The flushing can be configurable if needed, I just defaulted it to 10s and works great for my case; you can also add a number of events limit to trigger the write (this would make it similar to how nlog async targets and redis snapshots flush). The example I gave above actually closes the bulk insert after some time, so it'll error out.

```
private ConcurrentQueue<(string id, string databaseName, AuditEvent auditEvent)> _queue = new ConcurrentQueue<(string id, string databaseName, AuditEvent auditEvent)>();
private Timer _timer;
```

in the constructors:
```
_timer = new Timer((s) => FlushQueue().ConfigureAwait(false), null, new TimeSpan(0, 0, 10), new TimeSpan(0, 0, 10));
```

then we have 
```
private async Task FlushQueue()
{
    if (_queue.IsEmpty)
        return;

    var bulkInsertTargets = new Dictionary<string, BulkInsertOperation>();
    while (_queue.TryDequeue(out var result))
    {
        if (!bulkInsertTargets.ContainsKey(result.Item2))
            bulkInsertTargets.Add(result.Item2, _documentStore.BulkInsert(result.Item2));
        var bulkInsert = bulkInsertTargets[result.Item2];
        await bulkInsert.StoreAsync(result.auditEvent, result.id);
    }

    foreach (var target in bulkInsertTargets)
        target.Value.Dispose();
}

public override object InsertEvent(AuditEvent auditEvent)
{
    var databaseName = GetDatabaseName(auditEvent);

    var id = _documentStore.Conventions.GenerateDocumentId(databaseName, auditEvent);
    _queue.Enqueue((id, databaseName, auditEvent));
    return id;
}

/// <summary>
/// Insert an event to the data source returning the event id generated
/// </summary>
/// <param name="auditEvent">The audit event being inserted.</param>
/// <returns></returns>
public override async Task<object> InsertEventAsync(AuditEvent auditEvent)
{
    var databaseName = GetDatabaseName(auditEvent);

    var id = _documentStore.Conventions.GenerateDocumentId(databaseName, auditEvent);
    _queue.Enqueue((id, databaseName, auditEvent));
    return id;
}
```
