### ISSUE TITLE
Log SQl Read (Select *) Results

### ISSUE THREAD

**Issue by chobo2** [thepirat000/Audit.NET#515]
**Describe the bug**
Right now the low level logging only logs the select statements EF makes such as  

`Select * From TableA`

It does not record the actual results that come back from running this query.

**To Reproduce**
Implement Low Level logging with EF and SQL Audit Extensions

**Expected behavior**
All results form the select statements should also be logged.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework:  Current
 - Audit.NET.SqlServer: Current 
**Target .NET framework:**

For example:
 - .NET 5

**Comment by thepirat000** [comment]
Support for logging results for queries was added on version 19.2.2, please upgrade your references and re-test

For example:

```c#
public class MyContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Add the low-level interceptor
        optionsBuilder.AddInterceptors(new AuditCommandInterceptor()
        {
            IncludeReaderResults = true
        });
    }
    // ...
}

```

**Comment by chobo2** [comment]
> Support for logging results for queries was added on version 19.2.2, please upgrade your references and re-test
> 
> For example:
> 
> ```cs
> public class MyContext : DbContext
> {
>     protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
>     {
>         // Add the low-level interceptor
>         optionsBuilder.AddInterceptors(new AuditCommandInterceptor()
>         {
>             IncludeReaderResults = true
>         });
>     }
>     // ...
> }
> ```

Wow thanks for implementing this so far. One quick look this look great. I will be reviewing it in more detail later with my team next week and will let you know.

Thanks
