### ISSUE TITLE
After upgrade from 19.1.4 to 19.2.2 serialization broken

### ISSUE THREAD

**Issue by apavelm** [thepirat000/Audit.NET#520]
I spent a lot of time trying to solve annoying bug

Newtonsoft.Json.JsonSerializationException: Error converting value "000000000000000000000000" to type 'MongoDB.Bson.ObjectId'. Path '[0].id', line 3, position 36.
 ---> System.InvalidCastException: Invalid cast from 'System.String' to 'MongoDB.Bson.ObjectId'.

But the last thing I suspected was minor version upgrade. It broke all the application, it crashes everywhere. (SerializeAsBson didn't help)
Hopefully I identified the issue reason and downgraded.

Please let me know if those breaking changes were planned and if so how to fix that. Otherwise - please fix this issue.

**Comment by apavelm** [comment]
@thepirat000 Kindly please have a look

**Comment by thepirat000** [comment]
Can you share a sample code that reproduces the issue? and also mention your target .NET version

**Comment by apavelm** [comment]
Version is .NET 6

`await UpdateAudit(
                    () => entity,
                    async () => await collectionProvider.FindOneAndReplaceAsync(_ => _.Id == entity.Id, entity)
                );`

`private async Task UpdateAudit(Func<object> target, Func<Task> updateAction)
        {
            var options = new AuditScopeOptions
            {
                EventType = "MongoStorage",
                TargetGetter = target,
            };
            await using var scope = await AuditScope.CreateAsync(options);
            await updateAction();
            await scope.SaveAsync();
        }`

**Comment by thepirat000** [comment]
Can you also share your audit configuration `Audit.Core.Configuration.*`?

**Comment by apavelm** [comment]
`new MongoDataProvider(config => config
                        .ConnectionString(configuration.GetSection("Mongo")["ConnectionString"])
                        .Database("Audit")
                        .Collection(configuration.GetSection("Mongo")["Audit"])
                        .SerializeAsBson(true)`

`SerializeAsBson` was added yesterday, "just in case"

**Comment by apavelm** [comment]
`var jsonSerializerSettings = JsonConvert.DefaultSettings();
            Audit.Core.Configuration.JsonAdapter = new JsonNewtonsoftAdapter(jsonSerializerSettings);

            Audit.Core.Configuration.DataProvider = new MultiDataProvider(
                    new EntityFrameworkDataProvider(ef => ef
                        .UseDbContext(
                            (e) => new AuditStoreDbContext(configuration.GetConnectionString("ConnStr")))
                        .AuditTypeMapper(t => typeof(AuditLog))
                        .AuditEntityAction((ev, ent, auditEntity) =>
                        {
                            ... some EF related logic
                        })
                    ),
                    new List<string>() { nameof(ApplicationDbContext) },
                    new MongoDataProvider(config => config
                        .ConnectionString(configuration.GetSection("Mongo")["ConnectionString"])
                        .Database("SpotoAudit")
                        .Collection(configuration.GetSection("Mongo")["Audit"])
                        .SerializeAsBson(true)
                    )
             );`



MultiDataProvider code is here:

` public class MultiDataProvider: AuditDataProvider
    {
        private readonly EntityFrameworkDataProvider _efDataProvider;
        private readonly List<string> _efEventTypes;
        private readonly MongoDataProvider _mongoDataProvider;

        public MultiDataProvider(EntityFrameworkDataProvider efDataProvider, List<string> efEventTypes, MongoDataProvider mongoDataProvider)
        {
            _efDataProvider = efDataProvider;
            _efEventTypes = efEventTypes;
            _mongoDataProvider = mongoDataProvider;
        }

        public override object InsertEvent(AuditEvent auditEvent)
        {
            object eventId = null;

            if (!_efEventTypes.Contains(auditEvent.EventType))
            {
                eventId = _mongoDataProvider.InsertEvent(auditEvent);
            }

            {
                eventId = _efDataProvider.InsertEvent(auditEvent);
            }

            return eventId;
        }

        public override async Task<object> InsertEventAsync(AuditEvent auditEvent)
        {
            object eventId = null;

            if (!_efEventTypes.Contains(auditEvent.EventType))
            {
                eventId = await _mongoDataProvider.InsertEventAsync(auditEvent);
            }
            else
            {
                eventId = await _efDataProvider.InsertEventAsync(auditEvent);
            }

            return eventId;
        }

        public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
        {
            if (!_efEventTypes.Contains(auditEvent.EventType))
            {
                _mongoDataProvider.ReplaceEvent(eventId, auditEvent);
            }
            else
            {
                _efDataProvider.ReplaceEvent(eventId, auditEvent);
            }

        }

        public override async Task ReplaceEventAsync(object eventId, AuditEvent auditEvent)
        {
            if (!_efEventTypes.Contains(auditEvent.EventType))
            {
                await _mongoDataProvider.ReplaceEventAsync(eventId, auditEvent);
            }
            else
            {
                await _efDataProvider.ReplaceEventAsync(eventId, auditEvent);
            }
        }

    }`

**Comment by thepirat000** [comment]
Please note that if you use the default creation policy `EventCreationPolicy.InsertOnEnd`, then the following pattern will insert duplicated events:

```c#
await using var scope = await AuditScope.CreateAsync(options); 
await updateAction(); 
await scope.SaveAsync();
```

The `SaveAsync()` call will trigger the audit event insert, but the disposal of the scope will **also** trigger the insert. 

You should use `EventCreationPolicy.Manual` creation policy if you explicitly call `scope.Save()` / `scope.SaveAsync()`

**Comment by thepirat000** [comment]
Note the MongoDataProvider has a custom Serialize method, but your custom data provider is not using it, since it's calling the default base AuditDataProvider.Serialize. 

I'm not sure if this is the root cause of the issue,  but please try with `SerializeAsBson(true)` again, but also overriding the `Serialize` method on your custom data provider to use the MongoDataProvider implementation:

```c#
public class MultiDataProvider : AuditDataProvider
{
    public override object Serialize<T>(T value)
    {
        return _mongoDataProvider.Serialize(value);
    }
    // ...
}
```

**Comment by thepirat000** [comment]
@apavelm 
Has the problem been solved?

**Comment by thepirat000** [comment]
Nothing related was changed on that version

**Comment by apavelm** [comment]
then maybe your recommendation works. Thank you
