### ISSUE TITLE
Audit.NET.SqlServer causes problems for .NET 6

### ISSUE THREAD

**Issue by jvereecken** [thepirat000/Audit.NET#522]
We are in the process of upgrading everything to .NET 6. When upgrading Audit.NET.SqlServer to 19.2.2 we can see a dependency on Microsoft.EntityFrameworkCore.SqlServer 5.0.8 instead of 6.x which is causing version mismatch issues in our project

**Comment by thepirat000** [comment]
This was included in version 19.3.0, please upgrade your references and re-test.

Thanks!
