### ISSUE TITLE
Unable to store audit logs in separate Db Context

### ISSUE THREAD

**Issue by xantari** [thepirat000/Audit.NET#524]
**Describe the bug**
I don't know that this is a bug, or if it's just my lack of understanding of the documentation. I am attempting to use one DbContext called AppDbContext in attached sample to log any changes from AppDbContext to a different DB Context called "AuditSqlDbContext".

What happens however is I get this exception:

MissingMethodException: Constructor on type 'AuditNetTest.AuditSqlDbContext' not found.

This seems similar to issue #149 but the solution there doesn't work, you get a different error, and it is no longer advisable to call BuildServiceProvider() any longer (read the warning if you attempt it in .NET 6).

**To Reproduce**
Attached is a full example.

To get up and running quickly follow these steps, which will create two new databases for you with the AuditLog table (in the AuditSqlDbContext pointed to the "AuditDb" database) and the Orders table (in the AppDbContext pointed to the "Testing" database).

1. dotnet tool install --global dotnet-ef
2. dotnet add package Microsoft.EntityFrameworkCore.Design
3. dotnet ef database update --project AuditNetTest --context AuditSqlDbContext
4. dotnet ef database update --project AuditNetTest --context AppDbContext

The above steps should create two databases. One called "Testing", the other called "AuditDb" with the tables necessary to run this sample.

You may need to change the connection string, I use "localhost" as I have SQL Server installed locally.

Additionally step 1 and 2 might not be needed, depending on if you have done that in the past.

**Expected behavior**
I would expect it to log to the AuditLog table in the AuditDb database by using the AuditSqlDbContext.

**Libraries (specify the Audit.NET extensions being used including version):**
Full sample attached (Audit .NET 19.3.0)

**NOTE:** The audit testing event is in the Index.cshtml.cs code behind razor page.

**Target .NET framework:**
.NET Core 6

[AuditNetTest.zip](https://github.com/thepirat000/Audit.NET/files/9420349/AuditNetTest.zip)

**Comment by thepirat000** [comment]
And what about using a service scope?

Assuming you have a DbContext with some dependencies:

```c#
public class AuditSqlDbContext : DbContext
{
    private IDependency _dependency;

    public AuditSqlDbContext(IDependency dependency)
    {
        _dependency = dependency;
    }
}
```

Also assuming you are using minimal hosting / no Startup class, so in your `Program.cs`:

```c#
...

// Configure DI
builder.Services.AddScoped<IDependency, Dependency>();
// Configure DbContext
builder.Services.AddDbContext<AuditSqlDbContext>(opt => opt
    .EnableSensitiveDataLogging()
    .EnableDetailedErrors());

// Build app
var app = builder.Build();

// Configure DbContext factory for audit
Audit.Core.Configuration.Setup()
    .UseEntityFramework(opt => opt
        .UseDbContext(_ =>
        {
            using var scope = app.Services.CreateScope();
            return scope.ServiceProvider.GetRequiredService<AuditSqlDbContext>();
        }));

...
```

**Comment by xantari** [comment]
Tried that and now get this:

```
ObjectDisposedException: Cannot access a disposed context instance. A common cause of this error is disposing a context instance that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling 'Dispose' on the context instance, or wrapping it in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances. Object name: 'AuditSqlDbContext'.
Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
Microsoft.EntityFrameworkCore.DbContext.AddAsync(object entity, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Audit.EntityFramework.Providers.EntityFrameworkDataProvider.InsertEventAsync(AuditEvent auditEvent)
Audit.Core.AuditScope.SaveEventAsync(bool forceInsert)
Audit.Core.AuditScope.SaveAsync()
Audit.EntityFramework.DbContextHelper.SaveScopeAsync(IAuditDbContext context, IAuditScope scope, EntityFrameworkEvent event)
Audit.EntityFramework.DbContextHelper.EndSaveChangesAsync(IAuditDbContext context, IAuditScope scope, int result, Exception exception)
Audit.EntityFramework.AuditSaveChangesInterceptor.SaveChangesFailedAsync(DbContextErrorEventData eventData, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken)
AuditNetTest.Pages.IndexModel.OnGet() in Index.cshtml.cs
+
            await _db.SaveChangesAsync();
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+NonGenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

**Comment by thepirat000** [comment]
oh, you're right, the scope will be disposed before the SaveChanges to the audit DbContext.

I have another idea that I think it could work. But this time I will do some test before trying to answer :)

**Comment by xantari** [comment]
No problem, appreciate the help!

**Comment by thepirat000** [comment]
The idea is to add the `AuditSqlDbContext` (the context that stores the audits) as a dependency on the `AppDbContext` (the audited DbContext).

For example, maintaining the reference in a property:

```c#
public class AppDbContext : DbContext
{
    internal AuditSqlDbContext AuditContext { get; set; }

    public AppDbContext(DbContextOptions<AppDbContext> options, AuditSqlDbContext auditContext) : base(options)
    {
        AuditContext = auditContext;
    }
}
```

So on your startup configuration, you can use the `UseDbContext` overload that takes an EF Audit Event and returns the audit context. 

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(x => x.UseDbContext(ev => ((AppDbContext)ev.EntityFrameworkEvent.GetDbContext()).AuditContext)
```

> Note that you can access the App Db Context from the EF Audit Event using `GetDbContext()`.

**Comment by thepirat000** [comment]
@xantari 
were you able to solve the issue?

**Comment by xantari** [comment]
That works! I'll do some more testing.

Definately should be something for the documentation, because the current documentation seems to imply you don't need to do this.
