### ISSUE TITLE
Upgrade Azure Table Storage

### ISSUE THREAD

**Issue by aesser** [thepirat000/Audit.NET#528]
The Audit.NET.AzureStorage provider is marked as to be deprecated in future versions. I'm using the UseAzureTableStorage implementation of it and wonder if there are any plans/efforts to create a new or updating the existing provider to use the newer Azure.Data.Table implementation from Microsoft?

**Comment by thepirat000** [comment]
I will try to work on that in the following weeks

**Comment by thepirat000** [comment]
An initial release of an Azure Table Storage data provider using Azure.Data.Tables, was added on version 19.1.4

Use NuGet package [Audit.NET.AzureStorageTables](https://www.nuget.org/packages/Audit.NET.AzureStorageTables).

Please check the [README](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.AzureStorageTables/README.md).

**Comment by aesser** [comment]
It is working fine. I had one failure since the Azure.Data.Table package doesn't seem to support enums as column fields out of the box. Just converted them to strings and it worked. Thanks again 👍
