### ISSUE TITLE
Audit.EntityFramework: Old and new value are always the same

### ISSUE THREAD

**Issue by Wosniak** [thepirat000/Audit.NET#53]
Hi!

I´m using Audit.EntityFramework and on log output the old and new values for changed entity are always the same! 

My config on statup.cs:

```
Audit.Core.Configuration.Setup().UseSqlServer(c => {
                c.ConnectionString(Configuration.GetConnectionString("audit.db"));
                c.Schema("dbo");
                c.TableName("Event");
                c.IdColumnName("EventId");
                c.JsonColumnName("Data");
                c.LastUpdatedColumnName("LastUpdatedDate");
                
            });

            Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(x => x.IncludeEntityObjects(true)
                                     .AuditEventType("{context}:{database}"))
                .UseOptOut();
```

Thankyou for the library and support!

**Comment by thepirat000** [comment]
By default, the EF extension will not fill the `Target` property. 

You should see the column changes on the `EntityFrameworkEvent` property instead:

![image](https://user-images.githubusercontent.com/9836380/28089830-e6ba741e-664f-11e7-8ec4-169d6e8acfad.png)

How are you creating the `AuditScope`? Can you share the code?

**Comment by Wosniak** [comment]
Well, there it´s my mistake!

I´m using the library out of the box, and didn´t created an instance of Audit Scope, just inherited from AuditDbContext, letting the Audit.Net do it´s work.

Do you have some example on creating an audit scope to work with EntityFramewort.Audit?

Thank you for your support!

**Comment by thepirat000** [comment]
In fact, the EF extension internally creates its Audit Scope, so you cannot control the creation of the scope for the EF extension.

If you create a scope by using `AuditScope.Create`, you'll be creating a totally new scope, not related to any extension you have (i.e. EF). It will not contain the entity framework and it will create a completely isolated audit event.

I'm wondering what is your use case, why do you need to create the scope used by EF extension?

There is a way to get the audit scope already created by the EF extension. Check the [overrides](
https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#overrides) section on the documentation.

**Comment by Wosniak** [comment]
I thought in create a scope, based on what you said about the old values not written on log output. I just need to audit in some way the changes on my entities.

Now I´m wondering how it can be done, overriding the OnScopeCreated or OnScopeSaving may not be the answer, since I can´t get my old values in it´s scopes.

**Comment by thepirat000** [comment]
If your need is to audit the changes of your entities, it should be enough to make your DbContext to inherit from `AuditDbContext`, as stated on the EF extension [documentation](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#auditentityframework). 

You don't need anything else to track the old/new values, they should be included on the `EntityFrameworkEvent.Entries` on the ouput, as shown on my first response.

If they are not, please share the code where you are making an entity change and also the event output you get.

**Comment by Wosniak** [comment]
Here´s the method:
```
[Route("api/v1/[controller]")]
    public class StoreController : Controller
    {
        private readonly CatalogContext _ctx;

        public StoreController(CatalogContext ctx)
        {
            _ctx = ctx ?? throw new ArgumentNullException(nameof(ctx));
        }

        [HttpPut("{id}")]
        //[Authorize]
        public async Task<IActionResult> Put(Guid id, [FromBody]Store storeToUpdate)
        {         
                 _ctx.Stores.Update(storeToUpdate);
                await _ctx.SaveChangesAsync();

                return CreatedAtAction(nameof(GetByID), new { id = storeToUpdate.Id }, storeToUpdate);
        }
   }
```

Context:

```
public sealed class CatalogContext : AuditDbContext
    {
        public CatalogContext(DbContextOptions<CatalogContext> options) : base(options)  { }

        public DbSet<Category> Categories { get; set; }
        public DbSet<Product> Products{ get; set; }
        public DbSet<ProductAttribute> ProductsAttributes { get; set; }
        //public DbSet<ProductCategory> ProductsCategories { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Store> Stores { get; set; }
 }

```
Config on StartUp:

```
Audit.Core.Configuration.Setup().UseSqlServer(c =>
            {

                c.ConnectionString(Configuration.GetConnectionString("audit.db"));
                c.Schema("dbo");
                c.TableName("Event");
                c.IdColumnName("EventId");
                c.JsonColumnName("Data");
                c.LastUpdatedColumnName("LastUpdatedDate");
                
            });

            Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(x => x.IncludeEntityObjects(true)
                                     .AuditEventType("{context}:{database}"))
                .UseOptOut();

```

Output:
```
{
	"EventType": "CatalogContext:T4Good.Store.CatalogDB",
	"Environment": {
		"UserName": "...",
		"MachineName": "...",
		"Culture": "pt-BR"
	},
	"StartDate": "2017-07-12T23:43:11.7599374-03:00",
	"EndDate": "2017-07-12T23:43:12.1374379-03:00",
	"Duration": 378,
	"EntityFrameworkEvent": {
		"Database": "T4Good.Store.CatalogDB",
		"Entries": [{
			"Table": "Stores",
			"Action": "Update",
			"PrimaryKey": {
				"Id": "701fb141-35b7-4360-c0e5-08d4c2246860"
			},
			"Entity": {
				"Id": "701fb141-35b7-4360-c0e5-08d4c2246860",
				"StoreName": "Loja Teste",
				"URL": "http://www.lojateste.com.br",
				"Categories": [],
				"Products": []
			},
			"Changes": [{
				"ColumnName": "StoreName",
				"OriginalValue": "Loja Teste",
				"NewValue": "Loja Teste"
			},
			{
				"ColumnName": "URL",
				"OriginalValue": "http://www.lojateste.com.br",
				"NewValue": "http://www.lojateste.com.br"
			}],
			"ColumnValues": {
				"Id": "701fb141-35b7-4360-c0e5-08d4c2246860",
				"StoreName": "Loja Teste",
				"URL": "http://www.lojateste.com.br"
			},
			"Valid": true
		}],
		"Result": 1,
		"Success": true
	}
}
```

Once again, thank you  for your support!

**Comment by thepirat000** [comment]
A couple of more questions trying to reproduce your issue. 

Are you actually modifying the `StoreName` and `URL` properties as part of the update? 

Do you have any test code in which you explicitly change the properties, make the update and the audit output is not reflecting your changes?

**Comment by Wosniak** [comment]
For sure! 

> Are you actually modifying the StoreName and URL properties as part of the update?

Yep, StoreName and Url were changed.

> Do you have any test code you can share in which you explicitly change the properties, make the update and the audit output is not reflecting your changes?

No, for simple crud operatios I'm didn't use any kind of Unity Test.

> Are you targeting .net core or the full .net framework?

It is a .Net Core WebApi project

**Comment by thepirat000** [comment]
ok.

I guess the problem is because you're using the `DbContext.Update` method and the entity (the `Store` object) is not being tracked by the Entity Framework.

The Update method will put the entity state as `Modified` irrespective of whether it actually has been modified. If that's the case, EF will not automatically query the database to check for the current values, it will just trigger the SQL update on all its fields.

Check the [DbContext.Update documentation](https://docs.microsoft.com/en-us/ef/core/api/microsoft.entityframeworkcore.dbcontext#Microsoft_EntityFrameworkCore_DbContext_Update__1___0_)

One solution is to load the entity from database, and make the changes on this entity, like:

```c#
var ori = ctx.Stores.Find(storeToUpdate.Id);
ori.URL = storeToUpdate.URL;
ori.StoreName= storeToUpdate.StoreName;
ctx.SaveChanges();
```

This can also be accomplished in a general way with this trick (original idea from [here](https://stackoverflow.com/a/10949128/122195)):

```c#
// Attach the object to the graph
var entry = ctx.Stores.Attach(storeToUpdate);
// Backup updated values
var updated = entry.CurrentValues.Clone();
// Reload entity from database, to track the original values
entry.Reload();
// Set the current values updated
entry.CurrentValues.SetValues(updated);
// Mark the entity as modified
entry.State = EntityState.Modified;
ctx.SaveChanges();
```

**Comment by bosp02** [comment]
Hi Federico,
Came across this thread and encountered the same problem. 
Had an scaffolded MVC5 controller and view and the oldvalue was the same as the new value. in the event table.

The original (template gnerated) code that did NOT work was:
```
 public ActionResult Edit([Bind(Include = "id,Name,Street,City,BirthDay")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }
```

The new code, based on your last suggestion,  that worked was:
```
`  public ActionResult Edit([Bind(Include = "id,Name,Street,City,BirthDay")] Person person)
        {
             if (ModelState.IsValid)
            {
                var persondb = db.Persons.Find(person.id);
                db.Entry(persondb).CurrentValues.SetValues(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }`
```

The problem with the solution is that:
1. you need an extra roundtrip to the database
1. you need to  modify all code before the SaveChanges, 

Can this be simplified ?

Thanks in advance for your support

Piet

**Comment by imran-khanmemon** [comment]
i am facing the same value (old and new) problem, i have not use any thing else then the default functionality. i am using entityrframe work identity core 2.1.2 
Here is startup code
Audit.Core.Configuration.Setup()
            .UseEntityFramework(x => x
            .AuditTypeNameMapper(typeName => "AuditLog")
            .AuditEntityAction((evt, entry, auditEntity) =>
                {
                    var a = (dynamic)auditEntity;
                    a.ChangeDate = DateTime.UtcNow;
                    a.UserName = evt.Environment.UserName;
                    a.MachineName = evt.Environment.MachineName;
                    a.Action = entry.Action; // Insert, Update, Delete
                    a.IPAddress = evt.Environment.DomainName;
                    a.Culture = evt.Environment.Culture;
                    a.TableName = entry.Table;
                    a.Action = entry.Action;
                    a.PrimaryKey = Convert.ToInt64(entry.PrimaryKey.FirstOrDefault().Value);
                    a.ChangesJson = JsonConvert.SerializeObject(entry.Changes);
                }));

  entry.Changes has same values always

"Entries": [
      {
        "Table": "HerdMineral",
        "Action": "Update",
        "PrimaryKey": {
          "HerdMineralId": 1
        },
        "Changes": [
          {
            "ColumnName": "Boost",
            "OriginalValue": 1.25,
            "NewValue": 1.25
          },
          {
            "ColumnName": "BoostPeriod",
            "OriginalValue": 2,
            "NewValue": 2
          },
          {
            "ColumnName": "HerdId",
            "OriginalValue": 1,
            "NewValue": 1
          },
          {
            "ColumnName": "MineralDispensed",
            "OriginalValue": 45,
            "NewValue": 45
          },
          {
            "ColumnName": "MineralId",
            "OriginalValue": 1,
            "NewValue": 1
          },
          {
            "ColumnName": "MineralLimit",
            "OriginalValue": 111.0,
            "NewValue": 111.0
          },
          {
            "ColumnName": "MineralTank",
            "OriginalValue": 55,
            "NewValue": 55
          }
        ],
        "ColumnValues": {
          "HerdMineralId": 1,
          "Boost": 1.25,
          "BoostPeriod": 2,
          "HerdId": 1,
          "MineralDispensed": 45,
          "MineralId": 1,
          "MineralLimit": 111.0,
          "MineralTank": 55
        },
        "Valid": true
      }

**Comment by thepirat000** [comment]
Hi @bosp02 

As far as I know that cannot be simplified because of the way the Entity Tracker works on Entity Framework. 

When doing updates like that from an detached entity, EF will just execute the UPDATE operation, without querying the previous state from the database, so there is no way for the audit to get the values *before* the update.

So if you want to log the previous values, you need to retrieve them first.

**Comment by shreyassbhat** [comment]
```
// Attach the object to the graph
var entry = ctx.Stores.Attach(storeToUpdate);
// Backup updated values
var updated = entry.CurrentValues.Clone();
// Reload entity from database, to track the original values
entry.Reload();
// Set the current values updated
entry.CurrentValues.SetValues(updated);
// Mark the entity as modified
entry.State = EntityState.Modified;
ctx.SaveChanges();
```

Is there any way to standardize this code so that we can use it globaly

**Comment by thepirat000** [comment]
I don't think this is related to this library, you could reuse that code just by adding a method on your DbContext like:

```
public int AttachUpdateEntity(object entityToUpdate)
{
    var entry = this.Attach(entityToUpdate); // Attach to the DbContext
    var updated = entry.CurrentValues.Clone();
    entry.Reload();
    entry.CurrentValues.SetValues(updated);
    entry.State = EntityState.Modified;
    return this.SaveChanges();
}

```

**Comment by tessierp** [comment]
Hi,

Has the issue been resolved? I am facing the exact same issue.. I call the DbContext to save new values, the database is updated correctly  however Audit.NET is unable to keep track of the OriginalValue. In essence what is being reported is the the OriginalValue is the NewValue.

**Comment by thepirat000** [comment]
This is not an issue with this library, but with how the EF Change Tracker works.

The EF change tracker will only track the entities you have in memory, so in order to keep track of the previous value of an entity property, you should first query the entity, update the properties and save changes:

```c#
var entity = Context.Users.Single(x => x.Id == id);
entity.FirstName = "New name";
Context.SaveChanges();
```

```c#
var entity = new User() { Id = id, FirstName = "New name" };
Context.SaveChanges();
```

There is no way for the EF change tracker to know the previous

**Comment by tessierp** [comment]
Problem solved, thank you!

**Comment by thepirat000** [comment]
Starting from version 21.0.2, the Audit.EntityFramework and Audit.EntityFramework.Core libraries introduce a new feature. 

The setting called `ReloadDatabaseValues` can be globally or individually configured for a DbContext instance. It determines whether the original values of audited entities should be fetched from the database prior to saving the audit event.

Consider the following examples of update and delete operations:

```c#
using (var context = new MyAuditedContext())
{
    //context.ReloadDatabaseValues = true;

    context.Cars.Update(new Car() { Id = 123, Name = "New name" });
    await context.SaveChangesAsync();
}
```

```c#
using (var context = new MyAuditedContext())
{
    //context.ReloadDatabaseValues = true;

    context.Entry(new Car() { Id = 123 }).State = EntityState.Deleted;
    await context.SaveChangesAsync();
}
```

If the ReloadDatabaseValues is not set to true, the EF Change Tracker will lack knowledge of the original values. 

Enabling the `ReloadDatabaseValues` setting triggers an extra database query to retrieve the original values prior to the update operation. As a result, the audit event will contain the original values.

**Comment by shubhamCedargate** [comment]
Hey!, thepirat000 a huge thank you for all your help! 
 I'm incredibly grateful for your expertise.

**Comment by mhguelleh** [comment]
Hi @thepirat000,

Is there a way we can set this `ReloadDatabaseValues` globally when using depency inject in controllers, like in `Program.cs` ?

**Comment by thepirat000** [comment]
The configuration in applicable by DbContext, not by controller. You can do enable it globally (for any context) with the following code in your startup:

```c#
Audit.EntityFramework.Configuration.Setup()
    .ForAnyContext(config => config
        .ReloadDatabaseValues(true));
```
