### ISSUE TITLE
Method not found: System.String Microsoft.EntityFrameworkCore.EntityTypeExtensions.DisplayName

### ISSUE THREAD

**Issue by knopa** [thepirat000/Audit.NET#530]
**Describe the bug**
 Method not found: 'System.String Microsoft.EntityFrameworkCore.EntityTypeExtensions.DisplayName(Microsoft.EntityFrameworkCore.Metadata.ITypeBase)'.
System.MissingMethodException: Method not found: 'System.String Microsoft.EntityFrameworkCore.EntityTypeExtensions.DisplayName(Microsoft.EntityFrameworkCore.Metadata.ITypeBase)'.
   at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
   at Audit.EntityFramework.DbContextHelper.BeginSaveChangesAsync(IAuditDbContext context)

**To Reproduce**
Not sure yet - after some time all _auditHelper.BeginSaveChangesAsync(_auditContext); raise that exception for every entity

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core.v3: 19.4.1

**Target .NET framework:**
For example:
 - .NET Core 6
 - Ef Core 6.0.9

**Comment by thepirat000** [comment]
Looks like you're targeting EF Core 6, but using the wrong library for EF Core 3. 

Reference Audit.EntityFramework.Core instead of Audit.EntityFramework.Core.v3

**Comment by knopa** [comment]
You are correct, thanks. Funny how it works before without issues.
