### ISSUE TITLE
MongoDB driver saves dates as string instead of datetime

### ISSUE THREAD

**Issue by zidad** [thepirat000/Audit.NET#531]
**Describe the bug**
When using the mongodb driver for audit.net, the start/end dates are incorrectly stored as string

**To Reproduce**
Save any event using the default mongodb driver

**Expected behavior**
DateTime values should be stored as native timestamps in mongodb

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
- Audit.NET.MongoDB: 19.4.1

**Target .NET framework:**
 - .NET 6.0

**Comment by thepirat000** [comment]
Maybe related to this: https://github.com/thepirat000/Audit.NET/issues/457

**Comment by thepirat000** [comment]
Could you please try using BSON serialization and overriding the Serialize method of the MongoDbProvider as follows:

```c#
using Audit.Core;
using Audit.MongoDB.ConfigurationApi;
using Audit.MongoDB.Providers;
using MongoDB.Bson;
...
public class CustomMongoProvider : MongoDataProvider
{
    public CustomMongoProvider(Action<IMongoProviderConfigurator> config) : base(config) { }
    public override object Serialize<T>(T value)
    {
        if (value == null || value is string || value is BsonDocument)
        {
            return value;
        }
        if (BsonTypeMapper.TryMapToBsonValue(value, out BsonValue bsonValue))
        {
            return bsonValue;
        }
        return value.ToBsonDocument(typeof(object));
    }
}
```

And change your configuration to use your custom provider:

```c#
Audit.Core.Configuration.Setup()
    .UseCustomProvider(new CustomMongoProvider(config => config
        .ConnectionString("...")
        .Database("...")
        .Collection("...")
        .SerializeAsBson(true)   // <- Important
    ));
```

I'll be doing some more testing, trying to see if the serialization should be like that by default when using SerializeAsBson

**Comment by zidad** [comment]
That works great, I also like that it doesn't save the custom fields as dictionary.  

Only thing I added is this, which I personally prefer as default:

`        ConventionRegistry.Register("Save enums as strings", new ConventionPack { new EnumRepresentationConvention(BsonType.String) }, type => type == typeof (AuditEvent));
` 

Many thanks!

**Comment by zidad** [comment]
Ah so now the problem is that Target.New and Target.Old are not mapped correctly:

<img width="586" alt="Screen Shot 2022-09-29 at 15 27 58" src="https://user-images.githubusercontent.com/303034/193044383-c5cc6628-6ac4-49c3-8162-a6c467f24ab0.png">

**Comment by thepirat000** [comment]
That's right, and I'm not sure why it happens for the Target property but doesn't happen for the custom fields. 
Some types will be serialized as BsonDocument.

**Comment by zidad** [comment]
> That's right, and I'm not sure why it happens for the Target property but doesn't happen for the custom fields. Target Old/New will be serialized as BsonDocument if it cannot be parsed as a single BSON value.

Ah ok if it's expected. Target is a typed object so it doesn't need separate type information to deserialize I guess, but you'd say that BsonDocument is also unnecessary because it can always deserialize to that as fallback.

**Comment by zidad** [comment]
> That's right, and I'm not sure why it happens for the Target property but doesn't happen for the custom fields. Target Old/New will be serialized as BsonDocument if it cannot be parsed as a single BSON value.

This seems to work quite well for me:
```csharp
 public Custom MongoDbProvider(Action<IMongoProviderConfigurator> config) : base(config)
    {
        ConventionRegistry.Register("Save enums as strings", new ConventionPack {
            new EnumRepresentationConvention(BsonType.String)
        }, _ => true);
    }

    public override object Serialize<T>(T value)
    {
        if (value is null or string or BsonDocument)
            return value!;

        if (BsonTypeMapper.TryMapToBsonValue(value, out var bsonValue))
            return bsonValue;

        // make a copy of the value so Old and New are set correctly after the target is modified
        return BsonSerializer.Deserialize<T>(value.ToBsonDocument());
    }
```

<img width="660" alt="Screen Shot 2022-09-30 at 11 58 31" src="https://user-images.githubusercontent.com/303034/193245836-57179bca-41c1-473b-bc5c-cb4fc52c6342.png">

**Comment by thepirat000** [comment]
Thanks for the update. 

I think I cannot implement the default serialization like yours, since it will fail in some cases, for example if you added a TimeSpan custom field, or any other type that cannot be properly seialized.

**Comment by zidad** [comment]
I understand, thanks for your help!
