### ISSUE TITLE
Prefer ReadFormAsync over Request.Form

### ISSUE THREAD

**Issue by timloh-enjinstarter** [thepirat000/Audit.NET#534]
**Describe the bug**
HttpContext.Request.Form uses sync over async and can lead to thread pool starvation (https://learn.microsoft.com/en-us/aspnet/core/performance/performance-best-practices?view=aspnetcore-6.0#prefer-readformasync-over-requestform).

**To Reproduce**
N.A.

**Expected behavior**
N.A.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 19.4.1
 - Audit.WebApi.Core: 19.4.1

**Target .NET framework:**
.NET 6.0

**Additional context**
N.A.

**Comment by timloh-enjinstarter** [comment]
Pull request #535

**Comment by thepirat000** [comment]
This was included in version 20.0.0, thank you!
