### ISSUE TITLE
Mongo Json property naming policy is ignored when serialize as bson property in mongo setup is set to true

### ISSUE THREAD

**Issue by tahahasancomo** [thepirat000/Audit.NET#537]
**Describe the bug**
The datetime values were serialized as "string" instead of ISO datetime object in mongodb. We followed this fix from this link :https://github.com/thepirat000/Audit.NET/issues/457 and then datetime values were getting saved as ISO datetime which we wanted.
Now here is the problem. We have more than millions of mongo records saved in camelcase convention. We even have specified camecase naming convention in JSON serialization options settings in audit mongo setup. Still camecase names are not getting set for property names. This is happening after applying the fix.
Please note that before applying the fix from https://github.com/thepirat000/Audit.NET/issues/457, datetimes were getting saved as strings(wrong) but property names were getting saved as camel case ! 

See property convention before applying SerializeAsBson setting :-
![image](https://user-images.githubusercontent.com/110379240/197308126-192e68f2-cc3d-493a-9982-bc9d7dfc2a5e.png)

See property convention after applying SerializeAsBson setting :-

![image](https://user-images.githubusercontent.com/110379240/197308105-1850992f-70f8-4ab5-a90d-16062aee1eda.png)

**To Reproduce**
This is our code at startup=>

```
 JsonSerializerOptions options = new JsonSerializerOptions
                    { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, WriteIndented = true }; 
                Audit.Core.Configuration.JsonSettings = options;
                
                Audit.Core.Configuration.Setup()
                    .UseCustomProvider(new CustomMongoDbProvider(c => c
                        .ConnectionString(HubEnvironmentVariables.MongoConnectionString)
                        .Database(HubEnvironmentVariables.MongoDatabase)
                        .Collection("auditEvents")
                        SerializeAsBson(true)
                    ));

public class CustomMongoDbProvider : Audit.MongoDB.Providers.MongoDataProvider
    {
        public CustomMongoDbProvider(Action<IMongoProviderConfigurator> config) : base(config) {}
        public override object Serialize<T>(T value)
        {
            if (value is DateTime dt)
                return new BsonDateTime(dt);
            return base.Serialize(value);
        }
 }
```

**Expected behavior**
After applying the fix from the link specified, dates should be saved as ISODatetime object as well as the naming convention of properties should be camelcase as specified in json serialization option settings.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.WebApi.Core: 17.0.4
 - Audit.Net.MongoDB.Core: 20.0.0

**Target .NET framework:**
 - .NET Standard 6

**Comment by thepirat000** [comment]
Note that setting the JsonSerializerOptions has no effect when using SerializeAsBson:

https://github.com/thepirat000/Audit.NET/blob/163cf631f7a39faa47afbe81cf56093c21517259/src/Audit.NET.MongoDB/Providers/MongoDataProvider.cs#L191-L199

You should configure the mongo DB driver via a ConventionPack, for example:

```c#
ConventionRegistry.Register("Camel case convention", new ConventionPack()
{
    new CamelCaseElementNameConvention()
}, _ => true);
```

Note this should be executed before any connection is open

**Comment by tahahasancomo** [comment]
Thanks for your reply. It worked for all property names except "Action" property name.

![image](https://user-images.githubusercontent.com/110379240/197478587-387b70f4-f7f5-4f82-a9aa-033e4771fe90.png)

This is the code that we are using for naming convention. We only wanted audit log collection to have camecase naming convention only. So we only applied for "Audit.Core" namespace.
Please let us know how we can apply camel case convention for "Action" property name and all the properties inside that Bson.
Thanks.


```
ConventionRegistry.Register("Camel case convention", new ConventionPack()
       {
           new CamelCaseElementNameConvention(),
       }, t => t.Namespace.StartsWith("Audit.Core"));
```

**Comment by tahahasancomo** [comment]
Thanks. It worked !
