### ISSUE TITLE
Audit.WebApi ConfigurationApi `serializeActionParameters` non-configurable in global filter

### ISSUE THREAD

**Issue by nesterenko-kv** [thepirat000/Audit.NET#538]
There're no way to configure `_serializeActionParameters` field:
https://github.com/thepirat000/Audit.NET/blob/14c754cd63616fe126ea0da1470776f4376bdf12/src/Audit.WebApi/ConfigurationApi/AuditApiGlobalConfigurator.cs#L29

**Comment by thepirat000** [comment]
this was fixed on version 20.0.2, please upgrade your references and re-test

**Comment by nesterenko-kv** [comment]
Thanks
