### ISSUE TITLE
How to dispose created DbContext in EntityFrameworkDataProvider?

### ISSUE THREAD

**Issue by mannok** [thepirat000/Audit.NET#539]
```
            Audit.Core.Configuration.Setup().UseFactory(() => new EntityFrameworkDataProvider()
            {
                DbContextBuilder = ev => applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<WebDbContext>(),    // this line
                ExplicitMapper = ee => typeof(AuditEntry),
                AuditEntityAction = (evt, entry, auditEntity) =>
                {
                    var a = (AuditEntry)auditEntity;
                    a.Id = 0;
                    a.AuditDate = DateTime.UtcNow;
                    a.EntityType = entry.Table;

                    return Task.FromResult(true); // return false to ignore the audit
                }
            });
```

Please take the above code into consideration. Since this construction code will be called every time when a high level auditing take place. Without automatically disposal of such DbContext, it will lead to idle connection. May I know that how to control the lifetime of the connection?

**Comment by thepirat000** [comment]
You're completely right, if you provide a factory for the DbContext it won't be disposed.
Maybe adding a new setting to specify if the audit db context should be disposed after the audit operation.

**Comment by thepirat000** [comment]
I mean something like this;

```c#
Audit.Core.Configuration.Setup().UseFactory(() => new EntityFrameworkDataProvider()
{
    DbContextBuilder = ev => applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<WebDbContext>(),    
    DisposeDbContext = true,  // <-- Adding this line
    ExplicitMapper = ee => typeof(AuditEntry),
    ...
});
```

Or using the fluent API:

```
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => applicationBuilder.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<WebDbContext>())
        .DisposeDbContext()
        ....);
```

**Comment by mannok** [comment]
Hi @thepirat000 

Good one. Thanks so much for your effort!

**Comment by thepirat000** [comment]
The new `DisposeDbContext` setting was added on version 20.0.3, please upgrade your references and re-test

**Comment by mannok** [comment]
> The new `DisposeDbContext` setting was added on version 20.0.3, please upgrade your references and re-test

@thepirat000 Thank you so much for your prompt action. The most efficient maintainer I have ever seen.
