### ISSUE TITLE
Error on context.SaveChanges()

### ISSUE THREAD

**Issue by lincolnqjunior** [thepirat000/Audit.NET#55]
Hello, I'm stuck on this error trying to save my entity with the library:

`   em System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   em EntityKeyHelper.GetMapping(Type type, DbContext context)
   em EntityKeyHelper.GetColumnName(Type type, String propertyName, DbContext context)
   em Audit.EntityFramework.DbContextHelper.GetChanges(DbContext dbContext, DbEntityEntry entry)
   em Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
   em Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
   em Audit.EntityFramework.AuditIdentityDbContext`1.SaveChanges()
   em Stock.Data.Repositories.TransacaoRepository.ResolveTransaction(Boolean updateAveragePrice, Transacao[] transactions) na C:\Projetos\palm-stock\Palm.Stock\Stock.Data\Repositories\TransacaoRepository.cs:linha 99`

Thanks in advance for this wonderful job on auditing items, it's a time saver for us debuggin' things ;)

**Comment by thepirat000** [comment]
Hi, thanks for your comments.

Unfortunately with the information provided I cannot tell what could be happening.

Are you using any kind of inheritance on your model classes?
Does this happens when you modify a particular model class, or any?
Can you provide a minimal test code including the model classes having problems?

**Comment by lincolnqjunior** [comment]
Sorry about that...

I can send my configurations classes, if it helps:

**Startup.cs**
```c#
Audit.Core.Configuration.Setup()
                .UseSqlServer(connectionString: conn, lastUpdatedDateColumnName: "LastUpdatedDate", tableName: "Events");
```

**MyEntities.cs**
```c#
[AuditDbContext(Mode = AuditOptionMode.OptOut, IncludeEntityObjects = false, AuditEventType = "AUDIT:{database}")] 
public class Entities : Audit.EntityFramework.AuditIdentityDbContext<ApplicationUser>{}
```

**Transaction.cs**
```c#
public class Transacao : BaseEntity
    {
        public virtual ContaPalm Conta { get; set; }
        public DateTime TimeStamp { get; set; }
        public decimal Valor { get; set; }
        public decimal Saldo { get; set; }
        public Movimentacao Movimentacao { get; set; }
        public TipoMovimentacao TipoMovimentacao { get; set; }
        public string Memo { get; set; }
        public string OrigemDestino { get; set; }
        public decimal PrecoUnitario { get; set; }
        public string Usuario { get; set; }
        public string Controle { get; private set; }
}
```

**BaseEntity.cs**
```c#
public class BaseEntity
    {
        public virtual int Id { get; set; }
        public virtual bool FoiExcluido { get; set; }
    }
```

**TransacaoRepository.cs**
```c#
public void ResolveTransaction(bool updateAveragePrice = true, params Transacao[] transactions)
        {          
            lock (lockDeposit)
                lock (lockWithdrawal)
                {
                    try
                    {
                        foreach (Transacao t in transactions)
                        {
                            var last = GetLastTransaction(t.Conta.Prefixo, t.Conta.Sufixo);

                            if (CheckDuplicity(last, t)) continue;

                            if (t.Movimentacao == Movimentacao.Entrada && updateAveragePrice)
                                UpdateCostAverage(t, last.Saldo);

                            UpdateBalance(t, last.Saldo);
                            Add(t);                        
                        }

                        DbContext.SaveChanges(); // <-- THE ERROR HAPPENS HERE
                    }
                    catch (Exception ex)
                    {
                        throw ex;
                    }
                }
        }
```

All we wanna do, is to use audit with SQL Server, with the basic configuration.
There is something else that you need?

**Comment by thepirat000** [comment]
It's still hard to tell, sorry...

You should share the code where you're updating or modifying the entities.
What are you doing on UpdateCostAverage and UpdateCostAverage? 

This will be harder to do, but an alternative to temporarily debug will be to clone or download the Audit.NET repository and add it to your solution. Then run your program.
This will tell you exactly where it is failing, because from your exception message, we only know that a `.Single()` call is failing, but that method has many calls like that.

**Comment by lincolnqjunior** [comment]
Yeah, sure...

I will prepare a Unit test mocking these calls and adding the project as a reference, to see what is really happening. I will update you with the root cause and if I could work with you to solve the issue.

Thanks in advance.

**Comment by thepirat000** [comment]
Any update on this or can I close this issue?

**Comment by lincolnqjunior** [comment]
Sorry, I missed the time to do it because of other project.

You can close, but I'll let you know when change back to track

Em sex, 4 de ago de 2017 às 18:09, Federico Daniel Colombo <
notifications@github.com> escreveu:
