### ISSUE TITLE
Any examples in projects with multiple layers?

### ISSUE THREAD

**Issue by myersBR** [thepirat000/Audit.NET#552]
Any examples in projects with multiple layers? The scope needs to be created in the presentation layer, but the object to be monitored will be defined in another layer. Currently, when I do this, a new scope is created and the properties referring to the authenticated user are not generated in the event.

**Comment by thepirat000** [comment]
Maybe https://github.com/erossini/AuditNetWebApi 
If it doesn't help please provide more information on what have you tried so far,

**Comment by myersBR** [comment]
> Maybe https://github.com/erossini/AuditNetWebApi If it doesn't help please provide more information on what have you tried so far,

Unfortunately this example does not work for me. I have a project with a hexagonal architect, I need to access the scope within the Repository layer, for example, if I create a new scope it does not have the authentication information nor the information of the executed action.

**Comment by myersBR** [comment]
> Maybe https://github.com/erossini/AuditNetWebApi If it doesn't help please provide more information on what have you tried so far,

I managed to resolve.

I shared my IHttpContextAcessor through a CrossCutting layer and then I can get the audit scope through the command below.

ApiControllerExtensions.GetCurrentAuditScope(contextAccessor.HttpContext)

I'm going to implement an abstraction for this right in the dependency injection.
