### ISSUE TITLE
how to automatically ignore childaction in .net mvc

### ISSUE THREAD

**Issue by hlhxwithmj** [thepirat000/Audit.NET#554]
**Describe the bug**
If I call @Html.Action("GridView") as a child action to render dynamic content in my razor view, AuditAction.ActionName will be replaced with child action name not the real action name like "Index" thing.
Is this a bug or something? By labeling "GridView" child action as AuditIgnore

**Expected behavior**
Ignore child action automatically.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET.20.1.0
 - Audit.Mvc.20.1.0

**Target .NET framework:**
 - .NET Framework 4.5.1

**Comment by thepirat000** [comment]
Are you using MVC 5?
How are you setting up the audit in the controller/page model? can you share the code?

**Comment by hlhxwithmj** [comment]
> Are you using MVC 5? How are you setting up the audit in the controller/page model? can you share the code?

Yes, I'm using MVC5.
In DemoController.cs:
{
    public ActionResult Index(){}
    public PartialViewResult MyGridViewPartial(){}
}
In Demo/Index.cstml
{
    @Html.Action("MyGridViewPartial")
}
In browser, go to "http://localhost/Demo".
Then, I've got an output like ControllerName "Demo", ActionName "MyGridViewPartial".

**Comment by thepirat000** [comment]
Yes, it's a bug when you set up the `AuditAttribute` filter globally (or at the controller level) and ignore some of the controller methods (used as child actions) with `AuditIgnore`.

The MVC 5 engine will call the Action Filter method `OnResultExecuted()` in a way that is not possible to get the originating method.

You can see the issue described here:
- https://stackoverflow.com/questions/21566756/need-to-get-the-action-attributes-from-onresultexecuted
- https://stackoverflow.com/questions/17852416/filtercontext-for-actionresult-in-onresultexecuted-method-of-asp-net-mvc

A workaround could be to mark with `AuditAttribute` **only** those action methods that need auditing.

I still need to think a little bit more about this, but I guess another solution could be to provide a new configuration parameter to the attribute like `[AuditAttribute(IncludeChildActions = false)]` to allow ignoring the child actions. 
With this, you could set the attribute to the entire controller (or globally) and it will not log any results from the child actions.

**Comment by thepirat000** [comment]
`IncludeChildActions` was added on version 20.1.1, please upgrade your references and re-test

```c#
[Audit(IncludeChildActions = false)]
public class YourController : Controller
{
}
```

**Comment by hlhxwithmj** [comment]
Thanks, and it looks working great!

**Comment by hlhxwithmj** [comment]
This solution works fine when I get response from action like "Index". But it will be not that right when I call "POST" request from my partial view to refresh part of data even if having set the attribute on controller.

**Comment by thepirat000** [comment]
But AuditIgnore should work in that case, right?

**Comment by hlhxwithmj** [comment]
> But AuditIgnore should work in that case, right?

Yes, absolutely.

**Comment by thepirat000** [comment]
Did you try with AuditIgnore and is not working?

**Comment by hlhxwithmj** [comment]
AuditIgnore works well.
