### ISSUE TITLE
Support for ASP.NET MVC Core with full dotNet framework

### ISSUE THREAD

**Issue by schalkvanwyk** [thepirat000/Audit.NET#56]
Hi

Adding Audit.MVC to ASP.NET Core using the full dotNet framework > 4.5 does not register the "AuditAttribute" action filter. It seems that the correct action filter is not available since the "AuditAttribute" class requires "NETSTANDARD1_6".

It works when I add the "AuditAttribute" class to my project and remove the "NETSTANDARD1_6" conditional compiler directive.

Thanks for a great library

**Comment by thepirat000** [comment]
It should work for the full framework, there are two version of AuditAttribute, [one](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.Mvc/AuditAttribute.Core.cs) for core and [one](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.Mvc/AuditAttribute.cs) for the full framework.

Can you share your _project.json_ dependencies and frameworks?

I'm pasting a project.json of an asp.NET core project targeting full framework 4.6.1:

```
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Audit.Mvc": "7.1.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

**Comment by thepirat000** [comment]
oh, I think I've found the bug.

Since ASP.NET Core have merged the MVC and WebApi into one single Api, starting from full framework 4.5.1 we should reference the Microsoft.AspNetCore.* instead of Microsoft.AspNet.*

Will provide a fix soon.

Please share your project.json or at least tell me which version of the full framework are you targeting.

**Comment by thepirat000** [comment]
Please try again with library version >= 7.1.1

Now when targeting the full framework >= 4.5.1, it will use the unified AspNetCore API (Microsoft.AspNetCore.*)
And when targeting the full framework <= 4.5, it will use the old AspNet API (Microsoft.AspNet.*)

Feel free to re-open is you're still having problems with the new version.

**Comment by schalkvanwyk** [comment]
Cool. Thanks it's working.
