### ISSUE TITLE
Update 20.1.3 --> 20.1.4 downgrades EntityFrameworkCore 

### ISSUE THREAD

**Issue by bertzor** [thepirat000/Audit.NET#568]
Is there a reason why the latest version downgrades EntityFrameworkCore from 7.0.2 to 6.0.0?

 - Audit.NET.SqlServer 20.1.4

**Comment by thepirat000** [comment]
Audit.NET.SqlServer is still referencing EF Core 6 and never had a dependency on EF Core 7.

Are you experiencing any particular problems?

**Comment by thepirat000** [comment]
The newer version 20.1.5 is targeting .NET 7.0 and EF Core 7, please upgrade your references and re-test

**Comment by bertzor** [comment]
Ty this fixed the issue
