### ISSUE TITLE
Output to a network?

### ISSUE THREAD

**Issue by Oleg26Dev** [thepirat000/Audit.NET#57]
Is it possible to output log to a network (UDP)? as log4net can do it

**Comment by thepirat000** [comment]
great idea!

Will think on it a little bit and maybe start working on something

**Comment by thepirat000** [comment]
I have implemented a first version of an UDP packet provider for Audit.NET.

Please take a look:
https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.Udp

**Comment by Oleg26Dev** [comment]
Fast! 
Thanks, will try.
By the way, I use Log2Console to view logs sent via UDP.
