### ISSUE TITLE
How to ignore ActionParameters in the Audit Trail data?

### ISSUE THREAD

**Issue by santoshpatro** [thepirat000/Audit.NET#571]
Hi Daniel,
Thanks a lot for a great library along with good documentation aligned to specific scenarios. This is one of the best libraries I have used. I have implemented it in a asp.net core 3.1 web api project with the recommended approach : Middleware + Action Filters (Asp.Net Core): Adding the Audit Middleware together with the Global Action Filter (or Local Action Filters).

I have the following sample output:

{  
   "EventType":"POST Values/Post",
   "Environment":{  
      "UserName":"Federico",
      "MachineName":"HP",
      "DomainName":"HP",
      "CallingMethodName":"WebApiTest.Controllers.ValuesController.Post()",
      "AssemblyName":"WebApiTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
      "Culture":"en-US"
   },
   "StartDate":"2017-03-09T18:03:05.5287603-06:00",
   "EndDate":"2017-03-09T18:03:05.5307604-06:00",
   "Duration":2,
   "Action":{  
      "TraceId": "0HLFLQP4HGFAF_00000001",
      "HttpMethod":"POST",
      "ControllerName":"Values",
      "ActionName":"Post",
      "ActionParameters":{  
         "value":{  
            "Id":100,
            "Text":"Test"
         }
      },
      "FormVariables":{  
      },
      "RequestUrl":"http://localhost:65080/api/values",
      "IpAddress":"127.0.0.1",
      "ResponseStatus":"OK",
      "ResponseStatusCode":200,
      "RequestBody":{  
         "Type":"application/json",
         "Length":27,
         "Value":"{ Id: 100, Text: \"Test\" }"
      },
      "ResponseBody":{  
         "Type":"SomeObject",
         "Value":{  
            "Id":1795824380,
            "Text":"Test"
         }
      },
      "Headers": {
        "Connection": "Keep-Alive",
        "Accept": "text/html, application/xhtml+xml, image/jxr, */*",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-GB",
        "Host": "localhost:37341",
        "User-Agent": "Mozilla/5.0, (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0), like, Gecko"
      }
   }
}

From the above output I want ActionParameters not to be captured as part of the Audit trail data. I have gone through the documentation but did not see any out of the box solution for it. Can you please help me to know how can this is achieved.

Thanks,
Santosh

**Comment by thepirat000** [comment]
Currently, the only way to avoid the parameters being captured in the event object is by marking those with `AuditIgnoreAttribute`. Still, you can remove the parameters from the event object before saving the scope, by using a [custom action](https://github.com/thepirat000/Audit.NET#custom-actions).

For example:

```c#
// On your start-up code
using Audit.WebApi;

Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    scope.GetWebApiAuditAction().ActionParameters = null;
});
```

**Comment by thepirat000** [comment]
And thanks for the good comments about this library. I wish I could have it better documented, but since English is not my native language and I do it for free, sometimes it's hard to find the time to improve the documentation.
