### ISSUE TITLE
Audit.EntityFramework keeps creating new json file after incorrect password login

### ISSUE THREAD

**Issue by fgjorgjievski** [thepirat000/Audit.NET#573]
I am using Identity Server 4 and .NET Core 3.1.
When I am trying to login an admin user with incorrect password everytime json file is created in the root of Identity Server with this content in it
` "EventType": "ApplicationDbContext",
    "Environment": {
        "UserName": "IdentityServer AppPool",
        "MachineName": "DESKTOP-RFMEPKO",
        "DomainName": "IIS APPPOOL",
        "CallingMethodName": "Audit.EntityFramework.DbContextHelper+<CreateAuditScopeAsync>d__31.MoveNext()",
        "AssemblyName": "Audit.EntityFramework.Core, Version=16.2.1.0, Culture=neutral, PublicKeyToken=------",
        "Culture": "en"
    },
    "StartDate": "2023-02-21T14:06:38.6673651Z",
    "EndDate": "2023-02-21T14:06:38.757229Z",
    "Duration": 90,
    "EntityFrameworkEvent": { .... Removed for clarity`.

Here are my Audit configurations in Startup.cs

`
Audit.Core.Configuration.Setup()
                .UseEntityFramework(_ => _
                    .AuditTypeMapper(t => typeof(AuditLog))
                    .AuditEntityAction<AuditLog>((ev, entry, entity) =>
                    {

                        entity.AuditData = entry.ToJson();
                        entity.EntityType = entry.EntityType.Name;
                        entity.AuditDate = DateTime.Now;
                        entity.TablePk = entry.PrimaryKey.First().Value.ToString();
                        entity.AuditAction = entry.Action;
                        entity.AuditInternalUser = ev.CustomFields["audit_internal_user"]?.ToString();
                        entity.AuditCompanyUser = ev.CustomFields["audit_company_user"]?.ToString();
                    })
                    .IgnoreMatchedProperties(true));

            Audit.Core.Configuration.AddOnSavingAction(scope =>
            {
                var efEvent = scope.GetEntityFrameworkEvent();

                //Do not log failed DB commands
              
                if (!efEvent.Success)
                {
                    scope.Discard();
                }
                else
                {
                    // Remove entries for not included tables
                    var notIncluded = Enum.GetNames(typeof(AuditLogIgnoredTables));
                    efEvent.Entries.RemoveAll(e => notIncluded.Contains(e.Table));

                    // Completely discard the event if there are no entries left
                    if (efEvent.Entries.Count == 0)
                    {
                        scope.Discard();
                    }

                    foreach (var entry in efEvent.Entries)
                    {
                        if (entry.Action == "Update")
                        {

                            // Check all columns for GEOMETRY, if geomertry serilize with custom serializer
                            foreach (var change in entry.Changes)
                            {
                                if (change.OriginalValue is NetTopologySuite.Geometries.Geometry)
                                {
                                    change.OriginalValue = Models.Helpers.GeoJsonHelpers.GeometryToGeoJson((NetTopologySuite.Geometries.Geometry)change.OriginalValue);
                                    change.NewValue = Models.Helpers.GeoJsonHelpers.GeometryToGeoJson((NetTopologySuite.Geometries.Geometry)change.NewValue);
                                }
                            }

                            foreach (var columnValue in entry.ColumnValues)
                                entry.ColumnValues.Remove(columnValue);
                        }

                        // Check all columns for GEOMETRY, if geomertry serilize with custom serializer
                        var tempList = entry.ColumnValues.ToList(); //thread "safe" list

                        foreach (var colValue in tempList)
                        {
                            if (colValue.Value is NetTopologySuite.Geometries.Geometry)
                            {
                                entry.ColumnValues[colValue.Key] = Models.Helpers.GeoJsonHelpers.GeometryToGeoJson((NetTopologySuite.Geometries.Geometry)colValue.Value);
                            }
                        }

                    }

                }
            });
`

**Comment by thepirat000** [comment]
I guess what's happening is that your DbContext is executing an operation before your `Audit.Core.Configuration.Setup()` call, so the library is using the default data provider which is FileDataProvider and saves the audits to Json files.

**Comment by fgjorgjievski** [comment]
Yes, you are right
