### ISSUE TITLE
Microsoft.EntityFrameworkCore.DbUpdateException in Audit.EntityFramework.Core.dll

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#577]
**Describe the bug**
Encountering an error with Audit.EntityFramework.Core saving to the database. This happens sometimes, not sure what could be involved. I'm not able to see any additional information about the error, only that the error is in the Application Output pane in Visual Studio.

Here is the error:

> Exception thrown: 'Microsoft.EntityFrameworkCore.DbUpdateException' in Audit.EntityFramework.Core.dll

Do you have any suggestions on how to pinpoint the source of the error?

**To Reproduce**
It's possible that there is something going on in the database that gets in the way of Audit.EntityFramework.Core.

**Expected behavior**
Audit.EntityFramework.Core should be able to save to the database whenever it wants.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 20.1.6

**Target .NET framework:**
 - .net7.0

**Additional context**
This issue has been occurring occasionally since starting to use Audit.NET in 2020.

**Comment by thepirat000** [comment]
The information you provided is not enough. It could be or not related to the audit libary. Do you have the stack trace?

**Comment by mrlife** [comment]
I can try to reproduce and get a stack trace, however, the application doesn't halt when the exception is thrown, so it may be difficult to get the stack trace at the time of the exception.

Is there somewhere I should be able to try/catch to pinpoint when/where/why the exception is thrown?

**Comment by thepirat000** [comment]
If you can reproduce it in visual studio then you should be able to see the stacktrace if you stop on any exception

![image](https://user-images.githubusercontent.com/9836380/222815612-1a064d99-3610-4b70-8a96-76bace9822c3.png)

**Comment by mrlife** [comment]
Thanks, I found and turned on a setting (Visual Studio for Mac) that allows the debugger to step into external code, such as in nuget packages. I will post here when I have the stack trace and any other information I can get.

**Comment by mrlife** [comment]
Closing this out with the expectation the issue is something else. Thanks for your replies, as always.
