### ISSUE TITLE
Add Audit.SignalR support for ASP.NET Core

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#578]
Looking over the [Audit.SignalR readme](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.SignalR/README.md), there is the note about it not working with ASP.NET Core.

Following the [linked issue](https://github.com/aspnet/SignalR/issues/924), it looks like the needed support may have been added: https://github.com/dotnet/aspnetcore/issues/5353

If so, please consider adding Audit.SignalR support for ASP.NET Core.

**Comment by thepirat000** [comment]
Support for SignalR Core was added in version 20.2.0, please upgrade your references and re-test.

Note you must target .NET ≥ 7.0

**Comment by mrlife** [comment]
Thank you! I'm looking forward to trying it out.
