### ISSUE TITLE
Yet another Extensions?

### ISSUE THREAD

**Issue by Oleg26Dev** [thepirat000/Audit.NET#58]
Is it possible to add extensions for:

PostgreSQL?
Redis?

**Comment by thepirat000** [comment]
You are asking too much 😄 
But I will work on a Redis extension.

**Comment by Oleg26Dev** [comment]
Yes, you are right, too much. 
But time files and life too short;-)

**Comment by thepirat000** [comment]
I have just created a configurable Redis provider to store the audits as Redis Strings, Lists, Hashes, SortedSets or even publishing them to a PubSub channel.

Project: https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.Redis
Nuget: https://www.nuget.org/packages/Audit.NET.Redis/

I'm closing this issue.

Please feel free to open a new issue if you are having problems with the redis provider, and also you could create a new one for the PostgreSQL extension.

**Comment by Oleg26Dev** [comment]
great! thank you

**Comment by thepirat000** [comment]
Reopening this since I'm working on a simple Postgres provider

**Comment by thepirat000** [comment]
Also created a configurable PostgreSQL data provider.

Project: https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.NET.PostgreSql
Nuget: https://www.nuget.org/packages/Audit.NET.PostgreSql/
