### ISSUE TITLE
.NET Framework + Audit.NET.SqlServer + Microsoft.Data.SqlServer

### ISSUE THREAD

**Issue by reb3lzrr** [thepirat000/Audit.NET#581]
Hello,

We've been happly using Audit.WebApi to register who had access to which information in a corporate environment. There is this legacy-monolithic application which targets .NET framework 4.7.2, is hosted within Azure and uses a Azure Sql Database. 
We've been working hard to move towards a microservice-architecture. However, the reality is that this monolith will be around for atleast a few more years before it'll be completely rewritten.

To make this monolith more managable, I've been trying to upgrade many parts of the application. This includes using the `Microsoft.Data.SqlServer` to leverage new features such as Azure Active Directory authentication.

When used within .NET Framework, Audit.NET.SqlServer uses the types in `System.Data.SqlClient` namespace to write the data to the SqlServer. When using `Audit.NET.SqlServer` in conjunction with `Microsoft.Data.SqlClient.SqlConnection` an exception is thrown:
```
The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.
``` 

**My feature request is this:**
_When used within .NET Framework (4.6.2+), let Audit.NET.SqlServer use types within the `Microsoft.Data.SqlClient`-namespace to perform database tasks. This will allow legacy applications, such as the one we have, to leverage new features such as Azure Active Directory authentication._

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.WebApi: 20.2.0
 - Audit.NET.SqlServer: 20.2.0
 - Audit.NET: 20.2.0

**Target .NET framework:**
 - .NET Framework 4.7.2

**Comment by thepirat000** [comment]
This was added in version 20.2.1, please upgrade your references and re-test

**Comment by reb3lzrr** [comment]
I can confirm that your change had the desired effect and can be resolved.

Thanks for the effort!
