### ISSUE TITLE
Override feature doesn't work.

### ISSUE THREAD

**Issue by Li7ye** [thepirat000/Audit.NET#584]
**Describe the bug**

When call `AuditTypeNameMapper` method,  `IContextEntitySetting.Override` feature doesn't work. 

**To Reproduce**
refer to attachment(code).

**Expected behavior**
Override feature can work for `AuditTypeNameMapper` method.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 20.2.2

**Target .NET framework:**
 - .NET 6.0

[OverrideDontWork.zip](https://github.com/thepirat000/Audit.NET/files/10988941/OverrideDontWork.zip)

**Comment by thepirat000** [comment]
Thank you for providing the sample projects to reproduce the issues, that's really helpful.

This was fixed in version 20.2.3, please upgrade your references and re-test

**Comment by Li7ye** [comment]
It's working now. Thanks.
