### ISSUE TITLE
EventEntry.EntityType is null

### ISSUE THREAD

**Issue by Li7ye** [thepirat000/Audit.NET#585]
**Describe the bug**
When call `EntityFrameworkDataProvider.InsertEvent` method and has explicit map. `EventEntry.EntityType` will be null. But  `EntityFrameworkDataProvider.InsertEventAsync` is working.

**To Reproduce**
refer to attachment. 

**Expected behavior**
`EventEntry.EntityType` is not null.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 20.2.2

**Target .NET framework:**
 - .NET 6

[EntityTypeIsNull.zip](https://github.com/thepirat000/Audit.NET/files/10988963/EntityTypeIsNull.zip)

**Comment by thepirat000** [comment]
Again, thank you for providing the sample project!

This was fixed in version 20.2.3, please upgrade your references and re-test

**Comment by Li7ye** [comment]
It's working now. Thanks.
