### ISSUE TITLE
ElasticSearch provider create json file in working directory

### ISSUE THREAD

**Issue by ScaoDevTeam** [thepirat000/Audit.NET#594]
**Describe the bug**
We are using Audit.net with elastic search provider, everythings works fine but audit.net still create json file in working directory

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.net: 20.2.4
 - Audit..net.elasticsearch: 20.2.4

**Target .NET framework:**
For example:
 - .NET core 7

**Comment by thepirat000** [comment]
Can you share the code to reproduce this? Or share your audit configuration

**Comment by ScaoDevTeam** [comment]
I miss to tell you that i'm using entityframework core extension.

Hi, more info after some debugging:
- Error occurs only if i use the inheriting from **AuditDbContext** my data contex class.
- Json files are created only on application boot

I configure the global Audit global setup into Startup.cs  like this

```c#
 Audit.Core.Configuration.Setup()
                    .UseElasticsearch(config => config
                        .ConnectionSettings(new Uri("http://localhost:9200")
                       )
                    .Index(auditEvent => $"audit_db_{auditEvent.GetEntityFrameworkEvent().Entries.First().Action}".ToLower())
                    .Id(ev => Guid.NewGuid()));
``` 

If I remove the inherited strategy and setting up Audit during setups like this, every things seems work fine  😃 
```c#
 
                Audit.EntityFramework.Configuration.Setup()
                    .ForContext<RepositoryContext>(config => config.IncludeEntityObjects())
                    .UseOptOut()
```

**Comment by thepirat000** [comment]
can you share your DbContext class when it inherits from AuditDbContext? Are you overriding the SaveChanges method?

**Comment by ScaoDevTeam** [comment]
I simply inheritd the class, no override of Savechanges or others base class methods.

You said 

> Note the audit saving to json files is the default behavior until you call Audit.Core.Configuration.Setup() or until you set a different data provider instance to the Audit.Core.Configuration.DataProvider property

Does this make sense because with dependency injection (and the dbContext used ad server) I have not total control of the order wich the object will be instantiated.

Probably in this scenario the best practise configure Audit.NET in Setup.cs and not user inherit or override strategy

```c#
 public class RepositoryContext : AuditDbContext
    {

        public RepositoryContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Machine> Machines { get; set; }
        public DbSet<MachineDetailKey> MachinesDetailKeys { get; set; }
        public DbSet<MachinesGroup> MachinesGroup { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<ActualParameter> ActualParameters { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<Revision> Revisions { get; set; }
        public DbSet<RecipeKey> RecipeKeys { get; set; }
        public DbSet<RecipeKeyValue> RecipeKeyValues { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Session> Sessions { get; set; }
        public DbSet<MachineSendHistory> MachineSendHistory { get; set; }
        public DbSet<UnitMeasure> UnitMeasures { get; set; }

        public DbSet<SetupStage> SetupStages { get; set; }
        public DbSet<SetupParameter> SetupParameters { get; set; }
    }
```

**Comment by ScaoDevTeam** [comment]
Using inherits from AuditDbContext works if Audit.net configuration will be called in Program.Main() from Program.cs of .net core api web solution.

**Comment by thepirat000** [comment]
Ok, so this doesn't seem to be a bug, it's the DbContext executing operations before your audit data provider being set. I wonder what kind of events are logged to the .json files, maybe EF executing migrations?

**Comment by ScaoDevTeam** [comment]
In the json file i found log concerning early start operations like session users anche login actions made from client always on
