### ISSUE TITLE
Support CancellationToken on all async methods

### ISSUE THREAD

**Issue by zidad** [thepirat000/Audit.NET#597]
Maybe for a new major version, every async method should also have a corresponding CancellationToken

**Comment by thepirat000** [comment]
yes, I think the most painful will be the DataProvider async methods that will break any custom data provider

**Comment by thepirat000** [comment]
CancellationToken support was added in version 21.0.0, please upgrade your references and re-test

**Comment by zidad** [comment]
That's quite the PR. many thanks!
