### ISSUE TITLE
Working with Blob Object(Like Image or Long Length String)

### ISSUE THREAD

**Issue by MAliM1988** [thepirat000/Audit.NET#6]
Hi I'm Using Audit.EntityFramework with Custom Storage provider for Sql Server,How Can I Audit Image or Long Length String?

**Comment by thepirat000** [comment]
Please provide more information.. What do you want to audit? where are the images and strings and how they are changed?

**Comment by MAliM1988** [comment]
My Entity Has a Property with byte[] data type for saving image in to Sql Server,on my Owne Storage Provider When i'm calling

var json = new SqlParameter("json", auditEvent.ToJson());

That Json Is Completely Generate but when Is Save On Database json is 	
incorrect and not usable because of image file,the Data column in Sql Server is Overflow.

i'm convert byte of array to string and convert image to base64 for saving data in SQL as string (nvarchar(max)) but The problem still exists Data column in Sql Server is Overflow

my sql server version in 2014 ent

**Comment by thepirat000** [comment]
Do you need to store the images on the Audit table? You should probably avoid saving the images on the Audit table. 

If your images are on an isolated entity, you could use the `AuditIgnore` attribute. See [this](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#settings).

An alternative could be to override the `OnScopeSaving` on your `AuditDbContext` and explicitly remove the image data. See [this](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#overrides).

For example:
```c#
using Audit.EntityFramework;
...
protected override void OnScopeSaving(AuditScope auditScope)
{
    foreach(var entry in auditScope.Event.GetEntityFrameworkEvent().Entries)
    {
        if (entry.Table == "images_table") 
        {
            entry.ColumnValues.Remove("image_column");
        }
    }
}
```

The same can be done via a [Custom Action](https://github.com/thepirat000/Audit.NET#custom-actions).

**Comment by MAliM1988** [comment]
Hi Thank for Your Suggestion
My Problem Has Solved with

using Audit.EntityFramework;

public class YourContext : AuditDbContext
{
    protected override void OnScopeSaving(AuditScope auditScope)
    {
        foreach(var entry in auditScope.Event.GetEntityFrameworkEvent().Entries)
        {
            if (entry.Table == "images_table") 
            {
                entry.ColumnValues.Remove("image_column");
            }
        }
    }
}
