### ISSUE TITLE
Exclude auth headers on demand

### ISSUE THREAD

**Issue by Adrian-Sevan** [thepirat000/Audit.NET#60]
Great library. It would be nice if you could set a flag on the Audit Attributes (Web.Api, MVC) to exclude the AuthHeaders if any.

**Comment by thepirat000** [comment]
I think you can do that with [Custom Actions](https://github.com/thepirat000/Audit.NET#custom-actions).

For example:

```
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    var mvc = scope.Event.GetMvcAuditAction();
    mvc.Headers.Remove("Authorization");
});
```

The action passed to AddCustomAction will be executed for every event, before they are saved.

**Comment by Adrian-Sevan** [comment]
Thank you for the quick reply.
I ended up using a custom action like the one above.
I still think it would be more streamlined if there was a config to remove the Authorization.

Thank you again.
