### ISSUE TITLE
[AuditApi] - override middleware settings with controller attributes

### ISSUE THREAD

**Issue by SerhiyBalan** [thepirat000/Audit.NET#604]
Hello @thepirat000 

I'm trying to follow the middleware pattern ([AuditApi](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#3--middleware))

Platform: .NET 7, WebAPI

I setup Audit.WebApi.Core (21.00) like this:
```
applicationBuilder.UseAuditMiddleware(config => config
    .IncludeHeaders());
    .IncludeRequestBody()
    .IncludeResponseBody());
```

My test controller looks like this:

```
[AuditApi]
public class SampleController : ControllerBase
{
    [HttpGet]
    [AllowAnonymous]
    public Task<SomeModel> ([FromBody] SomeOtherModel model)
    {
        ...
    }
}
```

It works perfectly and logs in my SQL db (both request and response bodies as supposed)

But I have issues with overriding those values in controllers

I change my controller to

```
[AuditApi]
public class SampleController : BaseController 
{
    [HttpGet]
    [AllowAnonymous]
    [AuditIgnore]
    public Task<SomeModel> ([FromBody] SomeOtherModel model)
    {
        ...
    }
}
```

Audit.NET no more logs my request. Everything is ok here!

I change my controller to

```
[AuditApi]
public class SampleController : BaseController 
{
    [HttpGet]
    [AllowAnonymous]
    [AuditApi(IncludeResponseBody = false)]
    public Task<SomeModel> ([FromBody] SomeOtherModel model)
    {
        ...
    }
}
```

And... Audit.NET still logs my response! It ignores `IncludeResponseBody = false` :(
It begins respecting it only when I remove `IncludeResponseBody()` from middleware.

But I want to make response body logs everywhere except some places

So far the only workaround is to build complex middleware like

```
 .IncludeResponseBody(context =>
 {
    var logResponseBody = true;

    if (context.Request.Path == "/test")
    {
        logResponseBody = false;
    }

    // many other checks...

    return logResponseBody;
})
```

well, I not happy with this solution

So ideally I want approach # 4 as you mentioned: middleware + attributes.
But I can't achieve that fully.
Perhaps I'm missing something.

Thank you for any support

**Comment by SerhiyBalan** [comment]
I managed to find an another workaround

and it is kinda weird

```
[AuditApi]
public class SampleController : BaseController 
{
    [HttpGet]
    [AllowAnonymous]
    [return:AuditIgnore]
    [AuditApi(IncludeResponseBody = true)]
    public Task<SomeModel> ([FromBody] SomeOtherModel model)
    {
        ...
    }
}
```

so for some strange reason this combination works 
```
    [return:AuditIgnore]
    [AuditApi(IncludeResponseBody = true)]
```

and this one doesn't work
```
    [return:AuditIgnore]
    [AuditApi(IncludeResponseBody = false)]
```

**Comment by thepirat000** [comment]
The problem is that the configuration is independent between the AuditApiAttribute (filter) and the AuditMiddleware.

You're configuring the AuditApi filter not to log the response for that action, but the middleware will still log it since it has the IncludeResponseBody with no restrictions (`UseAuditMiddleware(_ => _.IncludeResponseBody())`)

On the other hand, the `AuditIgnoreAttribute` is globally used by both, the filter and the middleware.

I think you still have more options, one is including the logic to determine whether the response body should be logged by the audit middleware:

```
applicationBuilder.UseAuditMiddleware(config => config
	.IncludeResponseBody(ctx => !ctx.Request.Path.Value.Contains("/sample/action"))
	//...
);
```

Another option could be to exclude the response body from the audit event after it's created, but before it's saved with a custom action, I'm still checking to provide you with more examples

**Comment by SerhiyBalan** [comment]
@thepirat000 thank you very much for the tips!

Solutions 1 and 3 are not ideal for big projects. It is hard to maintain them if I use controller/action names as strings for filtering.

Solution 2 is a good one (with GetEndpoint).
It improves project maintainability a lot.
However, I decided to introduce two new attributes in my project: AuditIgnoreRequestAttribute and AuditIgnoreResponseAttribute.
For me, it is much easier to work with rather than working with the master attribute like [AuditApi(IncludeResponseBody = true)]

You can close this issue if you want
