### ISSUE TITLE
Compatible with netstandard1.6

### ISSUE THREAD

**Issue by Tabgyn** [thepirat000/Audit.NET#61]
Please add compatibility with .NETStandard version 1.6 for SqlServer

**Comment by thepirat000** [comment]
I don't remember why it's targeting netcoreapp instead of netstandard, will take a look, but please expect a delay.

**Comment by thepirat000** [comment]
Starting on version 7.1.3, you should be able to reference `Audit.SqlServer` from any NetStandard >= 1.3
