### ISSUE TITLE
Custom field empty in Entries Array

### ISSUE THREAD

**Issue by shubhamCedargate** [thepirat000/Audit.NET#611]
I am setting a custom field like this:

Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, async scope =>
{
  if (entry.ColumnValues != null)
  {
   if (entry.Table == "Patients")
      {
          var patientId = entry.ColumnValues["Id"] ?? string.Empty;
          scope.SetCustomField("patientId", patientId.ToString());
      }
  }
}

When doing this,
I get the custom fields in the entityFrameworkEvent node             
but get an empty JSON Object in each entry of the entries node.

Can I set custom fields for each entry of the entries node? 
( foreach (var entry in scope.Event.GetEntityFrameworkEvent()?.Entries) )

For reference, the output JSON looks like this:
{
    "entityFrameworkEvent": {
        "database": "DB",
        "connectionId": "bbbbbbbbbbbbb",
        "contextId": "aaaaaaaaaaaaaaaa",
        "entries": [
            {
                "table": "Patients",
                "name": "Patient",
                "primaryKey": {
                    "id": "111"
                },
                "action": "Update",
                "changes": [
                    {
                        "columnName": "Address",
                        "originalValue": "New York",
                        "newValue": "NY"
                    },
                    . . . 
                ],
                "columnValues": {
                    "id": "111",
                    . . .
                },
                "valid": true,
                "customFields": {}              // *****Custom fields here is empty here*****
            }
            // ***** I have many Entries here that need their own unique custom fields values *****
            ],
        "result": 43,
        "success": true,
        "customFields": { },  // Custom fields here is empty as well
    "eventType": "EF",
    "environment": {
        "userName": "Shubham.Pradhan",
        . . .
        "customFields": {}     // Custom fields here is empty as well
    },
    "customFields": {                    // ***** Custom fields is populated only here *****
        "user": "Shubham",
        "customField001": "Sync",
        "patientId": "111",
        "customField000": "3"
    },
    "startDate": "2023-06-26T02:06:14.4536551Z",
    "endDate": "2023-06-26T02:06:14.8113064Z",
    "duration": 358
}

Using :
Audit.EntityFramework.Core 21.0.1

EF save method:

  foreach (var patient in patients)
  {
      _db.Patients.Update(patient);
      //_db.BulkUpdate(patients);

      var patientOrders = patient.patientOrders;
      foreach (var patientOrder in patientOrders) {
          _db.patientOrders.Update(patientOrder);
      }
  }
  await _db.SaveChangesAsync();

**Comment by thepirat000** [comment]
Please share a complete code that compiles, I don't understand what's 'entry' here

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, async scope =>
{
if (entry.ColumnValues != null)
```

Are you introducing a closure? Whats the action you are exciting and what are you expecting to be logged?

**Comment by shubhamCedargate** [comment]
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, async scope =>
{
    try
    {
        if (scope != null)
        {
            var claimsUser = ClaimsPrincipal.Current;
            var fullName = claimsUser?.Identity?.Name;
            scope.SetCustomField("user", string.IsNullOrEmpty(fullName) ? "" : fullName);
        }
        foreach (var entry in scope.Event.GetEntityFrameworkEvent()?.Entries)
        {
            // Fix Primary Key properties
            if (entry.PrimaryKey != null)
            {
                foreach (var pkKey in entry.PrimaryKey.Keys.ToList())
                {
                    entry.PrimaryKey[pkKey] = entry.PrimaryKey[pkKey].ToString();
                }
            }
            //// Fix ColumnValues properties
            if (entry.ColumnValues != null)
            {
                var lastSourceOfModification = entry.ColumnValues["LastSourceOfModification"] ?? string.Empty;
                scope.SetCustomField("lastSourceOfModification", lastSourceOfModification);
                if (entry.Table == "Patients")
                {
                    var patientId = entry.ColumnValues["Id"] ?? string.Empty;
                    scope.SetCustomField("patientId", patientId.ToString());
                }
            }
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Audit.Core.Configuration Error: {ex}");
    }
});



I needed to set Unique Custom Values for each Entry of the Entries node of the Output JSON.
I am getting a customFields inside the entries Json object but it is always empty there and only
has values in the outermost customFields  Json (inside the entityFrameworkEvent Json object only)

**Comment by thepirat000** [comment]
The scope.SetCustomField will override a custom field in the base AuditEvent.

But the entry has its own custom fields property.

Instead of:

```c#
scope.SetCustomField("lastSourceOfModification", lastSourceOfModification);
```
Do:

```c#
entry CustomFields["lastSourceOfModification"] = lastSourceOfModification;
```
