### ISSUE TITLE
Limited configuration of MongoDB provider

### ISSUE THREAD

**Issue by MiniaczQ** [thepirat000/Audit.NET#614]
MongoDB provider should expose API to provider the entire `MongoDB.Driver.MongoClientSettings` to allow things like TLS usage.

**Comment by thepirat000** [comment]
Version 21.0.3 includes support to provide the MongoClientSettings and MongoDatabaseSettings. Please upgrade your references and re-test.

For example:

```c#
Audit.Core.Configuration.Setup()
    .UseMongoDB(config => config
        .ClientSettings(new MongoClientSettings() 
        { 
            Server = new MongoServerAddress("localhost", 27017), 
            UseTls = true 
        })
        .Database("Audit")
        .Collection("Event"));
```
