### ISSUE TITLE
Unable to use EntityFrameworkCore when using full .net

### ISSUE THREAD

**Issue by danzel** [thepirat000/Audit.NET#62]
When you include Audit.NET in a project built using full .net you get the `AuditDbContext` built on `System.Data.Entity`, rather than `Microsoft.EntityFrameworkCore`.

https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/AuditDbContext.cs#L7-L14

I think I can move my DbContext out to another (.net standard) project and then nuget it in there to make it work, but it's not ideal.

Thanks for the great project :)

**Comment by thepirat000** [comment]
Thanks for your comments.

I could make the library use `EntityFrameworkCore` for the full .net framework, but I have two concerns:
- For someone wanting to use `System.Data.Entity` from the full framework, will need to use an old version of the library or cheat the package installer.
- Note that starting on version 2, `Microsoft.EntityFrameworkCore` does not support the full .net framework, just the NetStandard 2.0.

**Comment by danzel** [comment]
Maybe you could distribute two builds on nuget instead - Audit.EntityFramework and Audit.EntityFrameworkCore ?

I ported our project to .net core 2 to get around the issue, I still couldn't get it to work right just moving the Data parts to a .net standard library.

**Comment by thepirat000** [comment]
I've created the `Audit.EntityFramework.Core` package for that purpose. 

Feel free to re-open the issue if you're still having problems.
