### ISSUE TITLE
AuditIdentityDbContext is not working with Microsoft.AspNetCore.Identity.EntityFrameworkCore 2.0

### ISSUE THREAD

**Issue by dietrichha** [thepirat000/Audit.NET#63]
Hi,

first awesome work! I was just giving .Net Core 2.0 a test ride and found some problems with AuditIdentityDbContext. It seems that the namespaces have moved. 

Thanks

**Comment by thepirat000** [comment]
Thanks for your comments.

Please try again with version >= 8.0.0, I've added support for netstandard 2.0.

Re-open this issue if you're still having problems.
