### ISSUE TITLE
Best way to "Include" related entity properties 

### ISSUE THREAD

**Issue by AndreOGodoy** [thepirat000/Audit.NET#636]
Given this entity below:

```csharp
public class TitleValue
{
    public required string Title { get; set; }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public required int Value { get; set; }
}


public class Status : TitleValue { }

public class Unit : TitleValue {}

public class Entity
{
    public int Id { get; set; }

    public int? StatusValue { get; set; }
    public Status? Status { get; set; }
    
    public int? UnitValue { get; set; }
    public Unit? Unit { get; set; }
 }
```

How can I load `Unit` and `Status` inside `AuditEntityAction`?

I'm currently trying with this configuration below, but `entry.Entity` will bring an object with all those properties as `null`. This makes sense, I think, but so what's the best way to load those properties? I thought of loading the db context and querying all the info, but maybe there is some more practical way?

The final desired behavior is to log the `Title` of the `TitleValue`, instead of the numerical StatusValue, for example, for better logs :)

```csharp
Audit.EntityFramework.Configuration.Setup()
    .ForContext<MyContext>(config => config
        .IncludeEntityObjects()
    );

Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeMapper(t => typeof(AuditLog))
        .AuditEntityAction<AuditLog>((ev, entry, auditEntity) =>
            {
                auditEntity.ActionType = entry.Action;
                auditEntity.EntityType = entry.EntityType.Name;
                auditEntity.Date = DateTime.UtcNow;
                auditEntity.User = ev.CustomFields["UserName"]?.ToString() ?? "";
                auditEntity.OldValue = string.Join(", ", entry.Changes?.Select(c => c.OriginalValue?.ToString()) ?? new List<string>());
                auditEntity.NewValue = string.Join(", ", entry.Changes?.Select(c => c.NewValue?.ToString()) ?? new List<string>());
                auditEntity.TablePk = entry.PrimaryKey.First().Value.ToString();
            }
        )
        .IgnoreMatchedProperties(true)
    );
```

Thanks in advance! I'm new to this framework, so forgive me if I'm missing something obvious

**Comment by AndreOGodoy** [comment]
I tried that, but the object comes as `null`

![image](https://github.com/thepirat000/Audit.NET/assets/37941785/850d33b4-bda9-4b3a-a285-cbc979a557bf)

I found that if I `.Include(e => e.Status)` before calling `await context.SavesChangesAsync()`, it will load correctly! But, will this imply that I need to `Include` all sub-entities before? 

Could I somehow load the dbcontext inside the `AuditEntityAction`, and include as needed, to avoid loading tons of unrelated properties? If yes, how? I have an idea on how to implement the second part, but currently having problems instantiating the db context there

**Comment by thepirat000** [comment]
You can access the DbContext inside your custom action with 

```c#
.AuditEntityAction<AuditLog>((ev, entry, auditEntity) =>
{
    var dbContext = entry.GetEntry().Context;
    // ...
});
```

So I guess you could explicitly load the related entities with:

```c#
dbContext.Entry(entity).Reference(e => e.Unit).Load();
dbContext.Entry(entity).Reference(e => e.Status).Load();
```
