### ISSUE TITLE
Primary keys generated by the database are not written to the audit log

### ISSUE THREAD

**Issue by dietrichha** [thepirat000/Audit.NET#64]
Hi,

is there a cause that the Primary keys are gathered before the roundtrip to the database and not afterwards? Now I was getting keys with e.g -12312313. 

Cound't you just make a list of the tracked/changed entities and gather the properties after the roundtrip to the database? At the Moment you are gathering everthing just before the roundtrip. 

Thanks!

**Comment by thepirat000** [comment]
Please try again with the latest version. This should be fixed on version >= 8.1.0

Feel free to re-open this issue if you're still having problems.

**Comment by dietrichha** [comment]
Hi, 

perfect now for Primary keys. Thanks a lot. However, if you create two "connected" entities, the foreign keys get not updated. They are still e.g. -1123  . Perhaps the easyiest way would be to capture the entities completly after the roundtrip to the database. But I'm not sure if someone uses some Magic in between, to do something that would alter the variables, so that you would capture a different state of the entities compared to the one that was send to the database.

**Comment by thepirat000** [comment]
yes, there are some problems if we gather the entities after the savechanges 
do you have a minimal code sample to reproduce the foreign keys problem?

**Comment by dietrichha** [comment]
When you create a Blog and a Blogpost in one roundtrip to the database.

Blog.ID will be updated as it is the Primary key.

BlogPost.BlogID will not be updated, as it is a Foreign Key
BlogPost.ID will be updated correctly.

**Comment by thepirat000** [comment]
This was fixed on version 8.2.0, please try again with latest package.

Now the PKs and FKs values should be updated after the insert operation.

Feel free to re-open the issue if you're still having problems
