### ISSUE TITLE
How to audit entities that have been changed\deleted because of on cascade behavior?

### ISSUE THREAD

**Issue by WalrusPUNCH** [thepirat000/Audit.NET#645]
I am using Audit.EntityFramework.Core. Version="23.0.0." with PostgreSQL.

I have configured ` .OnDelete(DeleteBehavior.SetNull)` behavior for my foreign key. 

So, when I delete an entity that is referred to by a foreign key in other table I receive only deleted entity audit event in `.AuditEntityAction<AuditLog>((auditEvent, eventEntry, auditLog) => {}`. 

But I need to audit all changes, including those caused by `OnDelete` behavior.

Is there a way to make this possible?

code from DbContext:
 `modelBuilder.Entity<B>()
            .HasOne(x => x.A)
            .WithMany(x => x.Bs)
            .HasForeignKey(x => x.AId)
            .OnDelete(DeleteBehavior.SetNull);`

**Comment by thepirat000** [comment]
Please share your entire Audit.EF configuration

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(...
```

**Comment by WalrusPUNCH** [comment]
```
        services.AddDbContext<AuditContext>(x =>
        {
            x.UseNpgsql(configuration.GetPgConnection());
        });
        
        Audit.Core.Configuration.Setup()
            .UseEntityFramework(ef => ef
                .UseDbContext(_ => services.BuildServiceProvider().GetRequiredService<AuditContext>())
                .AuditTypeMapper(_ => typeof(AuditLog))
                .AuditEntityAction<AuditLog>((auditEvent, eventEntry, auditLog) =>
                {
                    var entityFrameworkEvent = auditEvent.GetEntityFrameworkEvent();
                    if (entityFrameworkEvent == null) 
                    {
                        return;
                    }

                    var entityPrimaryKey = eventEntry.PrimaryKey.FirstOrDefault().Value?.ToString() ?? string.Empty;
                    var originalEntity = auditEvent.CustomFields[$"OriginalEntity_{entityPrimaryKey}"];
                    
                    auditLog.Action = eventEntry.Action;
                    auditLog.EntityName = eventEntry.Table;
                    auditLog.EntityId = Guid.TryParse(entityPrimaryKey, out var guid) ? guid : Guid.Empty;
                    auditLog.ContextId = entityFrameworkEvent.ContextId;
                    auditLog.CreatedAt = DateTime.UtcNow;
                    auditLog.CreatedBy = string.IsNullOrWhiteSpace(identityUsername) ? auditEvent.Environment.UserName : identityUsername;
                   auditLog.Payload = new HistoricalEventEntry(eventEntry, originalEntity);
                })
                .IgnoreMatchedProperties()
            );

        Audit.EntityFramework.Configuration.Setup()
            .ForContext<SnapshotContextTypedWrapper>(config =>
            {
                config.IncludeEntityObjects();
                config.ReloadDatabaseValues();
            });
        
```

Additionally I made an override of a OnScopeCreated method in my main db context (one, which I need to make audit of `SnapshotContextTypedWrapper : AuditDbContext`) to fetch original entity object before any changes. It looks like this:

``` 
    public override void OnScopeCreated(IAuditScope auditScope)
    {
        foreach (var eventEntry in auditScope.Event.GetEntityFrameworkEvent().Entries)
        {
            if (eventEntry.Action == AuditConstants.Action.Update)
            {
                var originalObject  = eventEntry.GetEntry().OriginalValues.ToObject();
                
                var primaryKeyPropertyName = eventEntry.GetEntry().Metadata.FindPrimaryKey()!.Properties[0].Name;
                var entityPrimaryKey = eventEntry.GetEntry().CurrentValues[primaryKeyPropertyName]!.ToString()!;
                
                auditScope.Event.CustomFields[$"OriginalEntity_{entityPrimaryKey}"] = originalObject;
            }
        }
    }
```


For clarification (it is saved as jsonb column in database):
```
public class HistoricalEventEntry
{
    public EventEntry EventEntry { get; set; }
    public object? OriginalEntity { get; set; }

    public HistoricalEventEntry(EventEntry eventEntry, object? originalEntity)
    {
        EventEntry = eventEntry;
        OriginalEntity = originalEntity;
    }
}
```

**Comment by thepirat000** [comment]
Can you confirm by adding a breakpoint after the line `var entityFrameworkEvent = auditEvent.GetEntityFrameworkEvent();` and inspecting its value, if you see the Delete and also the Updates in its `Entries` property ?

You should see something like this:

![image](https://github.com/thepirat000/Audit.NET/assets/9836380/3ce49152-1175-409f-95eb-a021ea7ea3d7)

If the entries are there, then the problem could be that something is failing when the first entity is being saved.

**Comment by WalrusPUNCH** [comment]
This is what I see. It is entity of type A

![image](https://github.com/thepirat000/Audit.NET/assets/43036478/0ab53965-2dde-438a-bced-fbee11119a32)

**Comment by WalrusPUNCH** [comment]
I replaced lazy loading with 
```
        modelBuilder.Entity<B>().Navigation(e => e.A).AutoInclude();
        modelBuilder.Entity<A>().Navigation(e => e.Bs).AutoInclude();
```
and now I see 3 entries in EntityFrameworkEvent:

![image](https://github.com/thepirat000/Audit.NET/assets/43036478/83d66c15-0c28-4bb5-9204-923c9226a592)

But is is possible to receive those 3 updates using lazy loading?

**Comment by thepirat000** [comment]
So far, I have been unable to reproduce. 

I'm trying using the following configuration:

```c#
builder.Services.AddDbContext<MyContext>(cfg => cfg
    .UseNpgsql("Server=localhost;Port=5432;User Id=postgres;Password=admin;Database=test645;"));

// EF input setup
Audit.EntityFramework.Configuration.Setup()
    .ForContext<MyContext>(_ => _
        .IncludeEntityObjects()
        .ReloadDatabaseValues());

// Audit output config
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .AuditTypeMapper(t => typeof(AuditLog))
        .AuditEntityAction<AuditLog>((ev, entry, auditEntity) =>
            {
                var entityFrameworkEvent = ev.GetEntityFrameworkEvent();
                
                auditEntity.ActionType = entry.Action;
            }
        )
        .IgnoreMatchedProperties()
    );
```

With these entities:

```c#
public class A
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int AId { get; set; }
    public ICollection<B> Bs { get; set; } = new List<B>();
}

public class B
{
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int BId { get; set; }
    public int? AId { get; set; } 
    public A? A { get; set; }
}
```

I also added your code for the OnScopeCreated...

And this is my test:

```c#
public void Test()
{
    // Arrange two Bs related to an A
    Audit.Core.Configuration.AuditDisabled = true;
    var a = new A()
    {
        AId = 1,
        Bs = new List<B>()
        {
            new() { BId = 100 },
            new() { BId = 200 }
        }
    };
    _ctx.As.Add(a);
    _ctx.SaveChanges();
    Audit.Core.Configuration.AuditDisabled = false;

    // Remove the A
    _ctx.Remove(a);
    _ctx.SaveChanges();
}
```

And I correctly get 3 entries in the audit event, and 3 calls to my `AuditEntityAction`.

Can you validate there are no `[AuditIgnore]` or `UseOptIn()` calls in your code?

**Comment by WalrusPUNCH** [comment]
Please, check my previous comments. I think I found the reason why I am not getting all entries.

Can I somehow receive all those "Update" and "Delete" action entries in EntityFrameworkEvent but with the global use of lazy loading for navigation properties?

**Comment by thepirat000** [comment]
I tried with lazy loading and virtual properties, but it worked as expected. 

Additionally, I tested with the AutoInclude feature, and it also worked well.

Would it be possible for you to provide a minimal project that reproduces the issue?

**Comment by WalrusPUNCH** [comment]
Yes, sure, I will try to reproduce it in some standalone project. May I see your testing project?

**Comment by thepirat000** [comment]
yes, here it is;

[test645.zip](https://github.com/thepirat000/Audit.NET/files/13909494/test645.zip)

**Comment by WalrusPUNCH** [comment]
Here it is. I provided two ways to reproduce it. So, check them both before, please. 
**I am using your code which you kindly provided above.**

MANUALLY (so, EF Core change tracker doesn't know anything) add those rows into database tables:
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/26552631-7d1e-4e48-b506-a6dbee585656)
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/640a3ffc-34fc-40ff-8b18-b01c534a6252)

I made it by running your code with delete section commented out:
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/87bdd89b-e09a-4856-93db-beb2f6df70dc)

Now, when you have records in database tables as shown on screens 1 and 2:

1. **uncomment delete section**
2. **comment out database deletion `//context.Database.EnsureDeleted();` to keep the data in DB**.
3. **comment out section of the code where you add entries into database** 
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/430841e5-2b60-4c21-a7e3-8737d8903b77)


Run code again and you will receive only 1 entry instead of 3 in entityFrameworkEvent.


---
Another way of doing this: 

Just add `context.ChangeTracker.Clear();` line after `Audit.Core.Configuration.AuditDisabled = false;` and before `var loaded_a = context.TableA.First();` as shown on screen to emulate the situation when EF`s change tracker doesn't track anything.
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/55bc441e-71ae-4072-bcc0-4e86e939d616)

Run code again and you will receive only 1 entry instead of 3 in entityFrameworkEvent.
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/d2ffaa22-bad9-4c52-b424-1704be567ec1)



_**IMPORTANT MENTION:**_ If you put breakpoint on line `context.TableA.Remove(loaded_a);` and manually investigate values of `loaded_a` variable properties when breakpoint is reached and after it continue execution, you will receive 3 entries in entityFrameworkEvent. 

I think this happens because when you check property values in debugger they are also lazy loaded and change tracker tracks them after this.

![image](https://github.com/thepirat000/Audit.NET/assets/43036478/43a05abc-ebd9-4ed6-96c3-6938124c0f0a)
![image](https://github.com/thepirat000/Audit.NET/assets/43036478/8ea5ba00-e259-4c29-b501-b3eaa3620862)

**Comment by thepirat000** [comment]
It appears that the issue lies within the Entity Framework's change tracker mechanism rather than the Audit.NET library itself. When the change tracker lacks awareness of related entities, they are consequently omitted from the audit entries.

To address this, there are two potential solutions:

- Explicitly Include Related Entities: You can explicitly include related entities using the Include method. For example:

```c#
var loaded_a = context.TableA.Include(a => a.Bs).First();
```

- Use the [Command Interceptor](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#low-level-command-interception): The command interceptor will generate audit events for the Delete and Updates. Note these audit events are not compatible with the Entity Framework data provider.
