### ISSUE TITLE
How to ingest data to AzureTableStorage month wise in the AuditTrail implementation using Audit.NET?

### ISSUE THREAD

**Issue by santoshpatro** [thepirat000/Audit.NET#650]
Hi Daniel,

Thanks a lot for sharing with us a great library which has a very good documentation also : https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md for implementation of Audit Trail.

I need your help for a scenario detailed at : https://stackoverflow.com/questions/77911644/how-to-ingest-data-to-azuretablestorage-month-wise-in-the-audittrail-implementat

Any help on this request is much appreciated

Thanks,
Santosh

**Comment by thepirat000** [comment]
Looks like you're calling the wrong overload of `TableName()`. If you need your table name to be dynamic, you must use `TableName(Func<AuditEvent, string>)` overload.

For example:

```c#
   .TableName(ev => GetTableName())
```

**Comment by santoshpatro** [comment]
Thanks @thepirate000 for your quick response. But the code sample I have added is part of the Configure method of Startup.cs which gets invoked only at the startup event of the application or in case the app restarts. Apart from that there is no other way this code block gets executed, hence can you please guide me here

**Comment by santoshpatro** [comment]
Thanks @thepirat000 for resolving my issue. Your solution fixed the issue now :)
