### ISSUE TITLE
Not available to use dbContext in .UseDbContext<MyDbContext> in Audit.Core.Configuration.Setup

### ISSUE THREAD

**Issue by Arce19** [thepirat000/Audit.NET#652]
Im not available to use `UseDbContext<MyDbContext>` in my UseEntityFramework configuration, im getting this error **'Constructor on type 'DbContext' not found.'**, i added that line because i had the loop problem, it work but getting the service of my applicationDbContext like this  `'return services.BuildServiceProvider().GetService<ApplicationDbContext>()'`, but i think thats not the right way, i already added the `[AuditIgnore]` to my Auidtable entity, ill leave my snippets of code below

this is my startup config

 ```
 public class Startup
   {
        public IConfiguration Configuration { get; }
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public virtual void ConfigureServices(IServiceCollection services)
        {
            // Configure services
            services.AddDbContext<ApplicationDbContext>(c => c
                .UseSqlServer(Configuration.GetConnectionString("EntityFrameworkConnection"))
                .AddInterceptors(new AuditSaveChangesInterceptor()));
              
              Audit.Core.Configuration.Setup()
                  .UseEntityFramework(_ => _
                     .UseDbContext<ApplicationDbContext>()
                     .AuditTypeMapper(t => typeof(Auditable))
                     .AuditEntityAction<Auditable>((ev, entry, entity) =>
                     {
                        entity.Comments = "";
                        entity.Action = entry.Action;
                        entity.Ip = "";
                        entity.UserName = ev.Environment.UserName;
                        entity.ActionDate = DateTimeOffset.UtcNow;
                        entity.Longitude = 0;
                        entity.Latitude = 0;
                        entity.Browser = "";
                        entity.Success = ev.GetEntityFrameworkEvent().Success;
                     })
                 .IgnoreMatchedProperties(true));
            }
  }
```

im getting this error 
**Constructor on type 'DbContext' not found.**

this is my db context
```
public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }
        public DbSet<Auditable> Auditable { get; set; }
        public DbSet<CurrencyPair> CurrencyPair { get; set; }

    }
```
    
if i do tihis:
```
.UseDbContext(ev =>
    {
        return services.BuildServiceProvider().GetService<ApplicationDbContext>();
    })
```
  instead of:
`.UseDbContext<ApplicationDbContext>()`
works but i dont thinks is the right way

**Comment by thepirat000** [comment]
Yes that's the right way to use the service provider to resolve the Dbcontext

**Comment by thepirat000** [comment]
Yes, that's one way to do it.

It may seem incorrect because you are **using** the service provider in the method that should be **configuring** the service provider...

I think it would be better to move the `Audit.Core.Configuration.Setup()` call to the Startup.Configure method.

For example:

```c#
public void Configure(IApplicationBuilder app)
{
	Audit.Core.Configuration.Setup()
    	.UseEntityFramework(x => x
        	.UseDbContext(ev => app.ApplicationServices.GetService<ApplicationDbContext>()));
}
```

Check this SO answer: https://stackoverflow.com/a/32461714/122195

**Comment by Arce19** [comment]
i tried that moving the `Audit.Core.Configuration.Setup()` to the Startup.Configure method, but now im getting this error
**Cannot resolve scoped service 'Demo.Data.ApplicationDbContext' from root provider.**, using this 
`.UseDbContext(ev => app.ApplicationServices.GetService<ApplicationDbContext>())

**Comment by thepirat000** [comment]
Please check this: https://github.com/thepirat000/Audit.NET/issues/539

Maybe this should work:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<ApplicationDbContext>())
        .DisposeDbContext()
        ....);
```

**Comment by Arce19** [comment]
Works perfect!, thank you for the detailed explanation and your answers @thepirat000
