### ISSUE TITLE
Feature Request - Enable configuration of Azure Blob Storage Tags

### ISSUE THREAD

**Issue by ScottRapsey** [thepirat000/Audit.NET#654]
As the title suggests, this is a feature request to enable the configuration of Azure Blob Storage Tags.  

Blob Tags, or 'Blob Index Tags', look similar to Blob Metadata but they are used for indexing and can therefore be used for querying blobs. 
See: [Manage and find Azure Blob data with blob index tags](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs) for more information 

Blob Tags would need to be mapped through the Configurator and the Data Provider in the exact same manner that Metadata currently is.  

It seems like it would be a relatively simple feature to add, but I'm not sure if there are any downside.

**Comment by thepirat000** [comment]
I can work on this feature, however, the drawback lies in my inability to test it since I don't have an Azure subscription, and the official emulator _officially_ doesn't support searching by tags 🤦🏻 

https://github.com/Azure/Azurite/issues/1312

**Comment by thepirat000** [comment]
Tag option added in version 25.0.2, please upgrade your references and re-test

For example:

```c#
Audit.Core.Configuration.Setup()
    .UseAzureStorageBlobs(config => config
        ...
        .Tags(ev => new Dictionary<string, string>() { { "eventType", ev.EventType } }));
```

**Comment by ScottRapsey** [comment]
Looks good.  
Appears to work perfectly with a 'legit' Azure Storage Account. 

<img width="574" alt="image" src="https://github.com/thepirat000/Audit.NET/assets/1840832/3230b534-e766-44be-b5d5-2c505aee4a79">



Thanks for the super fast turnaround.
