### ISSUE TITLE
CosmoDB & EFCore: Storing document per entry instead of per transation.

### ISSUE THREAD

**Issue by larsgullestrup** [thepirat000/Audit.NET#655]
I am wondering if there is a way to Flatten the json output to create a document for each efcore entry.

Similar to what is presented with the EntityFramework Provider, where all the types are mapped to an 'AuditLog',
Instead of a document with a list of entries, each entry is a document with a Guid link to the other entries in the same Entries set.

Primary issue with what I am getting now, is there is no easy way to setup a partition keys, as the closest details to the actual action happens 3 levels deep in the entries array.

Current Document being stored:
```
{
    "EntityFrameworkEvent": {
        "Database": "<<db_name>>",
        "ContextId": "6a1a9187-11a5-472e-a069-04e45381ec1c:0",
        "Entries": [
            ...List of Entry Details.
        ]
    },
    ...Other log data
} 
```
Desired Document
```
{
    "Database":  "<<database name>>",
    "LinkKey": "<<Guid for link entries saved togeather>>"
    
    ...Entry Details (Table, Name, Primary keys ect)
    
    ...Other log data
}
```

**Comment by thepirat000** [comment]
Not with the default AzureCosmosDataProvider. 

But, if the `GetContainer` method was exposed as protected instead of private [here](https://github.com/thepirat000/Audit.NET/blob/a27e1577f65b473ffd360cb5363df703cd51f53f/src/Audit.NET.AzureCosmos/Providers/AzureCosmosDataProvider.Cosmos.cs#L189), maybe you could create a derived AzureCosmosDataProvider that stores one document per entry.

Something like this:

```c#
public class CosmosEfDataProvider : AzureCosmosDataProvider
{
    public override async Task<object> InsertEventAsync(AuditEvent auditEvent, CancellationToken cancellationToken = new CancellationToken())
    {
        var container = base.GetContainer(auditEvent);    // <--- THIS

        var efEvent = auditEvent.GetEntityFrameworkEvent();

        foreach (var entry in efEvent.Entries)
        {
            var audit = new YourAudit() { Database = efEvent.Database, Entry = entry };
            await container.CreateItemAsync(audit, cancellationToken: cancellationToken);
        }

        return null;
    }

    public override object InsertEvent(AuditEvent auditEvent)
    {
        return InsertEventAsync(auditEvent).GetAwaiter().GetResult();
    }
}
```

If you think this could work, I can release a new version with the protected `GetContainer` method.

**Comment by larsgullestrup** [comment]
Hi Pirat, 

This looks like a great solution. Looks like this would also allow us to customize the entry altogether.

**Comment by thepirat000** [comment]
This was incorporated in version 25.0.3. Kindly update your references and re-test. The GetContainer method is now accessible through the derived data provider.

**Comment by larsgullestrup** [comment]
amazing, thank you so much!
