### ISSUE TITLE
How to connect AzureTableStorage using UserAssigned ManagedIdentity in the AuditTrail implementation using Audit.NET?

### ISSUE THREAD

**Issue by santoshpatro** [thepirat000/Audit.NET#666]
Hi Daniel,

Thanks a lot for sharing with us a great library which has a very good documentation also : https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md for implementation of Audit Trail.

I need your help for a scenario detailed at : https://stackoverflow.com/questions/78490377/how-to-connect-azuretablestorage-using-userassigned-managedidentity-in-the-audit

Any help on this request is much appreciated

Thanks,
Santosh

**Comment by thepirat000** [comment]
This was already answered in SO by Gaurav Mantri, [here](https://stackoverflow.com/a/78490688/122195) you can see the response.

You should be able to use managed identity by setting up the connection with the `.Endpoint()` configuration extension:

```c#
Configuration.Setup()
    .UseAzureTableStorage(config => config
        .Endpoint(new Uri("https://account.table.core.windows.net", new DefaultAzureCredential())
        
```

**Comment by santoshpatro** [comment]
Thanks @thepirat000 for your response. I tried it and getting an error : cannot convert from 'Azure.Identity.DefaultAzureCredential' to 'bool'

**Comment by santoshpatro** [comment]
Thanks @thepirat000 for your response.. I revalidated it once again and found a small type mistake from my side. It fixed the issue now :)
