### ISSUE TITLE
Add custom value to audit workflow

### ISSUE THREAD

**Issue by mrlife** [thepirat000/Audit.NET#667]
It looks like the .NET team doesn't have a workaround for accessing user data inside Startup.cs/Program.cs for a Blazor app. I was wondering if it would be feasible in Audit.NET to allow providing a value, such as a user id, for each user, since it can't be done at the server level.

I noticed the below in the [docs](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#custom-fields) and wondered if this was a way to accomplish this now. If a "UserName" is added in this way, does it populate a field called "UserName" in the audit table associated with MyEntities? Is "UserName" available in `AuditEntityAction()` as `scope.Event.Environment.CustomFields["UserName"]`?

```c#
using(var context = new MyEntitites())
{
	...
	context.AddAuditCustomField("UserName", userName);
	...
	context.SaveChanges();
}
```

Past discussions: https://github.com/thepirat000/Audit.NET/issues/440, https://github.com/thepirat000/Audit.NET/issues/483

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 25.0.4

**Target .NET framework:**
For example:
 - .NET 8.0.4

**Comment by thepirat000** [comment]
`AddAuditCustomField()` will insert the custom field value into the root Audit Event object. The storage of this field then depends on your Data Provider.

**Comment by mrlife** [comment]
Yes, this looks like the solution I've been searching for! I don't know why we didn't realize this solution before, but I'm grateful to have this working. Thank you!
