### ISSUE TITLE
Custom Provider - Event Creation Policy not being set

### ISSUE THREAD

**Issue by gl1tch** [thepirat000/Audit.NET#68]
Hi,

I'm currently using a custom data provider to perform some logging into a SQL database for a WCF service.

I have setup the configuration of the custom provider as per my extract below.

`public static void SetupAuditConfiguration()
        {
            Audit.Core.Configuration.Setup()
                                    .UseCustomProvider((AuditDataProvider)DIConfiguration.Container.GetInstance<ICustomSqlDataProvider>())
                                    .WithCreationPolicy(EventCreationPolicy.InsertOnStartReplaceOnEnd);
        }`

However i noticed that the _**ReplaceEvent**_ is never being called in my custom provider.
Doing the following in my service class (code below) 

` EventCreationPolicy x = Audit.WCF.AuditBehavior.CurrentAuditScope.EventCreationPolicy;`

shows me the EventCreationPolicy is being set to "Manual" no matter what I've tried i haven't been able to change it. The initial InsertEvent is being called properly.

Thanks in advance

**Comment by thepirat000** [comment]
Yes, by design the Creation Policy is overridden by the WCF extension to `Manual` and the event is saved when the audited method exits or throws an exception.

Do you need a different behavior for any reason?

**Comment by thepirat000** [comment]
I've changed the `AuditScope` creation logic for the WCF extension.

Starting from v8.5.0, it now respects the global Creation Policy or the one specified on the `AuditBehaviorAttribute`.

Feel free to re-open the issue if you're still having problems
