### ISSUE TITLE
Error with PartitionKey in .NET 8 Web API using Audit.NET and Azure Storage Table

### ISSUE THREAD

**Issue by santoshpatro** [thepirat000/Audit.NET#680]
Hi Daniel,

Thanks a lot for sharing with us a great library which has a very good documentation also : https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md for implementation of Audit Trail.

I need your help for a scenario detailed at : https://stackoverflow.com/questions/78741629/error-with-partitionkey-in-net-8-web-api-using-audit-net-and-azure-storage-tabl

Any help on this request is much appreciated

Thanks,
Santosh

**Comment by thepirat000** [comment]
The problem seems to be an invalid character in the PartitionKey.

https://stackoverflow.com/a/78748087/122195
