### ISSUE TITLE
How to use  DbContextFactory?

### ISSUE THREAD

**Issue by yedajiang44** [thepirat000/Audit.NET#681]

**Comment by thepirat000** [comment]
Is this question related to the audit library? Please provide more context, including the issue you're facing and what you've attempted so far.

Do you mean [this](https://learn.microsoft.com/en-us/ef/core/dbcontext-configuration/#using-a-dbcontext-factory-eg-for-blazor)?

**Comment by yedajiang44** [comment]
yes~ I can't use `usedbcontext` get dbcontext in di

**Comment by yedajiang44** [comment]
Sorry, I understand now, the lib creates the dbcontext without using di, you need to pass the dbcontext instance.

But why does the database not insert audit records when I savechange after add or update or delete?

```c#
Audit.EntityFramework.Configuration.Setup()
.ForContext<PgSqlDefaultDbContext>(config =>
{
    config.IncludeEntityObjects().AuditEventType("{context}:{database}").ExcludeValidationResults();
})
.UseOptIn()
.Include<TerminalEntity>()
.Include<VehicleEntity>()
.Include<DriverEntity>();
```

```
var scopeFactory = services.GetRequiredService<IServiceScopeFactory>();

Audit.Core.Configuration.Setup().UseEntityFramework(option =>
{
    option.UseDbContext(_ => services.GetRequiredService<IDbContextFactory<PgSqlDefaultDbContext>>().CreateDbContext())
    .DisposeDbContext()
    .AuditTypeExplicitMapper(mapper =>
    {
        mapper.AuditEntityAction<AuditEventEntity>((auditEvent, eventEntity, auditEntity) =>
        {
            auditEntity.Id = IdGenerator.Instance.NextId().ToString();
            auditEntity.Data = eventEntity.ToJson();
            auditEntity.EventType = eventEntity.EntityType.Name;
        });
    });
});
```

**Comment by thepirat000** [comment]
Your configuration looks good to me, maybe you want to try using the same service scope from the original savechanges. This will avoid the "services" free-variable closure:

```c#
using Audit.Core;
using Audit.EntityFramework;

Audit.Core.Configuration.Setup().UseEntityFramework(option =>
{
    option.UseDbContext(ev => ev.GetEntityFrameworkEvent().GetDbContext().GetService<IDbContextFactory<PgSqlDefaultDbContext>>().CreateDbContext())
    //....
```

Can you share the code of your `PgSqlDefaultDbContext` ? Is it inheriting from `AuditDbContext`?

**Comment by yedajiang44** [comment]
It's no inheriting from `AuditDbContext`
```
public class PgSqlDefaultDbContext(DbContextOptions<PgSqlDefaultDbContext> options) : DbContext(options)
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(GetType().Assembly, x => x.GetInterface(typeof(IEntityTypeConfiguration<>).FullName!) != null);
        modelBuilder.Entity<AuditEventEntity>().ToTable("AuditEvents");
        base.OnModelCreating(modelBuilder);
    }
}
```

**Comment by yedajiang44** [comment]
> Your configuration looks good to me, maybe you want to try using the same service scope from the original savechanges. This will avoid the "services" free-variable closure:
> 
> ```cs
> using Audit.Core;
> using Audit.EntityFramework;
> 
> Audit.Core.Configuration.Setup().UseEntityFramework(option =>
> {
>     option.UseDbContext(ev => ev.GetEntityFrameworkEvent().GetDbContext().GetService<IDbContextFactory<PgSqlDefaultDbContext>>().CreateDbContext())
>     //....
> ```
> 
> Can you share the code of your `PgSqlDefaultDbContext` ? Is it inheriting from `AuditDbContext`?

but `ev.GetEntityFrameworkEvent().GetDbContext()`has no `GetService`

**Comment by thepirat000** [comment]
I'm assuming you're using EF Core... Try adding `using Microsoft.EntityFrameworkCore.Infrastructure;`

**Comment by yedajiang44** [comment]
After a long try, I finally got the audit data，When using `UseOptIn` mode, the following conditions must be met

- Call the `Include` method after `UseOptIn`
- Specify mapping type in `AuditTypeExplicitMapper`

So my code ends up looking like this:
```c#
Audit.EntityFramework.Configuration.Setup()
.ForContext<PgSqlDefaultDbContext>(config =>
{
    config.IncludeEntityObjects().AuditEventType("{context}:{database}").ExcludeValidationResults();
})
.UseOptIn()
//----add start----
.Include<TerminalEntity>()
.Include<VehicleEntity>()
.Include<DriverEntity>();
//----add end----

var scopeFactory = services.GetRequiredService<IServiceScopeFactory>();

Audit.Core.Configuration.Setup().UseEntityFramework(option =>
{
    option.UseDbContext(_ => services.GetRequiredService<IDbContextFactory<PgSqlDefaultDbContext>>().CreateDbContext())
    .DisposeDbContext()
    .AuditTypeExplicitMapper(mapper =>
    {
        //----add start----
        mapper.Map<TerminalEntity, AuditEventEntity>()
        .Map<VehicleEntity, AuditEventEntity>()
        .Map<DriverEntity, AuditEventEntity>()
        //----add end----
        .AuditEntityAction<AuditEventEntity>((auditEvent, eventEntity, auditEntity) =>
        {
            auditEntity.Id = IdGenerator.Instance.NextId().ToString();
            auditEntity.Data = eventEntity.ToJson();
            auditEntity.EventType = eventEntity.EntityType.Name;
            auditEntity.CreateDateTime = DateTimeOffset.UtcNow;
        });
    });
});
```

There is too little documentation and examples for `UseOptIn` mode, I hope there can be some more clarification information or examples.

Anyway thank you very much for your contribution to Lib.

Finally, thank you very much for this code suggestion
```c#
option.UseDbContext(ev => ev.GetEntityFrameworkEvent().GetDbContext().GetService<IDbContextFactory<PgSqlDefaultDbContext>>().CreateDbContext())
```
