### ISSUE TITLE
Request headers must contain only ASCII characters.

### ISSUE THREAD

**Issue by kjartanvalur** [thepirat000/Audit.NET#683]
**Describe the bug**
I get an error only when testing localhost with a windows username containing characters that are not ASCII. I´m using 

**To Reproduce**
Have a Windows username containing a none ASCII character and using Audit.NET.AzureStorageBlobs with Audit.EntityFramework.Core
And every time a logging is triggered I get this error:
Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (Request headers must contain only ASCII characters.) 
   at Azure.Core.Pipeline.HttpClientTransport.<ProcessSyncOrAsync>d__12.MoveNext()
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.<ProcessAsync>d__4.MoveNext()
   at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<InnerProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__7.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()

**Expected behavior**
Expected the auditlog to work like it does in production and localhost where windows user has only ASCII characters in windows username.

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 26.0.0
 - Audit.NET.AzureStorageBlobs: 26.0.0

**Target .NET framework:**
 - Dotnet 8

**Comment by kjartanvalur** [comment]
Found out the problem. Needed to add HtmlEncode to the metadata I was adding. Then everything works
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    ...configs
.AccessTier(AccessTier.Cool)
    .Metadata(ev => new Dictionary<string, string>() { { "user", **HttpUtility.HtmlEncode(**ev.Environment.UserName) } }))
;

**Comment by thepirat000** [comment]
yeah, sadly the metadata is restricted to ASCII characters . https://github.com/Azure/azure-sdk-for-net/issues/10629
