### ISSUE TITLE
Audit.NET doesn't work with windows authentication

### ISSUE THREAD

**Issue by vivek-outamation** [thepirat000/Audit.NET#685]
### Summary:

- The Audit.EntityFramework.Core package is not functioning correctly with Windows Authentication in our .NET Core Web API project. Specifically, audit logs are not being created or saved when Windows Authentication is used for protected endpoints, though they work fine for anonymous endpoints.

### Details:

- Application Framework: .NET Core 8
- Audit.EntityFramework.Core Version: 26.0.0
- Audit.NET Version: 26.0.0
- Microsoft.EntityFrameworkCore Version: 8.0.7
- Microsoft.EntityFrameworkCore.Relational Version: 8.0.7
- Project Type: Web API

### Issue Description:

In our .NET Core Web API project, we are using Windows Authentication to secure our API endpoints. The Audit.EntityFramework.Core package is integrated to audit changes made through Entity Framework Core. We are encountering the following issues:

**Auditing Failure with Protected Endpoints:**
When accessing protected endpoints (those requiring Windows Authentication), audit records are not being generated or saved. This issue occurs despite the fact that auditing works correctly for endpoints marked with [AllowAnonymous].

**Behavior Summary:**
Anonymous Endpoints: Audit logs are successfully created and saved.
Protected Endpoints: No audit records are created, and no data is inserted into the audit log.

**Error Messages and Logs:**
There are no specific error messages or exceptions being thrown related to the auditing process in the logs. The absence of audit records suggests a failure in the auditing mechanism when Windows Authentication is applied.

**Comment by thepirat000** [comment]
Can you share a minimal project that reproduces the issue? There is no relation between the Audit.EntityFramework.Core and the Web API authentication mechanism, so I can't tell what the problem could be.

How are you configuring the Audit and the EF dbContext?

**Comment by vivek-outamation** [comment]
I have inherited AuditDbContext in MyDbContext
```
public class OutamateWorksCoreDbContext : AuditDbContext
{
    // My Entites added in DbSet
}
```
I have created my CustomAuditDataProvider by inheriting AuditDataProvider
```
public class CustomAuditDataProvider(IServiceScopeFactory _serviceScopeFactory) : AuditDataProvider
{
    public override async Task<object> InsertEvent(AuditEvent auditEvent)
    {
        //throw new Exception(JsonSerializer.Serialize(auditEvent));
        using (var scope = _serviceScopeFactory.CreateScope())
        {
            var context = scope.ServiceProvider.GetRequiredService<OutamateWorksCoreDbContext>();
            var efEvent = auditEvent.GetEntityFrameworkEvent();
            foreach (var entry in efEvent.Entries)
            {
                string modifiedBy = null;
                if (entry.ColumnValues["ModifiedById"] != null)
                {
                    modifiedBy = await context.Users.Where(u => u.Id == int.Parse(Convert.ToString(entry.ColumnValues["ModifiedById"]))).Select(u => u.Name).FirstOrDefaultAsync();
                }

                var auditLog = new AuditLog
                {
                    TableName = entry.Table,
                    Schema = entry.Schema,
                    Changes = entry.Changes.ToJson(),
                    Action = entry.Action,
                    ConnectionId = efEvent.ConnectionId,
                    ContextId = efEvent.ContextId,
                    PrimaryKey = int.Parse(entry.PrimaryKey["Id"].ToString()),
                    Success = efEvent.Success,
                    ColumnValues = entry.ColumnValues.ToJson(),
                    ModifiedBy = modifiedBy,
                };
                context.AuditLogs.Add(auditLog);
            }

            context.SaveChanges();
        }
        return null;
    }
}
```
I have configured this CustomAuditDataProvider in Program.cs
```
builder.Services.AddScoped<CustomAuditDataProvider>();
```

**Comment by thepirat000** [comment]
You must override InsertEvent AND InsertEventAsync in your custom data provider

**Comment by thepirat000** [comment]
I apologize for the confusion. The base `AuditDataProvider.InsertEventAsync()` actually [invokes the synchronous method](https://github.com/thepirat000/Audit.NET/blob/65e11932db687d4678cd347662c0252897dbdabf/src/Audit.NET/AuditDataProvider.cs#L47) by default. However, it is highly recommended to implement the asynchronous methods in your custom data provider to avoid calling asynchronous methods from synchronous ones.

For more information, you can refer to this article: https://learn.microsoft.com/en-us/archive/msdn-magazine/2015/july/async-programming-brownfield-async-development

While I'm not certain this will resolve the issue, it's worth a try.

**Comment by thepirat000** [comment]
I understand the issue now.

The Audit.EntityFramework.Core library does not use Dependency Injection (DI) to resolve the AuditDataProvider. Instead, it retrieves it from the AuditDbContext or from the global configuration.

One solution is to set the AuditDataProvider property in your DbContext constructor:

```c#
public class OutamateWorksCoreDbContext : AuditDbContext
{
    public OutamateWorksCoreDbContext(DbContextOptions options, IServiceScopeFactory serviceScopeFactory) : base(options)
    {
        this.AuditDataProvider = new CustomAuditDataProvider(serviceScopeFactory);
    }
}
```

Alternatively, you can set the global default data provider like this:

```c#
// in your startup code:
var app = builder.Build();

var serviceScopeFactory = app.Services.GetService<IServiceScopeFactory>();

Audit.Core.Configuration.Setup().Use(new CustomAuditDataProvider(serviceScopeFactory));
```

Moreover, you might not need the IServiceScopeFactory dependency in your DataProvider if you implement it this way:

```c#
using Microsoft.EntityFrameworkCore.Infrastructure;

public class CustomAuditDataProvider : AuditDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        var serviceScopeFactory = auditEvent.GetEntityFrameworkEvent().GetDbContext().GetService<IServiceScopeFactory>();

        using (var scope = serviceScopeFactory.CreateScope())

        // ...
```
