### ISSUE TITLE
ExecuteUpdateAsync not working in Audit.EntityFramework

### ISSUE THREAD

**Issue by zanyar3** [thepirat000/Audit.NET#686]
**Describe the bug**
When trying to use Audit.NET to audit updates made with  [ExecuteUpdateAsync ](https://learn.microsoft.com/en-us/ef/core/saving/execute-insert-update-delete#executeupdate), the audit records are not being created in the database.

**Expected Behavior**
Audit records should be created for updates made using `ExecuteUpdateAsync`.
No audit records are created when using ExecuteUpdateAsync to update records.

**Libraries (specify the Audit.NET extensions being used including version):**
Audit.EntityFramework.Core 26.0.0

**Target .NET framework:**
For example:
 - .NET Standard 2.1 class library
 
Example code:
```
 await dbContext.Products
            .Where(a => a.Id == id)
            .ExecuteUpdateAsync(a => a.SetProperty(d => d.IsDeactivated, v => !v.IsDeactivated));
```

**Comment by thepirat000** [comment]
Bulk updates/inserts are not tracked by the EF change tracker. So the savechanges interceptor will not intercept calls to ExecuteUpdate

Check this https://github.com/thepirat000/Audit.NET/issues/607#issuecomment-1592067863

**Comment by zanyar3** [comment]
If you are using **AuditCommandInterceptor** for auditing non-tracking operations and leveraging **CommandEvent** effectively,

We have encountered a new issue: How do we invoke AuditDataProvider when using **AuditCommandInterceptor**? 
Currently, the audit action is only being _saved to a file._

**Comment by thepirat000** [comment]
The Command interceptor uses the default data provider, which can be configured by assigning the `Audit.Core.Configuration.DataProvider` static property or with the fluent API for the data provider, such as: `Audit.Core.Configuration.Setup().UseSqlServer("...");`

Please note that the `EntityFrameworkDataProvider` cannot be used to store events generated by the command interceptor. Only the high-level audit events are processed by this data provider.

https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider
