### ISSUE TITLE
Audit.WebApi.Core middleware misses some fields. 

### ISSUE THREAD

**Issue by NormChalis** [thepirat000/Audit.NET#688]
Audit event object has empty fields and/or incorrect fields after request is invoked.

`StatusResponseCode` allways has 0 value.
`ResponseBody` is null
`ResponseHeader` also is null. 

 - Audit.NET: 26.0.0
 - Audit.WebApi: 26.0.0
 - .NET 8

**Comment by NormChalis** [comment]
Had to configure EventCreationPolicy as InsertOnEnd. and IsCreateAndSave had to set to false.

**Comment by thepirat000** [comment]
InsertO End is the default creation policy., isCreateAndSave false is also the default value
