### ISSUE TITLE
Audit.WebApi IAuditMiddlewareConfigurator.IncludeResponseBody gets invoked before actual request happens

### ISSUE THREAD

**Issue by NormChalis** [thepirat000/Audit.NET#690]
I want to include response body based on response headers. If that response, let's say, is a binary content or a file, i don't want it to be included. 

**To Reproduce**
1. Add a breakpoint in to the controller
2. Add a breakpoint in to the `IAuditMiddlewareConfigurator.IncludeResponseBody` functrion
3. Hence that `IncludeResponseBody` gets invoked before actual endpoint. 
4.  You can see that in `context.Response.Headers` are empty. 

**Expected behavior**

**Libraries (specify the Audit.NET extensions being used including version):**
Audit.WebApi

**Target .NET framework:**
- .NET 8

I can see that all filters gets invoked at one place. 
This line https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/AuditMiddleware.cs#L43 should be invoked after request happens.

**Comment by thepirat000** [comment]
The library needs to know if it will audit the response **before** the action is invoked, because it needs to replace the Response.Body stream with a MemoryStream before invoking the action, to capture the response content afterward.

So, if you need to decide after the action is invoked, you can do it with a custom action on saving, for example:

```
using Audit.WebApi;

Audit.Core.Configuration.AddOnSavingAction(scope =>
{
    var ac = scope.GetWebApiAuditAction();
    if (!ac.ResponseHeaders["Content-Type"].StartsWith("application/json"))
    {
        ac.ResponseBody = null;
    }
});
```

**Comment by thepirat000** [comment]
A new configuration setting SkipResponseBodyContent was introduced in version 26.0.1. Please upgrade your references and re-test.

You can now supply a predicate of the HttpContext, which will be evaluated AFTER the request execution. This allows you to perform something like the following:

```c#
app.UseAuditMiddleware(config => config
    .SkipResponseBodyContent(ctxAfterExecution => ctxAfterExecution.Response.Headers["Content-Type"] == "application/zip")
);
```

**Comment by NormChalis** [comment]
Thanks @thepirat000 it seems that new update fixes the issue. I've tested with different endpoints. 
On the same note I can give you a mu two cents on `Audit.WebApi` I've noticed that it has two issues which can be fixed by custom code: 

1. If resposne/request body is a json, then `BodyContent.Value` is set as a string, I'd expect it to be a json. But in all cases it is just set as a string: https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/AuditApiHelper.cs#L108
2. In response case `BodyContent.Length` allways is null.

**Comment by thepirat000** [comment]
1. You can use the Audit Action Filter to obtain a structured object in the request/response body output. The Middleware lacks awareness of the MVC action, it only hooks into the HTTP pipeline. (See https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.WebApi/README.md#4--middleware--action-filters)

2. The Body Length is derived from the Content-Length response header. If the server does not send this header, the value will be null. (See https://github.com/dotnet/aspnetcore/issues/14858)
