### ISSUE TITLE
Add custom fields in custom IAuthorizationFilter when using Audit.HttpClient

### ISSUE THREAD

**Issue by aintJoshinya** [thepirat000/Audit.NET#694]
I am using the Audit.WebApi extension to audit our endpoints. We have a custom authorization attribute that we are using and I would like to access the WebApi's audit scope to add some custom fields.

I see accessing the audit scope within controllers is possible using `[AuditApi]` attribute and` var auditScope = this.GetCurrentAuditScope();`

I don't appear to be able to do the same within the custom authorization attribute, though.

I would like to use `AuditApiAdapter.GetCurrentScope(HttpContext httpContext)`, as this appears to be what `this.GetCurrentAuditScope();` uses, but this is marked as internal.

as a workaround, I am roughly doing the same work that `AuditApiAdapter.GetCurrentScope(HttpContext httpContext)` is doing:
``` c#
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method)]
    public class CustomAuthorizationAttribute : Attribute, IAuthorizationFilter
    {
        public void OnAuthorization(AuthorizationFilterContext context)
        {
            //var auditScope = AuditApiAdapter.GetCurrentScope(context.HttpContext); //GetCurrentScope is internal!
            var auditScope = context.HttpContext.Items["__private_AuditApiScope__"] as AuditScope;
            auditScope?.SetCustomField("example",
                context.HttpContext.User.Claims.FirstOrDefault(x => x.Type == "example")?.Value);

            //...
        }

        //...
    }

```

Is there a better way to do this? The above works for me, but I'd prefer to avoid using the "__private_AuditApiScope__" string. Would it make sense to make AuditApiAdapter.GetCurrentScope public instead of internal? It could be useful to be able to access the audit context in other parts of the pipeline, another custom middleware for example.

**Comment by thepirat000** [comment]
you can use the HttpContext Extension Method defined [here](https://github.com/thepirat000/Audit.NET/blob/aae1de2b6d8635abe2857725ed60eae98b44d1ba/src/Audit.WebApi/ApiControllerExtensions.cs#L67).

For example:

```c#
using Audit.WebApi;

var auditScope = httpContext.GetCurrentAuditScope();
```

**Comment by aintJoshinya** [comment]
perfect, thank you!
