### ISSUE TITLE
Using postgresprovider with configuration datatype string results in illegal cast in psql.

### ISSUE THREAD

**Issue by johan-sv** [thepirat000/Audit.NET#695]
**Describe the bug**
In newer versions of the package there is a bug with the postgresprovider when inserting audit events. By using the string datatype for audit events the insertion into the database fails with error message in postgresql:
ERROR:  type "string" does not exist at character 60
STATEMENT:  insert into "AuditInfos" ("EventData") values (CAST ($1 AS String)) RETURNING ("Id")

**To Reproduce**
Configure audit.net to use the postgresql-provider.
Configure the datacolumn for the event table with the string datatype enum.
Trigger an audit event to be inserted into the database.

**Expected behavior**
The event data being inserted into the table without an exception being thrown.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.EntityFramework: 27.0.1
 - Audit.Net: 27.0.1
 - Audit.EntityFramework.Core: 27.0.1

**Target .NET framework:**
For example:
 - .NET 8

**Additional context**
Does not occur in Audit.Net: 22.1.0. Appears to have been cased some time after this version as I also experienced the same problem in version 25.
I'm running postgres in docker with image bitnami/postgresql:14

**Comment by thepirat000** [comment]
There’s an issue with the [DataType enum](https://github.com/thepirat000/Audit.NET/blob/1d0d59fa524a3108d80c70d420582c63d93b3c1f/src/Audit.NET.PostgreSql/ConfigurationApi/DataType.cs#L10): the value 'String' should be renamed to 'Text,' as PostgreSQL doesn't have a String type.

I'll work on a fix.

In the meantime, consider updating your configuration to use the default JSON type, which should work for varchar or text fields

```c#
  .DataColumn("data", DataType.JSON)
```

**Comment by thepirat000** [comment]
This was fixed in version 27.0.2, please upgrade your references and re-test

**Comment by johan-sv** [comment]
The issue has been fixed. Thank you.

**Comment by johan-sv** [comment]
The issue has been fixed. Thank you.
