### ISSUE TITLE
Question; Custom Audit Table per Entity

### ISSUE THREAD

**Issue by Interopnl** [thepirat000/Audit.NET#70]
Hi,

First of all thank you providing this wonderful library!

We have a requirement that basically needs us to store a copy of an entity before the change in a separate table, is it possible to extent the behavior of audit.net to accomplish this. 

For example we have an Order table and we need to audit the changes to an OrderAudit table and the same for the Orderline table that need to be audited to a OrderlineAudit table.

Looking forward in hearing from you.

**Comment by thepirat000** [comment]
Thanks for your comments.

For sure it can be done, but in order to give better help, could you tell what's the structure of the tables? 

(1) Does all the audit tables have the same fields, or (2) does they mimic the audited table with a couple of more fields?

[Audit.NET.SqlServer](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.SqlServer/README.md) extension can help you in case of (1).

On the other case you will need to code your own Data Provider since there is nothing like that already implemented by the library or its extensions.

**Comment by Interopnl** [comment]
Hi,

Thanks for the quick reply, we need to mimic the audited tables with some extra fields.

We have for example the Order table and we need to audit it to OrderAudit table, the starred fields are extra audit fields;

Could you provide some pseudo code on how the DataProvider would look like for SqlServer instance?

Order
-----------
Id
Number
Status
CreationDate
CustomerName

OrderAudit
------------
Id
Number
Status
CreationDate
CustomerName
*AuditDate
*UserName

**Comment by thepirat000** [comment]
you use EntityFramework to query/update the entities right?

**Comment by Interopnl** [comment]
Yes we use EntityFramework.

**Comment by thepirat000** [comment]
A quick implementation could be as follows:

```
public class CustomDataProvider : AuditDataProvider
{

    public override object InsertEvent(AuditEvent auditEvent)
    {
        var efEvent = auditEvent as AuditEventEntityFramework;
        using (var dbContext = new MyBaseContext())
        {
            foreach (var entry in efEvent.EntityFrameworkEvent.Entries)
            {
                if (entry.Entity.GetType().Name == "Order")
                {
                    AddOrderAudit(dbContext, auditEvent, entry.Entity as Order);
                }
                else if (entry.Entity.GetType().Name == "Orderline")
                {
                    AddOrderlineAudit(dbContext, auditEvent, entry.Entity as Orderline);
                }
            }
            dbContext.SaveChanges();
        }
        return null;
    }

    private void AddOrderAudit(MyBaseContext dbContext, AuditEvent auditEvent, Order order)
    {
        var orderAudit = new OrderAudit();
        orderAudit.Id = order.Id;
        //...
        orderAudit.AuditDate = DateTime.UtcNow;
        orderAudit.UserName = auditEvent.Environment.UserName;
        dbContext.OrderAudits.Add(orderAudit);
    }

    private void AddOrderlineAudit(MyBaseContext dbContext, AuditEvent auditEvent, Orderline orderline)
    {
        var orderlineAudit = new OrderlineAudit();
        orderlineAudit.Id = orderline.Id;
        //...
        orderlineAudit.AuditDate = DateTime.UtcNow;
        orderAudit.UserName = auditEvent.Environment.UserName;
        dbContext.OrderlineAudits.Add(orderlineAudit);
    }
}
```

But I will work trying to provide a generic implementation of this kind of auditing per table

**Comment by Interopnl** [comment]
Looking forward in seeing the generic implementation, in the meantime your CustomDataProvider worked like a charm.

Thanks for your support!

**Comment by thepirat000** [comment]
cool, will leave this open to track the generic implementation

**Comment by thepirat000** [comment]
Starting on version 8.6.0, the [Audit.EntityFramework](https://www.nuget.org/packages/Audit.entityframework/) package includes a generic EF Data provider that should help you in what you want to do.

You can see some documentation [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider).

Hope it helps, if you have any suggestion or problem please let me know.

Regards
