### ISSUE TITLE
SaveChangesGetAuditAsync() Missing in AuditIdentityDbContext

### ISSUE THREAD

**Issue by goofy5752** [thepirat000/Audit.NET#707]
I am using `Audit.NET` for Entity Framework Core to log changes in my database. My `DbContext` inherits from `AuditIdentityDbContext` because I'm integrating with Identity for user management. However, I need to retrieve the audit event when saving changes, and I've noticed that `SaveChangesGetAuditAsync()` is available in `AuditDbContext` but not in `AuditIdentityDbContext`.

### Expected Behavior
`SaveChangesGetAuditAsync()` (and possibly `SaveChangesGetAudit()`) should be available in `AuditIdentityDbContext` just like it is in `AuditDbContext`.

### Actual Behavior
Attempting to use `SaveChangesGetAuditAsync()` in a class inheriting from `AuditIdentityDbContext` results in a compilation error:

`'DataContext' does not contain a definition for 'SaveChangesGetAuditAsync' and no accessible extension method 'SaveChangesGetAuditAsync' accepting a first argument of type 'DataContext' could be found.`

### Versions
- `Audit.EntityFramework.Core` version: `27.0.3`
- `Audit.EntityFramework.Identity.Core` version: `27.0.3`
- `Microsoft.EntityFrameworkCore` version: `8.0.6`
- `Microsoft.AspNetCore.Identity.EntityFrameworkCore` version: `8.0.6`
- .NET version: `.NET 8`
- Database: `PostgreSQL`

### Question
Can `SaveChangesGetAuditAsync()` be added to `AuditIdentityDbContext` as it exists in `AuditDbContext`? Or, is there another recommended way to achieve this functionality when using Identity?

**Comment by thepirat000** [comment]
Added in version 27.1.0, please upgrade your references and re-test
