### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by zacharyboltz** [thepirat000/Audit.NET#71]
Hello.  I'm currently using the Audit.WebApi and Audit.NET.SqlServer libraries.  It's inserting audit information to my database, but I'm not seeing any Exception details included in the JSON Data string (even when exceptions are occurring).  It's not even outputting "Exception": null.

I've tried just adding the [AuditApi] attribute to my controller and also wrapping my try/catch logic inside a "using (var auditScope = this.GetCurrentAuditScope())" block.

Any help is appreciated.  Thank you.

**Comment by zacharyboltz** [comment]
I should also add that I'm targeting the .NET Core 2 framework.

**Comment by thepirat000** [comment]
If you're using Audit.WebApi the exception should be included on the _WebApiAuditAction_ part of the event, and it will not be reflected on the _Environment.Exception_ property.

Can you try with the following code on your startup, to validate if you get the exception text:
```
Audit.Core.Configuration.Setup()
    .UseDynamicProvider(x => x.OnInsertAndReplace(ev =>
    {
        var audit = ev.GetWebApiAuditAction();
        var error = audit.Exception;
    }));
```

**Comment by zacharyboltz** [comment]
Is it possible to UseDynamicProvider in conjunction with UseSqlServer in Startup, i.e. using Audit.WebApi, how would I log audit information (to include exceptions) to a database?

**Comment by zacharyboltz** [comment]
To respond to your suggestion... after adding the suggested code and debugging with the breakpoint, the error variable is always null even with a thrown exception.

**Comment by zacharyboltz** [comment]
Ok.  I see what I'm doing.  I was catching my expected exception and this was preventing it from bubbling up to Audit.WebApi to log.

**Comment by thepirat000** [comment]
cool.
Answering your question about _DynamicProvider_ in cunjunction with another provider. There is no built-in mechanism for that, but nothing stops you to wrap another dataprovider on using Dynamic or the Custom providers:

```
var sqlDp = new SqlDataProvider();
sqlDp.ConnectionString = "...";
//sqlDp...
Audit.Core.Configuration.Setup()
    .UseDynamicProvider(x => x.OnInsert(ev =>
    {
        return sqlDp.InsertEvent(ev);
    }).OnReplace((eid, ev) =>
    {
        sqlDp.ReplaceEvent(eid, ev);
    }));
```

or:

```
public class YourCustomProvider : AuditDataProvider
{
    private SqlDataProvider _sqlDp;
    public YourCustomProvider()
    {
        _sqlDp = new SqlDataProvider();
        _sqlDp.ConnectionString = "...";
        //_sqlDp...
    }
    public override object InsertEvent(AuditEvent auditEvent)
    {
        return _sqlDp.InsertEvent(auditEvent);
    }
    public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
    {
        _sqlDp.ReplaceEvent(eventId, auditEvent);
    }
}

Audit.Core.Configuration.Setup()
            .UseCustomProvider(new YourCustomProvider());
```

**Comment by zacharyboltz** [comment]
Awesome!  Thanks for your help.
