### ISSUE TITLE
Add NET 9 Support 

### ISSUE THREAD

**Issue by KAJOOSH** [thepirat000/Audit.NET#711]
Hello
The official and final version of NET 9 has been released.
Please upgrade the packages.

**Comment by thepirat000** [comment]
Are you experiencing any issues with this library or its extensions when targeting .NET 9?

**Comment by KAJOOSH** [comment]
> Are you experiencing any issues with this library or its extensions when targeting .NET 9?

I upgraded my source to "NET9" version.
I did not see any problem. But I said that maybe changes are needed from the "Audit.NET" side. That's why I said it.

**Comment by thepirat000** [comment]
Support for .NET 9 introduced in version 27.3.0.
