### ISSUE TITLE
StackOverflow exception when exception occurs using EF Core and the AuditSaveChangesInterceptor

### ISSUE THREAD

**Issue by glb-cblin** [thepirat000/Audit.NET#717]
**Describe the bug**
If I use AuditSaveChangesInterceptor and an exception occurs during db.SaveChanges, then the program "loops" into the audit until it crashes the process

If I remove the call to `opt.AddInterceptors(new AuditSaveChangesInterceptor());`, then it works

And so the problem is probably due to this interceptor or to a misusage on my side

**To Reproduce**
Create an AuditLog entity
```
[Table("audit_log")]
[AuditIgnore]
public class AuditLog
{
    [Key]
    public int Id { get; set; }
    public string AuditData { get; set; }
    public string EntityType { get; set; }
    public DateTimeOffset AuditDate { get; set; }
    public string AuditUser { get; set; }
    public string TablePk { get; set; }
}
```

Add it to the DbContext and migrations (not shown here)

Add the configuraiton like described in the [doc](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#map-multiple-entity-types-to-the-same-audit-type-with-independent-actions)
```
Audit.Core.Configuration.Setup()
    .UseEntityFramework(_ => _
        .AuditTypeMapper(t => typeof(AuditLog))
        .AuditEntityAction<AuditLog>((ev, entry, entity) =>
        {
            entity.AuditData = entry.ToJson();
            entity.EntityType = entry.EntityType.Name;
            entity.AuditDate = DateTimeOffset.UtcNow;
            entity.AuditUser = Environment.UserName;
            entity.TablePk = entry.PrimaryKey.First().Value?.ToString() ?? throw new InvalidOperationException();
        })
        .IgnoreMatchedProperties(true)
```

Add the interceptor
```
services.AddDbContext<Db>(opt =>
{
    opt.UseNpgsql(connectionString);
    opt.AddInterceptors(new AuditSaveChangesInterceptor());
});
```

Execute the following code twice
```
[HttpPost("/tmp")]
public ActionResult Tmp()
{
    _db.Add(new MyEntity() {  Id = "tmp" }); //the second execution will trigger a PK violation exception
    _db.SaveChanges();
    return Ok();
}
```

The first time, everything is fine (MyEntity and AuditLog are correctly persisted in the db)

The second time, I have a logical error 
```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "pk_my_entity"
```
But in this case, the programm "loops" infinetely until it completly crashes the main process

**Expected behavior**
I expect to behave the same with or without the interceptor

**Libraries (specify the Audit.NET extensions being used including version):**
 - Audit.EntityFramework.Core: 27.3.2

**Target .NET framework:**
.NET8

**Comment by glb-cblin** [comment]
In order to test if it really is due to the interceptor approach, I did a side project with inheritance of AuditDbContext (instead of using `opt.AddInterceptors(new AuditSaveChangesInterceptor());`) => it works (I mean, the exception is thrown "normaly" without crashing the whole process)

So to me, it looks like a bug in the interceptor approach (or I misconfigre something of course, but due to the fact that it works without the interceptor and that it works with the inheritance approach, I suppose this is really due to the interceptor...)

**Comment by thepirat000** [comment]
The StackOverflow is a consequence of using the same DbContext instance to store the audit events. 

Please check this https://github.com/thepirat000/Audit.NET/issues/652

You should be able to configure the audit data provider to use a different DbContext instance. 

For example:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => app.ApplicationServices.CreateScope().ServiceProvider.GetRequiredService<Db>())
        .DisposeDbContext()
        .AuditTypeMapper(t => typeof(AuditLog))
        ....);
```

**Comment by glb-cblin** [comment]
Hi @thepirat000 

Thanks for your time

With your proposed workaround, I have the exact same problem (i.e "infinite loop" when an exception occurs in the main db context during SaveChanges)

**Comment by thepirat000** [comment]
You are likely getting the same DbContext instance because it is registered as Scoped by default in the service provider. Here are some alternative options:

1. Register your DbContext as Transient:

```c#
services.AddDbContext<Db>(opt =>
{
    opt.UseNpgsql(connectionString);
    opt.AddInterceptors(new AuditSaveChangesInterceptor());
}, ServiceLifetime.Transient);
```

2. Manually create the DbContext instance for the audit:

```c#
Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => new Db(options))
        ...);
```

3. Use a free-variable closure to access the service provider in the `UseDbContext()` lambda and create a new service scope to obtain a new DbContext instance:

```c#
var serviceProvider = new ServiceCollection()
    .AddDbContext<MyDbContext>()
    .BuildServiceProvider();

Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => serviceProvider.CreateScope().ServiceProvider.GetService<MyDbContext>())
        ...);
```

4. Register a `DbContextFactory` and use the factory to create the new DbContext instance:

```c#
var serviceProvider = new ServiceCollection()
    .AddDbContextFactory<MyDbContext>()
    .BuildServiceProvider();

Audit.Core.Configuration.Setup()
    .UseEntityFramework(ef => ef
        .UseDbContext(ev => ev.GetEntityFrameworkEvent().GetDbContext().GetService<IDbContextFactory<MyDbContext>>().CreateDbContext())
        ...);
```

**Comment by glb-cblin** [comment]
Thanks again for your time

Yes my DbContext is Scoped, and this is needed for the Web API I am doing

Unfortunately, I cannot easily access the SP in the place where I am instanciating this code

In the end, I refactored my code and used the AuditDbContext inheritance approach and everything looks good for now
