### ISSUE TITLE
SetCusomField implementation for EF/WebApi/MVC

### ISSUE THREAD

**Issue by hzahed** [thepirat000/Audit.NET#75]
We are using Repository and Unit of Work patterns for our WebApi Core 2.0 application and we have used both of the EF and WebApi libraries of Audit.NET. 

Now We have an issue with adding CustomFeild for WebApi while using **AuditApiAttribute** filter.

I think there should be a way to add Custom Fields inside the **OnActionExecuting** or **OnActionExecuted** methods of this filter before calling **auditScope.Save()** which gives us the capability of adding custom fields for all actions of all controllers. 

My suggestion is something inside the **OnActionExecuting** before adding auditAction and auditScope like this:

<pre>var auditScope = AuditScope.Create(new AuditScopeOptions() { EventType = eventType, AuditEvent = auditEventAction, CallingMethod = actionDescriptior.MethodInfo }); 
auditScope.SetCustomField("UserName", httpContext.User?.Claims?.FirstOrDefault()?.Value);
httpContext.Items[AuditApiActionKey] = auditAction;
httpContext.Items[AuditApiScopeKey] = auditScope;
</pre>

Any suggestion would be appreciated.

**Comment by thepirat000** [comment]
I think what you are looking for is already implemented as Custom Actions. Audit.NET provides you with two _events_ in which you can hook your logic:
- Immediately after the scope creation: `OnScopeCreated`.
- Immediately before the event saving: `OnEventSaving`.

Check the [custom actions documentation](https://github.com/thepirat000/Audit.NET#custom-actions). 

Maybe you can do what you want inside an `OnScopeCreated`. Something like this:

```c#
Audit.Core.Configuration.AddCustomAction(ActionType.OnScopeCreated, scope =>
{
    scope.SetCustomField("UserName", httpContext.User?.Claims?.FirstOrDefault()?.Value);
});
```

**Comment by hzahed** [comment]
Superb! You are totally right. We will go this way then. Thank for your quick reply.
