### ISSUE TITLE
Self referencing loop detected with type error

### ISSUE THREAD

**Issue by xantari** [thepirat000/Audit.NET#76]
Receiving this error:

Self referencing loop detected with type 'System.Data.Entity.DynamicProxies.EventNotification_8467F4C3D800DD127C930B173871B98B115C175244321F3AF8BC4F690B3EBE6D'. Path 'EntityFrameworkEvent.Entries[0].Entity.EventNotification.AttendeeType.EventNotifications'.

Here is how I have dbcontext configured:

        public MyDbContext()
                : base("DefaultConnection")
        {
            Mode = AuditOptionMode.OptOut;
            IncludeEntityObjects = true;
        }

It appears you might need to set JsonSerializer settings somewhere, but I do not see option to override those settings.

Using Audit.EntityFramework. EF 6.1.3. Version of Audit.EntityFramework is 9.0.1.

This error occurs on SaveChanges().

**Comment by thepirat000** [comment]
That could be because, as stated on the documentation, if you don't specify a Data Provider, the FileLog data provider is used by default.

> If you don't specify a Data Provider, a default FileDataProvider will be used to write the events as .json files into the current working directory.

Check the documentation on how to configure the event output ([data providers](https://github.com/thepirat000/Audit.NET#data-providers))

**Comment by thepirat000** [comment]
By default, the JsonSerializer used to get the json, will use ´ReferenceLoopHandling.Ignore´ setting.

https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET/AuditEvent.cs#L73

Could you set up a DynamicDataProvider like this, just to check where the error is happening:

´´´c#
Audit.Core.Configuration.Setup()
	.UseDynamicProvider(config => config
		.OnInsert(ev => 
                {
                     var j = ev.ToJson(); // put a breakpoint here
                }));
´´´

Can you also add the stacktrace?

**Comment by xantari** [comment]
I am able to figure this out. It is because I did not setup the Audit.Core.Configuration.Setup()
    .UseEntityFramework method.

It then defaults to the file provider and that I believe has that set to not ignore reference loops I am guessing.

Thanks for your help. I am closing this issue.
