### ISSUE TITLE
UnauthorizedAccessException when calling SaveChanges() in EntityFramework

### ISSUE THREAD

**Issue by xantari** [thepirat000/Audit.NET#77]
Getting this error when calling SaveChanges() on my DbContext.

System.UnauthorizedAccessException occurred
  HResult=0x80070005
  Message=Access to the path 'C:\Program Files (x86)\IIS Express\20171118223620_636466629806201556.json' is denied.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

Why is this trying to write JSON file to filesystem instead of in memory?

Application is running within a web application.

Was going to Audit changes to entity framework context.

Setup:

        public HWPDbContext()
                : base("DefaultConnection")
        {
            Mode = AuditOptionMode.OptOut;
            IncludeEntityObjects = false;
        }

Have several classes marked with [AuditInclude]

Unable to get it to work.

EntityFramework version: 6.1.3
Audit.EntityFramework: 9.0.1

**Comment by thepirat000** [comment]
That could be because, as stated on the documentation, if you don't specify a Data Provider, the FileLog data provider is used by default.

> If you don't specify a Data Provider, a default FileDataProvider will be used to write the events as .json files into the current working directory.

Check the documentation on how to configure the event output ([data providers](https://github.com/thepirat000/Audit.NET#data-providers))

**Comment by xantari** [comment]
Yeah, sorry about this. I was just about to close these issues. I'm figuring out how to use this, and after much reading and experimenting I was able to find what I am missing and how this works.

Awesomely quick response!!!
