### ISSUE TITLE
How to audit join tables with Audit.EntityFramework?

### ISSUE THREAD

**Issue by xantari** [thepirat000/Audit.NET#78]
Given the following example and configuration how do you log the join table operations?

They get ignored currently by the Entity Framework Auditing framework.

When you insert a new EventAvailabilityResponse into the database, and add a "EventLocation" into the PreferredEventLocations list in the model shown below only the Insert to the EventAvailabilityResponse table is captured.

I have tried IncludeEntityObjects = True but it is missing the EventLocation inserts into the join table "EventAvailabilityResponseEventLocations"

**Model Classes:**
```
public class EventAvailabilityResponse
{
	public EventAvailabilityResponse()
	{
		EventAvailabilityResponseId = Guid.NewGuid().ToString();
	}

	[Key]
	[StringLength(36)]
	public string EventAvailabilityResponseId { get; set; }

	[StringLength(4000)]
	public string Comment { get; set; }
	public virtual EventNotification EventNotification { get; set; }
	public virtual List<EventLocation> PreferredEventLocations { get; set; }
}
```

```
  public class EventLocation
  {
    public EventLocation()
    {
      Location = string.Empty;
    }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int EventLocationId { get; set; }

    [Required]
    public string Location { get; set; }

    public string EventId { get; set; }
    public virtual Event Event { get; set; }

    public virtual List<EventAvailabilityResponse> EventAvailabilityResponses { get; set; }

  }
```

**Configuration Class:**

```
  internal class EventLocationConfiguration : EntityTypeConfiguration<EventLocation>
  {
    internal EventLocationConfiguration()
    {
      ToTable("EventLocations");

      HasMany(e => e.EventAvailabilityResponses)
          .WithMany(e => e.PreferredEventLocations)
          .Map(m => m.ToTable("EventAvailabilityResponseEventLocations")
          .MapLeftKey("EventLocationId").MapRightKey("EventAvailabilityResponseId"));
    }
  }
```

**Comment by xantari** [comment]
It looks like the auditing in Audity.EntityFramework needs to include "Independant Associations".

There is info about this here: https://stackoverflow.com/questions/33611135/tracking-changes-in-entity-framework-for-many-to-many-relationships-with-behavio

and here: 

https://stackoverflow.com/questions/7490509/entity-framework-4-1-many-to-many-relationships-change-tracking#answer-9833201

**Comment by thepirat000** [comment]
can you share the structure of your tables?

**Comment by thepirat000** [comment]
How do plan to audit changes to the join tables? If you don't map the relationship as an entity, but you use the [EF Data Provider](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#entity-framework-data-provider) you won't be able to provide an entity mapping (join table->join audit table).

Maybe I can add the relationships, but the entry will look very different than an entity change, maybe the relationships could be logged to a different place rather than the `EntityFrameworkEvent.Entries`. Will take a closer look and let you know

**Comment by xantari** [comment]
Yeah, these types of relationships should probably be logged in their own location. They are a bit wierd, in that the table it gets written to is not a real entity/class in the code. Instead it is just a join table in the database that you define like this:

```
      HasMany(e => e.EventAvailabilityResponses)
          .WithMany(e => e.PreferredEventLocations)
          .Map(m => m.ToTable("EventAvailabilityResponseEventLocations")
          .MapLeftKey("EventLocationId").MapRightKey("EventAvailabilityResponseId"));
```

Also, these join tables will only get Inserts/Deletes to them (if you think about it Updates would never occur, atleast I can't think of how they would occur) as they are always represented as a collections (Lists/ICollections) in .NET, and in order to change it you would remove an existing list item (Delete) or Add an item (Insert). Hope that makes sense.

So I don't need any additional data? I was going to create a whole project and upload it to show the example. But it sounds like you understand the issue.

**Comment by xantari** [comment]
Suggested name for the new "Entries" look alike: IndependantAssociationEntries.

**Comment by xantari** [comment]
Also, the code to do this is here: https://stackoverflow.com/questions/7490509/entity-framework-4-1-many-to-many-relationships-change-tracking#answer-9833201

**Comment by thepirat000** [comment]
Now a problem will be that the library will be potentially generating EF events with only association changes, with `EntityFrameworkEvent.Entries` as null, that will be a breaking change, maybe the independant associations should not be included by default. 

I still have work to do to make this work for EF and EF Core.

**Comment by xantari** [comment]
Maybe do not make extra "Entries" section, and instead add Enum to EventEntry instead?

```
public Enum TrackingType {
  Entity,
   IndependantAssociation
}
```

Then they mix with other entries, but we can do something different when Enum == IndependantAssociation?

**Comment by thepirat000** [comment]
The `EventEntry` is very different than an association entry. Inside EF, an association entry have two separated Entity objects and Primary Keys. Also properties like Valid, Changes and ColumnValues makes no sense for the association entry. 

I'm close to push a commit with some of the changes, please be patient since it could take some more time.

**Comment by thepirat000** [comment]
Just pushed version 9.1.0 that includes the `Associations` property on the `EntityFrameworkEvent`. 

Make sure to set the `IncludeIndependantAssociations` property to true on the Attribute or whatever method you use to configure the audit, since they are disabled by default.

Feel free to re-open the issue if you are still having problems.

**Comment by xantari** [comment]
Thanks for the update.

I tested this and I do notice one thing that I am wondering if it could be corrected.

The AssociationEntry class defines a tablename.

However the tablename is not the real database name. It is the association name.

I like the fact that it does show the association name, but I am wondering if we could make this the real table name.

For instance right now it says this for the table name: EventLocation_EventAvailabilityResponses

But the real database table name is this: EventAvailabilityResponseEventLocations

This is defined in the configuration for the entity relationships:

```
  internal class EventLocationConfiguration : EntityTypeConfiguration<EventLocation>
  {
    internal EventLocationConfiguration()
    {
      ToTable("EventLocations");

      HasMany(e => e.EventAvailabilityResponses)
          .WithMany(e => e.PreferredEventLocations)
          .Map(m => m.ToTable("EventAvailabilityResponseEventLocations")
          .MapLeftKey("EventLocationId").MapRightKey("EventAvailabilityResponseId"));
    }
  }
```

So I am thinking that the Tablename should have EventAvailabilityResponseEventLocations.

But perhaps keep the name you have in there now and add new property to AssociationEntry class called "LogicalName". As it really the class name association in .NET.

**Comment by xantari** [comment]
OK, I think changing it to just "Name" is a good idea.

I will simply make a Name to PhysicalTableName mapping database file instead with just two columns:

Name                                                                          PhysicalName
EventLocation_EventAvailabilityResponses                 EventAvailabilityResponseEventLocations

**Comment by Ramon-Aguilar** [comment]
Does this functionality exists for the .net core version?

**Comment by thepirat000** [comment]
No it's not. 

I was unable to find a solution for EF core. Looks like the core version does not expose the associasionts as relation entries on the change tracker.

If you have any suggestion please let me know
