### ISSUE TITLE
GetCollection extension method in MongodbProvider

### ISSUE THREAD

**Issue by hzahed** [thepirat000/Audit.NET#79]
We need to use Builders<AuditEvent>.Filter filters in our app. I noticed that you have provided an extension method to return IQueryable<T> as below:

> public IQueryable<T> QueryEvents<T>() where T : AuditEvent
        {
            var client = new MongoClient(_connectionString);
            var db = client.GetDatabase(_database);
            return db.GetCollection<T>(_collection).AsQueryable();
        }

Now my suggestion is to add another extension method like this:

> public IMongoCollection<T> GetCollection<T>() where T : AuditEvent
        {
            var client = new MongoClient(_connectionString);
            var db = client.GetDatabase(_database);
            return db.GetCollection<T>(_collection);
        }

So can send some native mongodb queries to the database.
Thank you for your attention in advance.

**Comment by thepirat000** [comment]
Done. Version 9.1.1. Re-open if any issues
