### ISSUE TITLE
AuditApiAttribute NullReferenceException

### ISSUE THREAD

**Issue by tommywulove** [thepirat000/Audit.NET#8]
Hi, the following is the response , and found that the potential Null Reference Exception.

{
"Message": "An error has occurred."
"ExceptionMessage": "Object reference not set to an instance of an object."
"ExceptionType": "System.NullReferenceException"
"StackTrace": " at Audit.WebApi.AuditApiAttribute.OnActionExecuted(HttpActionExecutedContext actionExecutedContext) at System.Web.Http.Filters.ActionFilterAttribute.OnActionExecutedAsync(HttpActionExecutedContext actionExecutedContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

AuditApiAttribute class
  public override void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
actionExecutedContext.Response  <--- may null if the exception throw. 

Following is my modified code AuditApiAttribute.

     public override void OnActionExecuted(HttpActionExecutedContext actionExecutedContext)
        {
            var httpContext = GetHttpContext(actionExecutedContext.Request);
            var auditAction = httpContext.Items[AuditApiActionKey] as AuditApiAction;
            var auditScope = httpContext.Items[AuditApiScopeKey] as AuditScope;
            if (auditAction != null && auditScope != null)
            {
                auditAction.Exception = actionExecutedContext.Exception.GetExceptionInfo();
                auditAction.ModelStateErrors = IncludeModelState ? GetModelStateErrors(actionExecutedContext.ActionContext.ModelState) : null;
                auditAction.ModelStateValid = IncludeModelState ? (bool?)actionExecutedContext.ActionContext.ModelState.IsValid : null;
                auditAction.ResponseBodyType = actionExecutedContext.Response == null ? "" : actionExecutedContext.Response.Content.GetType().Name;

                if (actionExecutedContext.Response != null)
                {

                    auditAction.ResponseStatus = actionExecutedContext.Response.ReasonPhrase;
                    auditAction.ResponseStatusCode = (int)actionExecutedContext.Response.StatusCode;
                    if (IncludeResponseBody)
                    {
                        var objContent = actionExecutedContext.Response.Content as ObjectContent;
                        auditAction.ResponseBody = objContent != null
                            ? new { Type = objContent.ObjectType.Name, Value = objContent.Value }
                            : (object)actionExecutedContext.Response.Content.ReadAsStringAsync().Result;
                    }
                }
                else
                {
                    auditAction.ResponseStatusCode =  500 ;
                    auditAction.ResponseStatus = "Internal Server Error";

                }
                // Replace the Action field and save
                auditScope.SetCustomField("Action", auditAction);
                auditScope.Save();
            }
        }

**Comment by thepirat000** [comment]
Hi @tommywulove 

Thanks for your suggestions!

Should we assume an Internal Server Error when the response is NULL? Why?

**Comment by tommywulove** [comment]
Hi @thepirat000 ,

Should we assume an Internal Server Error when the response is NULL? 
Yes.

What happens if the API action genuinely returns NULL?
In my case, I want to catch the raw exception or normal response for audit usage, and save to db. 
For this test case, I just throw new NotImplementedException() on the controller level, and the actionExecutedContext.Response is null, then the auditattribute threw a new null reference exception, and i cannot catch the original exception.  The api will return 500 error finally, but in the attributes, no response inside the actionExceutedContext. 

Here is the my test result.
![image](https://cloud.githubusercontent.com/assets/2859394/19918267/bc0c1382-a104-11e6-9ed8-d0b556095061.png)

Thank you for your response.

**Comment by thepirat000** [comment]
Ok, I see. Thanks for the explanation.

Fixed this also for .NET Core attribute, please use the latest package.
