### ISSUE TITLE
CamelCasePropertyNames for Entity keys

### ISSUE THREAD

**Issue by hzahed** [thepirat000/Audit.NET#80]
As you know JsonContractResolver for both ASP.NET CORE MVC/WebApi is CamelCasePropertyNameResolver by default.

The following example makes it clear.

ASP.NET CORE's Default JSON result:

> "entity": {
                        "code": "AAA",
                        "name": "aaa",
                        "id": "18915a05-36e4-4295-9736-067d5b28f8f0"
                    }

Current Audit.NET result:

> "Entity": {
                        "Code": "AAA",
                        "Name": "aaa",
                        "Id": "18915a05-36e4-4295-9736-067d5b28f8f0"
                    }

It would be nice to a have a JsonSerializerSettings option for this part too OR by default, it acts like asp.net core at least in the .NET CORE Package.

** We are using the MongoDBProvider to read the records by the way.

Any suggestion?

**Comment by thepirat000** [comment]
I guess you can do that since the MongoDB Provider allows to change the JsonSerializerSettings used to generate the BSon.

```c#
Audit.Core.Configuration.Setup()
    .UseMongoDB(_ => _
        .ConnectionString("mongodb://localhost:27017")
            .Database("Audit")
            .Collection("Event")
            .CustomSerializerSettings(new JsonSerializerSettings()
            {
                ContractResolver = new DefaultContractResolver() { NamingStrategy = new CamelCaseNamingStrategy() }
            }));
```

**Comment by hzahed** [comment]
Yes, you are right. it works as expected 👍 thank you! You may close this request now.
