### ISSUE TITLE
.NET Core 2.0 Migration Support?

### ISSUE THREAD

**Issue by phobos04** [thepirat000/Audit.NET#81]
Hi,
corgrats for this awesome project!

I'm evaluating adopting `Audit.NET.EntityFramework.Core` for auditing my EF context. The project is a .NET Core 2.0 Web App targeting `netcoreapp2.0`. I'm already using the general `Audit.NET` package as well as `Audit.NET.SqlServer` for auditing my DB changes in a global `Audit` table with `json` formatted data, and testing `Audit.NET.WebApi` for auditing my web requests data.

Please, does `Audit.NET.EntityFramework.Core` support EF Migrations? Are the `Audit_*` tables automatically updated as the audited ones when an EF Migration is applied?

Thank you so much.

**Comment by thepirat000** [comment]
Hi, thanks for your comments.

I guess you are referring to the [EF Data Provider](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#entity-framework-data-provider). The audit tables structures are up to you. The library will not create or alter the audit tables by itself. So I guess the answer to your question is no, the audit tables are not updated by the library.

You need to create and maintain your audit tables and just provide a way to do the mapping from the entities to the Audit entities. Also, by default, it will try to copy the property values with the same name from the entity to the audit entity, but you can change the default behavior and/or provide a custom entity action ([AuditEntityAction](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#ef-provider-options)) to be performed.
