### ISSUE TITLE
Incorrect Response Status

### ISSUE THREAD

**Issue by Jacquers** [thepirat000/Audit.NET#82]
I'm using v9.1.2 and getting a ResposeStatus of 200 when I'm expecting 500.

Below is a section from the controller method. 

Any help would be appreciated, thanks.

```
catch (Exception ex)
            {
                //Log.Fatal(ex, "{methodName}: An unexpected error occurred.", methodName);
                return StatusCode(500, new { success = false, error = GetExceptionMessage(ex) });
            }
```

```
public override object InsertEvent(AuditEvent auditEvent)
        {
            var eventType = "";

            var auditEntries = new List<object>();

            var dbContext = new AuditContext(_connectionString);

            var startDate = auditEvent.StartDate.ToUniversalTime();

            DateTime? endDate = null;
            if (auditEvent.EndDate != null)
            {
                endDate = auditEvent.EndDate.Value.ToUniversalTime();
            }

            if (auditEvent is AuditEventWebApi)
            {
                eventType = "WebApi";

                var aewa = auditEvent as AuditEventWebApi;

                var webapi = new WebapiLog();

                webapi.TenantId = Guid.Empty; //todo: fix
                webapi.Username = "todo"; //todo: fix
                webapi.StartDate = startDate;
                webapi.EndDate = endDate;
                webapi.Duration = auditEvent.Duration;
                webapi.ControllerName = aewa.Action.ControllerName;
                webapi.MethodName = aewa.Action.ActionName;
                webapi.MethodParams = "";
                foreach (var ap in aewa.Action.ActionParameters)
                {
                    webapi.MethodParams += ap;
                }
                webapi.Environment = JsonConvert.SerializeObject(aewa.Environment);
                webapi.IpAddress = aewa.Action.IpAddress;
                webapi.UserAgent = "todo";
                webapi.ResponseStatus = aewa.Action.ResponseStatus;
                webapi.ErrorMessage = aewa.Action.Exception;

                auditEntries.Add(webapi);
                dbContext.WebapiLog.Add(webapi);
            }
```

**Comment by thepirat000** [comment]
Fixed on version 9.1.3, please retry with latest package version

**Comment by Jacquers** [comment]
Thanks very much, it's now showing 'internal server error' as the Response Status and 500 as the code.

The response body however is null. I'm expecting the following so I can log it. Could you please fix it? :)

```
{
    "success": false,
    "error": "Sales Order  already exists."
}

```
btw, In the environment field it's showing the following, not sure about the exception message.

`{"Culture": "en-ZA", "UserName": "myusername", "Exception": "Exception: Exception from HRESULT: 0xE0434352", "MachineName": "machinename", "AssemblyName": "VSc.DSO.API, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "CallingMethodName": "VSc.DSO.API.Controllers.EDIController.CreateSalesOrderAsync()"}
`
Any idea why the exception message comes through like this or if it's possible to get the actual exception message?

**Comment by thepirat000** [comment]
Did you set the `IncludeResponseBody` to true on the `AuditApiAttribute` ? By default it does not log the body of the response.

For the exception details, the audit api event includes the detailed information on `Action.Exception` property. So check that one instead of the `Environment.Exception` that is only a general indicator of an unhandled exception. Check the code that updates `Environment.Exception` property [here](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET/AuditScope.cs#L282).

**Comment by Jacquers** [comment]
No, it wasn't set, I'll do so now. Thanks for your help, it's appreciated :)
