### ISSUE TITLE
Disconnected Entities Scenario

### ISSUE THREAD

**Issue by hzahed** [thepirat000/Audit.NET#83]
We are using Audit.Net inside an ASP.NET Core WebApi 2.0 project. Our architecture is based on atomic disconnected entities for Crud operations. Do you have any idea how we can set the old and new entity properties in Audit.Net entity logs?

**Comment by thepirat000** [comment]
I don't get your question, sorry. The old/new target property 
Are you using `Audit.WebApi` or `Audit.EntityFramework`? or both at the same time?
You can set the target (old/new) when manually creating a new `AuditScope`, or after its creation by accessing the `scope.Event.Target` property.

**Comment by hzahed** [comment]
`scope.Event.Target` is exactly what I was searching for :-) 
Thank your for your help.
