### ISSUE TITLE
By Passing MongoDB Audits on Error

### ISSUE THREAD

**Issue by hzahed** [thepirat000/Audit.NET#84]
We are using Audit.Net in an ASP.NET Core WebApi 2.0 project. Project's database is on MSSQL server but we use Audit.Net MongoDB Provider to save logs on MongoDB.

Now the question is that when we want to perform SaveChangesAsync in the context, is there any way to save changes to MSSQL and ignore possible MongoDB exception or errors?

**Comment by thepirat000** [comment]
I don't get why, if you want to save your logs to MSSQL, are you using the mongodb provider? Can you please provide more details about your requirement or problem?

Also you mention SaveChangesAsync, I guess you are using Audit.EntityFramework, right?

**Comment by hzahed** [comment]
Ops sorry! Our scenario is a bit complicated. Now I try to make it clear:

We have an ASP.NET Core 2.0 WebApi project. We save all our own records in MSSQL database. In addition, while we are saving the records, we use Audit.EntityFramework to generate audits and Audit.MongoDB provider to save the Audit records in MongoDB.

The point is that when we call SaveChangesAsync two different requests are being called inside of the Audit.EntityFramework, one for MSSQL to save the actual record and one for MongoDB to save the Audit records. 

Now we want to make sure that if for any reason saving in MongoDB database faced an exception we already had saved the records in MSSQL. Somehow we want to make sure that in the first step actual records are being saved in MSSQL then try to save the Audit records in MongoDB. 

I tried to clarify the concern, is it clear now?

**Comment by thepirat000** [comment]
Assuming your setup is:
- Your entities on MSSQL via entity framework (using audit.entityframework)
- The audit events on MongoDB (using audit.net.mongodb)

> we want to make sure that if for any reason saving in MongoDB database faced an exception we already had saved the records in MSSQL

The audit event saving doesn't take place until your dbcontext's SaveChanges has completed its execution (successfully or not), so your entities are already saved when the audit event saving is triggered. 

> we want to make sure that in the first step actual records are being saved in MSSQL then try to save the Audit records in MongoDB

That's how it works

1. Execute the SaveChanges on your dbcontext
2. If 1 throws exception: Update the exception details on the audit event 
3. Save the event (in your case to mongodb)

**Comment by hzahed** [comment]
That's perfect. Thank you for your explanations. My issue is resolved now.
