### ISSUE TITLE
Action.UserName null

### ISSUE THREAD

**Issue by Jacquers** [thepirat000/Audit.NET#86]
I'm able to get the User in my controller from ClaimsPrincipal User, but in public override object InsertEvent(AuditEvent auditEvent)
        {
} the Action.UserName is null.

The project is .Net Core 2. A difference from your examples is that I inherit from Controller not ApiController. 

I'm using the following auth:

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o =>
            {
                o.Audience = Configuration["Vsc.Auth:Audience"];
                o.Authority = Configuration["Vsc.Auth:Authority"];
                o.RequireHttpsMetadata = Configuration.GetValue<bool>("Vsc.Auth:RequireHttpsMetadata");
                o.IncludeErrorDetails = true;
            });

and app.UseAuthentication();

**Comment by thepirat000** [comment]
The UserName on the action should be the same as the one on `HttpContext.Current.User.Identity.Name`. Can you check if you get the user name on that property when you enter your action?

**Comment by Jacquers** [comment]
Here is what I get using the immediate window when debugging:

HttpContext.Current.User.Identity.Name
error CS1061: 'HttpContext' does not contain a definition for 'Current' and no extension method 'Current' accepting a first argument of type 'HttpContext' could be found (are you missing a using directive or an assembly reference?)

HttpContext.User
{System.Security.Claims.ClaimsPrincipal}
    Claims: {System.Security.Claims.ClaimsPrincipal.<get_Claims>d__21}
    CustomSerializationData: null
    Identities: Count = 1
    Identity: {System.Security.Claims.ClaimsIdentity}

**Comment by thepirat000** [comment]
and what about `HttpContext.User.Identity.Name`?
