### ISSUE TITLE
Feature: Direct support for EntityFramework

### ISSUE THREAD

**Issue by sven5** [thepirat000/Audit.NET#9]
Hi Frederico,

While playing around with Audit.NET I would love to see direct integration of EntityFramework. 
I mean a possibility to save EventEntry and other data (POCO objects) directly to existing DbContexts via DbSets.
Currently I'm trying to implement my own CustomDataProvider to achieve this goal. I will try to fetch all EntityFrameworkEvents and use their data for saving. 

The reason for this: I need a possibility to show the end user changes made by other users on an entity. That way I need the data in plain format to show in data grids - not json.

Regards
Sven

**Comment by thepirat000** [comment]
Yes, I think somethinkg like this should work:

```c#
public class CustomDataProvider : AuditDataProvider
{
    public override object InsertEvent(AuditEvent auditEvent)
    {
        using (var ctx = new YourExistingDbContext())
        {
            //Fetch the EF event info
            var efEvent = auditEvent.GetEntityFrameworkEvent();

            var x = new YourAuditClass()
            {
                Database = efEvent.Database,
                Blame = auditEvent.Environment.UserName
                //...
            };
            foreach (var entry in efEvent.Entries)
            {
                x.Entries.Add(new YourAuditEntryClass()
                {
                    Table = entry.Table,
                    //...
                });
            }
            ctx.Audits.Add(x);
            ctx.SaveChanges();
            return x.Id;
        }
    }
}
```

**Comment by sven5** [comment]
Hi Frederico,

yes I already started implementing my own DataProvider. I'm using copies of your audit event classes with extensions needed for EF (e.g. Key property). I'm mapping the events with AutoMapper to my audit entity classes. It's working.

Regards
Sven
