### ISSUE TITLE
Error on context.SaveChanges() 2

### ISSUE THREAD

**Issue by Braidon** [thepirat000/Audit.NET#90]
As was already posted, exception throws at SaveChanges(). As it seems, framework incorrectly works with inherited classes. I've created an example to show.
[AuditTest.zip](https://github.com/thepirat000/Audit.NET/files/1568247/AuditTest.zip)

**Comment by thepirat000** [comment]
You are right, the EF6 version of the library is unable to resolve the mapping. I'm working on a fix

**Comment by thepirat000** [comment]
Please upgrade to version >= 10.0.1

I had to change the way the library obtains the mapping. Part based on [this](https://lowrymedia.com/2014/06/10/ef6-1-mapping-between-types-tables-including-derived-types/). 

The EF6 public mapping API really sucks... I hope the library now covers most of the use cases and that I'm not breaking anything.

All the unit tests are passing. I'va added your tests (and a couple more) as unit tests for the library.

Hope it helps.

Feel free to re-open the issue if you're still having problems
