### ISSUE TITLE
Using both EF 6 and EF core same time in net standard 2 and net full

### ISSUE THREAD

**Issue by oruchreis** [thepirat000/Audit.NET#91]
We are using ef core and ef 6 same time in net full projects and net standard 2 projects. But if I use Audit.EntityFramework, I can't use audit in efcore with net full projects. If I use Audit.Entityframework.Core, then I can't use ef6 in netstandard projects. If I use both, this time projects can't build because of same namespace with same class of AuditDbContext. Is there any solution for this scenerio?

I've decided not to use audit.net in efcore with net full projects until I found a workaround. Until then I've decoreted base dbcontext implementation with compiler directives:
```
    public class MembershipContext :
#if NET47
        IdentityDbContext<User, Role, long, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
#elif NETSTANDARD2_0 || NETCOREAPP2_0
        Audit.EntityFramework.AuditIdentityDbContext<User, Role, long, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
#endif
```

**Comment by oruchreis** [comment]
I've decided not to use audit.net in efcore with net full projects until I've found a workaround. Until than I've decoreted base dbcontext implementation with compiler directives:
```
    public class MembershipContext :
#if NET47
        IdentityDbContext<User, Role, long, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
#elif NETSTANDARD2_0 || NETCOREAPP2_0
        Audit.EntityFramework.AuditIdentityDbContext<User, Role, long, UserClaim, UserRole, UserLogin, RoleClaim, UserToken>
#endif
```

**Comment by thepirat000** [comment]
Can you give more details about your setup or share a sample solution? 

Do you have one project targeting both frameworks or one project for .NET core EF7 and another one for .NET full EF6?

**Comment by oruchreis** [comment]
- Applications
   - Asp.Net Mvc 5 Project (net47)
   - Asp.Net Core Project (net47, netcoreapp2.0, multi-target)
   - Asp.Net Core Project (net47)
- Data
   - EF6 library (net47)
   - EF Core library (net47 and netstandard2.0, multi-target)

The applications above uses both data libraries which target EF6 with net47 and EF Core  net47 and netstandard2.0.

**Comment by thepirat000** [comment]
so you should import the Audit.EntityFramework in your EF6 library and Audit.EntityFramework.Core to your EF Core library. Did you tried like that?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by oruchreis** [comment]
Yes I've tried that, and I couldn't build, because there are two AuditDbContext with the same namespace.

**Comment by thepirat000** [comment]
which of your projects failed to build? I guess not the EF data libraries right?

**Comment by oruchreis** [comment]
I've figured it out that EfCore library has reference to the Ef6 library indirectly. Which i think this cause the issue. But I can't change this behavior for a while. We try to migrate all projects to net core, and for a while they must work together. I'll prepare a sample solution to reproduce this issue later. But I can say that if I use EF6 library with Audit.EntityFramework  and EfCore library with Audit.EntityFramework.Core, than I can't build projects because of this error:  
`error CS0433: The type 'AuditDbContext' exists in both 'Audit.EntityFramework.Core, Version=10.0.2.0, Culture=neutral, PublicKeyToken=571d6b80b242c87e' and 'Audit.EntityFramework, Version=10.0.2.0, Culture=neutral, PublicKeyToken=571d6b80b242c87e'`

**Comment by thepirat000** [comment]
I think this is not a bug on the library. You should not mix EF versions. Also if I change the namespace of the Core package, I will be breaking backward compatibility.

**Comment by bhupendrasinghnegi** [comment]
Does that mean the following scenario holds true in respect to using EntityFramework (EF) Audit Extension

1. Project on .NET 4.5 using EF 6.0 -- will work
2. Project on .NET Core using EF core -- will work

I have scenario 1 please confirm so that I can plan

**Comment by thepirat000** [comment]
yes. both scenarios are supported already

**Comment by bhupendrasinghnegi** [comment]
@thepirat000 : Thanks a lot for your prompt reply, appreciated.
