### ISSUE TITLE
EF6 - updated entity ColumnName is null

### ISSUE THREAD

**Issue by Braidon** [thepirat000/Audit.NET#92]
Hello!
I use EF6 and a custom data provider to save events at DB. I have two classes - base and derived. When I updating derived class (containing base properties) at InsertEvent, list of changes (List<EventEntryChange> Changes) contains null ColumnName property of base class.
Here is a sample project.
[AuditTest.zip](https://github.com/thepirat000/Audit.NET/files/1591335/AuditTest.zip)

Thank you

**Comment by thepirat000** [comment]
Thanks for providing the sample project, that makes things easier to me. 

This is fixed on version 10.0.3, please upgrade to latest package versions.

I'm closing this but feel free to re-open if you're still facing issues. Regards.
